### ISSUE TITLE
HTTP 400 without a ErrorResponse object for Skype For Business

### ISSUE THREAD

**Issue by ricardopieper** [microsoft/BotFramework-Services#1]
Hi, the @AzureSupport twitter account (signed by RS) told me to create an issue here.

The documentation says:

> Any response that specifies an HTTP status code in the 4xx range or 5xx range will include an ErrorResponse object in the body of the response

I set up a Skype For Business account and my endpoint is now receiving messages. When I try to respond a message, I'm getting a HTTP 400 error for some reason. The body of the answer should clarify what I'm doing wrong, but instead I get this:

```
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/PlatformService' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

            <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;Off&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

    </body>
</html>
```

Not very helpful I'd say.

The issue is, we have a working integration with Webchat and Skype, and they are working correctly. Actually the code for Skype and Skype For Business is 100% the same. I believe this should work. We're using Directline API 3.

Soon I'll be able to get the actual HTTP payload I'm sending, we're also in the process of debugging this. I'll also share my token with the person on Twitter.

**Comment by ricardopieper** [comment]
This is the payload I'm sending:
```

{
    "text": "Boa tarde, Ricardo Pieper! Como posso ajudar você?",
    "type": "message",
    "serviceUrl": "https://webpooldm20r04.infra.lync.com/platformservice/tgt-dcaefcf21bde5e7d9890dfc2d9a1fa15/botframework",
    "from": {
        "id": "<REDACTED>",
        "name": "<REDACTED>"
    },
    "conversation": {
        "id": "MzIyNmI3YWQjc2lwOmV1cm9mYXJtYTJAdWJvdHN0ZXN0ZS5vbm1pY3Jvc29mdC5jb20="
    },
    "recipient": {
        "id": "sip:ricardo@ubotsteste.onmicrosoft.com",
        "name": "sip:ricardo@ubotsteste.onmicrosoft.com"
    }
}

```

**Comment by ksikorsk** [comment]
Hi Ricardo,

I'm on the platform team.  Just wanted to inform you that we are looking into the issue.  I know you're under a tight timeline, so we are prioritizing this.  Given that your logs have not revealed anything useful we are attempting at a local repro of the issue, but it takes some time to set up the environment.

Appreciate your patience,
Kamil

**Comment by ksikorsk** [comment]
One clarification, in the issue you referenced you said "I just redid everything from scratch again and it worked. Re-created the whole resource on Azure and everything. If I see this error again I can point the application ID and everything else."

Does this mean you are unblocked?

**Comment by ricardopieper** [comment]
No, that was days ago, and it was for the normal skype, not skype for business. We're still having problems.

I'll try to provide a cUrl soon and monitoring a local request with fiddler.

**Comment by ricardopieper** [comment]
@ksikorsk we've just talked, if you need the cUrl i can send it by email or something

**Comment by ricardopieper** [comment]
Also @ksikorsk we saw that application insights wasn't showing up anything about Skype For Business. My colleague just noticed the issue #13

**Comment by ricardopieper** [comment]
@ksikorsk Thank you for your service today. I think the mistake you found on our end solves #8 because I was putting the wrong thing in the URL.

For those wondering, the contract requires us to add the conversation ID in the URL for the REST call. We were using the recipient ID instead of the conversation ID, thus everything exploded fantastically. 

However, I think this issue should remain open because the contract violation still happens (http 400 without a ErrorResponse).

**Comment by jameslew** [comment]
I wanted to update this after a long gap to let you know that while i believe this item was addressed, the business decision has been made that Skype for Business channel will not be coming out of preview state, and no new bots or features will be added.  Strategically Microsoft is directing customers to Microsoft Teams.

Your current Skype for Business bots will continue to work for some time (currently likely into Q1 2020) after which they will cease to be able to connect to Skype for Business users.
