### ISSUE TITLE
Sign In Card Does Not Render in Web Chat

### ISSUE THREAD

**Issue by kashifkhan** [microsoft/BotFramework-Services#100]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.15.2.2
* Active Channels: Web Chat
* Deployment Environment:  Azure Bot Service, Azure App Service, local development with Emulator

## Issue Description
When running the sample code for Oath login https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/AadV2Bot the bot is able to render a sign card in the emulator but not in web chat. Running the web chat in Edge or Chrome renders the following when sign in is requested "[File of type 'application/vnd.microsoft.card.oauth']"

## Code Example
https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/AadV2Bot

## Reproduction Steps
1. Deploy https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/AadV2Bot on Azure
2. Enable Web Chat Channel
3. Enter in "me" command

## Expected Behavior
Expect to see the Sign in card which allows a user to authenticate against the graph API

## Actual Results
Since the card is rendered an attachment the browser (Edge, Chrome) display "[File of type 'application/vnd.microsoft.card.oauth']" . In the emulator it works as intended.

**Comment by mingweiw** [comment]
We don't want to update webchat at the existing embed url because we don't know who's relying on its existing behavior. The new webchat (4.4) embed is available at https://webchat.botframework.com/embed/b/gemini?s=YOUR_SECRET&b=YOUR_BOT_ID.
