### ISSUE TITLE
GroupMe channel returns HTTP status 500 when sending Image or Location via ChannelData

### ISSUE THREAD

**Issue by sphanley** [microsoft/BotFramework-Services#101]
I'm building a Bot Framework bot that's connected to the GroupMe channel. According to the (non Bot Framework specific) [GroupMe Bot tutorial](https://dev.groupme.com/tutorials/bots), GroupMe supports bots sending Image or Location attachments, by sending a message with the following syntax: 

>     {
>       "bot_id"  : "j5abcdefg",
>       "text"    : "Hello world",
>       "attachments" : [
>         {
>           "type"  : "image",
>           "url"   : "https://i.groupme.com/somethingsomething.large"
>         }
>       ]
>     }
>
> Or:
> 
> 
> 
>     {
>       "bot_id"  : "j5abcdefg",
>       "text"    : "Hello world",
>       "attachments" : [
>         {
>           "type"  : "location",
>           "lng"   : "40.000",
>           "lat"   : "70.000",
>           "name"  : "GroupMe HQ"
>         }
>       ]
>     }

When my bot receives a message from a human user that contains a location attachment, it comes through like this: 

```
{
   ... 
   "channelData":[  
      {  
         "type":"location",
         "lat":"70.000",
         "lng":"40.000",
         "name":"GroupMe HQ"
      }
   ],
   ...
}
```

Based on that, I'm trying to send a location from my bot using the following code: 

```
var msg = MessageFactory.Text(messageText);
msg.ChannelData = new dynamic[]
{
    new {
        type = "location",
        lng = "40.000",
        lat = "70.000",
        name = "GroupMe HQ"
    }
};
                                
await turnContext.SendActivityAsync(msg);
```

However, this results in a 500 status code from my bot's endpoint, printing the following in chat:

> Service Error:POST to {BotName} failed: POST to the bot's endpoint failed with HTTP status 500

Or, occasionally: 

> Service Error:POST to {BotName} timed out after 15s

If there's something wrong with my syntax, I'd appreciate a correction - otherwise, I suspect that there's a defect in the way that the GroupMe channel service is processing ChannelData.

**Comment by sphanley** [comment]
Per [this issue on the BotBuilder SDK repo](https://github.com/Microsoft/botbuilder-dotnet/issues/286), I've also tried the following code: 

    msg.ChannelData = JObject.FromObject(new[]
    {
        new {
            type = "location",
            lng = gym.Location.Longitude,
            lat = gym.Location.Latitude,
            name = gym.Name
        }
    });

and 

    msg.ChannelData = JObject.FromObject(new
    {
        attachments = new[]
        {
            new
            {
                type = "location",
                lng = gym.Location.Longitude,
                lat = gym.Location.Latitude,
                name = gym.Name
            }
        }
    });

The first snippet doesn't work at all, even in the emulator - it causes an exception "ArgumentException: Object serialized to Array. JObject instance expected."

The second snippet works in that it doesn't cause a 500 error, but no attachment is received in GroupMe (and for some reason I'm seeing the message duplicated).

**Comment by sphanley** [comment]
I've now tried what I think is the most explicitly correct syntax: 

Given the following model classes:

**Comment by sphanley** [comment]
I've now tried what I think is the most explicitly correct syntax. Given the following model classes:

```
[Serializable]
public class GroupMeChannelData : JArray
{
    public void Add(GroupMeAttachment attachment)
    {
        Add(JToken.FromObject(attachment));
    }
}

[Serializable]
public class GroupMeAttachment
{
    [JsonProperty("type")]
    virtual public string Type { get; set; }
}

[Serializable]
public class GroupMeLocationAttachment : GroupMeAttachment
{
    [JsonProperty("type")]
    public override string Type => "location";
    [JsonProperty("lat")]
    public string Latitude { get; set; }
    [JsonProperty("lng")]
    public string Longitude { get; set; }
    [JsonProperty("name")]
    public string Name { get; set; }
}
```

I generated the attachment using as below: 

```
var msg = MessageFactory.Text(messageText);
var channelData = new GroupMeChannelData
{
    new GroupMeLocationAttachment()
    {
        Latitude = "70.000",
        Longitude = "40.000",
        Name = "GroupMe HQ"
    }
};
msg.ChannelData = channelData;

await turnContext.SendActivityAsync(msg);
```

In the Bot Framework Emulator, this sends a message with ChannelData formatted exactly as I'm led to believe GroupMe is expecting, based on the GroupMe docs as well as the ChannelData I see when my bot receives attachments from non-bot users in the chat. However, this still causes a 500 error when sent to the actual GroupMe channel. Based on that, I feel strongly that this is a defect in the connector service.

**Comment by anusharavindrar** [comment]
Hello @sphanley, if your goal is to send a location from the bot, you can instantiate an HTTP client and then make the [api](https://dev.groupme.com/docs/v3#messages) calls. Also, can you try using the code below to see if you are able to send location from the bot.

```
var reply = MessageFactory.Attachment(new Attachment("image/png", "https://i.imgur.com/vta1imR.png"));
            reply.ChannelData = JObject.FromObject(new { attachment = new {
                    type = "location",
                    lng = "40.000",
                    lat = "70.000",
                    name = "GroupMe HQ"
                }
            });
    
           await turnContext.SendActivityAsync(reply);
```
I tried using the above code and it does send the location.

**Comment by sphanley** [comment]
Thanks for the response, @anusharavindrar! You're right, if I use the snippet you posted, I do see both the image and location attachments come through in my GroupMe chat. However, if I try to remove the Image attachment and only add the location attachment to a message that otherwise only contains text, I receive a 500 error. Can you try that and let me know if you see the same? I would expect that to be valid. Here's the code:

            var reply = MessageFactory.Text("Location-only test");
            reply.ChannelData = JObject.FromObject(new { attachment = new {
                    type = "location",
                    lng = "40.000",
                    lat = "70.000",
                    name = "GroupMe HQ"
                }
            });
    
           await turnContext.SendActivityAsync(reply);

I'd really love to avoid having to spin up an HTTPClient and make API calls directly - that's the whole reason I'm using the Bot Framework to begin with, you know?

**Comment by sphanley** [comment]
Additionally, when I do use your sample code and send the message containing the image attachment, somehow the JSON received is this: 
```
attachments: [
    {type: "image", url: "https://i.groupme.com/800x1412.png.231291571d6c4432bb61a7e2f9578421"},
    {lat: "70.000", lng: "40.000", name: "GroupMe HQ", type: "location"}
]
```

So somehow, the channel connector is inferring that this is an image, replacing the `image/png` type with `image`, and then reuploading it to GroupMe's image host? It feels like there's just a lot of undocumented behavior happening inside the connector channel service.

**Comment by anusharavindrar** [comment]
Correct. If you use just the location attachment to the message, it throws up an error. I did try the code which you pasted above and encountered the same issue before coming up with the workaround which I shared. There seems to be an issue with the GroupMe connector and how it is processing the channelData.

**Comment by sphanley** [comment]
Ok! Just wanted to confirm that we were on the same page. Strange that adding the image Attachment allows the channelData location attachment to be correctly processed as well.

**Comment by daveta** [comment]
Hi @sphanley, I've contacted the developer that owns the code, we're going to dig in. Thanks again for the time reporting. We'll get back to you.

**Comment by sphanley** [comment]
Sounds great. If you need any clarification or reproduction steps for any of this, please let me know - I really appreciate the level of support you all are providing!

**Comment by hcyang** [comment]
hi @craigjensen and @jameslew, any updates?

**Comment by sphanley** [comment]
Seconding the request for any updates - I'm working on a GroupMe Bot Framework project and have features I'd love to move forward with, but the largely broken attachment support is really limiting. Thanks for your work on resolving this issue!

**Comment by carlosscastro** [comment]
@sphanley this is being investigated, we'll provide an update once we have a concrete plan. We apologize for the delay, and completely agree that broken attachment support is a limiting factor. Thanks for your patience!

**Comment by sphanley** [comment]
Thanks for the update @carloscastro! I appreciate the ongoing investigation.

**Comment by arturl** [comment]
Thank you for the issue report and working with us to get to the detail.  We've evaluated the issue and determined that it doesn't fit in our current semester's schedule.  We have added it to our backlog for future planning, but do not have an ETA to offer at this time.

**Comment by sphanley** [comment]
Gotta say, this is really disappointing, especially considering that GroupMe is a first-party Microsoft channel - I understand that it's likely a low-traffic channel, and fully addressing this such that GroupMe attachments are well-supported by the framework is a big lift, but I'd hope that you'd at least consider prioritizing fixing the broken connector such that it's possible to send dynamic attachments via ChannelData, like is done for unsupported attachments on other channels. If this and #97 are both just going to be closed without any remediation, then the GroupMe channel is fundamentally unusable for a huge swath of very basic and important channel functionality. 

It's a shame that the channel connectors (or at least those that don't depend on any undocumented APIs) aren't open source like the core framework - were that the case, I'd personally take a stab at getting at least minimal viable attachment support functioning correctly.
