### ISSUE TITLE
[Teams] Images sent from teams to bot are not accessible

### ISSUE THREAD

**Issue by jmnsf** [microsoft/BotFramework-Services#102]
**Issue:** When a user sends an image attachment to a bot via MS Teams, the attachment's URL is not accessible. For example:

```
λ curl -v https://smba.trafficmanager.net/emea/v3/attachments/0-weu-d8-c0eefd41d5780e60966d61f934e5de0b/views/original
*   Trying 52.166.139.91...
* TCP_NODELAY set
* Connected to smba.trafficmanager.net (52.166.139.91) port 443 (#0)
* schannel: SSL/TLS connection with smba.trafficmanager.net port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 188 bytes...
* schannel: sent initial handshake data: sent 188 bytes
* schannel: SSL/TLS connection with smba.trafficmanager.net port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with smba.trafficmanager.net port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with smba.trafficmanager.net port 443 (step 2/3)
* schannel: encrypted data got 1024
* schannel: encrypted data buffer: offset 5120 length 5120
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with smba.trafficmanager.net port 443 (step 2/3)
* schannel: encrypted data got 894
* schannel: encrypted data buffer: offset 6014 length 6144
* schannel: sending next handshake data: sending 158 bytes...
* schannel: SSL/TLS connection with smba.trafficmanager.net port 443 (step 2/3)
* schannel: encrypted data got 51
* schannel: encrypted data buffer: offset 51 length 6144
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with smba.trafficmanager.net port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /emea/v3/attachments/0-weu-d8-c0eefd41d5780e60966d61f934e5de0b/views/original HTTP/1.1
> Host: smba.trafficmanager.net
> User-Agent: curl/7.55.1
> Accept: */*
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 254
* schannel: encrypted data buffer: offset 254 length 103424
* schannel: decrypted data length: 225
* schannel: decrypted data added: 225
* schannel: decrypted data cached: offset 225 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 225 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 225
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 401 Unauthorized
< Content-Length: 61
< Content-Type: application/json; charset=utf-8
< Server: Microsoft-HTTPAPI/2.0
< Date: Mon, 05 Aug 2019 16:02:55 GMT
<
{"message":"Authorization has been denied for this request."}
```

**Expected behavior:** Bot should be able to access the image.

The full activity received from the bot framework is as follows:
```elixir
%{
  "attachments" => [%{
    "contentType" => "image/*", 
    "contentUrl" => "https://smba.trafficmanager.net/emea/v3/attachments/0-weu-d8-c0eefd41d5780e60966d61f934e5de0b/views/original"
  }, 
  %{
    "content" => "<div><div>\n<div><span><img height=\"250\" src=\"https://eu-api.asm.skype.com/v1/objects/0-weu-d8-c0eefd41d5780e60966d61f934e5de0b/views/imgo\" width=\"360.9913793103448\" id=\"x_0-weu-d8-c0eefd41d5780e60966d61f934e5de0b\" itemscope=\"\" itemtype=\"http://schema.skype.com/AMSImage\" style=\"vertical-align:bottom; width:360px; height:250px\"></span>\n<div>&nbsp;</div>\n</div>\n\n<div>teste</div>\n</div>\n</div>", 
    "contentType" => "text/html"
  }], 
  "channelData" => %{
    "tenant" => %{
      "id" => "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    }
  }, 
  "channelId" => "msteams", 
  "conversation" => %{
    "conversationType" => "personal", 
    "id" => "a:1zOmgmxm-RKD3zj0OiXMiiQyRjw79b1kEWltTL1MzJMa9xot5KqtD_zFJetsDqnkvVQ8TDutkQH71ytqR3Dw4sV2R_uU38nF-tmfJBTnVfiWRSOt_4frSPZewdj5od5I1", 
    "tenantId" => "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  }, 
  "entities" => [%{
    "country" => "US", 
    "locale" => "en-US", 
    "platform" => "Windows", 
    "type" => "clientInfo"
  }], 
  "from" => %{
    "aadObjectId" => "c55e5aa7-caea-4cf2-b21a-eea6c4c431fb", 
    "id" => "29:1Z8yBsRaJGHEORpb60D-RZr8hQlm3OHGsaj0CRPYuWeAfuHaQhYK2CWR97ZTW1dCs0Z8-tS_OJMXtjte7o1Pv4A", 
    "name" => "João"
  }, 
  "id" => "1565020147508", 
  "localTimestamp" => "2019-08-05T16:49:07.5239574+01:00", 
  "locale" => "en-US", 
  "recipient" => %{
    "id" => "28:b0cbbf6c-5c36-4106-b22f-6145eafbbe26", 
    "name" => "Bot"
  }, 
  "serviceUrl" => "https://smba.trafficmanager.net/emea/", 
  "text" => "\n\n \n\n\nteste\n\n", 
  "textFormat" => "plain", 
  "timestamp" => "2019-08-05T15:49:07.5239574Z", 
  "type" => "message"
}
```

Also note the `src` attribute in `content` that appears to be truncated (and also doesn't work).

**Steps to reproduce:**
1. Use the snipping tool anywhere on your screen.
2. Paste it onto a private message to a bot. Example:
![image](https://user-images.githubusercontent.com/6831662/62485628-1e7d4300-b7b5-11e9-96ae-e0200d699410.png)
3. Send.

**Comment by dmvtech** [comment]
As the error states, this is a permission issue. There is no authentication supplied for that request.

The good news is that Teams supplies an additional property in the message content called downloadUrl. This ulr contains a temporary auth token to retrieve the content from the location (ODfB).
Here is a Node/JavaScript example no how you could make to handleIncomingAttachment. Let me know if you would like a C# one.
```
let isteams = false;
        if(turnContext.activity.channelId === "msteams") {
            isteams = true;
        }

        // Prepare Promises to download each attachment and then execute each Promise.
        const promises = turnContext.activity.attachments.map(attachment => this.downloadAttachmentAndWrite(attachment, isteams));
```

And downloadAttachmentAndWrite:
```
let url = "";
        //console.log(turnContext);
        if (isteams) {
            url = attachment.content.downloadUrl;
        } else {
            // Retrieve the attachment via the attachment's contentUrl.
            url = attachment.contentUrl;
        }
```

**Comment by jmnsf** [comment]
Hi @dmvtech, thanks for the response. There is no `downloadUrl` in the content however, that activity object I provided is the full payload that's coming from Bot Framework. I've added steps to reproduce in the original post.

**Comment by SidU** [comment]
Bot needs to provide the bearer token to download the attachment. Here's some sample illustrating how to do this:
```
                        var token = await new MicrosoftAppCredentials(microsoftAppId, microsoftAppPassword).GetTokenAsync();

                        using (var httpClient = new HttpClient())
                        {
                            httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                            var attachmentContent = await httpClient.GetAsync(attachment.ContentUrl);
                        }
```

**Comment by w-piotr** [comment]
Hi,
As this has been reported as a bug I would like to mention one more issue regarding copy-paste attachments. As you download it there is no information what is the extension of the attachment. For the attachments uploaded using the paperclip icon 
![image](https://user-images.githubusercontent.com/49780873/63443436-1835ca80-c435-11e9-8979-9a69e9c1dc7d.png)
there is a Name property in the Attachment object which contains the extension but the copy-paste attachments Name property is null.

**Comment by jmnsf** [comment]
@SidU thanks for the suggestion, but I'm getting 403s even with the bot's bearer token.

**Comment by SidU** [comment]
What is the serviceUrl value that you are issuing the GET against to fetch
the image?

**Comment by jmnsf** [comment]
@SidU none, I'm accessing the attachment's URL directly: `https://smba.trafficmanager.net/emea/v3/attachments/0-weu-d8-c0eefd41d5780e60966d61f934e5de0b/views/original"`

**Comment by hcyang** [comment]
@SidU, this issue has been reassigned to you, please take a look. Thanks.

**Comment by siduppal** [comment]
@jmnsf can you pl share a self contained repro of the issue?

**Comment by jmnsf** [comment]
@siduppal I could try, but how would that look? The issue is with the `JSON` payload sent by the bot framework on behalf of MSTeams to the bot endpoint. Any HTTP server at the endpoint works for a repro.

**Comment by Wajeed-msft** [comment]
@jmnsf - I tried featching inline images and it is working fine for me. Could you please share code snippet which can help us repro this?

**Comment by jmnsf** [comment]
@Wajeed-msft I still don't know what code you're looking for exactly. The issue doesn't appear to be in code, it's in accessing the `contentUrl` sent by MSTeams. You can repro this by pasting `https://smba.trafficmanager.net/emea/v3/attachments/0-weu-d8-c0eefd41d5780e60966d61f934e5de0b/views/original` in your browser. You have access to my bot, so you can try pasting an image as I described in this issue and I'll give you the link to that.

**Comment by Wajeed-msft** [comment]
These URLs need Bot authentication. Could you please share fiddler trace with request/response for downloading the image?

**Comment by jmnsf** [comment]
@Wajeed-msft thanks for the suggestion, I retried the request with the bot's authentication headers and was able to read the content. I must've done something wrong [here](https://github.com/microsoft/BotFramework-Services/issues/102#issuecomment-524801584)

So the URL in `content_url` is fetchable, but the URL inside `content` is not. It also looks mangled. RE fiddler, I've installed it and was able to intersect the request, though it's mostly HTTPS handshake data.

**Comment by stevengum** [comment]
@Wajeed-msft are there any other steps you can recommend for @jmnsf?

**Comment by Wajeed-msft** [comment]
@jmnsf- Are you still facing issues with image download?

**Comment by jmnsf** [comment]
@Wajeed-msft the link that's embedded in `content` is still not working, even with authentication. It looks mangled. I'm having to "parse" the HTML in content and replace the broken link with an authorized one based on the ID attribute which feels hacky and unnecessary. If the Bot Framework can generally send a pre-authorized `downloadUrl` for attachments, it would be expected that all URLs be like this, both the ones in `contentUrl` and `content`.

**Comment by clearab** [comment]
Can you send an example of what you mean by "garbled"? I've been unable to reproduce the behavior you're describing.

**Comment by jmnsf** [comment]
@clearab there's one [here](https://github.com/microsoft/BotFramework-Services/issues/102#issue-476942480) (check the `src` attribute):

> `"content" => "<div><div>\n<div><span><img height=\"250\" src=\"https://eu-api.asm.skype.com/v1/objects/0-weu-d8-c0eefd41d5780e60966d61f934e5de0b/views/imgo\" width=\"360.9913793103448\" id=\"x_0-weu-d8-c0eefd41d5780e60966d61f934e5de0b\" itemscope=\"\" itemtype=\"http://schema.skype.com/AMSImage\" style=\"vertical-align:bottom; width:360px; height:250px\"></span>\n<div>&nbsp;</div>\n</div>\n\n<div>teste</div>\n</div>\n</div>"`

**Comment by johnataylor** [comment]
@clearab do you have any update on this?

**Comment by clearab** [comment]
Hi - my apologies for the delayed response. Can you please confirm for me that you're using the `content` field from the `attachments` array, and not the message?

**Comment by jmnsf** [comment]
Hi @clearab, I am using the one in attachments. I don't think there's any other that I have available, I posted the full payload.

**Comment by clearab** [comment]
In the original payload you posted, attachments.contentUrl is not garbled. That URL should be working to retrieve the image as expected.

"attachments" => [%{
    "contentType" => "image/*", 
    "contentUrl" => "https://smba.trafficmanager.net/emea/v3/attachments/0-weu-d8-c0eefd41d5780e60966d61f934e5de0b/views/original"
  }

**Comment by jmnsf** [comment]
@clearab yep, I mentioned that it's possible to pull that URL [here](https://github.com/microsoft/BotFramework-Services/issues/102#issuecomment-534130615). The issue is we're talking about embedded images here; it's not enough to pull the image, I have to know where _in the content_ each attachment is.

This would be easier if the URLs inside `content` were valid, since I'd only have to find-and-replace with an authorized URL. However, it's mangled, so we can't. What I'm doing right now as a workaround is running a partial match on the `contentUrl` and each URL inside `content` and replacing with an authed URL. This isn't ideal since it only takes a small change in the URL structure by Microsoft Teams and my code stops working.

**Comment by pintux** [comment]
Hi,
any news about this issue?
I'm trying to get a image from  https://smba.trafficmanager.net/emea/v3/attachments/0-weu-d14-098241ee675ddf7fe06b1c223d8e2e1a/views/original using Bearer Auth using my Bot password but it always return me a 401 `{"message":"Authorization has been denied for this request."}`

**Comment by PylotLight** [comment]
I am also facing the same issue, trying to find a useable url to grab the image.
The whole payload is here:
`{"contentType":"image/*","contentUrl":"https://smba.trafficmanager.net/apac/v3/attachments/0-sa-d5-660912596a9c791800d78d4eba19eddf/views/original","content":null,"name":null,"thumbnailUrl":null}`
The attachment code:
`var attachment = turnContext.Activity.Attachments?.FirstOrDefault();`

Any suggestions?

**Comment by Wajeed-msft** [comment]
Hi @PylotLight - Could you please try [File Upload sample code](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet#example-using-the-bot-framework-sdk) and let me know if it works for you? If it doesn't work, could you please share your App Manifest which we could test at our end?

**Comment by PylotLight** [comment]
> Hi @PylotLight - Could you please try [File Upload sample code](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet#example-using-the-bot-framework-sdk) and let me know if it works for you? If it doesn't work, could you please share your App Manifest which we could test at our end?

I ended up finding another sample for getting a token to download from the secure link.
So that'll work for now.

**Comment by craigcliff** [comment]
Hi @PylotLight, do you mind please sharing the sample that you used?

Thanks

**Comment by PylotLight** [comment]
@craigcliff Hey Try this:
I used this to handle attachments that are uploaded to onedrive/sharepoint, and those uploaded directly to teams, might be a better way, but at least it works.

```
if (attachment.ContentUrl.Contains("donvale-my.sharepoint.com"))
{                
    SharepointJson SharepointObject =  JsonConvert.DeserializeObject<SharepointJson>(attachmentJson);
    client.DefaultRequestHeaders.Clear();
    imageresponse = client.GetByteArrayAsync(SharepointObject.content.downloadUrl).Result;
}
else
{
    AuthenticationConfig config = AuthenticationConfig.ReadFromJsonFile("appsettings.json");
    var token = await new MicrosoftAppCredentials(config.MicrosoftAppId, config.MicrosoftAppPassword).GetTokenAsync();
    client.DefaultRequestHeaders.Clear();
    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
    imageresponse = client.GetByteArrayAsync(attachment.ContentUrl).Result;
}
```

**Comment by craigcliff** [comment]
Thank you pylotlight... Much appreciated.

**Comment by yashna-shravani** [comment]
> Bot needs to provide the bearer token to download the attachment. Here's some sample code illustrating how to do this:
> 
> ```
>                         var token = await new MicrosoftAppCredentials(microsoftAppId, microsoftAppPassword).GetTokenAsync();
> 
>                         using (var httpClient = new HttpClient())
>                         {
>                             httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
>                             var attachmentContent = await httpClient.GetAsync(attachment.ContentUrl);
>                         }
> ```

Can anybody help with downloading the image through ContentUrl in Python. Not sure how authentication is done for Bot in MSTeams developed using SDK Python in this case

**Comment by DireWolfCoder** [comment]
> > Bot needs to provide the bearer token to download the attachment. Here's some sample code illustrating how to do this:
> > ```
> >                         var token = await new MicrosoftAppCredentials(microsoftAppId, microsoftAppPassword).GetTokenAsync();
> > 
> >                         using (var httpClient = new HttpClient())
> >                         {
> >                             httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
> >                             var attachmentContent = await httpClient.GetAsync(attachment.ContentUrl);
> >                         }
> > ```
> 
> Can anybody help with downloading the image through ContentUrl in Python. Not sure how authentication is done for Bot in MSTeams developed using SDK Python in this case

Did you find a way to get it done in python ?

I've gotten the bearer token successfully like this

import requests

headers = {
    'Host': 'login.microsoftonline.com',
    'Content-Type': 'application/x-www-form-urlencoded'
}


data = {
    'grant_type': 'client_credentials',
    'client_id': app_id,
    'client_secret': app_password,
    'scope': 'https://api.botframework.com/.default'
}
res = requests.post(url = 'https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token', data = data, headers = headers)

# %%
token = res.json()['access_token']

. But when I request the image I get 403 error

**Comment by DireWolfCoder** [comment]
@yashna-shravani did you find a solution for this already?

**Comment by yashna-shravani** [comment]
Yeah I was able to download it by authenticating first. Have to check the
exact code. Its been a while.

**Comment by DireWolfCoder** [comment]
That would be awesome if you cound check it, Feels like I've checked the whole internet for an answer

The Following is my request: 

import requests

headers = {'Authorization': f'Bearer {token}', 'Content-Type': 'image/*'}
url = "https://smba.trafficmanager.net/emea/v3/attachments/0-weu-d17-870639fec793510ad8fedf1215d9f152/views/original"
response = requests.get(url, headers=headers)

response.content = b'{"error":{"code":"BotError","message":"Access Forbidden"}}

**Comment by yashna-shravani** [comment]
Authenticate using
credentials =MicrosoftAppCredentials(appid, apppasswrd)
Token= credentials.get_access_token()

Request.get(file.content_url, headers)

//use above token in headers

**Comment by Benji-py** [comment]
Still getting the same error, Do I need to provide the some additional access rights to the bot application?

This is my code: 

from botframework.connector.auth import MicrosoftAppCredentials
import requests

credentials = MicrosoftAppCredentials(app_id, app_password)
token = credentials.get_access_token()

headers = {'Authorization': f'Bearer {token}','Content-Type': 'image/*'}
url = "https://smba.trafficmanager.net/emea/v3/attachments/0-weu-d17-c56fcfe6fe7c1e8cb9cf6c2ad6d3cc4d/views/original"
response = requests.get(url, headers=headers)

print(response.content) # = b'{"error":{"code":"BotError","message":"Access Forbidden"}}

**Comment by DireWolfCoder** [comment]
Thanks for conversing with me! It got me rethink my authentication and turns out I was using the wrong App to authenticate. It works now!

**Comment by NuxXDev** [comment]
> Hi, As this has been reported as a bug I would like to mention one more issue regarding copy-paste attachments. As you download it there is no information what is the extension of the attachment. For the attachments uploaded using the paperclip icon ![image](https://user-images.githubusercontent.com/49780873/63443436-1835ca80-c435-11e9-8979-9a69e9c1dc7d.png) there is a Name property in the Attachment object which contains the extension but the copy-paste attachments Name property is null.

@w-piotr
Did you ever find a way to access copy and pasted images? I am having the same issue.  I can access image and attachments that were added using the paperclip.

**Comment by elabbarw** [comment]
I managed to solve my issue with MicrosoftAppCredentials by including the tenant id. e.g:
MicrosoftAppCredentials(botappid,botapsecret,channel_auth_tenant='tenantid')

**Comment by HarishBisht-Enzo** [comment]
> I managed to solve my issue with MicrosoftAppCredentials by including the tenant id. e.g: MicrosoftAppCredentials(botappid,botapsecret,channel_auth_tenant='tenantid')

Hi, Could you please share the code snippet of how you were able to resolve this issue.

**Comment by mrkog3** [comment]
Hello @HarishBisht-Enzo  in python the problem solve with this code:

`from botframework.connector.auth import MicrosoftAppCredentials
import requests

file=turn_context.activity.attachments[0]
url=file.content_url
token=MicrosoftAppCredentials(app_id,app_password)
headers = {'Authorization': 'Bearer '+' '+token.get_access_token()}
response = requests.get(url, headers=headers)`
 
best wishes!

**Comment by jobygeorge99** [comment]
> Thanks for conversing with me! It got me rethink my authentication and turns out I was using the wrong App to authenticate. It works now!

@DireWolfCoder
How did you do it, could show the code snippet?
