### ISSUE TITLE
MSTeams: Carousel Card not displaying recently.

### ISSUE THREAD

**Issue by droidriz** [microsoft/BotFramework-Services#103]
Version: SDK V3 Bot Framework
Deployment : Azure
Language : C#
Adpative card Verison : 1.0
Bot Builder Version : 3.15.3
Bot Connector Version : 3.15.3 or tried even 3.20.*
Channel: MSTeams

we developed a bot which takes some input, according to it displays 9 adaptive cards in carousel format.
this was working till day before yesterday. the bot was showing carousel cards in teams channel without any errors but suddenly from today i am facing an error just when bot reply in attachment the carousel card.

The main exception which it gives is : 
Exception: Microsoft.Bot.Connector.ErrorResponseException: Operation returned an invalid status code 'BadRequest

Traced in local with ngrok
`Exception: Microsoft.Bot.Connector.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
at Microsoft.Bot.Connector.Conversations.d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Connector.ConversationsExtensions.d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.AlwaysSendDirect_BotToUser.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.InputHintQueue.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.AutoInputHint_BotToUser.d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.MapToChannelData_BotToUser.d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.LogBotToUser.d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.DialogContext.d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()`

**Comment by peterinnesmsft** [comment]
Looking at the description of this, this looks similar to the issue that I also filed. Our bot started receiving HTTP 400 responses when sending replies to users seemingly out of nowhere. I've spent a few hours investigating and I'm positive that there hasn't been a code change in my bot to cause the regression.

What I seem to have been able to pin this down to is that request payloads to the Bot Connector API over a certain size seem to be causing the issue. When I stripped down some of the content in our reply that we send, the Connector service seems to accept it.

If you're able to easily test sending a smaller payload in the request, it may be good to see if you can lend any credence to my theory.

**Comment by droidriz** [comment]
> Looking at the description of this, this looks similar to the issue that I also filed. Our bot started receiving HTTP 400 responses when sending replies to users seemingly out of nowhere. I've spent a few hours investigating and I'm positive that there hasn't been a code change in my bot to cause the regression.
> 
> What I seem to have been able to pin this down to is that request payloads to the Bot Connector API over a certain size seem to be causing the issue. When I stripped down some of the content in our reply that we send, the Connector service seems to accept it.
> 
> If you're able to easily test sending a smaller payload in the request, it may be good to see if you can lend any credence to my theory.


Yes, you are correct i also changed from 10 adaptive cards to 2 in carousel card and it seems to work.
but previously it was working with 10 and as teams support upto only 10 cards at a time in carousel due to limitation we limited our requirement to 10 now we are facing this issue

**Comment by stevkan** [comment]
Attempting to repro the issue to verify the bug. Will keep you posted.

**Comment by stevkan** [comment]
@droidriz, after a fair amount of wrangling, I am able to produce a carousel of adaptive cards in Teams. Initially, I encountered the same issue as you had but I made a few adjustments that I would like you to test.

For clarity, my starting point was the [cards-CarouselCards](https://github.com/microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp/cards-CarouselCards) sample from the v3 C# BotBuilder-Samples repo.

First, I updated BotBuilder nuget packages to v3.15.3.

Next, if you are not already using it, switch to the AdaptiveCards package v.1.2.2 and uninstall the older Microsoft.AdaptiveCards package. I don't know how your project is structured, but the [cards-AdaptiveCards](https://github.com/microsoft/BotBuilder-Samples/tree/v3-sdk-samples/CSharp/cards-AdaptiveCards) sample references `using global::AdaptiveCards;`. You will need to replace that with `using AdaptiveCards;`.

Lastly, structure you code to match the following. Again, I don't know how your project is setup, so this _may_ require some tinkering. I've purposely kept the code simple so it's easier to follow, implement, and test as you add in new elements. Once you get it working you can experiment with moving code around.

If of use, I have included my packages.config below in case you suspect another package or package version might be blocking.

Hope of help!

```csharp
namespace CarouselCardsBot
{
    using System;
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using AdaptiveCards;
    using Microsoft.Bot.Builder.Dialogs;
    using Microsoft.Bot.Connector;

    [Serializable]
    public class CarouselCardsDialog : IDialog<object>
    {
        public async Task StartAsync(IDialogContext context)
        {
            context.Wait(this.MessageReceivedAsync);
        }

        public virtual async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> result)
        {
            var reply = context.MakeMessage();

            reply.AttachmentLayout = AttachmentLayoutTypes.Carousel;
            reply.Attachments = new List<Attachment>();

            var card1 = new AdaptiveCard("1.0");
            card1.Actions.Add(new AdaptiveCards.AdaptiveSubmitAction()
            {
                Data = "card1",
                Title = "card1"
            });

            var card2 = new AdaptiveCard("1.0");
            card2.Actions.Add(new AdaptiveCards.AdaptiveSubmitAction()
            {
                Data = "card2",
                Title = "card2"
            });

            var card3 = new AdaptiveCard("1.0");
            card3.Actions.Add(new AdaptiveCards.AdaptiveSubmitAction()
            {
                Data = "card3",
                Title = "card3"
            });

            reply.Attachments.Add(new Attachment()
            {
                Content = card1,
                ContentType = AdaptiveCards.AdaptiveCard.ContentType
            });
            reply.Attachments.Add(new Attachment()
            {
                Content = card2,
                ContentType = AdaptiveCards.AdaptiveCard.ContentType
            });
            reply.Attachments.Add(new Attachment()
            {
                Content = card3,
                ContentType = AdaptiveCards.AdaptiveCard.ContentType
            });

            await context.PostAsync(reply);

            context.Wait(this.MessageReceivedAsync);
        }
    }
}
```

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AdaptiveCards" version="1.2.2" targetFramework="net46" />
  <package id="Autofac" version="4.2.1" targetFramework="net46" />
  <package id="Chronic.Signed" version="0.3.2" targetFramework="net46" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net46" />
  <package id="Microsoft.Azure.DocumentDB" version="1.11.0" targetFramework="net46" />
  <package id="Microsoft.Azure.KeyVault.Core" version="1.0.0" targetFramework="net46" />
  <package id="Microsoft.Bot.Builder" version="3.15.3" targetFramework="net46" />
  <package id="Microsoft.Bot.Builder.Azure" version="3.2.5" targetFramework="net46" />
  <package id="Microsoft.Bot.Builder.History" version="3.15.3" targetFramework="net46" />
  <package id="Microsoft.Bot.Connector" version="3.15.3" targetFramework="net46" />
  <package id="Microsoft.CSharp" version="4.5.0" targetFramework="net46" />
  <package id="Microsoft.Data.Edm" version="5.6.4" targetFramework="net46" />
  <package id="Microsoft.Data.OData" version="5.6.4" targetFramework="net46" />
  <package id="Microsoft.Data.Services.Client" version="5.6.4" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Logging" version="1.1.4" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.4.403061554" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Protocols" version="2.1.4" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="2.1.4" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.1.4" targetFramework="net46" />
  <package id="Microsoft.Rest.ClientRuntime" version="2.3.4" targetFramework="net46" />
  <package id="Microsoft.WindowsAzure.ConfigurationManager" version="3.2.3" targetFramework="net46" />
  <package id="Newtonsoft.Json" version="12.0.2" targetFramework="net46" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.1.4" targetFramework="net46" />
  <package id="System.Spatial" version="5.6.4" targetFramework="net46" />
  <package id="WindowsAzure.Storage" version="7.2.1" targetFramework="net46" />
</packages>
```

![adaptiveCard](https://user-images.githubusercontent.com/18403946/63904485-0076bd00-c9c6-11e9-8c9c-cefa1e4c94d7.gif)

**Comment by stevkan** [comment]
Closing this issue as resolved. If you have further questions or concerns regarding this issue, please feel free to reopen.
