### ISSUE TITLE
Telegram connector cannot handle empty text in hero cards

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Services#104]
When you send a message activity to Telegram, it works fine when the activity's `text` property is empty. It also works fine if you send a hero card with only buttons and no `title`, `subtitle`, or `text` properties. However, if you set an empty string as one of those properties, you will get an error like this:

```json
{
  "error": {
    "code": "ServiceError",
    "message": "Bad Request: message text is empty",
    "innerHttpError": {
      "statusCode": 400,
      "body": {
        "ok": false,
        "description": "Bad Request: message text is empty",
        "error_code": 400
      }
    }
  }
}
```

Telegram seems to be a channel that can separate one activity into multiple messages in situations like these. I suspect what's going on behind the scenes is that the connector looks at a hero card's `title`, `subtitle`, and `text` properties and tries to form a message out of them if they're not null. However, it runs into problems if the only available non-null strings are empty.

At least one customer is having issues because of this: https://github.com/microsoft/BotBuilder-V3/issues/157

## Repro steps

1. Send a hero card to Telegram where at least one of `title`, `subtitle`, or `text` is an empty string and all of them are null or empty
2. See error

## Expected behavior

The Telegram connector should treat empty strings the same as null in this case.

**Comment by arturl** [comment]
Fix available -- should be deployed before 10/18

**Comment by arturl** [comment]
I sent a hero card with empty title, subtitle and text and it worked fine:
![image](https://user-images.githubusercontent.com/1875734/66968389-c6c34980-f039-11e9-8c87-930bba7f12bb.png)

If you still need a fix, please attach the exact repro case.
Do I understand correctly that using `null` instead of empty string works? If so, just use null.

**Comment by v-kydela** [comment]
I'm very sorry Artur! It looks like I did leave out some vital information from the original post. This can't be reproduced with just the empty strings, and it also can't be reproduced by including images in the card. It only happens when the card has buttons.

Here's a repro for C#:

```c#
public static async Task TestEmptyHeroCardAsync(ITurnContext turnContext, CancellationToken cancellationToken)
{
    HeroCard heroCard = new HeroCard(string.Empty, buttons: new List<CardAction>
    {
        new CardAction("imBack", "imBack title", value: "imBack value"),
    });

    await turnContext.SendActivityAsync(MessageFactory.Attachment(heroCard.ToAttachment()), cancellationToken);
}
```

Here's a repro for Postman:

```http
POST /v3/conversations/123456789/activities HTTP/1.1
Host: telegram.botframework.com
Content-Type: application/json
Authorization: Bearer <token>
Cache-Control: no-cache
Postman-Token: <guid>

{
  "type": "message",
  "attachments": [
    {
      "contentType": "application/vnd.microsoft.card.hero",
      "content": {
      	"title": "",
      	"buttons": [
      	  {
      	    "type": "imBack",
      	    "title": "imBack title",
      	    "value": "imBack value"
      	  }
      	]
      }
    }
  ],
  "from": {
    "id": "YourBot",
    "name": "YourBot"
  }
}
```

**Comment by arturl** [comment]
Fix available. Deployment ETA 10/24

**Comment by arturl** [comment]
Fix deployed
