### ISSUE TITLE
[Teams] Bot does not get notified on first install

### ISSUE THREAD

**Issue by jmnsf** [microsoft/BotFramework-Services#107]
We're testing a bot in Microsoft Teams. The manifest is generated by the App Tools inside MS Teams itself and the app is installed as a Custom App. When the bot is installed we generally receive a message such as this one:

```elixir
%{
  "channelData" => %{
    "eventType" => "teamMemberAdded", 
    "team" => %{
      "aadGroupId" => "514f94e8-1ed9-418c-be23-0e82f1cf2d06", 
      "id" => "19:88e9c30e8bc14882b22cc6921095fddd@thread.skype", 
      "name" => "Bot Test"
    }, 
    "tenant" => %{"id" => "6db182dd-f7ca-4263-a028-d2fcf2c2fc5a"}
  }, 
  "channelId" => "msteams", 
  "conversation" => %{
    "conversationType" => "channel", 
    "id" => "19:88e9c30e8bc14882b22cc6921095fd86@thread.skype", 
    "isGroup" => true
  }, 
  "from" => %{
    "aadObjectId" => "a53d7526-d0e9-436f-9443-ddb317ef3608", 
    "id" => "29:10DR04CMJxmhh26fbS6c0a8HgJdWNHT1t1NkG-v1jDm76t-sBYaA8FhiXhEJqAVzPgfb6N20xIn5r76hZ4YtYIA"
  }, 
  "id" => "f:c5591677-3844-e439-e314-3ca087b98546", 
  "membersAdded" => [
    %{"id" => "28:2e4adddd-3fd9-4d9a-ab53-e362621e9b7e"}
  ], 
  "recipient" => %{
    "id" => "28:2e4adddd-3fd9-4d9a-ab53-e362621e9b7e", 
    "name" => "Bot"
  }, 
  "serviceUrl" => "https://smba.trafficmanager.net/emea/", 
  "timestamp" => "2019-04-24T00:44:22.541Z", 
  "type" => "conversationUpdate"
}
```

I say "generally" because the very first time the bot is installed in the tenant/team, we don't get _anything_ from the Bot Framework and are completely blind to the fact that the app was installed. We also don't get any messages sent to the bot and the client must recourse to re-installing the app for it to work.

Any help/feedback on how to improve this is appreciated.

**Comment by stevkan** [comment]
When testing, how are you interacting with the bot? If this is personal scoped, then a conversationUpdate is sent **only** once to the bot regardless if the bot is removed and reinstalled.

You can read more about managing conversationUpdate and memberAdded/teamMemberAdded in different team member environments [here](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-notifications#team-member-or-bot-addition).

Please let me know if you have other questions or this doesn't address your concern.

**Comment by jmnsf** [comment]
@stevkan it's team scoped, though most interactions are personal. It's very hard to test this since it only happens in the very first install onto a team; on subsequent (un)installs we receive `conversationUpdates` as expected.

We've had customers install the bot, message it directly multiple times, and nothing arrives on our side. It's become frustrating because the only solution we have to this is "please uninstall and re-install the app" which doesn't sound professional.

**Comment by stevkan** [comment]
Can you post the manifest that is generated for installing this as a Custom App? Can you also post your relevant code (onMembersAdded, onConversationUpdate, etc.)?

**Comment by stevkan** [comment]
@jmnsf, are you still needing help with this issue?

**Comment by jmnsf** [comment]
@stevkan sure:

```javascript
{
    "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json",
    "manifestVersion": "1.5",
    "version": "0.0.1",
    "id": "3ac8829d-fad1-46ac-9d9e-435b5d869dc0",
    "packageName": "com.skoach.app",
    "developer": {
        "name": "Skoach",
        "websiteUrl": "https://skoach.com",
        "privacyUrl": "https://skoach.com/tos",
        "termsOfUseUrl": "https://skoach.com/tos"
    },
    "icons": {
        "color": "color.png",
        "outline": "outline.png"
    },
    "name": {
        "short": "SkoachDev",
        "full": ""
    },
    "description": {
        "short": "Skoach improves your team's performance through cultural change",
        "full": "Skoach leverages the latest research in Behavioral Science and Habit Creation to promote healthy habits around the critical soft skills that drive high-performing environments. We help your team create new habits around autonomy, growth and feeling safe at work."
    },
    "accentColor": "#FFFFFF",
    "bots": [
        {
            "botId": "2e4addff-3fd9-4d9a-ab53-e362621e9b7e",
            "scopes": [
                "team"
            ],
            "supportsFiles": true,
            "isNotificationOnly": false
        }
    ],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": []
}
```

Not sure about the code itself since it's not even running. As mentioned on the issue, we're not receiving any events from the BF.

We haven't had any new installs recently, and so haven't seen the bug either.

**Comment by stevkan** [comment]
I've tried repro'ing the issue using your manifest as a guide, but I am unable to do so successfully.
A few questions:
- At what point in your code are you trying to capture the events (e.g. ConversationUpdate)?
- You mention the bot is 'team' scoped though most customer interactions are 'personal'. Have you tried adding the 'personal' scope to see how that might affect the outcome?
- Have you installed this app as a custom app multiple times? If so, are you uninstalling the app first before re-installing?
- If the bot is installed with a 'team' scope, how are customers able to install/uninstall the bot? Testing this with a team member showed he was unable to actually uninstall the bot. It would go thru the motion, but would immediately pop back fully functional.

**Comment by stevkan** [comment]
Hi @jmnsf, just checking in if you are still needing help on this issue.

**Comment by stevkan** [comment]
Closing the issue due to a lack of response. If the issue persists, please feel free to reopen.
