### ISSUE TITLE
Suggested Actions do not work in Teams (web or desktop)

### ISSUE THREAD

**Issue by mikeydavison** [Microsoft/BotFramework-Services#11]
I created a bot that uses the suggested actions functionality.  It works as expected in the emulator and in web chat.  In Teams the suggested actions do not show up.  I deployed the suggested actions sample bot and observed the same behaviour.

**Comment by EricDahlvang** [comment]
Hi @mikeydavison 

Teams does not render Suggested Actions.  The [Channel Inspector](https://docs.botframework.com/en-us/channel-inspector/channels/Teams?f=SuggestedActions&e=example1) is useful for determining which channels support which features.
