### ISSUE TITLE
Telegram message sent in channel with "inline mode" disabled results in error

### ISSUE THREAD

**Issue by stevkan** [microsoft/BotFramework-Services#110]
When "Inline mode" is disabled for a bot and a user sends a message within a channel containing the bot then this error is produced:

[onTurnError]: Error: Bad Request: inline keyboard expected

Associated activity prior to error, if of use:
```
{ type: 'message',
  id: '25AMeushyaQ',
  timestamp: 2019-08-08T03:14:50.725Z,
  serviceUrl: 'https://telegram.botframework.com/',
  channelId: 'telegram',
  from: { id: '-1001209693181', name: 'some_channel' },
  conversation:
   { isGroup: true, id: '-1001209693181', name: 'some_channel' },
  recipient: { id: 'some_bot', name: 'some_bot' },
  text: 'hi',
  entities:
   [ { mentioned: [Object], text: 'some_bot', type: 'mention' } ],
  channelData:
   { update_id: 344945225,
       channel_post:
        { message_id: 43,
          chat:
           { id: -1001209693181,
             title: 'some_channel',
             username: 'some_channel',
             type: 'channel' },
             date: 1565234090,
             text: 'hi'
           }
        }
   }
}
```

**Comment by NickEricson** [comment]
Hi @stevkan 
Thanks for reporting this. I tried this out for a C# bot and got it to work. Here is what I did:

I created a C# echo bot and enabled Telegram. Then I enabled inline mode in Telegram (https://core.telegram.org/bots/inline).

I the bot code I looked at the Activity Channel Data, when I see an "inline_query" node I return a message (Text set to null) with Channel Data set to the "answerInlineQuery" values Telegram wants.

From telegram if I message my bot using @mybotname a message I see the results from the bot appear in Telegram.

Here is some hacked up code:

`
            var channelData = turnContext.Activity.ChannelData;
            if (channelData != null)
            {
                var kvp = (JObject)channelData;
                if (kvp.ContainsKey("inline_query"))
                {
                    var queryId = channelData.inline_query.id;

                    var answerInlineQuery = MessageFactory.Text(null);
                    dynamic outChannelData = new ExpandoObject();
                    answerInlineQuery.ChannelData = outChannelData;
                    outChannelData.method = "answerInlineQuery";
                    outChannelData.parameters = new ExpandoObject();
                    outChannelData.parameters.inline_query_id = queryId;

                    dynamic queryResults = new ExpandoObject[1];
                    outChannelData.parameters.results = queryResults;

                    queryResults[0] = new ExpandoObject();
                    queryResults[0].type = "photo";
                    queryResults[0].id = "123456789";
                    queryResults[0].photo_url = @"http://upload.wikimedia.org/wikipedia/commons/1/16/HDRI_Sample_Scene_Balls_%28JPEG-HDR%29.jpg";
                    queryResults[0].thumb_url = @"http://upload.wikimedia.org/wikipedia/commons/1/16/HDRI_Sample_Scene_Balls_%28JPEG-HDR%29.jpg";
                    queryResults[0].title = "Sample Jpeg";

                    await turnContext.SendActivityAsync(answerInlineQuery, cancellationToken);
                    return;
                }
            }
`
