### ISSUE TITLE
Facebook channel allows one character lesser than the allowed  limit for button title

### ISSUE THREAD

**Issue by thilakrajrk** [microsoft/BotFramework-Services#112]
As per Facebook [documentation](https://developers.facebook.com/docs/messenger-platform/reference/buttons/url#properties), the character limit for button text is 20 (including spaces). Exceeding this will result in three dots `...`

While using the bot framework for posting the message, it accepts only 19 characters, but if I use another framework instead of bot framework, it accepts 20 characters.

#### Below screenshot with 19 characters:

![19_chars](https://user-images.githubusercontent.com/22424377/62995080-bc8ba000-be7c-11e9-822c-8a69a508e687.PNG)

#### Adding one more character:

![20_chars](https://user-images.githubusercontent.com/22424377/62995133-ea70e480-be7c-11e9-9642-994a03583fea.PNG)

#### 20 characters (including space) :

![converse_20_chars](https://user-images.githubusercontent.com/22424377/62995292-869aeb80-be7d-11e9-96db-aa580764b13f.PNG)

#### Character length:

![converse_length](https://user-images.githubusercontent.com/22424377/62995320-a3372380-be7d-11e9-9d0e-1dca15b61ac7.PNG)

**Comment by v-kydela** [comment]
Hi @thilakrajrk - It does look like the problem is in our connector service and we've raised a bug internally. You can circumvent the bug by including your buttons in channel data rather than in an attachment. https://blog.botframework.com/2017/03/28/custom-channel-data/
