### ISSUE TITLE
Is there any documentation on the GroupMe channel's "Enable direct messaging" feature?

### ISSUE THREAD

**Issue by sphanley** [microsoft/BotFramework-Services#113]
When connecting a Bot Framework bot to the GroupMe channel, there's a checkbox for "Enable direct messaging". Checking it seems to create some sort of virtual chatroom in my GroupMe account called "BotFrameworkPrivateDMGroup", but I can't figure out what this actually allows me to do - I don't know how to send or receive DMs as my bot. Is there any documentation on how this feature is intended to be used?

**Comment by sgellock** [comment]
@sphanley thanks for opening this issue.  I've asked our support team to engage with you to see how we can help

**Comment by anusharavindrar** [comment]
@sphanley, investigating the issue and have submitted the question to our services team.

**Comment by sphanley** [comment]
@anusharavindrar thanks! Sorry to be keeping you so busy with all of these GroupMe channel questions!

**Comment by craigjensen** [comment]
Checking the "Enable direct messaging" checkbox configures the bot so that it receives direct messages sent to the GroupMe user who owns the application.  You can try it out by sending a DM to the user and  it should also be sent to your bot

**Comment by sphanley** [comment]
Interesting! So there's still no way to allow users to DM the bot directly, only by going through the owner? That's unfortunate, but makes sense based on the fact that bots can't even be @-mentioned. Thanks for the information - if there's anywhere in documentation (or even in a help tooltip on the "Enable direct messaging" checkbox) that this can be clarified, it would likely help others in the future.

**Comment by craigjensen** [comment]
Thanks for pointing this out.  I've opened a bug to add this info to the docs.

**Comment by CoHealer** [comment]
Closing as issue is resolved. Tracking bug has been opened for doc update.
