### ISSUE TITLE
URLs escaped before being passed to Slack

### ISSUE THREAD

**Issue by yoagauthier** [microsoft/BotFramework-Services#116]
### Bot Info:
- REST API used
- Active channel: Slack
- Deployment Envirnonment: Azure Bot Service

### Issue description
I try to use [Slack URL Buttons](https://api.slack.com/docs/message-attachments#attaching_link_buttons_to_a_message) by using the [channelData field](https://docs.microsoft.com/fr-fr/azure/bot-service/rest-api/bot-framework-rest-connector-channeldata?view=azure-bot-service-4.0#create-a-full-fidelity-slack-message).

Here's what looks like my channelData field : 
```
"channelData": {
    "text": "Testing Text",
    "channel": "XXXX",
    "attachments": [
      {
        "callback_id": "postBack",
        "fallback": "Testing Text",
        "actions": [
          {
            "type": "button",
            "text": "Option 1",
            "url": "https://dev.botframework.com/"
          },
          {
            "type": "button",
            "text": "Option 2",
            "value": "option-2",
            "name": "option-2"
          }
        ]
      }
    ]
  }
```
Here is what is renders : 
![image](https://user-images.githubusercontent.com/19170035/63869464-77a55480-c9b8-11e9-8a61-fad141e18fd2.png)

The URL button is missing.

### Expected Behaviour
Testing the exact same message with [Slack API Tester](https://api.slack.com/methods/chat.postMessage/test), with the following configuration : 
- channel & token filled appropriately
- text: `Testing text`
- attachments
```
<",
        "fallback": "Testing Text",
        "actions": [
          {
            "type": "button",
            "text": "Option 1",
            "url": "https://dev.botframework.com/"
          },
          {
            "type": "button",
            "text": "Option 2",
            "value": "option-2",
            "name": "option-2"
          }
        ]
      }
    ]
```
I get 
![image](https://user-images.githubusercontent.com/19170035/63869847-1b8f0000-c9b9-11e9-8ab9-27f91af7a899.png)
with button "Option 1" effectively redirecting to https://dev.botframework.com/

I expect to get the same thing using `channelData` field of Bot Service.

### Hypothesis
In [Slack documentation](https://api.slack.com/docs/message-attachments#attachment_fields), they specify that _Invalid URLs will result in a message posted with the button omitted._ So I suppose there's something with the Bot Service that messes the channelData field, probably trying to escape URLs.

When I try to send the same attachment on Slack API Tester with URL `https%3A//dev.botframework.com/`, it does not work, as with Bot Service.

Is there any way to prevent Bot Service from escaping URLs ?

**Comment by jameslew** [comment]
Further update, our developer thinks he has discovered a solution to the issue and is working on a fix.  With the US holiday next week, ETA would be end of next week; more likely would be the following week.

**Comment by yoagauthier** [comment]
Hi @jameslew , 
This is great news, thanks for getting back to me ! 

Please let me know when the fix is available so I can also update my bots.
Best !

**Comment by bwamie** [comment]
PR has been raised on this.
Fix is expected in prod in the next deployment.
@yoagauthier  @jameslew

**Comment by tsuwandy** [comment]
@bwamie, has the fix been deployed?  If so, could you close this issue?  Thanks!

**Comment by jameslew** [comment]
Yes, i can confirm this should now be deployed and in production.  Please let us know if you find otherwise.
