### ISSUE TITLE
Create button on Bot Channel Registration blade does not proceed as expected

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-Services#117]
## Repro steps

1. Go to Azure Portal
1. Create a new Bot Channel Registration
1. Input all information as needed
1. Click Create button
1. (Verify) It said "Validation successful"
1. (Verify) The Notifications button (bell) on upper-right say it is deploying

## Expected

After clicking the "Create" button, it should navigate to the deployment page, a.k.a. `DeploymentDetailsBlade`. When you create an Azure Web App, they navigate to the deployment page for status-ing. I think ABS should do the same.

Actual, the "Create" button did nothing. And before and after the deployment is completed, navigating out of the page will prompt the user saying they have unsaved changes, which looks scary to most users.

## Screenshot

After clicking on "Create" button, the validation kick off. After validation completed, it looks like this. And stay on this page forever.

![image](https://user-images.githubusercontent.com/1622400/64394092-6c31d900-d009-11e9-82f3-8cea4db0c72b.png)

**Comment by mickeydjw** [comment]
Issue being tracked in internal backlog.
