### ISSUE TITLE
Setting bot endpoint take too long time to propagate

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-Services#118]
## Repro steps

1. Go to Azure Portal
1. Find a Bot Channel Registration
1. Go to Settings blade
1. Modify the messaging endpoint to a new URL

## Expected

Within a few minutes, using Direct Line token to connect to the service, it should point to the new message endpoint.

Actual, it took 20-30 minutes to reflect the changes. This hurt dev RTT a lot because it took way longer than a coffee break. And there are no indications when the change is sync-ed to all of the servers. This negative anticipation could probably impact CSAT/DSAT.

**Comment by swagatmishra2007** [comment]
This was a bug on the service side. This is now fixed
