### ISSUE TITLE
Naming of Streaming Extension keys are inconsistent with other env var

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-Services#120]
The DL SE key is named as `DirectLineExtensionKey`. The name is not good for a few reasons:

- For cross-platform and OSS perspective, environment variable should be in `UPPER_CASE` format (upper case with underscore as hyphenation)
- Environment variables for other Azure Web App settings are in `UPPER_CASE` format as well, ABS should follow the trend

![image](https://user-images.githubusercontent.com/1622400/63969772-724b1700-ca57-11e9-8325-9961e4c2c573.png)

**Comment by Jeffders** [comment]
This is already fixed in a new version; it will be aliased as DIRECTLINE_EXTENSION_KEY
