### ISSUE TITLE
Hosting 2 or more bot with streaming extensions on a single App Service Plan

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-Services#122]
Today, Web App Azure Site Extension (ASE) talk to the bot via named pipes at `\\.\pipes\bfv4.pipes.incoming` and `\\.\pipes\bfv4.pipes.outgoing`.

If there are 2+ bots on the same App Service Plan, they will be using the same name for the named pipes.

And since bot developers may not aware that there are other apps on the same App Service Plan that also host other bots, they will be have a hard time figuring out why it is not working (they will see `EADDRINUSE` on Node.js).

Multiple Web App hosting on same App Service Plan is a very common practices and supported by Azure. See details at, https://azure.microsoft.com/en-us/pricing/details/app-service/plans/. In short, Azure allows unlimited number of Web App on a single App Service Plan.

![image](https://user-images.githubusercontent.com/1622400/64084350-886b0880-ccdf-11e9-96e0-273905923b9a.png)

**Comment by compulim** [comment]
Looks like named pipe will work across processes from different user accounts. Kernel in Azure Web Apps should namespace it.

https://docs.microsoft.com/en-us/windows/win32/ipc/named-pipe-security-and-access-rights

**Comment by Jeffders** [comment]
On an app service, there is a sandbox between web applications. This sandbox includes named pipes. So you can run multiple WebApps running DL ASE on the same App Service Plan. I've been doing that all summer and there hasn't been an issue.

However, you cannot run two WebApps on the same Azure Web App.
