### ISSUE TITLE
After deleting and recreating a Web App Bot that was connected to the GroupMe channel, I now can't update or delete the GroupMe channel connection

### ISSUE THREAD

**Issue by sphanley** [microsoft/BotFramework-Services#123]
I created a Web App Bot, which I connected to the GroupMe channel. Later on, while attempting to delete a different resource, I accidentally deleted this Web App Bot instance, so I had to recreate it. Now, after recreating it, when I try to add the GroupMe Channel to the bot, it comes up already prefilled with my Access Token and Client ID, but if I try to save or delete the channel connection, I get an error that says: 

> Unable to save. Failed to register with GroupMe with: Unauthorized ID: {a bunch of letters, numbers, and symbols}

or

> Couldn't delete. Empty service error response. ID: {a bunch of letters, numbers, and symbols}

Is there any way I can clear out this vestigial channel connection so that I can reconnect my Web App Bot to GroupMe?

**Comment by sphanley** [comment]
Update: It turns out that what was coming up prefilled was not actually the correct access token. If this fails to reproduce on your end, I'm willing to concede that this could have been some sort of browser autofill issue on my end. Apologies if that's the case!

**Comment by anusharavindrar** [comment]
@sphanley, Hello again!!! I tried to repro your issue. However, when I tried to add the GroupMe channel to the bot, it did not come up prefilled with the Access Token and Client ID. I am guessing it was due to some browser related issue which autofilled the details. Hope this helps!!

**Comment by sphanley** [comment]
Hi @anusharavindrar - thanks for looking into it, I agree that it was probably a local browser issue. Apologies for the false alarm!
