### ISSUE TITLE
Streaming extensions: Conversation ID should not be required for starting a conversation

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-Services#124]
When comparing WS/REST vs. Streaming Extensions (a.k.a. SE), using token with conversation ID burnt (JWT token).

- WS/REST
   - If conversation ID is not presented, it means creating or joining a conversation (POST)
      - The result will be a JSON with the conversation ID same as the one in the token
      - If conversation is already started, this call will succeed with HTTP 200
   - If conversation ID is presented, it means joining a conversation (GET)
- SE
   - If conversation ID is not presented, it is an error (`Incorrect conversation id in request`)

On the WS/REST API side, whether conversation ID is presented means either creating or joining a conversation. But on SE API, conversation ID is always required.

Although these 3 protocols are not exactly equal, we should reduce inconsistencies as much as we could, so we would reduce confusion from our customers' standpoint.

**Comment by Jeffders** [comment]
In current DL ASE, you can establish the socket with either a secret or token, no conversationID is needed. (i.e. Connect no longer requires a conversation ID).

You can then call StartConversation as normal.
