### ISSUE TITLE
Streaming extensions: Difference in handling Adaptive Cards

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-Services#125]
## Background

We send Adaptive Cards from a bot, but the result is different if the AC JSON is sent through Streaming Extensions vs. Web Socket.

The original JSON sent from the bot can be found at https://github.com/compulim/BotFramework-MockBot/blob/master/src/commands/Cards/Inputs.ts.

The screenshot shows JSON captured through network trace.

- Left one is Adaptive Cards sent through Streaming Extensions, same as raw JSON
- Right one is Adaptive Cards sent through Direct Line channel, altered

![image](https://user-images.githubusercontent.com/1622400/64224151-53031e00-ce8b-11e9-87bb-1e6df0f173e1.png)

- Left one is through SE, with the `Input.ChoiceSet` in "compact" mode
- Right one is through Web Socket, with the `Input.ChoiceSet` in "expanded" mode

![image](https://user-images.githubusercontent.com/1622400/64224297-eb010780-ce8b-11e9-9b87-4185622242da.png)

Looks like in SE, if `style` is not set, it default to `compact`. But in Web Socket, if it is unset, it default to `expanded` (set explicitly through Direct Line channel).

## Reproduce

1. Go to https://compulim.github.io/webchat-loader
1. Click "Dev" on the version
1. Select "MockBot"
1. Click "Open Web Chat in new window"
1. Type "card inputs"
1. Observe the output
1. Open https://compulim.github.io/webchat-loader again
1. This time, select "MockBot with Streaming Extensions"
1. Click "Open Web Chat in new window"
1. Type "card inputs"

## Expected result

They are the same. Either both in expanded state or compact state.

I am unsure if we should change the current behavior. But sending the JSON as raw as possible sounds like a better idea to me. But on the other hand, we should not change users' expectations.

## Additional context

It is probably related to this, https://github.com/microsoft/BotFramework-Services/issues/87#issuecomment-500662897.

**Comment by swagatmishra2007** [comment]
Documentation needs to be updated to highlight the difference in behaviour between directline and dl-ase

**Comment by mickeydjw** [comment]
@Jeffders Any updates on this issue?

**Comment by jameslew** [comment]
Updating documention coming shortly per @DDEfromOR

**Comment by Jeffders** [comment]
Documentation is now merged. Thanks @DDEfromOR
