### ISSUE TITLE
Recent issues in Azure Bot service

### ISSUE THREAD

**Issue by YutongTie-MSFT** [microsoft/BotFramework-Services#126]
Hi team, I am Yutong from Azure CXP team. We work with our customers and monitor the various social media channels/forums for any issues in our services. We have recently come across some issues in the bot service which seem to effect multiple customers. Could you please take a look at the following issues or forward them to appropriate teams so they can be addressed.

Issue 1: Bot channel registration endpoints does not get updated after any updates from portal.
•	The customer has provided steps to reproduce the issue and we are able to confirm that the same behavior is seen. The updates to endpoints seems to be saved after a green tick is seen in the field where the endpoint needs to be updated but the portal throws up a pop up to save unsaved edits while exiting this blade from the Azure portal. 
https://social.msdn.microsoft.com/Forums/en-US/b69220fe-af32-4224-ae11-65c753934fe6/bot-channels-registration-messaging-endpoint-does-not-update-after-change?forum=AzureCognitiveService
https://social.msdn.microsoft.com/Forums/en-US/d8c23599-18e8-47eb-b72e-9bb4487b79dd/bot-channels-registration-messaging-endpoint-does-not-update-after-change?forum=AzureCognitiveService

Issue 2: New password generation from Manage link of Azure bot channel registration does not work.
•	Customers are unable to use the manage option to update the password or certificate and keys from the bot channel registration page. They are redirected to a page which says page not found. We are unable to replicate the same under MS tenant version of the portal but multiple customers have reported this issue. 

Manage option redirects to a page not found.
 << OLE Object: Picture (Device Independent Bitmap) >> 
Similar issues. 
o	 << Message: Cannot generate new password for Bot Channel Registration >> 
o	https://social.msdn.microsoft.com/Forums/azure/en-US/d73dc060-c492-4952-af65-36f01a167605/cannot-generate-new-password-for-bot-channel-registration?forum=AzureCognitiveService

•	Workaround for issue 2 has been provided to customers to help them set new passwords directly from the app service.
 << Message: RE: Cannot generate new password for Bot Channel Registration >> 
https://social.msdn.microsoft.com/Forums/en-US/f270ca07-54f5-4cfd-a673-925f113bf4ca/cannot-generate-new-password-for-bot-channel-registration?forum=AzureCognitiveService

Issue 3: Integration questions of bot with facebook.
•	Do we have an option to add multiple facebook page id’s to the bot channel configuration programmatically? We could not find an API reference to get the same updated from the current documentation. Could you please confirm if this is possible?
•	What is the limit to the one of pages that can be connected to the facebook connector? The channel settings page in the portal allows us to add pages but is there a limit to the number of pages that can be added for one bot?
https://social.msdn.microsoft.com/Forums/en-US/cb25fa4a-326c-42b4-a2c0-2e7db1eedc8c/bot-with-facebook-integration-question?forum=AzureCognitiveService

**Comment by jameslew** [comment]
#2 should now be resolved.  We'll investigate 1 & 3 and provide an update.  @dmvtech

**Comment by dmvtech** [comment]
number 1 has been addressed by the comment that is now added in this page:
![image](https://user-images.githubusercontent.com/43397658/77196354-6d57be80-6aa0-11ea-8414-52a5906adc97.png)

**Comment by dmvtech** [comment]
Regarding number 3: there is no way to do this programmatically nor through CLI tools. It can be done with the UI only.

As these questions have been answered, I am closing this. If you need further assistance, please create new tickets for a specific issue.
