### ISSUE TITLE
Bot Channel Registration Channels blade returns Internal Server Error

### ISSUE THREAD

**Issue by etbuilder** [microsoft/BotFramework-Services#127]
The bot channel registration suddenly started to return errors...

**Error** is:
Microsoft.Bot.Connector.ErrorResponseException: Operation returned an invalid status code 'ServiceUnavailable'

**Channel used**: Facebook

When clicking the edit button for the channel on Azure Bot Channel Registration, azure page fails with error 'The page cannot be displayed because an internal server error has occurred.'

![Annotation 2019-09-04 164717](https://user-images.githubusercontent.com/30491836/64260752-20f9c680-cf34-11e9-9eb1-b923f1a27a1a.png)

**Comment by sgellock** [comment]
@etbuilder thank you for opening the issue.  We've assigned the issue to an engineer in our services team.  We're seeing an issue on our side and are investigating.  Will provide more details once we understand more

**Comment by hcyang** [comment]
@hristp, this seems a service interruption issue, please update this ticket once you have more info (per you are the service DRI this week).

**Comment by hristp** [comment]
Hi @etbuilder,
What is your bot registration name?
Also, does this still happen for you, and could you give me a timestamp of when this happens?
Thanks!

**Comment by etbuilder** [comment]
@hristp I think the issue is resolved now, we are not seeing errors any more as of now.
