### ISSUE TITLE
[Azure Bot service] 503 Service Unavailable while configuring FB Messenger

### ISSUE THREAD

**Issue by areckkimo** [microsoft/BotFramework-Services#128]
[question]

When FB messenger requests Webhook API, but FB messenger receives 503 service unavailable in the FB developer's console.

My chatbot builds on Azure Bot Function and develops with Bot framework V3 Nodejs

I don't change any code. The chatbot almost haven't got messages from MS Azure Bot service  since 2019/9/4

screenshot: [https://social.msdn.microsoft.com/Forums/getfile/1479455](https://social.msdn.microsoft.com/Forums/getfile/1479455)

**Comment by cleemullins** [comment]
Thanks for reporting this. @hristp is investigating this and should reply shortly.

**Comment by hristp** [comment]
Hi @areckkimo, what is the name of your bot?

**Comment by hristp** [comment]
@areckkimo, can you give me some more info where this is happening?
- Are you trying to configure a bot like this: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0?
- Is it failing on one of the steps above?

How often are you seeing this? Any particular times you can share with me?

Thanks!

**Comment by areckkimo** [comment]
> @areckkimo, can you give me some more info where this is happening?
> 
> * Are you trying to configure a bot like this: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0?

Yes, I had configured.

> * Is it failing on one of the steps above?
 No
> How often are you seeing this? Any particular times you can share with me?

Since 2019/9/4, It hasn't worked well. When I send messages to the chatbot, the chatbot most time doesn't reply messages. Although the chatbot sometimes can reply messages, It isn't full messages.

> Thanks!

**Comment by areckkimo** [comment]
> Hi @areckkimo, what is the name of your bot?

m.me/twTrainChatBot

**Comment by hristp** [comment]
@areckkimo, we had some instability with the Facebook channel yesterday that was causing dropped requests. It was fixed yesterday.
Do you still see issues?

**Comment by areckkimo** [comment]
> @areckkimo, we had some instability with the Facebook channel yesterday that was causing dropped requests. It was fixed yesterday.
> Do you still see issues?

It seems to work. I am going to observe them these days.
thank you for help

**Comment by kelvin-snapnet** [comment]
kelvin Olori (kelvin@snapnet.com.ng) has sent you a protected message.            Read the message            Learn about messages protected by Office 365        
    
    
        
            Microsoft respects your privacy. To learn more, please read our Privacy Statement.             Microsoft Corporation, One Microsoft Way, Redmond, WA 98052

**Comment by cleemullins** [comment]
@areckkimo - I'm going to close this out. If anything goes wrong, please re-open this ticked or file a new one.
