### ISSUE TITLE
Analytics doesn’t track Skype for business. 

### ISSUE THREAD

**Issue by martinlarosa** [microsoft/BotFramework-Services#13]
I have bots working with the Bot Framework v3 and v4 through Web, Skype for Business, MS Teams and Slack. In the Azure Portal, in the Bot service I go to analytics and see usage data but not for Skype for Business. Also when I query for custom events in App Insights Analytics I only see entries for the other channels. 
Is there a problem with that channel? Is there something that has to be done in order to enable it? I didn't see any mention about that in the documentation, and interestingly enough the example screenshot contains a lot of channels but not Skype for business, odd being a Microsoft documentation.

**Comment by nyxsys** [comment]
tracking this here now https://github.com/Microsoft/botbuilder-js/issues/568

**Comment by nyxsys** [comment]
Reopening due to resolution to https://github.com/Microsoft/botbuilder-js/issues/568

**Comment by arturl** [comment]
Working on a fix.

**Comment by martinlarosa** [comment]
Any update on this?

**Comment by jameslew** [comment]
I wanted to update this after a long gap to let you know that while i believe this item was addressed, the business decision has been made that Skype for Business channel will not be coming out of preview state, and no new bots or features will be added.  Strategically Microsoft is directing customers to Microsoft Teams.

Your current Skype for Business bots will continue to work for some time (currently likely into Q1 2020) after which they will cease to be able to connect to Skype for Business users.
