### ISSUE TITLE
Facebook Channel (messaging_referrals) Sends unordered messages to bot endpoint

### ISSUE THREAD

**Issue by etbuilder** [microsoft/BotFramework-Services#131]
Hi,

We are facing an issue where incoming messaging_referrals webhook event from Facebook Messenger are not being sent in order from the Azure Bot Channel Registration.

1- When a user clicks on an AD on Facebook Messenger
2- Facebook send a messaging_referrals webhook event, followed by a messages webhook events.

The issue occurs on Bot Channel Registration where sometimes the above order is not maintained, the messages webhook event is sent to the bot endpoint followed by the messages_referrals webhook event.

**Comment by Jeffders** [comment]
Thank you for the question. Right now, the Bot Service does not guarantee the order of messages that are sent from Facebook in this way.
