### ISSUE TITLE
Bot timeout on conversationUpdate request should result in 502 instead of 401

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-Services#133]
> Related to https://github.com/microsoft/BotFramework-WebChat/issues/2409.

Repro steps:

1. Start a conversation and post an activity, e.g. in Web Chat
1. The bot should receive `conversationUpdate` activity HTTP request before any user-originated activity
1. Instead of returning the HTTP response, let the request time out

Expected:

`POST` to `directline.botframework.com/.../conversations/<cid>/activities` should return 502 Gateway Timeout.

Actual:

We received 401 Unauthorized.

Additional context:

We are unsure if an "enhanced" token is used. We are sure it is a token generated via Direct Line channel.

**Comment by NickEricson** [comment]
Thank you for reporting this issue. We should have a fix deployed in the next few weeks. We will revert to the original behavior.

**Comment by NickEricson** [comment]
A fix was deployed world wide for this last week. Please let me know if you are still seeing this issue.
