### ISSUE TITLE
Intermittent 502 (Bad Gateway) when trying to retrieve token for bot

### ISSUE THREAD

**Issue by kds-snyder** [microsoft/BotFramework-Services#134]
Intermittently, when sending GET to the bot token controller in order to retrieve a token to open the bot, result 502 (Bad Gateway) occurs. This has happened 8/7/19, 9/16/19, 9/17/19, and 9/20/19. 

Each time, I was able to resolve the error by stopping and starting the app service, or redeploying the bot. Every time that this happened, I checked the Application Insights exception events, and the  DirectLine issues in the Channels, but there were no entries for the time that the 502 occurred, and no entries related to 502 (Bad Gateway).

If a 502 (Bad Gateway) occurs, it seems to me that there should be some error log entry available in the Azure portal to provide some information about the issue.

**Comment by jwiley84** [comment]
Hi @kds-snyder! On the occurrance that this happens, does it return 502 just once, and then the bot continues conversation as normal, or begins conversation after that? Or do all following messages result in 502s?

**Comment by kds-snyder** [comment]
All subsequent attempts to retrieve a token result in 502. I have only been able to resolve it by stopping and starting the app service, or redeploying the bot.

**Comment by jwiley84** [comment]
Is your bot set to 'always on' in the configuration? Also, can you post your bot's app ID or handle?

**Comment by kds-snyder** [comment]
I'm not sure where the setting 'always on' is; can you explain where to find it? As far as I've seen, when the bot is deployed it is always active unless the 502 is occurring.

The bot app ID is 698982ce-f453-4f0a-a6f2-8721b5d91d89.

**Comment by kds-snyder** [comment]
The 502 occurred again yesterday, but this time there are entries in the Application Insights exceptions. There are about 20 entries, first one at 9/26/2019, 3:30:18.361 PM (8:30 PST), last one at 9/26/2019, 3:46:51.128 PM (8:46 PST). I actually only saw there was a problem at about 11:15 PST, so the entries stopped before the problem was corrected. I don't really see anything in the exception to explain why the 502 occurred.
![image](https://user-images.githubusercontent.com/14143452/65789198-a4f93580-e111-11e9-8d5d-8a5a600a813e.png)

**Comment by jwiley84** [comment]
Hi Karen. Can you post the code you're using to send the GET to the bot token controller? 

As for the 'always on' -> typically intermittant 502s are the result of the bot 'timing out' after a  period of inactivity (ie, no one has messaged the bot in a few hours/days). In the bot app service, select 'Configuration' under the App Service Settings. In the new blade, choose 'General Settings' at the top, then scroll down to 'always on' and toggle it to on:

![image](https://user-images.githubusercontent.com/17333688/65985901-9e333100-e437-11e9-87e4-0519deaef3a6.png)

**Comment by kds-snyder** [comment]
I checked, and the 'always on' setting was off. I don't think it is related though, because the latest 502 occurrence was yesterday 12:16 pm PST, and I see from the Application Insights that the last bot message to a user was yesterday 11:52 am PST. I also have a test bot deployed to a different resource group, with much less traffic, and the 502 has never occurred for the test bot. Still, I have changed the setting to on for both bots.

This is the jquery code to open the bot (I tried inserting it as code, but in the preview all the carriage returns were gone):
    **// Store for webchat middleware to send events for messages from/to bot
    const store = window.WebChat.createStore(
        {},
        ({ dispatch }) => next => action => {
            if (action.type === 'DIRECT_LINE/INCOMING_ACTIVITY') {
                const event = new Event('webchatMessageFromBot');
                event.data = action.payload.activity;
                window.dispatchEvent(event);
            }
            else if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
                const event = new Event('webchatMessageToBot');
                action.payload.activity.channelData = { // pass user role to bot
                    role: HelpCenter.user.role
                };
                event.data = action.payload.activity;
                window.dispatchEvent(event);
            }
            return next(action);
        }
    );
    var botTokenApiUrl = <URL for bot token controller>;
    // Chat button click handler
    $('.webchat-btn').click(function () {  
        $.get(botTokenApiUrl, function (result) {
            if (result == null) {
                alert('Sorry, unable to open the Q&A Bot');
                notifyBotError('Null bot token', botTokenApiUrl, HelpCenter.user.email);
            }
            else {
                botToken = result.token;
                window.WebChat.renderWebChat({
                    directLine: window.WebChat.createDirectLine({ token: botToken }),
                    store,
                    styleOptions: {
                        bubbleBackground: '#eceff1',
                        bubbleFromUserBackground: '#0078d7',
                        bubbleFromUserTextColor: 'White',
                        hideUploadButton: true,
                        primaryFont: "'Segoe UI', 'Arial', 'sans-serif'"
                    },
                    userID: userId.toString(),
                    username: HelpCenter.user.email,                    
                }, document.getElementById('webchat-control'));
                $('.webchat-container').css('display', 'block');
            }
        }).error(function () {
            alert('Sorry, something went wrong with opening the Q&A Bot');
            notifyBotError('Error retrieving bot token', botTokenApiUrl, HelpCenter.user.email);
        });
    });**

I was speculating that the problem could be due to the bot storing user state in local memory; maybe it is running out of memory and crashing, which would explain why the 502 occurs in the bot with more traffic?

**Comment by jwiley84** [comment]
Karen, I am so sorry for not getting back to you. Is your bot deployed with local memory as storage? Is it saving any information from the users at all? Local Memory is advised only for debugging purposes. It effectively "resets" as soon as you turn your bot off. It's not meant for deployment purposes.

**Comment by kds-snyder** [comment]
The bot is using local memory for storage, and I realize that it is cleared whenever the bot is re-deployed or restarted. I have not yet been able to allocate the time needed to change to Azure storage or Cosmos DB. However, is using local memory for storage a potential cause of the intermittent 502 errors?

**Comment by jwiley84** [comment]
It's a potential cause. What version of the SDK are you using?

**Comment by jwiley84** [comment]
If your bot is deployed to azure, you can go into the 'build' function on the bot management portion of the overview blade, and select 'open online code editor'. That should get you a list of the associated files, including '<BOTNAME>.deps.json'. It will have a list of the dependencies and their versions, like this:

![image](https://user-images.githubusercontent.com/17333688/67964160-09019480-fbbd-11e9-994a-2314d627bb70.png)

**Comment by kds-snyder** [comment]
In the online code editor there is 'HelpDeskBot.deps.json' with the following, so it appears that I am using the 4.4 SDK:
![image](https://user-images.githubusercontent.com/14143452/67984981-1f234b00-fbe5-11e9-889f-cda7a10764c8.png)

![image](https://user-images.githubusercontent.com/14143452/67985118-5db90580-fbe5-11e9-9786-36ece22fbc5c.png)

**Comment by CoHealer** [comment]
@jwiley84 will reengage when back in office on Monday.

**Comment by jwiley84** [comment]
Sorry for the delay, was away from the office. 

Can you update your packages to 4.6.0 (or at least 4.5.3?)

**Comment by kds-snyder** [comment]
I'm not sure how to update the packages. Do I do that via Visual Studio?

**Comment by jwiley84** [comment]
If you're not using some sort of release pipeline, then yes, you'd have to pull the files down from azure, update the packages in then nuget package manager, and then redeploy the bot.

**Comment by kds-snyder** [comment]
When I updated the packages in NuGet package manager, I got the warning below, so not sure if the update succeed
![image](https://user-images.githubusercontent.com/14143452/69273577-76d22800-0b8d-11ea-9127-3e4f8871ab0f.png)

**Comment by v-kydela** [comment]
Hello @kds-snyder 

You can tell if the update succeeded by checking the version of each package in NuGet Package Manager. If an update for a package is still available then it will have an up icon.

![image](https://user-images.githubusercontent.com/41968495/69364903-17851e00-0c48-11ea-8989-57ec61b08173.png)

If you're having trouble updating all of your packages at once then you should try just updating Microsoft.AspNetCore.App to the latest version first and then seeing if you can update the other packages.

Please refer to the [docs](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio) if you would like to better understand how to use NuGet Package Manager.

**Comment by CoHealer** [comment]
@kds-snyder do you still require assistance?

**Comment by kds-snyder** [comment]
The Nuget packages were updated, but it seems that the bot does not function with the updated packages when deployed. **Microsoft.AspNetCore.App** is already the latest version, so it does not need to be updated. After updating the Nuget packages and building the solution, there were the following warnings:
![image](https://user-images.githubusercontent.com/14143452/69885835-31101080-12ad-11ea-901e-894ee181d93b.png)
To see if it was possible to run the bot anyway, I tested in the emulator, which did work, but when I deployed the bot and then tried to open it from my UI, I got 500 Status code in response to the attempt to retrieve the token. I then resolved the warnings by doing the following:

- Installed Version 2.1.2 of **Microsoft.AspNetCore.Razor.Design** Nuget package

- Modified **Startup.cs**:
•	In the call to **services.AddTransient**, changed **TelemetrySaveBodyASPMiddleware** to **TelemetryInitializerMiddleware**
•	Removed **app.UseBotApplicationInsights()**

However, the same problem occurred: when the bot was deployed, 500 status code result was received when attempting to retrieve a token.

**Comment by v-kydela** [comment]
@kds-snyder - So you're getting a 500 error now instead of a 502?

You say Microsoft.AspNetCore.App is already the latest version, but your warnings say you're still using Microsoft.AspNetCore.App 2.1.1. This is very strange, and it's hard to diagnose what's going on here. Perhaps your project has been corrupted somehow and your code will have to be moved to a fresh project. Please check the contents of your HelpDeskBot.csproj file and see what versions it thinks you're using.

Also, have you updated your bot to use external storage yet?

**Comment by kds-snyder** [comment]
@v-kydela, thank you for noticing this discrepancy. 

The Microsoft.AspNetCore.App version in the Nuget package manager is 2.2.8.
![image](https://user-images.githubusercontent.com/14143452/69887637-f5c60f80-12b5-11ea-8982-12383c0daad9.png)

I believe the version discrepancy is caused by this line in Startup.cs, which I had overlooked until you pointed out the issue; presumably it overrides the Nuget version:
services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

I changed Version_2_1 to Latest (only other choice was Version_2_0) and rebuilt, but I'm still getting the warning about Microsoft.AspNetCore.App 2.1.1. Do I need to edit the csproj file manually? It contains:
![image](https://user-images.githubusercontent.com/14143452/69888143-58200f80-12b8-11ea-8b46-edf25b5e57f3.png)


Also, I have not yet been able to find the time to update the bot to use external storage. However, the 502 error has not occurred since October 16, so although I know that I do need to change to external storage, I'm not sure that using local storage contributed to the 502 error.

**Comment by v-kydela** [comment]
@kds-snyder - Memory storage is the most common cause of errors that are only encountered in published bots. I would consider the likelihood to be very high that it is causing problems for you.

For your package issue, please try uninstalling Microsoft.AspNetCore.App, then checking to make sure it's been removed from your csproj file, then reinstalling it.

**Comment by kds-snyder** [comment]
I'm not sure how to uninstall Microsoft.AspNetCore.App in the Nuget manager. The Uninstall button is not enabled. And now I noticed that 2.1.1 is shown in Nuget as the installed version, on the right.
![image](https://user-images.githubusercontent.com/14143452/69890552-62480b00-12c4-11ea-84ff-b947a9a73502.png)

**Comment by v-kydela** [comment]
@kds-snyder - It looks like you're viewing the packages for your solution instead of the packages for your project. You can manage the packages for your project by right-clicking the project in Solution Explorer.

It's possible that the package is [implicitly defined](https://docs.microsoft.com/en-us/nuget/consume-packages/install-use-packages-visual-studio#update-a-package) for you, which might mean you'll have to [update your .NET Core installation](https://dotnet.microsoft.com/download) on your machine.

Are you sure you want to use Razor in your bot? Is your bot responsible for the markup of a web page?

**Comment by kds-snyder** [comment]
@v-kydela, the package is implicitly defined, and I will have to update the .NET Core installation. But if I do that, will it still be possible to build branches that have Microsoft.AspNetCore.App 2.1.1?

I do not believe that I need Razor. The bot was based on sample code that probably had the package installed. I know that I didn't add the Razor package.

**Comment by v-kydela** [comment]
@kds-snyder - The .NET Core version is actually part of your project settings. You can use any installed version:

![image](https://user-images.githubusercontent.com/41968495/69892649-9c151380-12bc-11ea-8dc7-ffc781d286d9.png)

**Comment by kds-snyder** [comment]
I changed the .NET version in project properties to .NET Core 2.2, and then the Microsoft.AspNetCore.App version was 2.2.0 for the project and solution Nuget package managers. But when I try to open the bot from the UI, I still get status code 500. It seems that something in the updates caused the bot to not function correctly.

**Comment by v-kydela** [comment]
@kds-snyder - Please go ahead and try out the instructions in [this document](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-500-errors) to help troubleshoot your 500 errors

**Comment by kds-snyder** [comment]
@v-kydela, regarding adding Application Insights Telemetry as described at https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net, I already have  an Application Insights app for the bot in the Azure portal. I added Telemetry middleware in the bot as described at https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0, and the bot does log custom events and traces. So will this procedure to add telemetry in Visual Studio create another Application Insights app in the Azure portal in addition to the Application Insights app that already exists?

**Comment by kds-snyder** [comment]
I switched to the dev branch and deployed it, because I was making some website changes that required a functioning bot, and still got the 500 error! Same thing when I deployed the master branch, which is currently deployed to the production resource group and working fine there. It looks like I'll have to delete all the resources in the test resource group and re-create them.

**Comment by CoHealer** [comment]
@kds-snyder do you still require assistance or did recreating the resources resolve your issue?

**Comment by kds-snyder** [comment]
I reached out to our Microsoft contact engineer to ask if they know what setting in the Azure portal I could check, because it seemed excessive to me that I would have to delete and recreate all the resources. I haven't heard back yet.

**Comment by v-kydela** [comment]
@kds-snyder - Can you explain what UI you mean here?

> But when I try to open the bot from the UI, I still get status code 500. 

Please provide screenshots and repro steps to help explain the problem you're experiencing.

**Comment by kds-snyder** [comment]
The problem has changed; now if I deploy the **dev** branch, the bot works fine. But when I deploy the branch with updated packages, I get 502 status code result. 

The repro step is to click the Q&A bot button.
I posted the jquery that is used to open the bot in the comment that I wrote on 10/2/18. This is the HTML for the button:
`<a class="webchat-btn" href="#" title="Search for answers with the Q&amp;A Bot">
    <span>Q&amp;A Bot</span>
</a>`

This is from the network tab of the Chrome dev tools:
![image](https://user-images.githubusercontent.com/14143452/70944891-d7c41300-2008-11ea-8b44-1fbd7627e4ab.png)

**Comment by v-kydela** [comment]
@kds-snyder - If you run your website locally in debug mode then you should be able to get more information about this error. You can try using ngrok: https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/

**Comment by v-kydela** [comment]
@kds-snyder - Are you still working on this?

**Comment by kds-snyder** [comment]
I'm trying to figure out how to run the website locally in debug mode.

**Comment by v-kydela** [comment]
@kds-snyder - Do you need help with that? Are you running ASP.NET Core?

**Comment by kds-snyder** [comment]
I had to submit a request for the IT department to approve my access to https://ngrok.com, because it is blocked, so I haven't been able to try it yet.

**Comment by v-kydela** [comment]
@kds-snyder - You can use [Azure Service Bus](https://blog.botframework.com/2019/04/16/debugging-your-locally-hosted-v4-bot-using-azure-relays/) as an alternative to ngrok in order to debug your project locally.

It feels like this issue has drifted pretty far and I'm not sure the problems you're facing now reflect the problems that you had originally opened the issue about. Would it be all right if we closed this issue so that you can open a new one if you still need help with the problem you're currently facing?

**Comment by kds-snyder** [comment]
@v-kydela, I will try with Azure Service Bus. It's true that this issue has drifted far. Last time a 502 error occurred in the production bot was October 16. Since then, there have been intermittent errors, but with status code 0, and it was always possible to open the bot afterwards, so those errors were non-blocking. You can go ahead and close the issue, and if I need help, I can open another issue.
