### ISSUE TITLE
CORS to directline.botframework.com should not return * for Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-Services#136]
According to MDN, in the spec, if the CORS is a credentialed request (i.e. request with `Cookie` or `Authentication` header), it must not return `Access-Control-Allow-Origin: *`. Instead, it must return a host name.

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
https://www.w3.org/TR/cors/

Traffic we observed:

![image](https://user-images.githubusercontent.com/1622400/65710248-7f075e80-e047-11e9-94e2-76274a156728.png)

Excerpt from MDN "Credentialed requests and wildcards", about the non-`*` requirement:

![image](https://user-images.githubusercontent.com/1622400/65710097-25069900-e047-11e9-90f7-6c23e7556222.png)

Excerpt from MDN "Requests with credentials", about the definition of "credentialed request":

![image](https://user-images.githubusercontent.com/1622400/65710183-54b5a100-e047-11e9-87c7-c49cec984204.png)

Excerpt from W3C "6.1 Simple Cross-Origin Request, Actual Request, and Redirects", about the non-`*` requirement:

![image](https://user-images.githubusercontent.com/1622400/65710496-fd640080-e047-11e9-939e-6cdf0c5eb18b.png)

Excerpt from W3C "Terminology", about the definition of credentials:

![image](https://user-images.githubusercontent.com/1622400/65715967-08705e00-e053-11e9-9ff3-f23cf1b2efa9.png)

**Comment by jameslew** [comment]
Moved to an internally tracked item in the Bot Service devops instance.  Thank you!

**Comment by karangupta8** [comment]
Hi @jameslew , has this been fixed yet? If yes, where can I find the steps to reciprocate the solution?
