### ISSUE TITLE
Any GroupMe message sent with text that contains a TinyURL or bitly URL silently disappears

### ISSUE THREAD

**Issue by sphanley** [microsoft/BotFramework-Services#137]
I've got a GroupMe bot built with the Bot Framework which has been working smoothly. Without any code changing on my end, as of 10/2 sometime after 6:49 PM EST but before 11:18 PM EST, something seems to have broken where any messages sent by my bot which contain a URL in their text are no longer showing up in GroupMe. The bot instance doesn't seem to receive any sort of error - the messages just disappear in transit. I'm not sure whether this is a bot service issue or a GroupMe issue, but since there's no meaningful bug tracker for GroupMe, I figured I'd start here.

**Comment by anusharavindrar** [comment]
@sphanley hello again,not sure what might be the reason behind this sudden behavior. Can you share your botHandle or AppID so that I can check the bot logs on my end? In the meanwhile, I will try to repro the behavior on my end to narrow down the issue.

**Comment by sphanley** [comment]
Hello again @anusharavindrar! :) You can check the AppId "bd0fb49f-b078-4701-9494-d3ddf35bdf5e". An example of the issue is that anytime a user says "!map" in the chat, the bot is supposed to respond with a message containing a bit.ly URL to a map. This message, and all other messages containing URLs, are not making it to GroupMe. The bot ID I provided is for my "sandbox" bot - I've got another bot instance running the same code and the same issue happens there - and no code change has been elevated to my bot since before the issue began.

**Comment by sphanley** [comment]
Just wanted to update that the issue can be reproduced simply by deploying a stock "Echo bot" instance via the new Web App Bot creator and connecting it to the GroupMe channel. Any user-sent message which contains a URL will fail to be echoed back by the bot into the GroupMe chat.

**Comment by anusharavindrar** [comment]
Hello @sphanley , so I tried to repro your issue, but I was able to successfully get the message with the URL echoed back by the bot. A few clarifying questions to better repro your issue:

1. Were you able to send messages with URL successfully before? If you could attach a screenshot of the failed test case, then I can try to replicate the same in mine.
2. Can you make use of [ngrok](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/) to locally run your bot and try sending messages with URL ?
3. Are you making use of the GroupMe web client or the desktop client?
4. Also, are you able to send other types of messages and the test is failing specifically for the messages with URL?

I am looking through your bot logs to zero-in on the probable issue causing this and will post my findings soon.

**Comment by sphanley** [comment]
Intestingly, the issue appears to have resolved it across all of my bot instances, again without any code change on my end. For completeness's sake, though, here's answers to your questions:

* I was able to have my bot send messages containing URLs with no problem - the last instance I saw go through successfully before this issue started was at 6:49 PM ET on 10/2. I first noticed an instance of an expected URL message being missing at 11:18 PM ET on 10/2. I'll add a screenshot showing the expected and actual behaviors when I get a chance. 

* I did not try using ngrok to debug the bot from my local machine. However, if I tested the bot in the Web Chat tool in Azure portal, I could see the expected message from the bot containing a URL. The message containing a URL only failed to appear when chatting in the actual GroupMe chat.

* I reproduced the issue via both the GroupMe web UI as well as the GroupMe Android client.

* Aside from #101 which documents my ongoing issues around attachments, I've seen no other issues with any other kind of messages being after being sent by the bot. 

Hopefully, whatever was at fault has been resolved on the backend and things just stay working. Thanks for your investigation!

**Comment by anusharavindrar** [comment]
Glad to hear that the issue was resolved and thank you for the detailed explanation. I will mark this as resolved and close. Please feel free to open a new issue if you encounter problems in the future with the GroupMe channel :)

**Comment by anusharavindrar** [comment]
Glad to hear that the issue was resolved and thank you for the detailed explanation. I will mark this as resolved and close it. Please feel free to open a new issue if you encounter problems in the future with the GroupMe channel :)

**Comment by sphanley** [comment]
Hello @anusharavindar! Bad news - I'm experiencing the same issue again, and again, no change whatsoever has been made to my code or azure configuration. Any chance this can be reopened so someone can look into if there's an issue between the Bot Service and GroupMe?

**Comment by sphanley** [comment]
Interestingly - it seems like the issue may be specifically with URL shorteners. The URLs being sent by my bot are all bit.ly URLs, and we've discovered that when users in our chats send bit.ly or tinyurl URLs in messages, those messages are showing up normally for the users who sent them, but aren't visible to anyone else. Any chance someone on the Microsoft side can investigate whenever there's any known GroupMe changes/issues around blocking URL shorteners?

**Comment by CoHealer** [comment]
Reactivating with positive repro of the issue. @craigjensen / @jameslew can someone please assist?

**Comment by sphanley** [comment]
For what it's worth, it seems like other GroupMe users are confirming that it's a general GroupMe issue that's affecting bitly and tinyURL links - sounds like it's not specific to using the Bot Framework GroupMe service. I found other people discussing it on the GroupMe subreddit: https://www.reddit.com/r/GroupME/comments/dem0x5/bitly_links_do_not_show_up_any_longer/

**Comment by anusharavindrar** [comment]
Hello @sphanley, I was able to repro the issue with bit.ly and tinyURL links, but it works fine with other URL shorteners like Short URL and Cuttly. The issue seems to be on the GroupMe side on how they handle and allow the shortened URLS.

**Comment by sphanley** [comment]
I agree - it seems like it's a GroupMe issue, not a bot service issue. Do any of you know whether there's a better way to transfer this issue to the relevant GroupMe folks other than just emailing their support address? 

Just to capture the last of my findings: I tried a handful of URL shorteners, here's the results.

http://tinyurl.com/c8xugfa - didn’t work
http://bit.ly/ZKdYbB - didn’t work
http://is.gd/05d0R5 - didn’t work
http://goo.gl/4PdrB - worked
http://t.co/8svYjZdL - worked
http://tiny.cc/sb37sw - worked

**Comment by jameslew** [comment]
We're working to identify the right team contact for this issue.  @mickeydjw is following up.

**Comment by compulim** [comment]
Talked to @mickeydjw offline, we are still finding the right contacts for this issue and #97.

**Comment by sphanley** [comment]
For what it's worth, I can't reproduce this issue anymore - bit\.ly URLs are showing up normally in my group chats. I'm assuming it was fixed, either intentionally or incidentally, on the GroupMe side.

**Comment by CoHealer** [comment]
Thanks @sphanley. With this not repro'ing any more I'm going to close this issue. Please continue to track #97 and #101 for further updates.
