### ISSUE TITLE
broken documentation link on facebook channel config page

### ISSUE THREAD

**Issue by swagatmishra2007** [microsoft/BotFramework-Services#138]
The "What do I do with my Callback URL and Verify Token?" link points to [https://docs.microsoft.com/en-us/bot-framework/thirdparty-channels/channel-facebook#configure-webhook-callback-url-and-verify-token](this link), which returns a 404

**Comment by jameslew** [comment]
Looks like the path was changed: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0.  I'll get entered as a hopper bug.

**Comment by jameslew** [comment]
Entered into the backlog.  Closing as it's tracked in product db.
