### ISSUE TITLE
Facebook Graph Api v2.10 depreciation handling on botbuilder

### ISSUE THREAD

**Issue by wethil** [microsoft/BotFramework-Services#139]
When you go [developer messenger page (facebook)](https://developers.facebook.com/docs/messenger-platform/) you will see the warning `Reminder: Graph API v2.10 will be deprecated on Nov 05, 2019. Please use the API Upgrade Tool to understand how this might impact your app. For more details see the changelog`

I don't know if botbuilder is ready for this change if it is not, I can try to migrate and open PR about that. But I am not sure which package I should work on. Where exactly a request converted for facebook messenger API calls?

**Comment by jameslew** [comment]
We are in progress on updating our Facebook channel implementation to the latest SDK.  Thank you for the notice, I should have an ETA shortly.

**Comment by jameslew** [comment]
I've investigated.  In mid-year we upgraded to 3.2, and in the next week you should see further upgrade to SDK 4.0. In either case the warning should be benign for you, you're already using the most recent.

**Comment by wethil** [comment]
You mean if I am using the last version of botbuilder (v4.x) this means graph api version won't be a problem right?

**Comment by jameslew** [comment]
Yes, but more specifically, the Graph implementation is done in the Bot Service itself, not in the SDK; the SDK (unless you're using a channel specific adapter in the SDK) is channel agnostic.

**Comment by jameslew** [comment]
Thanks for reporting; I think we can mark this one as closed now - though do feel free to raise if you have any further questions.

**Comment by wethil** [comment]
Okey, thank you for help
