### ISSUE TITLE
Adaptive Cards - Cannot display more than 7 cards on the channels 

### ISSUE THREAD

**Issue by aishwaryaumachandran** [microsoft/BotFramework-Services#141]
## Issue
*Card carousel with more than 7 cards does not work on the following channels - Teams, Directline, Facebook. It works correctly on the emulator*

Please find the illustrative screenshot of the response from the emulator (Response has 16 cards):

<img width="561" alt="Screen Shot 2019-10-14 at 9 58 56 AM" src="https://user-images.githubusercontent.com/24215001/66758440-43083200-ee6c-11e9-870f-ee191f8302d5.png">

Please find the illustrative screenshot of the response from Teams for the same question:

<img width="586" alt="Screen Shot 2019-10-14 at 9 59 12 AM" src="https://user-images.githubusercontent.com/24215001/66758484-5ddaa680-ee6c-11e9-8474-0a60ba65b892.png">

**Comment by stevkan** [comment]
@aishwaryaumachandran, can you post the code you are using for generating and calling the carousel cards? Also, which SDK and version are you using? It is also important to note that it is the individual channels that determine how they handle the various activities, including receiving card carousels.

That said, I tested the three channels with the following results:

- Direct Line (via Web Chat) supported 16 cards. Did not test beyond that number.
- Teams: Supported up to 10 cards.
- Facebook: Would render (rounding down, in most cases) half the number of cards sent in a carousel. For example, if 16 cards were sent, then 8 would render.

I will look into this particular issue regarding Facebook. Beyond that, I will wait until you are able to supply your code.

**Comment by stevkan** [comment]
@aishwaryaumachandran, are you still needing help on this? Are you able to provide your code?

**Comment by stevkan** [comment]
Closing due to a lack of activity.
