### ISSUE TITLE
Directline API failures causing downtime of bots

### ISSUE THREAD

**Issue by bhushanvadgave** [microsoft/BotFramework-Services#142]
We have multiple bot services running in production serving multiple customer businesses. All of our bots have become unresponsive due to Directline API failures.

Below is the error we are seeing in our bot services.
``
POST to 'https://directline.botframework.com/v3/conversations/BwFsKMH1RkWGpM14IOOnWM-h/activities/BwFsKMH1RkWGpM14IOOnWM-h%7C0000017' failed: [503] Service Unavailable
``
Help us resolve the issue as early as possible.

**Comment by DanielTizon** [comment]
This is not serious. Supposedly this is a production-ready service, and it is not the first time that we have many hours of downtime in **EUROPE REGION**.

**Comment by ckkashyap** [comment]
Sorry about that.
We had an incident in our european  data centers where a number of requests resulted in 503 (Service Unavailable) responses. We have taken mitigation steps and are closely monitoring the services. Please let us know if you continue to experience issues.

**Comment by sharmadine** [comment]
The Botha are back again. I wish the issue doesn't reoccur again.
