### ISSUE TITLE
[Feature Request]: Change channel id in directline

### ISSUE THREAD

**Issue by muminasaad** [microsoft/BotFramework-Services#143]
## Issue
Cannot diffirentiate between multiple implemented directline channels.

I have implemented multiple channels that are not supported by Microsoft and to customize the UX i need to differentiate between them.

it would be great if we can customize channel id or add the site name that is defined in the azure portal somewhere 

## Proposed change
Customizable channel id or add site name to request

## Customer Impact 
Customize UX

**Comment by johnataylor** [comment]
@dandriscoll a custom feature request - can you comment? thanks

**Comment by dandriscoll** [comment]
Hi @muminasaad this is not possible with today's architecture. Bot Framework has a security model that prevents impersonation or spoofing between channels -- it ensures separation between channels and allows bot code to rely on channel IDs as a basis for other IDs within the system: user IDs, conversation IDs, etc. Changing this would require changes to our security infrastructure.

Instead, you have three ways to separate uses of Direct Line within your code. One of them is natively supported and is designed specifically for your use case:

1. (Recommended) The Direct Line configuration page allows you to allocate different "sites," with associated keys and configurations. The site ID appears in the `recipient.id` field in any Activities your bot receives, in the format `<bot ID>@<site ID>`. Use the site ID to distinguish between uses.
2. Pass this data in the user ID, which is then available in the `from.id` field in Activities your bot receives.
3. Pass this data in the `channelData` field.

Given the availability of these solutions, we will not be adding the capability to change channel IDs at this time. If you have questions or feedback, don't hesitate to ask.

**Comment by muminasaad** [comment]
@dandriscoll Actually the first point you have mentioned is what i am searching, and if you can check the third line of the original request it says
" add the site name that is defined in the azure portal somewhere " 

Thank you for mentioning this information it would help alot as it was not mentioned in the documentation and i was not able to find nor rely on it

**Comment by muminasaad** [comment]
@dandriscoll Can you provide a way to know the site id from the portal

**Comment by muminasaad** [comment]
@dandriscoll  Thank you i found the answer.

for anyone is checking for the answer, the Recipient.Id property will have the following format:

BotHandle@SiteID

the Bot handle is under settings in the WebApp Bot
the Site ID can be parsed from the Token as the following: 
     Assume you have the following Token ABCD.EFGHJKLMN.OPQRSTUV=-
     Split it by "." and the first part of the token is the site ID
