### ISSUE TITLE
BotFrameworkAdapter.CreateConversation call for SMS fails to provide Conversation Id

### ISSUE THREAD

**Issue by olliecwl** [microsoft/BotFramework-Services#144]
## Versions
What package version of the SDK are you using: 4.6.0-preview1
What nodejs version are you using: 11.12
What browser version are you using: N/A
What os are you using: Windows 10 Pro

## Describe the bug
Our bot is hosted outside of Azure and interacts with users via SMS. Our bot is registered on Azure and we are using it as a go-between for our SMS provider.

When we attempt to [create a conversation](https://github.com/microsoft/botbuilder-js/blob/d7afd3fae5b2fb98771134717e775be207868e4b/libraries/botbuilder/src/botFrameworkAdapter.ts#L356) with a new user by contacting the [SMS service url](https://sms.botframework.com), the JSON response is in Pascal case. The mappers used in [@azure/ms-rest-js](https://github.com/Azure/ms-rest-js) assume all content received is in Camel case. The Bot Framework Adapter fails to transfer the correct Conversation Id on [line 383](https://github.com/microsoft/botbuilder-js/blob/d7afd3fae5b2fb98771134717e775be207868e4b/libraries/botbuilder/src/botFrameworkAdapter.ts#L383): response.id is undefined, but response.Id has a value.

## To Reproduce
1. Set up your bot with an SMS handler
2. Clone this repository: https://github.com/olliecwl/v4bot
3. Add your MS AppId/Password in .env
4. Add your mobile and your bot's mobile to the bottom of index.js
5. Add a breakpoint to [line 382](https://github.com/microsoft/botbuilder-js/blob/d7afd3fae5b2fb98771134717e775be207868e4b/libraries/botbuilder/src/botFrameworkAdapter.ts#L382)
5. Run your bot. At the breakpoint, you should see that response.Id does have a value.

## Expected behavior
The activity passed along to the logic in the BotFrameworkAdapter.createConversation call should contain a conversation object with a defined id value.

## Current workaround
Reset the activity's conversation id once the turnContext has been received in your logic function.

## Additional context
I understand that the fix for this is probably best generated further upstream. I'm just unsure where. The mappers in ms-rest-js? The code running on sms.botframework.com? Open to suggestions.

[bug]

**Comment by johnataylor** [comment]
@dandriscoll can you assign this appropriately. We think this is a limitation of the support in the twillio channel?

**Comment by stevkan** [comment]
I was able to successfully repro this issue. The SDK doesn't appear to have changed in significant ways so I would agree that this is likely a channel issue.

**Comment by DDEfromOR** [comment]
Picking this up to look into on the SDK and Service sides and figure out where to make the fix.

**Comment by DDEfromOR** [comment]
Looking at this from the channel side and hunting for inconsistencies between the formatting in responses vs requests sent from the channel to the bot. The code hasn't changed in over 6 months and this is the first report of the bug so I'm digging a bit deeper to make sure something hasn't changed upstream before deciding where the fix should live.

**Comment by DDEfromOR** [comment]
I've filed a bug against the channel as I feel this behavior is unintentional, but also recognize it has likely always been the implementation. Any changes to the involved code will have a large blast radius that impacts multiple channels, so it's not something we'll do quickly or without careful consideration, but it is now on the radar. 

I'm going to close this ticket since it's in the Services repo and we now have a bug in the internal system to track against the specific channel, but if anyone wants to reopen it and transfer to an appropriate repo to pursue one of the alternative fixes Jason aptly illustrated I won't object, the channel bug will move forward regardless.
