### ISSUE TITLE
Facebook insists on formal application review or will ban the bot channel on Dec 16.

### ISSUE THREAD

**Issue by Valerii-Poliakov** [microsoft/BotFramework-Services#146]
Hi
We have bot which is working in Workplace by Facebook environment for more than 1 year. The channel created as Custom Integration in Workplace and corresponding token passed to the Azure Bot Channel Registration.  
Now this integration has the following warning "This integration has not yet completed this updated review process. On December 16, 2019, we will remove access to any integration that has not passed our updated review process."
I used Workplace Direct Support to convince them that it's just custom integration and not a SaaS for other Workplace customers but without success. 
Direct Support answer is "According to our system this particular bot is hosted by 'Microsoft Bot Framework', you will have to work with Microsoft on creating a third party app."
Could you please suggest what to do to avoid ban in December?

Best Regards
Valerii

**Comment by v-kydela** [comment]
Hello @Valerii-Poliakov 

Microsoft is currently working to make sure your bot will continue to work. The only thing I know of that's required from your end is to enable your integration:

![image](https://user-images.githubusercontent.com/41968495/67793154-91562d00-fa37-11e9-93c9-26073c7abab0.png)

I will ask for more information and let you know if there's anything else you need to do.

**Comment by Valerii-Poliakov** [comment]
Thank you for response. Waiting for updates.

**Comment by dandriscoll** [comment]
Hi @Valerii-Poliakov -

You're correct, starting December 16, 2019, Workplace by Facebook is changing security model for custom integrations. Current integrations built using Microsoft Bot Framework v4 on JavaScript/Node.js may be updated to use the [Bot Framework Facebook for Workplace Adapter](https://www.npmjs.com/package/botbuilder-adapter-facebook) and deployed using Azure Web App to continue working past that date. New Microsoft Bot Framework bots that are targeting Workplace should also be developed using that adapter.

**Comment by Valerii-Poliakov** [comment]
Hi @dandriscoll 

So, I have to migrate my bot code from ver. 3.15 to ver. 4.x and use "Bot Framework Facebook for Workplace Adapter" in order to avoid Dec 16th ban. Am I understand right?

Best Regards
Valerii

**Comment by CoHealer** [comment]
That's correct @Valerii-Poliakov. Closing as resolved. If you have questions arise during the 3.5 > 4 migration, please open an issue in the[ BotBuilder v3 repo](https://github.com/microsoft/BotBuilder-V3) and add a reference to this issue. Someone on the Bot Framework Support Engineers team will assist you.

**Comment by yoagauthier** [comment]
Hello @dandriscoll !
I want to provide a third party bot on Workplace (so no custom integration). I am currently using the REST API for our bot and we configure it on the Azure Bot Channel Registration portal for other channels (Slack ..).

I understood from the [Workplace integration doc](https://developers.facebook.com/docs/workplace/third-party-apps/development) that the deployment process changed, in particular :
- Page ID is not needed anymore to integrate the app
- There is a complex process to get the token needed for the API calls on the Facebook Graph API

However, the Bot Channel Registration portal has not changed : it's mandatory to provide a Page ID, it does not seem to do the OAuth redicrection correctly ... 
![image](https://user-images.githubusercontent.com/19170035/71967541-ccc56280-3203-11ea-8c06-166a7d387c8c.png)

My questions are : 
1. Are there any backward compatibility for the Bot Service portal integration with new Workplace process ? If so, how can we configure that ([doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-facebook?view=azure-bot-service-4.0#connect-a-bot-to-facebook-workplace) does not details how to do it for 3rd party apps)
2.  If not, is there any plan in the BotFramework team to adapt the portal for that new process ? Or are we obliged to move to a self hosted bot using the adapter you mentionned earlier ?

Best Regards !
