### ISSUE TITLE
Watermark reset issues for DirectLine API

### ISSUE THREAD

**Issue by rrc2k4** [microsoft/BotFramework-Services#149]
We had observed water mark reset issues for our bot hosted on Azure services and when consumed through Direct Line API channel. 

In middle of the conversations where the current water mark value was more than 0 it was observed that water mark value got reset for the message that was posted to bot and next posted conversations it started again from 1 while the current expected water mark value was 6 or 7 or 13.

We observed this issue on 21st,22nd & 23 October for almost 18 conversations while unable to replicate the same now. Was there any issue in bot framework during those days?

**Comment by v-kydela** [comment]
Hi @rrc2k4 - it would help if I could get some more information. Can you provide a bot ID so we can check it in our logs? I would also like to know how you're determining what the watermark is, and whether you're sure a new conversation wasn't being started

**Comment by rrc2k4** [comment]
Hi Kyle, I am not sure if i can share the bot id in this post as it is hosted in our customer environment. Need to check with customer before sharing details.  

Regarding watermark value for every post, we capture the watermark value from the bot response and for every pull of messages we capture the updated watermark. we are making sure that we have the correct water mark value for pulling the messages and we don't initiate new conversation in middle of conversation as that logic is only implemented while page load. No scope of re-initiating the conversation.

We had raised support issue through Azure portal and will wait for response from Microsoft. will share that update on this post once i get the same.

**Comment by rrc2k4** [comment]
Microsoft Support request ID : 119111223001489

**Comment by CoHealer** [comment]
Adding @Jeffders, referencing https://github.com/microsoft/BotFramework-DirectLineJS/issues/242 as it appears to be a duplicate.

**Comment by v-kydela** [comment]
That issue was posted on October 23, and this issue occurred from October 21-23. This is consistent with there having been a problem with Direct Line at that time.

**Comment by CoHealer** [comment]
Issue is not repro'ing and there's nothing new in the logs.
