### ISSUE TITLE
AAD token not refreshed by service

### ISSUE THREAD

**Issue by crow-ua** [microsoft/BotFramework-Services#150]
We are using Microsoft.Bot.Builder v.4.6.2 and want to leverage Azure Bot Service OAuth connection to Azure Active Directory v2.
There is following code:
```
var adapter = (IUserTokenProvider)dc.Context.Adapter; 
var token = await adapter.GetUserTokenAsync(dc.Context, _appSettings.OAuthConnectionName, null, cancellationToken);
```
It returns valid token only after sign in, when it expires it still returns the same token, `TokenResponse.Expiration` is null.
I've debugged this method down to `Microsoft.Bot.Connector.UserToken` internals, the response from service indeed returns old token generated few days ago.
App Registrations and Bot Channel are configured according to this [guide](https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/tabs/how-to/authentication/auth-aad-sso.md). I suspected there may be a problem with App Registration itself (it was created a year ago through now deprecated Bot portal), so I've recreated a new one (c3eaa6b7-f8ea-4f0f-bbdc-8b0c079865b1) and it still reproduces.
I've googled an issue on SO that may be related ([OAuth refresh token from Azure Bot Service](https://stackoverflow.com/questions/52277586/oauth-refresh-token-from-azure-bot-service)), but it does not help since `offline_access` scope is now added by Bot automatically.
This issues has been already reported as support request ID 119111124002496 ("Support Request: Azure Bot Service does not renew AAD token"), you can find more details there.
Maybe our problem is just a configuration issue, so please provide guidance to fix it.

**Comment by axelsrz** [comment]
@carlosscastro hey could you take a look at this and work with Jeff if necessary? Thanks.

**Comment by carlosscastro** [comment]
Hello @crow-ua, I'm investigating this. Thanks for reporting!

**Comment by crow-ua** [comment]
@carlosscastro If you need any additional information feel free to contact me. I'm happy to help and try to resolve this issue asap.

**Comment by crow-ua** [comment]
Support engineer suggested to call `OAuthPrompt` in bot and it should refresh token.
I presume this originates from [here](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/18.bot-authentication/Dialogs/MainDialog.cs#L67):
```
private async Task<DialogTurnResult> DisplayTokenPhase1Async(WaterfallStepContext stepContext, CancellationToken cancellationToken)
{
    await stepContext.Context.SendActivityAsync(MessageFactory.Text("Thank you."), cancellationToken);

    var result = (bool)stepContext.Result;
    if (result)
    {
        // Call the prompt again because we need the token. The reasons for this are:
        // 1. If the user is already logged in we do not need to store the token locally in the bot and worry
        // about refreshing it. We can always just call the prompt again to get the token.
        // 2. We never know how long it will take a user to respond. By the time the
        // user responds the token may have expired. The user would then be prompted to login again.
        //
        // There is no reason to store the token locally in the bot because we can always just call
        // the OAuth prompt to get the token or get a new token if needed.
        return await stepContext.BeginDialogAsync(nameof(OAuthPrompt), cancellationToken: cancellationToken);
    }

    return await stepContext.EndDialogAsync(cancellationToken: cancellationToken);
}
```
My code:
```
private async Task<bool> IsConnected(DialogContext dc, CancellationToken cancellationToken)
{
    var user = await _accessors.User.GetAsync(dc.Context, () => new IntegratedUser(), cancellationToken);
    var adapter = (IUserTokenProvider)dc.Context.Adapter;
    var token = await adapter.GetUserTokenAsync(dc.Context, _appSettings.OAuthConnectionName, null, cancellationToken);
    if (token != null)
    {
        // Here i'm getting "old" token that expired weeks ago
        _logger.LogError($"***Token BEFORE***{user?.MsTeamsUserId}:\r\n{token?.Token}");
    }

    var result = await dc.BeginDialogAsync(nameof(OAuthPrompt), cancellationToken: cancellationToken);
    var tokenResponse = (TokenResponse)result.Result;
    if (tokenResponse != null)
    {
        // Getting ultimately the same token here
        _logger.LogError($"***Token AFTER***{user?.MsTeamsUserId}:\r\n{tokenResponse?.Token}");
    }

    return !string.IsNullOrEmpty(tokenResponse?.Token);
}
```
No prompt is displayed. Debug log is interesting because it may indicate second time ADAL was indeed doing request to AAD and not going to cache:
```
info: MicrosoftTeams.Integration.App.Bots.TeamsBotHttpAdapter[0]
      GetTokenAsync: Acquired token using ADAL in 0.
fail: MicrosoftTeamsIntegration.Jira.JiraBot[0]
      ***Token BEFORE***(OID):
      ey...(CUT)...
info: MicrosoftTeams.Integration.App.Bots.TeamsBotHttpAdapter[0]
      GetTokenAsync: Acquired token using ADAL in 46.
fail: MicrosoftTeamsIntegration.Jira.JiraBot[0]
      ***Token AFTER***(OID):
      ey...(CUT)...
```
Maybe there is some sort of problem with ADAL itself (I remember some v1/v2 AAD shenanigans previously)? Although it works just fine for our tabs.

**Comment by carlosscastro** [comment]
Hello @crow-ua. Apologizes that we didn't update the issue, however there was work on the background related to this. This is related to a bug on our service (not SDK) which we fixed before the holidays but just got deployed. The service that provides the oauth connection tokens to the bot was returning expired tokens. Even though the service does not renew tokens on the bot's behalf, it is wrong for it to return expired tokens. The newly deployed version of the service should return nothing if the token expired. In that case you can just re-show the OAuth prompt and re-obtain the token from the user.

Could you try again now that the service behaves differently after the last deployment?

Also, a few notes about your other comments. The token is retrieved from our token service and not from ADAL. The adal logs you are when the bot acquires the token to talk to the channel, not for the oauth connection so I would not use them to diagnose this issue in particular. the OAuth connection token is in an external service owned by us and all there is in the sdk are calls to that service. 

Please let me know if the new service behavior helps!

**Comment by crow-ua** [comment]
@carlosscastro We've already noticed changed behavior, and unfortunately it still does break our workflow. Our bot is essentially an integration with on-premises system and valid AAD token passed along with request is a security requirement. Making every user sign in in bot every hour instead of silently refreshing token is too ugly. 
It looks like we need to revert back to MSAL + Azure Cache for Redis and throw away Bot Service + OAuth connection approach. What's funny, it would still work in other products that integrate with Google services because their token is refreshed automatically ;(.

**Comment by carlosscastro** [comment]
@crow-ua, I see, that is not a great user experience, I agree. Let me pass the message on to my team to see whether there is a plan to do automatic refresh at some point. I'll update this after talking to them. Thanks for your input!

**Comment by carlosscastro** [comment]
@crow-ua: good news is that there is a solid plan to do automatic update. Bad news is that we don't have a clear timeline yet, so we cannot really commit at this date. Feel free to check in with me or revive this bug to check back in.
