### ISSUE TITLE
[Directline] Very slow to establish websocket

### ISSUE THREAD

**Issue by Crazedpeanut** [microsoft/BotFramework-Services#151]
Our customers are having intermittent issues sending messages to their bots. This normally begins with a long initial connection. 

Response Time: around  80,000 ms
GET wss://directline.botframework.com/v3/directline/conversations/5GvoKcen2xv4tLBWLYZHS5-0/stream 
Conversation ID: 5GvoKcen2xv4tLBWLYZHS5-0
x-ms-request-id |e41973cbdf82584f9d3d238b6fa4641f.77d6027c_
Timestamp: 2019-11-20T03:53:14.638Z

**Comment by jwiley84** [comment]
Are your bots deployed on Azure? If so, are they set to 'always on'?

**Comment by DDEfromOR** [comment]
Assigning to @mickeydjw for triage. This will be the classic, non-duplexed, WebSocket on DirectLine SaaS. I took a quick look in our logs and couldn't find any tracing for the conversation mentioned above.

**Comment by Crazedpeanut** [comment]
> Are your bots deployed on Azure? If so, are they set to 'always on'?

Yes, deployed on Azure and set to 'always on'. We don't see this long request in our logs

**Comment by mickeydjw** [comment]
Is this issue still occurring for your customers?

**Comment by dandriscoll** [comment]
Hi @Crazedpeanut are you still experiencing this problem? We would like to take a look but have not been able to find details about the one example you sent. It has also been removed from our logs so we would need a more recent instance to investigate further. A conversation ID or a URL like you sent in your first post should be sufficient.

**Comment by mickeydjw** [comment]
Closing due to lack of response
