### ISSUE TITLE
[LINE Channel] When the bot is in a group which type is room, it cannot send messages correctly.

### ISSUE THREAD

**Issue by fuine6** [microsoft/BotFramework-Services#153]
I create a [room](https://developers.line.biz/en/reference/messaging-api/#source-room), it can chat with multiple members, but it is not a group.

I send a message to the room, I expected the bot to respond in the room, but the bot responded to the personal chat room.
![capture8](https://user-images.githubusercontent.com/34824302/70198200-2c35db80-1749-11ea-85a9-a5f1482ca754.png)

The message from ngrok.
```
{
    "type": "message",
    "id": "c3f6b6e101164989bca837931217e35a",
    "timestamp": "2019-12-05T02:15:27.4789323Z",
    "serviceUrl": "https://line.botframework.com/",
    "channelId": "line",
    "from": {
        "id": "U46eb74ae1dd9cd8772bb63xxxxxxxxxx", // <- This is my userId.
        "name": "LINE"
    },
    "conversation": {
        "isGroup": false, // <- Should be true?
        "id": "U46eb74ae1dd9cd8772bb63xxxxxxxxxx|Iegtzf7rAtF"
    },
    "recipient": {
        "id": "Iegtzf7rAtF",
        "name": "thebot-test"
    },
    "text": "test message"
}
```

**Comment by stevkan** [comment]
@fuine6, can you check that you enabled group chat for you bot in Line?

To do so:

- Log into Line and access the [developer site](https://developers.line.biz/en/services/bot-designer/), then access your Line bot.
- Next, click on the "Messaging API", scroll down to "Line Official Account Features" => "Allow bot to join group chats", and click the "edit" link to the right. This will open up a separate settings page.
- On this new settings page, click on "Account settings", scroll down to "Chat settings" => "Group and multi-person chats", and change the selection to "Allow account to join groups and multi-person chats". Click "Ok" on the popup window to save the changes.

Enabling group chat in Line allowed my bot to respond directly to the group chat window.

**Comment by fuine6** [comment]
Bot works well in groups, but not in room, this is the channelData I received.
```
{
  "message": {
    "text": "test",
    "id": "11042332700003",
    "type": "text"
  },
  "replyToken": "4fb642a3d393452c8883ecxxxxxxxxxx",
  "type": "message",
  "source": {
    "type": "room",
    "userId": "U46eb74ae1dd9cd8772bb63xxxxxxxxxx"
  },
  "timestamp": 1575659075110
}
```

**Comment by youyu16** [comment]
looks like roomId was lost. investigating
