### ISSUE TITLE
[LINE Channel] Activity.From.Name is always 'LINE'

### ISSUE THREAD

**Issue by fuine6** [microsoft/BotFramework-Services#154]
I can't seem to get the sender's name from Activity.From.Name, the value is always 'LINE'.

```
{
    "type": "message",
    "id": "8c422f28aac54edbb08eff1986d3fee1",
    "timestamp": "2019-12-05T09:21:06.7657149Z",
    "serviceUrl": "https://line.botframework.com/",
    "channelId": "line",
    "from": {
        "id": "U46eb74ae1dd9cd8772bb63xxxxxxxxxx",
        "name": "LINE"
    },
    "conversation": {
        "isGroup": false,
        "id": "U46eb74ae1dd9cd8772bb63xxxxxxxxxx|Iegtzf7rAtF"
    },
    "recipient": {
        "id": "Iegtzf7rAtF",
        "name": "thebot-test"
    },
    "text": "test"
}
```

Is this correct?

**Comment by mdrichardson** [comment]
@fuine6 This was actually fixed in a recent PR after another customer noticed this. You should see the change go live in the next couple of weeks. The change is on the backend, so no need to update packages. Please re-open this if you still experience the issue in a couple of weeks.

**Comment by fuine6** [comment]
I found this change has taken effect, but only if the user and the bot are friends.

Is there a way to get the sender's name when the sender and robot are not friends?

Currently, I have to use api to get the name of the sender in the [group](https://developers.line.biz/en/reference/messaging-api/#get-group-member-profile) or [room.](https://developers.line.biz/en/reference/messaging-api/#get-room-member-profile)

**Comment by mdrichardson** [comment]
@youyu16 Is this intended?

**Comment by youyu16** [comment]
Yes, bot need to be a friend of the user to get user profile depend on LINE document.
https://developers.line.biz/en/docs/messaging-api/user-consent/
![image](https://user-images.githubusercontent.com/17819112/71389465-74a13480-2637-11ea-9e8a-f24127acd93c.png)

**Comment by fuine6** [comment]
> Yes, bot need to be a friend of the user to get user profile depend on LINE document.
> https://developers.line.biz/en/docs/messaging-api/user-consent/

Is it possible to use this [api](https://developers.line.biz/en/reference/messaging-api/#get-group-member-profile)?

It can get user profiles of users who have not added the bot as a friend.

**Comment by youyu16** [comment]
@fuine6  Thanks for reminding, Just aware of the API, let me see what I can do.

**Comment by mickeydjw** [comment]
Fix has been checked in.
