### ISSUE TITLE
[LINE Channel] Activity.Conversation.IsGroup is always 'false'

### ISSUE THREAD

**Issue by fuine6** [microsoft/BotFramework-Services#156]
I am in a group, but the value is false.

```
{
    "type": "message",
    "id": "IvmqcwZ8bOK",
    "timestamp": "2019-12-07T09:38:34.6512244Z",
    "serviceUrl": "https://line.botframework.com/",
    "channelId": "line",
    "from": {
        "id": "C24b314735ca91e6c3048bexxxxxxxxxx",
        "name": "LINE"
    },
    "conversation": {
        "isGroup": false,
        "id": "C24b314735ca91e6c3048bexxxxxxxxxx|Iegtzf7rAtF"
    },
    "recipient": {
        "id": "Iegtzf7rAtF",
        "name": "thebot-test"
    },
    "text": "123",
    "channelData": {
        "message": {
            "text": "123",
            "id": "11045308695717",
            "type": "text"
        },
        "replyToken": "1f3c9797555440b2bb19d5xxxxxxxxxx",
        "type": "message",
        "source": {
            "type": "group",
            "groupId": "C24b314735ca91e6c3048bexxxxxxxxxx",
            "userId": "U46eb74ae1dd9cd8772bb63xxxxxxxxxx"
        },
        "timestamp": 1575711514196
    }
}
```

**Comment by mdrichardson** [comment]
@fuine6 I can confirm that I can reproduce this issue. I have also identified where the backend code needs to change, but I am unsure of the repercussions of changing it. For now you could use `channelData.source.type` to determine if it is a group or not (as well as grab the userId like your last question).

@youyu16 Do you have any comments on this?

**Comment by youyu16** [comment]
@mdrichardson I think this bug is already been fixed and waiting next regular release.

**Comment by mdrichardson** [comment]
@youyu16 I thought that might be the case. Thanks for confirming.

@fuine6 I'm going to close this for now. Feel free to re-open if you don't see that it's been fixed in a couple of weeks.
