### ISSUE TITLE
Multiple Asterisks in Dialog Choice are Truncated in Twilio

### ISSUE THREAD

**Issue by cdwaddell** [microsoft/BotFramework-Services#158]
I am not sure which integration point causes this issue, but when I present the user with a dialog prompt where I present the user with masked values:

```
- c******ll@g****.com
- d*****ll@h*****.com
```

I receive a text with the following items to choose from:

```
1. c***ll@g**.com
2. d***ll@h***.com
```

Note this works fine in the emulator or in the web interface. It only seems to be an issue with the Twilio integration.

![image](https://user-images.githubusercontent.com/3679097/70450976-9c5a9f00-1a72-11ea-99df-186241ba4578.png)

If this is not a bug, is there some form of documentation to know when I need to adjust values on one platform verses another.

**Comment by cdwaddell** [comment]
We had a similar problem with line breaks as noted in the following issue #49, so we added a hack specifically for SMS.

**Comment by stevkan** [comment]
Hi @cdwaddell, if you wrap the choice string values in triple backticks (```), the string will display as you intended with the text being read as a block.

The issue is that the connector is designed to render any markdown formatted text passed thru it. Generally, this isn't an issue however, in the case of Twilio, it _appears_ that the service does not support markdown resulting in it being stripped out. For instance, I tested sending `_c******ll@g****.com_` which should have italicized the text (and does so when run thru Web Chat and Emulator). But, the result was the same in Twilio, `c****ll@g**.com`, which coincides with the "bold" markdown syntax (`**`) also being removed despite it being mid-word and next to similar characters (*).

I'm going to mark this as a bug for further consideration. In the meantime, the below solution should point you in the right direction.

Hope of help!

```js
async maskedValue ( stepContext ) {
  let message = 'Choose your email'

  let choice1 = {
    value: "```c******ll@g****.com```"
  }  
  
  let choice2 = {
    value: "```d*****ll@h*****.com```"
  }

  const choices = [ choice1, choice2 ];

  return await stepContext.prompt( 'choicePrompt', {
    prompt: message,
    choices: choices,
    style: ListStyle.list
  } );
}
```

![twilio](https://user-images.githubusercontent.com/18403946/70611000-5bb96d80-1bb9-11ea-8f98-ef8033db0044.jpg)

**Comment by cdwaddell** [comment]
Thanks @stevkan.

**Comment by cdwaddell** [comment]
@stevkan Apparently this introduces a problem in the chat emulator. Before I added the backticks, I was presented with buttons:
![image](https://user-images.githubusercontent.com/3679097/70632451-d788d980-1bfc-11ea-8231-c6f35f7dc9d3.png)

Now I am presented with a single message that is not interactive:
![image](https://user-images.githubusercontent.com/3679097/70632120-3e59c300-1bfc-11ea-9789-bd3475040d8d.png)
I am assuming this will be the same experience in the web chat.

**Comment by cdwaddell** [comment]
I am going to work around this issue by conditionally adding the backticks on Twilio only.

**Comment by dandriscoll** [comment]
Hi @cdwaddell, another workaround is to suppress markdown formatting by setting the ```textFormat``` property on the activity to ```plain```. This will inhibit the markdown processing from taking place.

Let us know if any issues applying either of these workarounds.

**Comment by dandriscoll** [comment]
(You can find the textFormat field documented here: https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#text-format Simply apply it to the activity before sending it.)

**Comment by dandriscoll** [comment]
Closing this issue as a solution (`textFormat: 'plain'`) and a workaround (backticks) are available. Let us know if you have additional questions.
