### ISSUE TITLE
How to associate each connection with a different tenant

### ISSUE THREAD

**Issue by maximicciullo** [microsoft/BotFramework-Services#160]
Hi, 

We are using our bot application and we've in mind to use **botframework-webchat** in order to connect it. We just been doing some prove of concept using **Direct Line** and all went well, but we're concerned about the following:

- how can we associate each connection with each tenant? 

- How can we sure each connection only correspond to a tenant and no other can use it to connect? 

Thanks in advance!
Maxi

**Comment by anusharavindrar** [comment]
Hello @maximicciullo , could you elaborate more on what you are trying to achieve and about your bot application?

**Comment by maximicciullo** [comment]
Hi @anusharavindrar,

We have a bot that needs to be put in private sites of different clients. The bot is multitenant so we need to make sure we can securely determine from which tenant(or website?) the user is chatting from.
 
Our requirements would be:

- Identify the tenant for the user

- Make sure they can’t fake the tenant so that they can’t access the wrong information. 

- Be able to provide the web chat client to our customers so that they can access the backend through DirectLine in a secure way.

**Comment by anusharavindrar** [comment]
@maximicciullo  I would suggest you to get started by implementing [Enhanced Direct Line Authentication Features](https://blog.botframework.com/2018/09/25/enhanced-direct-line-authentication-features/) and also look at the [sample](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/19.a.single-sign-on-for-enterprise-apps) for single sign on for enterprise apps. Also, if you want to make sure they do not fake the tenant, then I would suggest you to ask the users to [sign in](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp).

**Comment by dandriscoll** [comment]
Hi @maximicciullo, you can separate each tenant into a "site" within Direct Line. Sites contain distinct keys and configurations, and are designed to allow a single bot to be exposed in different security domains. Clients cannot impersonate the site ID -- it is locked by the DL secret/token.

You can allocate new sites within the UI or via the ARM API.

Your bot can identify the site by inspecting the activity.recipient.id field. It will be "<bot ID>@<site ID>" for all activities sent with channelId of "directline" or "webchat"

**Comment by maximicciullo** [comment]
Hi @anusharavindrar and @dandriscoll for both anwsers! 

I've been trying to use DL with **Enhanced authentication options** enabled and I got a 500 Service Error.

I'm trying with different ways as using a script with in html file and also as hitting directly with Postman and both cases I got same error. 

Let me show you the json body that I'm sending in the Request (with the Authorization Header with the corresponding secret value)

`{
      User: {
         id: "dl_12345",
         name: "UserTest"
      },
      trustedOrigins: ["http://localhost:5000"]
}`

And the Response is **500 internal Server Error** 

`{
  "error": {
    "code": "ServiceError"
  }
}`

BTW, if I try to hit the service without the Json Body with the User I got the following right error:

**400 Bad Request**
`{
  "error": {
    "code": "BadArgument",
    "message": "tokenParameters is missing User."
  }
}`

Can you confirm if that service has any problem from MSFT side? 

Thanks!

**Comment by DDEfromOR** [comment]
Hi @maximicciullo,

Just to be sure, when you're sending the request to the generate endpoint are you including the Content-Type header with a value of application/json? Postman automatically does this if you set the body type to JSON. While working to repro this issue I learned the hard way leaving body set to text causes a ServiceError response.

**Comment by maximicciullo** [comment]
Hi @DDEfromOR, you're totally right! the body type was wrong... thank you very much! 

Now I got a **200 ok** with the conversationId and token. 

By the way, I don't understand why it gave me that response if I remove the **trustedOrgins** string, Shouldn't it fail anyway?

**Comment by DDEfromOR** [comment]
Awesome! I'm glad you're able to generate tokens now. 

My understanding is the trustedOrigins string is optional because at least one trusted origin has to be defined on the bot's channel configuration when enabling enhanced authentication options for DirectLine, but to be certain I've emailed the subject matter expert and will give you a better answer once I hear back.

**Comment by maximicciullo** [comment]
Great @DDEfromOR, thanks for your soon help!

**Comment by maximicciullo** [comment]
Hi, in order to give more information about my issue I'm goin to leave here all the different scenarios that I was doing and testing. I'm aiming to validate a tenant using Direct Line in our Web Chat, so to do that I set **Enhanced Authentication Options enable** in Portal Azure and then define the necessary Request with Secret, UserId and TrustedOrigins values as mentioned in documentation to get the Token from the Response.

### **SCENARIO 1:**

Portal Azure Channel Configuration:

- Site: Default Site

- Enhanced authentication options: Enabled

- Trusted Origin Site: http://localhost:5000

- Request: POST to `https://directline.botframework.com/v3/directline/tokens/generate` with secret defined in HEADER and the following JSON BODY `{
	"User": {
		"id": "dl_12345",
        "name": "UserTest"
    },
    "trustedOrigins": ["http://localhost:5000"]
}`

- Response: 200 OK with `conversationId`, `token` and `expires_in`

- WebChat: Up and running in Localhost OK

- **Expected Behavior: OK!!**

### **SCENARIO 2:** (JSON BODY without trusted origins string site)

Portal Azure Channel Configuration:

- Site: Default Site

- Enhanced authentication options: Enabled

- Trusted Origin Site: http://localhost:5000

- Request: POST to `https://directline.botframework.com/v3/directline/tokens/generate` with secret defined in HEADER and the following JSON BODY `{
	"User": {
		"id": "dl_12345",
        "name": "UserTest"
    }
}`

- Response: 200 OK with `conversationId`, `token` and `expires_in`

- WebChat: Up and running in Localhost OK. Should not be working because trusted origin was not defined in request.

- **Expected Behavior: Fail because I did not define the trusted origin string value in request and I got Token to use... It should filter by trusted origin site because it's enabled in portal azure to that site**

### **SCENARIO 3:** (Changing to a different Trusted Origin Site in Portal Azure)

Portal Azure Channel Configuration:

- Site: Default Site

- Enhanced authentication options: Enabled

- Trusted Origin Site: https://anothersite.com

- Request: POST to `https://directline.botframework.com/v3/directline/tokens/generate` with secret defined in HEADER and the following JSON BODY `{
	"User": {
		"id": "dl_12345",
        "name": "UserTest"
    },
    "trustedOrigins": ["https://anothersite.com"]
}`

- Response: 200 OK with `conversationId`, `token` and `expires_in`

- WebChat: Up and running in Localhost OK. Should not be working because trusted origin site now is `https://anothersite.com` and Web Chat is running in Localhost 5000.

- **Expected Behavior: Fail because trusted origin site different to Web Chat host. Should not be working correclty.**

### **SCENARIO 4:** (Changing to a different Trusted Origin Site in Portal Azure and JSON BODY without trusted origins string site)

Portal Azure Channel Configuration:

- Site: Default Site

- Enhanced authentication options: Enabled

- Trusted Origin Site: https://anothersite.com

- Request: POST to `https://directline.botframework.com/v3/directline/tokens/generate` with secret defined in HEADER and the following JSON BODY `{
	"User": {
		"id": "dl_12345",
        "name": "UserTest"
    }
}`

- Response: 200 OK with `conversationId`, `token` and `expires_in`

- WebChat: Up and running in Localhost OK. Should not be working because trusted origin site now is `https://anothersite.com` and Web Chat is running in Localhost 5000. And also trusted origin site is not present in Request.

- **Expected Behavior: Fail because trusted origin site different to Web Chat host and also is not present in Request. Should not be working correclty.**

### Summary
As you can see, setting **Enhanced authentication options: Enabled** only validate to set a **UserID** into the Request but nothing happens about the Trusted Origins String defined or not into the Request. 

Please, let me know if I'm doing something wrong using trusted origins optional

Thanks!

**Comment by maximicciullo** [comment]
Hi @DDEfromOR, did you have any news? Please let me know! 

Thanks!

**Comment by Jeffders** [comment]
When you have the Enhanced Authentication enabled, you will see the following behavior for which trusted origins are used:

1. If you configure trusted origins as part of the configuration UI page, then these will ALWAYS be used as the only set. Sending no or additional trusted origins when generating a token or starting a conversation will be ignored (i.e. they are NOT appended to the list or cross validated).

2. If you have not configured trusted origins as part of the configuration UI, then any you send as part of the API calls will be used.

**Comment by anusharavindrar** [comment]
@maximicciullo does the above explanation answer your doubts? Do you need any more help?

**Comment by maximicciullo** [comment]
Hi @anusharavindrar, I was trying to do what @Jeffders mentioned and I guess I'm almost to solve it.

I was doing option 1 that @Jeffders mentioned but I got a 500 error response when I hitted direct line token generator endpoint. 

I got trusted origins as part of the configuration UI page and in the request I only set the header with secret and body with userId and name... I guess I'm not correctly creating the fetch body json.

Can someone help me if I'm doing that wrong or just give me a working example of how to hit token generator api using fetch function with header and body, please?

Also I've trying to use `body: JSON.stringify()` passing a user with id and name but I got same error.

Attached you can see consolo log error and also the fetch code that I'm using. 

Thanks for all your help!

<img width="679" alt="trustedOrigins" src="https://user-images.githubusercontent.com/3813607/72688016-47369200-3ae2-11ea-8704-6921794f643a.png">
<img width="840" alt="fetchCode" src="https://user-images.githubusercontent.com/3813607/72687952-b495f300-3ae1-11ea-9eb5-9d95a2dcd61b.png">
<img width="1440" alt="consoleLogDebug" src="https://user-images.githubusercontent.com/3813607/72687953-b5c72000-3ae1-11ea-9655-dea6d58adb2e.png">

**Comment by maximicciullo** [comment]
Hi @anusharavindrar, I was trying to use the option 1 that @Jeffders mentioned but I'm afraid is not working as I try to used it. Let me show you and please correct me if I'm wrong! 

1. In Portal Azure ->  Channels  -> Default Site, I've activated **Enhanced authentication options**. Then I added a **trusted origin site** as https://anothersite.com (that's not a real site). 

<img width="674" alt="DirectLineConfiguration" src="https://user-images.githubusercontent.com/3813607/72694821-14f25800-3b15-11ea-80b0-7f15066ee1ae.png">

2. From my client JS a did a fetch request only with HEADER using Secret from Default Site in Direct Line previously mentioned and also settled the BODY using a user information (id and name, and not using trusted origins array).

<img width="901" alt="FetchJsonTokenGenerator" src="https://user-images.githubusercontent.com/3813607/72694891-597df380-3b15-11ea-8677-56cfd153e73a.png">

3. Then I used `npx serve` in order to get the web chat up and running in my browser locally from `http://localhost:5000`

4. My intention with this scenario is to don't get the webchat window running and get an error becasue I set an unreal site (https://anothersite.com) in azure portal channel directline and I'm running the server from localhost. So locahost differ to anothersite.com defined in portal azure

5. As **NOT EXPECTED** result I got the web chat window up and running perfectly working.
<img width="1440" alt="webchatBrowserWindow" src="https://user-images.githubusercontent.com/3813607/72695311-d3fb4300-3b16-11ea-9408-d06cd2e9ef6e.png">


So, my concern is how can I filter sites different (in this case) from localthost and the trusted origins site I define in portal azure. 
 
Please, hope that someone can help me to understan how really trusted origins optional works, I've been searching information and examples but is really difficult to find them

Above all, thanks for your response and your time!

**Comment by Jeffders** [comment]
Trusted origins is not an origin request header filter right now, so what you are trying is expected to work. It is used in user sign-in scenarios with DirectLine and WebChat to avoid needing to add the magic code two-factor authentication code.  You can read about this here:
https://blog.botframework.com/2018/09/01/using-webchat-with-azure-bot-services-authentication/

We do have a preview feature that will do an origin check on Direct Line APIs with Trusted origins. 

We will work on improving the documentation around trusted origins as I agree this isn't clear.

**Comment by maximicciullo** [comment]
Ok, that's a huge problem for us. 

Do you have a deadline for the new feature @Jeffders ?

Thanks!

**Comment by Jeffders** [comment]
Send me an email at jeffders at Microsoft dot com with your bot and or subscription and I can whitelist you. Does that work?

**Comment by maximicciullo** [comment]
Sure, thank you!

**Comment by CoHealer** [comment]
Closing with white-listing

**Comment by karangupta8** [comment]
Hi @Jeffders , I have the same issue in my org where cyber security has pointed out this vulnerability of CSRF attack.
I see this thread is 6 months old. Is there any new ETA on the feature release of verifying request headers?
Our org will not let us use a preview feature in production. Is there any other alternate that can be used to fix this issue?
It'll be highly appreciated as it has become a very huge showstopper for our project right now.

**Comment by iliosana** [comment]
Hi @Jeffders, do you have any update on this?
