### ISSUE TITLE
Telegram connector says Delete Activity is not supported

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Services#163]
When a bot tries to use the [Delete Activity](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference#delete-activity) conversation operation, the Telegram connector service returns the same error that Direct Line and all the other channels that don't support Delete Activity return ("This channel does not support this operation"), but [the Telegram Bot API *does* support message deletion](https://core.telegram.org/bots/api#deletemessage). Also, messages can be *edited* using the Telegram connector service so the expectation is that messages can be deleted as well.

## To reproduce

```c#
await turnContext.DeleteActivityAsync(id, cancellationToken);
// "This channel does not support this operation"
```

**Comment by mickeydjw** [comment]
Hopper item created.  Closing Issue.
