### ISSUE TITLE
MS Bot to Teams Integration issue 

### ISSUE THREAD

**Issue by Rakesh5594** [microsoft/BotFramework-Services#167]
Bot OnSend Activity is returning twice and it results error: activity must include non empty 'text' field or at least 1 attachment

**Comment by mdrichardson** [comment]
Since you have this opened [on SO](https://stackoverflow.com/questions/59679230/ms-bot-to-teams-integration-issue), I'm going to close this and provide support there.

**Comment by Rakesh5594** [comment]
Hi Richardson, The SDK Version we are using are v4 and attached the error we are getting in Azure as warnings and below is log report FYR.. In mainDialog: displayHelpOptions step Innnnnnn onSendActivities Innnnnnn onSendActivities Dispatch Intent: Qna IT intents In QnaMaker dialog - confirm Innnnnnn onSendActivities Innnnnnn QnA if Innnnnnn onSendActivities Regex not found. Sending answer Innnnnnn onSendActivities INSIDE SENDACTIVITY Hi! How may I help to make your day better? Innnnnnn MainDialog intro step Innnnnnn onSendActivities Innnnnnn onSendActivities
