### ISSUE TITLE
AttachmentBot failes to upload file

### ISSUE THREAD

**Issue by mindncz** [microsoft/BotFramework-Services#168]
## Sample information
1. Sample type: BotBuilder-Samples/samples
2. Sample language: dotnetcore
3. Sample name: AttachmentsBot

## Describe the bug
GetUploadedAttachmentAsync throws exception: "Operation returned an invalid status code 'NotFound'"  in Teams. 
When tested in Bot emulator, GetUploadedAttachmentAsync works well and the file could be uploaded.

## To Reproduce
1. Add AttachmentBot into some team
2. Reply option 3 to AttachmentBot 
3. AttachmentBot replies message "Sorry, it looks like something went wrong."

## Expected behavior
The attached file "architecture-resize.png" will be uploaded successfully.

**Comment by EricDahlvang** [comment]
Yes, Bots require users to accept files sent to them.  More information can be found here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet#using-the-teams-bot-apis

**Comment by EricDahlvang** [comment]
The services team pointed out the maximum message size is 256k, which explains the inline attachment failure.  A PR is here https://github.com/microsoft/BotBuilder-Samples/pull/2130 to reduce the image size, which enables Sample 15 on the Direct Line channel.

**Comment by abhi421** [comment]
GetUploadedAttachment is still not working in Teams.
When tested in Bot emulator, GetUploadedAttachment works well and the file could be uploaded.
Sample type: BotBuilder-Samples/samples
Sample language: NodeJS
Sample name: 15. handling attachment

**Comment by arturl** [comment]
Reopening. Apparently since size is not the issue here. Assigned to @johnataylor

**Comment by EricDahlvang** [comment]
GetUploadedAttachment is not intended to work on Teams. Sample 56 with the  FileConsentCard is the sample to use for teams.

**Comment by EricDahlvang** [comment]
From the readme of sample 15:

NOTE: A specific example for Microsoft Teams, demonstrating how to upload files to Teams from a bot and how to receive a file sent to a bot as an attachment, can be found here

**Comment by EricDahlvang** [comment]
Closing this, since sample 15 is not intended for Teams.

**Comment by dgancho** [comment]
> Yes, Bots require users to accept files sent to them. More information can be found here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet#using-the-teams-bot-apis

@EricDahlvang This link is broken, 404

**Comment by billreynolds007** [comment]
404 bump

**Comment by Jagadeesh-MSFT** [comment]
Hi @dgancho, @billreynolds007   Could you please try this [document](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/bots-filesv4#message-requesting-permission-to-upload).
