### ISSUE TITLE
directline.botframework.com SSL/TLS handshake failed 

### ISSUE THREAD

**Issue by songohannyc** [Microsoft/BotFramework-Services#17]
Hi,

Around 3:30 PM EST today, we notice that directline.botframework.com SSL/TLS handshake failed.
I don't see any status issue at https://azure.microsoft.com/en-us/status/ on Azure Bot.

Could someone from Microsoft please comment what is going on? 
Please also note that the issue appears to occur on our servers in US-EAST and US-Central, not US-WEST.

Below is the curl output in US-EAST.
```
curl -v https://directline.botframework.com
* Rebuilt URL to: https://directline.botframework.com/
*   Trying 40.121.91.199...
* Connected to directline.botframework.com (40.121.91.199) port 443 (#0)
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake`
```

Appear to be okay in US-WEST.
```
curl -v https://directline.botframework.com
* Rebuilt URL to: https://directline.botframework.com/
*   Trying 40.121.91.199...
* Connected to directline.botframework.com (40.121.91.199) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.botframework.com
* Server certificate: Microsoft IT TLS CA 2
* Server certificate: Baltimore CyberTrust Root
> GET / HTTP/1.1
> Host: directline.botframework.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Cache-Control: private
< Content-Length: 146
< Content-Type: text/html; charset=utf-8
< Location: https://dev.botframework.com/
< Server: Microsoft-IIS/10.0
< X-AspNetMvc-Version: 5.2
< Strict-Transport-Security: max-age=31536000
< Date: Fri, 02 Nov 2018 00:58:02 GMT
...
..
.
```

**Comment by vincec-msft** [comment]
A hotfix has been deployed and Direct Line is looking healthy again.

The issue was posted here, but hasn't been updated yet. We're still watching to make sure the system is happy.

https://portal.azure.com/#blade/Microsoft_Azure_Health/AzureHealthBrowseBlade/serviceIssues

I'm not sure why the main status page was not updated.

**Comment by vincec-msft** [comment]
System remains stable. Closing this.
