### ISSUE TITLE
Not able to retain selected values in adaptive card On Submit.

### ISSUE THREAD

**Issue by Rakesh5594** [microsoft/BotFramework-Services#170]
I am trying to retain the selected values in adaptive cards after submitting with user input. So I am using updateActivity() function(which is an in-built function).
When I try to run the code on Webchat channel(and emulator) it throws onTurnError() after user submits the adaptive card.
So it the issue from my side or the updateActivity() is not supported by microsoft in webchat channel(and bot emulator). Also if not supported, what is the work around for this issue?

**Comment by v-kydela** [comment]
@Rakesh5594 - Are you talking about the Teams issue described [here](https://stackoverflow.com/questions/57870044/adaptive-card-clears-input-on-submit) and [here](https://stackoverflow.com/questions/59710556/after-submit-adaptive-cards-are-not-retaining-value-of-text-entered-in-text-box)? 

If so, that problem does not apply to Web Chat and Emulator. Adaptive Cards do not clear their inputs on those channels so there's nothing you need to do.

**Comment by Rakesh5594** [comment]
But I have been facing the issue in webchat as well as in emulator.
I have attached the image below, before submitting the cards I have selected the values as below.
![before_submit](https://user-images.githubusercontent.com/55781178/72608335-6a2d3e80-3948-11ea-920e-89452d171ddb.JPG)

After clicking next, the values are replaced by the placeholder values from the json file.

![after_submit](https://user-images.githubusercontent.com/55781178/72608334-6a2d3e80-3948-11ea-87c9-d33c8a768505.JPG)

For the first field, my json is as follows. Is it something to do with placeholder values or the value key in my json?

![jsonCard](https://user-images.githubusercontent.com/55781178/72608336-6ac5d500-3948-11ea-9854-913ac11759ed.JPG)

**Comment by v-kydela** [comment]
@Rakesh5594 - What version of Emulator are you using? Here's a screenshot of Emulator 4.7 retaining all Adaptive Card inputs after the submit action is clicked:

![image](https://user-images.githubusercontent.com/41968495/72635770-772f3b00-3912-11ea-9390-f733e35ae265.png)

If you are experiencing something different in Emulator, please post a screenshot of that. If you are experiencing something different in Web Chat, you will need to provide your Web Chat code because I cannot reproduce this in any version of Web Chat.

**Comment by Rakesh5594** [comment]
I am using version 4.5 of bot emulator. Can you please let me know what exactly the code do you want me to post?
I am using waterfall dialog to send the adpative cards.
The versions for botbuilder and botbuilder-dialogs are 4.5.1 and 4.5.3 respectively

Below is the waterfall dialogs to be called
![waterfallcode](https://user-images.githubusercontent.com/55781178/72780106-f474eb80-3c43-11ea-9a8a-561683d880a5.JPG)

The first step of the model is as follows-
![firststep](https://user-images.githubusercontent.com/55781178/72780104-f3dc5500-3c43-11ea-8c6c-7dbd55c2f1ef.JPG)

The second step followed is-
![secondstep](https://user-images.githubusercontent.com/55781178/72780102-f2129180-3c43-11ea-9ce1-3c3b0ba19967.JPG)

**Comment by v-kydela** [comment]
@Rakesh5594 

1. Can you update to [the latest version of Emulator](https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.7.0) and see if you're still experiencing the problem?
1. You just posted bot code. I asked for your Web Chat code. I need to see the HTML that you're using to host the Web Chat client.
1. It would help if you could provide the full JSON for an Adaptive Card that you're reproducing the problem with.
1. Please provide a [video](https://www.screentogif.com/) of the problem occurring in Web Chat and Emulator.

**Comment by sw353552** [comment]
@v-kydela 
Upon updating the emulator, it worked fine. Should we also update Webchat to 4.6.0?

**Comment by v-kydela** [comment]
@sw353552 - I have repeatedly asked for your Web Chat code and you have not given it to me so I don't know how you expect me to comment on that. Generally you should be using `/latest/webchat.js` so that you don't have to do any updating, but if you're using a specific version then yes you should either update it or switch to the "latest" URL.

**Comment by sw353552** [comment]
@v-kydela Yes Me and Rakesh are from the same team.
My webchat code looks like this,

import {
    DirectLine
} from 'botframework-directlinejs';
import React from 'react';
import ReactWebChat, { createDirectLine, createStore, Components } from 'botframework-webchat';
import * as AdaptiveCards from "adaptivecards";
import axios from 'axios';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
const { Composer } = Components;
const { connectToWebChat } = window.WebChat;
var msgParam = '';

class WebBot extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            service: '',
            cardType: '',
            margin_left: '',
            boxWidth: '',
            root_width: '',
            directLine: '',
            actionType: '',
            payloadValue: '',
        }
        // We are creating our own version of Redux store, which includes middleware and an optional initial state.
        this.store = window.WebChat.createStore({}, ({
            dispatch
        }) => next => action => {
            // console.log("action--> ", action);
    this.setState({actionType : action.type});
                if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {

                    // After connected, we will send a message by dispatching a Redux action.
                    if (this.state.service) {
                        dispatch({
                            type: 'WEB_CHAT/SEND_EVENT',
                            payload: {
                                name: this.state.service
                            }
                        });
                    }
                    else {
                        dispatch({
                            type: 'WEB_CHAT/SEND_EVENT',
                            payload: {
                                name: 'empty'
                            }
                        });
                    }
                }

                else if (action.type === 'DIRECT_LINE/INCOMING_ACTIVITY') {
                    // When receiving an activity of type "event" with name of "sample:backchannel", prompt it out.
                    const {
                    activity
                } = action.payload;

                    if (activity.type === 'event' && activity.name === 'sample:backchannel') {
                        alert(JSON.stringify(activity, null, 2));
                    }
                }
                else if(action.type === "DIRECT_LINE/POST_ACTIVITY_FULFILLED"){
                    // console.log("Payload value",this.state.payloadValue);
                    this.setState({payloadValue: action.payload});
                }
                
                return next(action);
            });

        var display = '';
        this.attachmentMiddleware = () => next => card => {
            if (card.attachment.contentType === 'application/vnd.microsoft.card.custom') {
                card.attachment.contentType = 'application/vnd.microsoft.card.adaptive';
                this.state.cardType = card.attachment.content.body[0].items[0].text;
                   
            }
            
            return next(card)
        }
    }

    async componentDidMount() {
        try {
            var param = this.getUrlVars()['m'];
            msgParam = this.state.cardType;
            
            this.setState({ service: param });
            
        }
        catch (err) {
            console.log(err);
        }
            const uuid = this.getUrlVars()["q"];
    
            // API to fetch token
            
            const {
 token, email, fullname
 } = await res.json();
                this.setState({ token: token, username: fullname, email: email });
                this.directLine = new DirectLine({ token: token});
                this.setState({ directLine: this.directLine });
        }
    render() {
        const { props } = this;

        return (
            !!this.state.directLine && (
                
                    <ReactWebChat 
                        userID={this.state.email}
                        username={this.state.username}
                        className="chat"
                        // activityMiddleware={this.activityMiddleware}
                        directLine={this.state.directLine}
                        store={this.store}
                        attachmentMiddleware={this.attachmentMiddleware}
                        adaptiveCardHostConfig={
                            {
                                actionTitleToWrap: true, spacing: 'small',
                                containerStyles: {
                                    default: {
                                        foregroundColors:
                                            {
                                                default:{default: "#034ea1", subtle: "#00f07507"},
                                                dark: { default: "#000000", subtle: "#66000000" },
                                                light: { default: "#BA042D", subtle: "#00BA042D" },
                                                accent: { default: "#034EA1", subtle: "#88034EA1" },
                                                good: { default: "#54A254", subtle: "#DD54A254" },
                                                warning: { default: "#EE7203", subtle: "#00EE7203" },
                                                attention: { default: "#CC3300", subtle: "#DDCC3300" },
                                            },
                                    },
                                }
                            }}
                        styleOptions={{
                            
                            sendBoxButtonColorOnHover: '#034ea1',
                            suggestedActionBorderRadius: '15px',
                            bubbleFromUserBackground: '#034ea1',
                            bubbleFromUserTextColor: '#ffffff',
                            fontWeight: 400,
                            suggestedActionBackground: '#034ea1',
                            sendBoxRadius: '15px',
                            textBoxWidth: this.state.boxWidth,
                            textBoxMarginLeft: this.state.margin_left,
                            rootWidth: this.state.root_width,
                            bubbleFromUserBorder: 'solid 0px #E6E6E6',
                            suggestedActionBorderRadius: '0px',
                        }}
                    />
            )
        );
    }
}

export default WebBot;


And my Webchat version is - 4.5.2. I will try updating it to 4.6.0

**Comment by v-kydela** [comment]
@sw353552 - Okay, I see now that you're integrating Web Chat with React. If you had gone with [the JavaScript option](https://github.com/microsoft/BotFramework-WebChat#integrate-with-javascript) then you could be accessing the latest version automatically with no need to update.

Have you updated Web Chat yet?

**Comment by v-kydela** [comment]
@sw353552 - Are you still working on this?

**Comment by sw353552** [comment]
@v-kydela After updating Webchat, adaptive cards are retaining the values selected by the user.

Thnx for helping.
