### ISSUE TITLE
How I know if it is better working with Web App Bot or Bot Channel Registration?

### ISSUE THREAD

**Issue by lpnieto** [microsoft/BotFramework-Services#171]
I would like to deploy a chatbot which I have in Visual Studio project in Azure Directory to connect it throw Teams Application. How I can be sure that it is the correct option? what is the difference between them?  Because the panel configuration is difference, App Settings appears in Web App Bot but not in Bot Channel Registration.
Thaanks! :)
![image](https://user-images.githubusercontent.com/57186595/72615064-144e9b80-3934-11ea-9535-ed6b5e628626.png)

**Comment by jwiley84** [comment]
Hi @ilpnieto

The Web App Bot and Bot Channels Registration serve two slightly different purposes. A Web App Bot is going to be a conglomerate of your bot code, an app service, and you channels registration. It's a good choice if you want to create a pre-deployed bot, then download and alter the code, then redeploy. It's essentially a web app (your bot code and the app service), and your bot channels registration added together and pre-configured.

A Bot Channels Registration is just that. Its  just the channels registration with no code. If you want to host your bot code somewhere else,  or if you are using an alternate deployment style to the one outline in our "How to deploy your bot" documentation, this is what you're going to create. Using this method means you'd have to create your own app service (this is where those app settings you mention lives), and web app. For further instruction, here is a barebones ["How to deploy using Visual Studio"](https://github.com/jwiley84/SelfHelpReadmes/blob/master/VisualStudioDeploy.md).  

If you further questions, feel free to ask!

**Comment by lpnieto** [comment]
Hi Jessica! First of all thank you for your support. I have a bot deploy with Visual Studio (I tested locally throw Bot Framework and it is running fine). I will check this information to next steps. Thanks you!! 👍

**Comment by Rakesh5594** [comment]
I am using version 4.5 of bot emulator. Can you please let me know what exactly the code do you want me to post?
I am using waterfall dialog to send the adpative cards.
The versions for botbuilder and botbuilder-dialogs are 4.5.1 and 4.5.3 respectively

Below is the waterfall dialogs to be called
![waterfallcode](https://user-images.githubusercontent.com/55781178/72724546-9e536a00-3ba9-11ea-9b29-a6ae6a36105d.JPG)

The first step of the model is as follows-
![firststep](https://user-images.githubusercontent.com/55781178/72724548-9e536a00-3ba9-11ea-8dab-968a2fe5e5c1.JPG)

The second step followed is-
![secondstep](https://user-images.githubusercontent.com/55781178/72724545-9d223d00-3ba9-11ea-8e34-72b09fce526f.JPG)
