### ISSUE TITLE
webchat URL - redirection with gemini

### ISSUE THREAD

**Issue by jbkcmouli** [microsoft/BotFramework-Services#175]
🚨 The issue tracker is not for implementation questions 🚨

[Question]
Hi,
Some one can please let us know why 
webchat URL in the below format
https://webchat.botframework.com/embed/botname?s=secret
is redirecting to new one with slight change with gemini added in URL
https://webchat.botframework.com/embed/<botname>/gemini?b=<botname>&s=<secret>

this redirection is causing issues for our integration of WebChat in Non-Browser Clients..

**Comment by botframeworkTest** [comment]
@jbkcmouli , the embed WebChat package is being upgraded to v4.6.0. This is why you see the extra redirect. 

Can you add some details about the HTTP client you use and the integration errors? Many non-browser HTTP clients will allow you to follow client side redirects. Example: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.allowautoredirect?view=netframework-4.8

**Comment by p-nagpal** [comment]
@jbkcmouli , the embed WebChat package is being upgraded to v4.6.0. This is why you see the extra redirect.
Can you add some details about the HTTP client you use and the integration errors? Many non-browser HTTP clients will allow you to follow client side redirects. Example: https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.allowautoredirect?view=netframework-4.8

**Comment by Tiger519** [comment]
@p-nagpal I have noticed the changes as well. For now it seems to be just visual changes, but all the colors have been completely stripped . This will not be acceptable for us to use with end users. Is there a way to restore the previous UI? I happen to have the same bot in two environments, of which only one is redirecting to Gemini. See screenshot attached.

![image](https://user-images.githubusercontent.com/27689397/73403378-4f01ed80-42bd-11ea-80ab-34acc854c061.png)

**Comment by p-nagpal** [comment]
@Tiger519, we are looking at offering styling options in the future. However, this might not work for you in the short term.

The Embed control can be upgraded by the service for new features, security and accessibility fixes at any time. If you want more control over the exact version of WebChat including branding/styling, then we recommend using WebChat from the CDN. This allows you specify the version and style. Here is a good sample to get started: https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.getting-started/a.full-bundle

That said, this upgrade will be rolling out to your other bot fairly soon. If you want your bots to be excluded from the upgrade now, please email me at ponagpal at microsoft dot com. Include your bot id(s).

**Comment by p-nagpal** [comment]
@jbkcmouli, I forgot to mention, if you want your bots to be excluded from the upgrade now, 
please email me at ponagpal at microsoft dot com. Include your bot id(s).

**Comment by jbkcmouli** [comment]
@p-nagpal thank you for the help; the client we use is SWT - Eclipse; while the investigation is going on with that how to handle the re-direction; I would take your offer to provide my bot-ids to be excluded
Since we are in production already;
I will send you the details from my official e-mail id.
