### ISSUE TITLE
Getting {"code":"ResourceNotFound","message":"/ does not exist"} exception while adding custom app to private channel in teams

### ISSUE THREAD

**Issue by ganeshsam14** [microsoft/BotFramework-Services#178]

**Comment by dmvtech** [comment]
Hi @ganeshsam14 Please provide more details. We need information about exactly what you are trying to do, steps to reproduce, version numbers, etc.

**Comment by dmvtech** [comment]
@ganeshsam14 Please let us know if you still need assistance with this. If so, please provide more information and resources to reproduce the problem.

**Comment by ganeshsam14** [comment]
@dmvtech sorry for the late response, I'm getting ResourceNotFound exception in Teams application while trying to add custom app to private channel.

![image](https://user-images.githubusercontent.com/22378589/74248043-fcf59a80-4cb4-11ea-8a01-e664549c8d06.png)

**Comment by dmvtech** [comment]
Bots cannot be added to private channels.

@Virtual-Josh @clearab For additional visibility/comments.
