### ISSUE TITLE
[Feature request] Add Webex Teams (Cisco Spark) channel

### ISSUE THREAD

**Issue by ogarules** [microsoft/BotFramework-Services#18]
Can we get Webex Teams Channel anytime soon?

**Comment by vviswadeep** [comment]
Is there any update on this Issue??

**Comment by EricDahlvang** [comment]
@vviswadeep BotKit, built on the Bot Framework, has a WebEx Adapter: https://botkit.ai/docs/v4/platforms/webex.html

**Comment by jameslew** [comment]
We do have this on our overall backlog, but as Eric mentions, the BotKit adapter hopefully will be useful for your needs.  Thanks!
