### ISSUE TITLE
Increase bot token ttl

### ISSUE THREAD

**Issue by prashanthsridhar** [microsoft/BotFramework-Services#182]
Is there a way to increase to the lifetime of the directline token.

**Comment by stevkan** [comment]
@prashanthsridhar, unfortunately, no there is no way to adjust the lifetime of the Direct Line token. However, you can always make a call to the `v3/directline/tokens/refresh` API to refresh the token giving it a new expiry. You can read more about calling the refresh API [here](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0#refresh-token).
