### ISSUE TITLE
[Feature Request]: Support for Discord as a channel

### ISSUE THREAD

**Issue by rurounijones** [microsoft/BotFramework-Services#184]
Add Discord ( https://discordapp.com ) as a channel for the Microsoft Bot Framework:

MVP: Text channel
Amazing-to-have: Voice channel

Migrating request from issue on old repo @ https://github.com/microsoft/botframework-sdk/issues/3248 that had 43 positive reactions

**Comment by jameslew** [comment]
Thank you!  We currently do not have Discord on our short term roadmap, though I will add it to the backlog.

**Comment by drewB** [comment]
As discord has become much more popular is there any update on this?

**Comment by xieofxie** [comment]
@drewB please reopen or create a new one with detailed requirements, thanks!
