### ISSUE TITLE
502 errors while connecting to bot using directline.

### ISSUE THREAD

**Issue by srikarcheruku** [microsoft/BotFramework-Services#187]
Hi I am getting 502 error saying the gateway time out exception. And this is happening only once in a while at random. 

We are using bot builder v4.4, memory storage of bot builder storing some information.

I would like to know what could be the root cause for it.

**Comment by stevengum** [comment]
@srikarcheruku, can you additional information about your bot configuration and where you're seeing these 502s? Is your bot being locally run or is it deployed to Azure?

**Comment by srikarcheruku** [comment]
Hi Steve

Thanks for the response.

It is a JS bot and has been deployed to Azure.

I am trying to connect to bot from front end using direct line, I am seeing these errors in directline channel issues in azure bot application.

What all do you need for bot configuration?

**Comment by dmvtech** [comment]
Do you have Application Insights setup for either or both of the App Service or Bot Channels Registration/Web Application bot?

This is likely related to the bot taking longer than 15 seconds. You can use logging/tracking to get a better picture of where your bot is taking time. To get a general idea if your bot is taking a long time and may be flirting with the 15 second timeout, you can run the following query in your app insights for your app service:

```
let start_time = ago(7d);
let end_time = now();
requests
| where duration > 14000
| where timestamp > start_time and timestamp < end_time
| limit 100
```

More info on 502:
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-general-problems?view=azure-bot-service-4.0#what-causes-the-direct-line-30-service-to-respond-with-http-status-code-502-bad-gateway

**Comment by dmvtech** [comment]
Hi @srikarcheruku Do you still need assistance on this? Did you find any info from the query or any logging/tracking?

**Comment by srikarcheruku** [comment]
Hi @dmvtech, i checked the logs and the bot is taking more than 15 seconds to reply sometimes. We are checking how to reduce the latency from the bot application.

Anyways Thanks for the help @dmvtech .
