### ISSUE TITLE
[Teams] Error on POST to 'https://smba.trafficmanager.net/emea/v3/conversations': [400] Bad Request on session.endConversation() method

### ISSUE THREAD

**Issue by yasminagavalda** [microsoft/BotFramework-Services#188]
### Issue
When bot uses the session.endConversation() method, it gets the following error:
````
Error: POST to 'https://smba.trafficmanager.net/emea/v3/conversations/a%3A1OLYJ4NLRNxMIwxK6a2OqGYvGv30ZzfINPLVLdaXoCb7Uc9sO39Z65scLB7o7S1xz5AZKGPPUND-71i5WAKkOdNW75BVBsRcViD_Lt7n92H3v--F6rDZrSwLHj22etMjJ/activities/1583319974539' failed: [400] Bad Request
    at Request._callback (/Users/ygavalda/projects/chatbot-security-awareness/node_modules/botbuilder/lib/bots/ChatConnector.js:650:46)
    at Request.self.callback (/Users/ygavalda/projects/chatbot-security-awareness/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/ygavalda/projects/chatbot-security-awareness/node_modules/request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/ygavalda/projects/chatbot-security-awareness/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
````
It only happens on Teams
It does not happen from the WebChat test.

So I guess it is related with the Teams channel.

### Expected behavior
No error

### Steps to reproduce
1. Include `session.endConversation()` method in your bot.
2. Connect to bot using Teams channel.
3. When the bot uses  `session.endConversation()` method, it will emit the error.

### Actual results
The body request sent on `session.send('message1')` method is:
````
{
  "type": "message",
  "text": "message1",
  "locale": "en-GB",
  "localTimestamp": "2020-03-04T13:15:04.721Z",
  "from": { "id": "28:4e60ca0b-7396-4f38-b669-6c804eb707d2", "name": "AXA-GO-Security-PROD" },
  "recipient": {
    "id": "29:1I_e6Ry6h-zpOXhU0OBBCIKGAyOBrSj7cssbwoF7MHfyG2OPS-bM8UfhQ65hccUpU-OOEjCkAMa2Ft54dUp1FAQ",
    "name": "GAVALDA Yasmina",
    "aadObjectId": "f67fda16-4520-4766-af42-502a9cd18b21"
  },
  "inputHint": "ignoringInput"
}

````

The body request sent on `session.endConversation()` method is:
````
{
  "type": "endOfConversation",
  "code": "completedSuccessfully",
  "locale": "en-GB",
  "localTimestamp": "2020-03-04T11:06:32.857Z",
  "from": { "id": "28:4e60ca0b-7396-4f38-b669-6c804eb707d2", "name": "AXA-GO-Security-PROD" },
  "recipient": {
    "id": "29:1I_e6Ry6h-zpOXhU0OBBCIKGAyOBrSj7cssbwoF7MHfyG2OPS-bM8UfhQ65hccUpU-OOEjCkAMa2Ft54dUp1FAQ",
    "name": "GAVALDA Yasmina",
    "aadObjectId": "f67fda16-4520-4766-af42-502a9cd18b21"
  }
}
````

The error received in the response to the request above is:
````
{ "error": { "code": "BadArgument", "message": "Unknown activity type" } }
````

It seems that the type `endOfConversation` is not recognized

**Comment by jwiley84** [comment]
Hi! What package version are you using?

**Comment by yasminagavalda** [comment]
Hi @jwiley84! I am using v3 Node SDK.

**Comment by EricDahlvang** [comment]
I think the Teams channel does not support the concept of ending a conversation, so this activity type is not recognized.

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#uncategorized

**Comment by siduppal** [comment]
@Wajeed-msft can you pls take a look?

**Comment by Wajeed-msft** [comment]
Chat in Microsoft Teams is persistent. There is no end of conversation. Once user creates a conversation with bot it can't be ended. You get same conversation id whenever user chats with the bot.

Please add a check for channel before you call `endConversation()`.

**Comment by yasminagavalda** [comment]
@Wajeed-msft What is the way to clear the dialogs stack in a chatbot in Teams?

**Comment by Wajeed-msft** [comment]
If you want to pop all dialogs off the stack, you can clear the dialog stack by calling the dialog context's cancel all dialogs method.

**Comment by yasminagavalda** [comment]
Hello @Wajeed-msft,
As I have seen, dialog context is included in botbuilder-dialogs which is only available for v4, correct me if I'm wrong. We are using v3. 
Is there any way to clear the dialogs stack in a chatbot in Teams developed with v3 Node SDK?

**Comment by clearab** [comment]
@EricDahlvang or @stevengum can you assist here?

**Comment by EricDahlvang** [comment]
The endConversation method in the v3 sdk can be found here: https://github.com/microsoft/BotBuilder-V3/blob/master/Node/core/lib/Session.js#L273

You should be able to clear state similar to how this method is, but without sending an endOfConversation activity to the channel.

More information about clearing state can also be found here: https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-state?view=azure-bot-service-3.0#delete-data

**Comment by MichaelHaydenAtMicrosoft** [comment]
@yasminagavalda , please let us know if clearing the state was able to resolve your issue as per the [above fix](https://github.com/microsoft/BotFramework-Services/issues/188#issuecomment-614827735)

**Comment by yasminagavalda** [comment]
@MichaelHaydenAtMicrosoft I tried it last week and by clearing the state I was able to fix the issue. Thanks!

**Comment by MichaelHaydenAtMicrosoft** [comment]
Thank you! Closing issue.

**Comment by NickEricson** [comment]
Closing, thanks!
