### ISSUE TITLE
Feature Request: Ability for bot to post a reacion

### ISSUE THREAD

**Issue by attozk** [microsoft/BotFramework-Services#189]
As a developer I would like for my to be able to post a reaction to a thread.

Currently bots can only read reactions, but not add reactions.

**Comment by jameslew** [comment]
Hello @Attozk; sorry for the delay in responding. Can you tell us which channel you're using?

**Comment by attozk** [comment]
No worries, @jameslew would be nice to have the bot be able to add reactions to messages in Teams client

**Comment by jameslew** [comment]
Great clarification; @Wajeed-msft , can you comment here?

**Comment by Wajeed-msft** [comment]
@attozk - We have raised new feature request for this. We are tracking it internally.

**Comment by attozk** [comment]
Thanks!

**Comment by arturl** [comment]
At this point there is no ETA on when this feature becomes available, closing the issue.
