### ISSUE TITLE
Channel Viber

### ISSUE THREAD

**Issue by TemoxaGreenMoney** [microsoft/BotFramework-Services#19]
Hi!

You could add to the list of supported channels such as Viber ? :)

**Comment by sgellock** [comment]
I've moved this over to the appropriate repo so the team responsible for this area can assess.  please refer to https://github.com/Microsoft/BotFramework-Services/issues/19

**Comment by jameslew** [comment]
We are tracking this in our backlog, though we do not have a scheduled date for implementation.  There are some Github community provided adapters for the SDK findable via search however that you might investigate that might suit your immediate needs.
