### ISSUE TITLE
token.botframework.com is missing viewport meta tag

### ISSUE THREAD

**Issue by iMicknl** [microsoft/BotFramework-Services#191]
Currently token.botframework.com doesn't scale well on mobile, because it doesn't have a meta tag to define the viewport and scale. This makes it very small and hard to read, without manually zooming.

```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

![IMG_7029](https://user-images.githubusercontent.com/1424596/76461351-053e1400-63e0-11ea-9c6c-e7a812b74605.PNG)

**Comment by Jeffders** [comment]
Thank you for reporting this!

I checked in a fix for this, but it won't be deployed for another few weeks, so look for this to roll out in April. It's a lot easier to use with the Viewport tag on there :-)

**Comment by iMicknl** [comment]
Thanks @Jeffders!

**Comment by Jeffders** [comment]
This has now been deployed.
