### ISSUE TITLE
Getting 502 (Bad Gateway) in Teams for replying a "Typing" activity

### ISSUE THREAD

**Issue by sebihanu** [microsoft/BotFramework-Services#194]
Hi!

I receive 'BadGateway' response for the following snipped code. This started to happen from 03/16/2020 only in Teams. In Facebook and in WebChat it works fine.

```
            var typingMsg = ((Activity)turnContext.Activity).CreateReply();
            typingMsg.Type = ActivityTypes.Typing;

            var options = new PromptOptions
            {
                Prompt = typingMsg,
                RetryPrompt = typingMsg
            };

            await turnContext.SendActivityAsync(typingMsg, cancellationToken);
```

Exception:
> Operation returned an invalid status code 'BadGateway' -  at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
>    at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
>    at Microsoft.Bot.Builder.TurnContext.

Request logs from Teams

> Sending HTTP request "POST" https://smba.trafficmanager.net/emea/v3/conversations/a%3A1Km6T1wWFOitOxyFwSpELvEfEtKFhpVznS5LY2tJSBepLcEeC6w54rHwbyBhOWyt1BmmyeCmirAO5HZU97dAsW2GVksSSiulZTIg0ns7E66XNlp3AbtXvkIACW8GbZqr-/activities/f%3A3403087762237306074	Information	2020-03-17 14:31:15.473
> Received HTTP response after 4426.8968ms - BadGateway	Information	2020-03-17 14:31:19.900

The same requests from Facebook channel

> Sending HTTP request "POST" https://facebook.botframework.com/v3/conversations/3058030140916158-114245083457964/activities/m_5xv1SDtE7l69iltPyabHntk5lIzoPRshww-F5a-MAxKnDmu-ulk7oojiLShrq9RJkFlLhlvZv7DhjfeDBtMq9w	Information	2020-03-17 14:43:09.120
> Received HTTP response after 225.4309ms - OK	Information	2020-03-17 14:43:09.343

I'm using .Net packages of Microsoft Bot Builder, version 4.7.0.

**Comment by jameslew** [comment]
Adding @Wajeed-msft from MSTeams to help you with this issue.  Thanks for reporting!

**Comment by Wajeed-msft** [comment]
@sebihanu- Are you trying this in tenant from Europe region?

**Comment by sebihanu** [comment]
Yes, West Europe

**Comment by Wajeed-msft** [comment]
I have raised the ticket for this. This seems related to recent outage happened in Europe region.

**Comment by sree00718** [comment]
Hello..Is this issue fixed?If not any update on how long it could take?

**Comment by mkulgeorge** [comment]
This is not working as of yesterday? has this been fixed?

**Comment by s-stefanov** [comment]
Experiencing the same issue and this is really a blocker!
Can be reproduced with normal `Echo Bot` and adding this snippet:
`
        this.onMessage(async (context, next) => {
            await context.sendActivity({ type: ActivityTypes.Typing });

            // By calling next() you ensure that the next BotHandler is run.
            await next();
        });
`

**Comment by Wajeed-msft** [comment]
Please take a look at [API outage: Bots posting typing indicators may receive 502s](https://developer.microsoft.com/en-us/microsoft-teams/blogs/outage-bots-posting-typing-indicators-will-receive-502s/).

**Comment by s-stefanov** [comment]
I understand. Thank you for the quick reply. 💯
