### ISSUE TITLE
The page cannot be displayed because an internal server error has occurred.

### ISSUE THREAD

**Issue by joynext** [microsoft/BotFramework-Services#195]
Keep getting this error from the Channels Blade of my Bot Cognitive servce

<img width="688" alt="Screen Shot 2020-03-22 at 11 11 16 AM" src="https://user-images.githubusercontent.com/60085952/77241524-2f88a080-6c2e-11ea-982a-cd788e49d6e9.png">

I am unable to integrate my q and a bot to the slack or Ms teams

Note: Issue happens after I click Ms Teams , Slack , Facebook etc..

**Comment by EricDahlvang** [comment]
Hi @joynext 

Thank you for reporting this.  However, I'm unable to reproduce the problem with my bots.  It might be related to a local browser cache.  Have you tried signing out, and back in?  or using incognito browser mode?

**Comment by joynext** [comment]
Thanks Eric, it looks like this is now fixed. closing the issue now.

**Comment by mountju** [comment]
hello, @joynext !
I have the same issue now. 
what did you do to fix it?
