### ISSUE TITLE
I'm getting repeated responses from my azure chat bot in Slack.

### ISSUE THREAD

**Issue by joynext** [microsoft/BotFramework-Services#196]
I'm getting repeated responses from slack channel. 
<img width="355" alt="Screen Shot 2020-03-24 at 10 02 16 AM" src="https://user-images.githubusercontent.com/60085952/77381005-b917aa00-6db7-11ea-97a2-ad340319d888.png">

It works perfectly fine from azure web chat as well as from MS Teams. (as well as from the local bot emulator)

<img width="440" alt="Screen Shot 2020-03-24 at 10 08 31 AM" src="https://user-images.githubusercontent.com/60085952/77381040-d0ef2e00-6db7-11ea-9c57-19cc54aba0fa.png">

**Comment by jwiley84** [comment]
Hi @joynext!

I'm unable to repro this. Can  you explain more about your bot?  Is it a standard echo bot? Did you create it locally and then deploy it, or did you create it straight on Azure? What language SDK is it in?

**Comment by jwiley84** [comment]
@joynext Are you still experiencing this issue?

**Comment by joynext** [comment]
Thank you, it looks like the error is now gone.
