### ISSUE TITLE
Access token has expired

### ISSUE THREAD

**Issue by Utilisator** [microsoft/BotFramework-Services#198]
In my teams bot (C#) implemented Authentication with Azure AD. On my Channel Registrator I added Generic OAuth2 connection. Bot flow is:
1. Sign in on Azure tenant
2. Periodically get Microsoft Graph Security Alerts from logged in tenants via Microsoft.Graph library

After an hour throw an exception - "Microsoft.Graph : Access token has expired".
Question is  - in which way can I solve this problem? Are there any mechanism implemented in Bot Framework SDK or I must implement it myself. 
P.S. - Configure access token MAXAGE parameter on Azure isn't best practice.

**Comment by Jeffders** [comment]
This is a known behavior with the token service: that it can return an expired token. If you get that exception, you can call the SignOut method on the BotFrameAdapter and then sign the user in again by sending them a new OAuthPrompt.

There is a workitem on the service team to improve the expired token handling within the service, but that won't be addressed for several more weeks at this point.  

And yes, I agree, do not change the expiration of your application as this is not a best practice.
