### ISSUE TITLE
Error when showing CSV attachment when deployed in MS Teams channel , working properly in local machine.

### ISSUE THREAD

**Issue by balyasbabu** [microsoft/BotFramework-Services#199]
The CSV is generated during the execution of the code for each session.
Using bot framework sdk-V3

Code used below

          fs.readFile('./'+session.message.user.id+'.csv', function(err, data){
             var contentType = 'text/csv';
             var base64 = Buffer.from(data).toString('base64');
             var csvpath=process.cwd();
             csvpath=csvpath+'\\'+session.message.user.id+'.csv';    
             var msg = new builder.Message(session)
              .addAttachment({
                 contentUrl: csvpath,
                contentType: contentType,
                 name: 'Results.csv',
              });
             session.send(msg);

**Comment by stevkan** [comment]
To attach a file to be sent from a bot in Teams, you need to employ the methods described under [Send and receive files through your bot](https://docs.microsoft.com/en-us/microsoftteams/platform/resources/bot-v3/bots-files) found in the Teams docs. This doc provides example code in C#, but you should be able to interpolate it into Javascript to meet your needs.

Additional information can be referenced [here](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_createuploadsession?view=odsp-graph-online#upload-bytes-to-the-upload-session) regarding creating an upload session for sending files or parts of files.
