### ISSUE TITLE
Attachments on Skype For Business

### ISSUE THREAD

**Issue by ricardopieper** [Microsoft/BotFramework-Services#20]
Hi,

I know SFB is still in beta, but are attachments on SFB supported?

I tried sending an attachment to my bot but seems like the webhook didn't even fire. Also, the file transfer on SFB failed for some reason.

I'm looking for mistakes on my end but we log every incoming message, and seems like nothing happens at all when I send an attachment on SFB. On normal skype, it works fine.

Thanks

**Comment by ricardopieper** [comment]
BD on @azuresupport Twitter sent me this link: https://t.co/CVf56kldPe

So it seems it's not supported yet.

If this information is right, this can be closed.

**Comment by jwiley84** [comment]
Hi Ricardo! 

While the SfB channel is built on the skeleton of the Skype one, it still lacks some of the fully developed features that other channels, include Skype-not-for-Business have. While the Skype team is working on it, it is unfortunately still in developer preview, and this appears to be one of it's 'not supported YET' features. I'm going to close this issue, but please reach out if you have further questions about the framework or specific channels.
