### ISSUE TITLE
Facebook location (GeoCoordinates) webhook api v6.0 support

### ISSUE THREAD

**Issue by jvanderbiest** [microsoft/BotFramework-Services#201]
Starting with version 6.0 of the Facebook webhook API any location picker messages are not picked up by the Azure Bot Service (message sent with my Android phone on Facebook Messenger). This is still working with <= v5.0 and the messages are still received (I verify by using ngrok web interface if the message is forwarded from the bot service).

The problem is that when creating a new Facebook application, you are not allowed to downgrade your API even if v5.0 is still [supported until Feb 2022](https://developers.facebook.com/docs/graph-api/changelog/#graph-api-changelog).

More info about the request [here](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messages)

> New Feature
> On March 4th, 2020 we introduced Messenger webhook versioning. For v6.0 and above we adjusted the way attachments type fallback and image with a sticker are sent.

A sample request received from the Azure bot service that works with v5.0 Facebook API, with v6.0 we don't get anything back.
```json
{
    "type": "message",
    "id": "XXX",
    "timestamp": "2020-04-01T06:41:43.275Z",
    "serviceUrl": "https://facebook.botframework.com/",
    "channelId": "facebook",
    "from": {
        "id": "XXX",
        "name": "XXX"
    },
    "conversation": {
        "isGroup": false,
        "id": "XXX"
    },
    "recipient": {
        "id": "XXX",
        "name": "XXX"
    },
    "attachments": [],
    "entities": [
        {
            "geo": {
                "elevation": 0,
                "latitude": "XXX",
                "longitude": "XXX",
                "type": "GeoCoordinates"
            },
            "type": "Place"
        }
    ],
    "channelData": {
        "sender": {
            "id": "XXX"
        },
        "recipient": {
            "id": "XXX"
        },
        "timestamp": "XXX",
        "message": {
            "mid": "XXX",
            "seq": 0,
            "is_echo": false,
            "attachments": [
                {
                    "type": "location",
                    "payload": {
                        "coordinates": {
                            "lat": "XXX",
                            "long": "XXX"
                        }
                    },
                    "title": "emp's Location",
                    "url": "XXX"
                }
            ]
        }
    }
}
```

**Comment by arturl** [comment]
Thanks for the report @jvanderbiest, we'll start working on it soon. I'll respond back when we have an ETA for deployment.

**Comment by arturl** [comment]
We have a fix available. ETA for deployment sometime early May (will resolve when deployed).
In the new format, the `Latitude` and `Longitude` will not be present. Instead, the entity will have a deep link to Bing map API in the `hasMap` field.

Usage example:

```C#
if(turnContext.Activity.Entities.Any())
{
    var entity = turnContext.Activity.Entities[0];
    if (entity.Type == "Place")
    {
        dynamic place = entity.Properties;
        if (place.hasMap != null)
        {
            await turnContext.SendActivityAsync($"location '{place.hasMap}' received");
            return;
        }
    }
}
```

**Comment by jvanderbiest** [comment]
@arturl thanks for the update and the quick implementation.

Can you confirm we are still able to read the `Latitude` and `Longitude` values from the different structure?

**Comment by arturl** [comment]
@jvanderbiest, sometimes lat/lon will be in the deep link, and sometimes you will get an address or a place name. Look for a Bing maps APIs for getting info about a place.

**Comment by jvanderbiest** [comment]
@arturl thanks but we were always using the coordinates directly for further bot processing and changing the implementation like this we are unable to provide that functionality. Is this because of the Facebook API v6.0 where you are unable to just forward these coordinates?

**Comment by arturl** [comment]
Facebook doesn't send the coordinates. It sends a URL that the channel forwards as is.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MichaelHaydenAtMicrosoft** [comment]
We believe this issue has been resolved, thank you, closing.

**Comment by arturl** [comment]
Closing - thanks for verifying.
