### ISSUE TITLE
[Tracking] Add support for deleteActivity and updateActivity

### ISSUE THREAD

**Issue by benbrown** [microsoft/BotFramework-Services#205]
Adding support for these methods in WebChat will bring support for these methods to the emulator, which is important to allow developers to truly test their applications which may rely on these methods!

According to @compulim this would involve a few lines here:

https://github.com/Microsoft/BotFramework-WebChat/blob/master/packages/core/src/reducers/activities.js#L83

**Comment by jayadrathamondal** [comment]
Any news on this feature? We need this feature badly.

**Comment by BeeMaia** [comment]
We also need to update activities in transcript. Any news on it?
Thanks

**Comment by Sujit-Gaikwad** [comment]
Any update on this feature???

**Comment by MichaelHaydenAtMicrosoft** [comment]
Hello, thank you for the feedback.  I conferred with our team on this and unfortunately we do not have a short term ETA for this feature, it is a large work item and needs to be evaluated against other priorities.  We’ve captured this in our planning backlog however and will evaluate it during upcoming planning milestones. Our apologies for any inconvenience here.

**Comment by Sujit-Gaikwad** [comment]
Hi @dmvtech,
can you please keep this issue for tracking. atleast will get to know by which quater this feature is expected to replese.
regards,
sujit gaikwad

**Comment by arturl** [comment]
@compulim, looking at WebChat repo I don't see the support there. Can you confirm? 
We do support it in some channels that allow it, for example Telegram.

**Comment by arturl** [comment]
Not supported.

**Comment by jrpavoncello** [comment]
We also require this to support hiding hero cards or adaptive cards after they've been interacted with.

**Comment by JordyGit** [comment]
Please add support for updating activities in the bot emulator.

**Comment by lordscarlet** [comment]
For me, I need this functionality for removing an activity if it contains PII.

**Comment by jrpavoncello** [comment]
Definitely won't work for everybody, but we ended up sending our own custom event activity to tell our custom WebChat implementation to hide "deleted" activities.

**Comment by AidanStrong** [comment]
I would like this functionality to delete sensitive data after a short period of time.

**Comment by Godrules500** [comment]
Any update on this?

**Comment by Fulll3** [comment]
Any update? Would be very useful for LLM implementation. Updating it's streamed message response via webchat.

**Comment by ShalithaCell** [comment]
Any update on this?

**Comment by Bmastaz** [comment]
A user interacts with an adaptive card and presses submit in webchat. This would be very useful enhancement. And it seems abandoned.

**Comment by gurvancampion** [comment]
Any update? Or did someone found an alternative to support it when using Botframework WebChat? so we can have the same behaviour like on Teams where it's supported
