### ISSUE TITLE
Traffic from MS Teams conversational bot not reaching bot through Azure Application Gateway

### ISSUE THREAD

**Issue by ramgesg** [microsoft/BotFramework-Services#206]
## Versions
SDK : 4.7
NodeJS: 10.20
OS: Alpine 3.11.6

## Describe the bug
Traffic from MS Teams conversational bot not reaching bot through Azure Application Gateway

## To Reproduce
1. Deploy Bot Application in AKS Cluster
2. Expose the service via Application Gateway
3. Enable Teams Channel
4. See Application Gateway for access logs. No traffic should be found

## Expected behavior
Traffic from MS Teams should reach application gateway

## Additional context
[StackOverflow](https://stackoverflow.com/questions/61412834/traffic-from-ms-teams-conversational-bot-not-reaching-bot-through-azure-applicat)

Traffic from webchat is logged in AzureDiagnostics table, but traffic from Teams is not reaching the application gateway, meaning no logs of traffic.
Same bot service, when the endpoint is changed to a self hosted bot receives the traffic from MS Teams via Microsoft.BotService

Note: Application gateway is configured with external public DNS, well known CA certificate, multi site listener and WAF disabled

[bug]

**Comment by dmvtech** [comment]
@Gousia-MSFT @Wajeed-msft Are you guys able to give any insight or assistance here?

@clearab as well.

**Comment by Wajeed-msft** [comment]
@ramgesg - Could you please share the Bot Id and timestamp of the issue?

**Comment by ramgesg** [comment]
@Wajeed-msft , please find below the details;
BotID: 5a879d25-5db7-4481-844f-ba3d053e8b85
TimeStamp: 4/27/2020, 3:42:13.546 PM (UTC)

Note: The timestamp is as per application insights, hence there might have been minor latency

Additional information :

Activity ID: 1588002132547
Activity type:  message
Bot ID: MBFBOT
Channel ID: msteams
Conversation ID: a:1vstDiztKcL0xGIiDfmxdvXOq8YBiaEK9sQOn9BSUR26SFEiSBmtEgBErUmtYaEQ1JnsKD5mL2NvaXWiO3jMp_BjCZYsaQrd2KTDTepiqqKP-Eirna2BrcRZDxLwm7mBb

**Comment by Wajeed-msft** [comment]
@ramgesg - We are looking into logs for this.

**Comment by Wajeed-msft** [comment]
Could not create SSL/TLS secure channel is a very generic error. Though from the connections settings on the bot endpoint it might be caused by cipher suites. SMBA supports following cipher suites:
	
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA

If the bot doesn't have any of those enabled, then it can be a reason for the connectivity issue.

Here is similar post: https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/36#issuecomment-473683294

**Comment by ramgesg** [comment]
@Wajeed-msft, Thank you for the information. In our Azure Application gateway's SSL policy following cipher suites were missing; adding it resolved the issue. Can this be added in the documentation [Bot works in Web Chat but not in other channels](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-bot-configuration?view=azure-bot-service-4.0#bot-works-in-web-chat-but-not-in-other-channels)

Missing cipher suites:
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
