### ISSUE TITLE
Downloading media attachements on message from Teams

### ISSUE THREAD

**Issue by eduardocampano** [microsoft/BotFramework-Services#207]
I'm trying to download an audio attachment from a message payload coming from Teams but I get a 401. I tried using an access token from `token.botframework.com` but no luck yet.  

```
....
"attachments": [
   {
     "id": "xxx",
     "contentType": "application/vnd.microsoft.card.audio",
     "contentUrl": null,
     "name": null,
     "thumbnailUrl": null,
     "content": "{\"duration\":\"PT13S\",\"media\":[{\"url\":\"https://eu-api.asm.skype.com/v1/objects/0-neu-d6-xxxx/views/audio\"}]}"
  }
]
```

I did some research but I couldn't find any proper documentation. Can please you point me in the right direction?

Thanks in advance.

**Comment by dmvtech** [comment]
Are you doing something like the following?:
```
var token = await new MicrosoftAppCredentials("appId", "password").GetTokenAsync();
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
```

With Teams, another option is to use `Attachment.Content["downloadUrl"]`. But, that can cause issues at times, specifically if files were sent via clipboard. That's why the above is better. 

Please see more info here:
https://stackoverflow.com/questions/61230395/cannot-access-images-from-microsoft-teams-activity-when-added-by-clipboard

**Comment by eduardocampano** [comment]
Correct, I tried the approach you mention and using the ctor overload with the tenantId, which produces a different access token. But I still get 401. Do I need to negotiate another access token for this skype API?

In the messagePayload I get on the message extension I don't get any `downloadUrl`, the JSON I shared is the only information I have about the attachment.

**Comment by eduardocampano** [comment]
When using:
```
var token = await new MicrosoftAppCredentials("appId", "password").GetTokenAsync();
```
or the constructor with the `tenantId` returns a JWT access token is meant to be used with `https://api.botframework.com`.

I tried, for example, grabbing the object ID from the skype API URL and then use it with Bot Framework REST API :
```
https://smba.trafficmanager.net/apis/v3/attachments/{objectId}
```

But I still get 401 response. 

I couldn't find any good documentation to obtain a `skype_token` to be able to access the attachment from the Skype API

**Comment by dmvtech** [comment]
I'm still looking into this. Unfortunately I'm having (different) problems of my own investigating. Thanks for your patience. Stand by.

**Comment by dmvtech** [comment]
@anusharavindrar is investigating

**Comment by anusharavindrar** [comment]
This is an issue with downloading media from teams, and the problem is being tracked [here](https://github.com/MicrosoftDocs/msteams-docs/issues/1805).
