### ISSUE TITLE
Problem with Skype Web Control

### ISSUE THREAD

**Issue by odysseus1973** [microsoft/BotFramework-Services#21]
Hi!

Skype Web Control Skype web control does not show icons
![google chrome 2018-11-13 18 02 43](https://user-images.githubusercontent.com/7000262/48422440-b9d61000-e76f-11e8-9eb3-022e0bdb5bec.png)

What could be the problem?

```
<span class="skype-button bubble " data-bot-id="myid"></span>
<script src="https://swc.cdn.skype.com/sdk/v1/sdk.min.js"></script>
```

Thanks!

**Comment by dmvtech** [comment]
Can you grab a Fiddler trace and/or a F12 Network/HAR trace and see if you see anything there?

I'm wondering if there is any HTTP error codes for those images that might shed some light. Or just to confirm that it is 200, and therefore possibly a rendering issue.

**Comment by odysseus1973** [comment]
Hi! 
Apparently it was a temporary problem. I looked through F12, there were no errors. Now everything works. 

Thanks!
