### ISSUE TITLE
Botframework - OAuth mixed scope settings (MSGraph and Azure Devops)

### ISSUE THREAD

**Issue by msalemor** [microsoft/BotFramework-Services#210]
## Version
4.8

## Describe the bug

Following the directions on this document:

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp

I also tried to add Azure DevOPs as part of the permissions, but testing the connection and while running the code, the jwt toke that was returning did not include the ADO scope and audience. When I changed the scopes to include only the ADO scope, I did get the right audience and scope for ADO, and the token worked to retried projects in my ADO instance.

## To Reproduce

1. Follow the directions on this document:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv1%2Ccsharp
2. To the Service Principal add Azure Devops delegated impersonation permission.
3. To the Bot OAuth setting add the ADO scope.
4. Save and test the connection.
5. Navigate to jwt.ms, inspect the token and notice that the MS Graph scopes are displayed but not the DevOps ones.

Alternate test;

1. In the Bot OAuth settings, edit the connection and remove all scopes except for the ADO one.
2. Save and then test the connection.
3. Navigate to jwt.ms, inspect the token and notice that ADO scope shows.

## Expected behavior

I was expecting to get both the MSGraph scopes and the ADO scopes configured in the Service Principal permission.

## Additional context

Customer is developing a Bot that will leverage ADO API over the Teams channel.

[bug]

**Comment by swagatmishra2007** [comment]
you need 2 separate oauth connections - one for the devops scopes and one for graph scopes.
The reason is that both sets of scopes generate separate tokens, and hence aad only looks at the set of scopes it encounters first -  So you get a graph token if user_impersonation is at the end and a devops token if you have it at the beginning
