### ISSUE TITLE
[Waiting for Adaptive Card fix] Part of the content of Adaptive Card is lost while sending through Direct Line channel

### ISSUE THREAD

**Issue by compulim** [microsoft/BotFramework-Services#214]
(Original reported at https://github.com/microsoft/BotFramework-WebChat/issues/3166)

> Corresponding labels added because this is a customer reported issue. I am just copying it here.

## Background

The customer is sending an Adaptive Card with an image stored using data URI. The original card is in the [attachments](#attachments) section below.

The size of the image is [well under limit](https://docs.microsoft.com/da-dk/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-service-4.0#activities). The card is 98 kB, while the limit is "256 K characters" (which can be upward of 400 kB due to encoding).

## Observation

When sent, the channel behaviors:

- Did not reject the content
- Stripped the image out of the Adaptive Cards
- Continue to send the card to client
   - The card is *intact*, except the image is lost

Per customer's observation, when sending the card through Emulator, no parts of the content is lost.

### The original card

![image](https://user-images.githubusercontent.com/1622400/82590937-6b1ee880-9b53-11ea-8549-5a3d31c1e90b.png)

### Traffic received on the Web Socket connection

![image](https://user-images.githubusercontent.com/1622400/82590969-75d97d80-9b53-11ea-97a8-a9e0104a2d84.png)

## Expectation

The Direct Line channel must not remove any parts of the content. If the channel consider the card is too large, it should reject it.

Stripping part of the content is both *user data loss* and *silent error*.

## Attachments

- [card.lg.zip](https://github.com/microsoft/BotFramework-Services/files/4663983/card.lg.zip)

**Comment by p-nagpal** [comment]
There is a silent error when reading the card in the C# Adaptive Card library. This card format seems to be allowed in the visualizer https://adaptivecards.io/visualizer/index.html?hostApp=Bot%20Framework%20WebChat but in C#, there is a failure reading this file as an Adaptive card, specifically converting the png string to a Uri. This failure is swallowed and the result is an invalid Adaptive Card without the image (data loss as perceived by the customer).

The failure occurs at AdaptiveTypedElementConverter --> 
ReadJson --> serializer.Populate(jObject.CreateReader(), result);
(AdaptiveCards\source\dotnet\Library\AdaptiveCards\AdaptiveTypedElementConverter.cs:line 100)

                var result = (AdaptiveTypedElement)Activator.CreateInstance(type);
                try
                {
                    serializer.Populate(jObject.CreateReader(), result);
                    result.InternalID = internalID;
                }
                **catch (JsonSerializationException) { }**

We have opened an issue with the Adaptive cards team to request for a fix / further guidance: https://github.com/microsoft/AdaptiveCards/issues/4738

**Comment by NickEricson** [comment]
We will, in the near future, begin processing Adaptive Cards less in the DirectLine channel. This should allow arbitrary properties to flow through DirectLine. The client will need to interpret these properties which, depending on the client, may mean an AdaptiveCard library update.

I will update this thread when that change is in production.

**Comment by NickEricson** [comment]
@compulim We have found that some cards (OAuth cards) require some transform as they go through the DirectLine channel otherwise they end up being interpreted as a string during serialization which breaks WebChat. We need to consider more scenarios here before we make any changes because of unintended side effects. Perhaps we should chat offline and report back.

**Comment by NickEricson** [comment]
@compulim We have a workaround for this issue so I am resolving this for now. We can revisit the benefits of schema validation or passthrough in the future as we gain additional information.
