### ISSUE TITLE
DeleteActivityAsync doesn't work on Teams app on iOS.

### ISSUE THREAD

**Issue by baki32** [microsoft/BotFramework-Services#218]
Hi,
we are facing issue with our bot that is working on teams. We are leveraging option to delete messages to simulate Suggested actions functionality. When we need to collect specific input from user we display buttons and on the next turn that activity is removed. It works fine on teams app in Windows. However deletion doesn't happen in iOS. Since channel is shared I was able to do screenshots of the conversation in both platforms. 

![1](https://user-images.githubusercontent.com/22841494/83257668-216a7980-a1b5-11ea-98fe-fea29a3d9c7b.PNG)

![iOs1](https://user-images.githubusercontent.com/22841494/83257671-22031000-a1b5-11ea-8a76-6ee2e68c30c1.png)

![2](https://user-images.githubusercontent.com/22841494/83257669-216a7980-a1b5-11ea-85c6-fa90436a5a84.PNG)

![iOs2](https://user-images.githubusercontent.com/22841494/83257667-20394c80-a1b5-11ea-991a-da8563e4bd09.png)

Notice that on iOS the bar with buttons wasn't removed from the conversation despite on windows it working as expected.

**Comment by Trinetra-MSFT** [comment]
@baki32 , We have forwarded your query to right channel. we will update you shortly

**Comment by baki32** [comment]
Hi, sorry I have missed your question - I am running iOS 13.5.1 and also latest Teams client 2.0.14

**Comment by baki32** [comment]
Hello, is there any update?

**Comment by Trinetra-MSFT** [comment]
We have an Bug for this.  we will update once it is resolved

**Comment by Wajeed-msft** [comment]
Internal Tracker: [Bug 954637: DeleteActivityAsync doesn't work on Teams app on iOS](https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/954637)

**Comment by arturl** [comment]
Work still in progress according the internal ticket.

**Comment by Trinetra-MSFT** [comment]
@baki32 , Please find the [recording for iOS mobile](https://drive.google.com/drive/folders/1Sc6vqakr1AFjsoeCw20U0vsKIzGEVwDn?usp=sharing). Team has fixed the issue. They found message doesn't get deleted if you stay on that chat once you move from chat and come back the activity got deleted. PR for the fix will be raised soon.

**Comment by arturl** [comment]
Issue is fixed.
