### ISSUE TITLE
Unable to add email channel in azure bot service

### ISSUE THREAD

**Issue by kittu610** [microsoft/BotFramework-Services#221]
Hi 
![error](https://user-images.githubusercontent.com/49742373/83856948-eed1fb00-a737-11ea-9473-ae5fe9390e4c.PNG)

I was trying to enable the email channel in azure bot service but its trowing an error.

please find the following image for reference

**Comment by dmvtech** [comment]
Hi @kittu610 This is a O365 email account that you are using, correct?

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-email?view=azure-bot-service-4.0

**Comment by kittu610** [comment]
Hi 

Sorry for the delay 
Yes i was using o365 mail id

**Comment by Nikitha-MSFT** [comment]
@kittu610  - Could you please go through the [docs ](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-email?view=azure-bot-service-4.0)as suggested by dmvtech

**Comment by dmvtech** [comment]
The email channel uses the Exchange Web Service API's (EWS). So the account you use must have EWS access enabled.  Some accounts don't which may be the problem you are experiencing.   We've also seen several instances recently where EWS access has been revoked which causes bots to suddenly stop working.  I'd recommend that you use an account that you have full control over to avoid these situations.

You can use the attached tool to run (from a shell) to see if it succeeds or fails.

[EwsTestExe.zip](https://github.com/microsoft/BotFramework-Services/files/4789533/EwsTestExe.zip)
