### ISSUE TITLE
[Slack] Generating Bot Embed Code for OAuth v2

### ISSUE THREAD

**Issue by Vignesh25viswanat** [microsoft/BotFramework-Services#223]
Slack recently deprecated the bot scope in favor of more granular scopes. I have already migrated my app from the bot scope to granular scopes on the Slack' developer portal. I'm trying to get an embed code for my "Add to Slack" button. I'm trying to get the embed code from channel settings on Bot services as defined here [https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs](url)

The embed code in my channel settings still point to Slack' legacy bot scope. The embed code is 
**https://slack.com/oauth/authorize?scope=bot/oauth/.....**

I'm expecting an embed code that points to the new granular scopes on oauth2, the URL i expect would be **https://slack.com/oauthv2/authorize?scope=app_mentions:read....**

Is there a workaround to this issue?

**Comment by youyu16** [comment]
@Vignesh25viswanat Can you delete the slack channel and add it again?
then the link will be the V2 auth and you can modify the scope on your own.
![image](https://user-images.githubusercontent.com/17819112/84849395-be6b5480-b087-11ea-95aa-4312e17304c7.png)

**Comment by dmvtech** [comment]
@Vignesh25viswanat Have you been able to test the workaround suggested by @youyu16 ?

**Comment by Vignesh25viswanat** [comment]
@dmvtech We will test this next week and test the workaround. Thank you for following-up

**Comment by dmvtech** [comment]
Just touching base. Any update?

**Comment by Vignesh25viswanat** [comment]
@dmvtech We were able to general an embed URL based on oauthV2 after we deleted and created the channel again. However, the scope contains more permissions than we requested on api.slack.com. Based on @youyu16 we would need to modify the scope on our own to tailor it to the permissions we requested on slack api?

**Comment by arturl** [comment]
@Vignesh25viswanat, right -- look at the scope parameter in the generated link (`https://slack.com/oauth/v2/authorize?scope=your_scopes_here`) and replace it using any of the scopes from [https://api.slack.com/scopes](https://api.slack.com/scopes).

**Comment by Vignesh25viswanat** [comment]
I can confirm that this works. Thank you!!

**Comment by arturl** [comment]
Thank you for confirming!

**Comment by dmvtech** [comment]
Closing this as resolved.
