### ISSUE TITLE
Facebook channel information is not deleted when I delete a bot

### ISSUE THREAD

**Issue by turbozapekanka** [microsoft/BotFramework-Services#224]
I experienced this a few weeks ago, just forgot to report.
Not sure if this is a "feature" but I see this as a potential security breach.

Repro steps:
1. Deploy a bot.
2. Connect to the facebook (appID, App Secret, pageID, page token)
3. delete the bot.
4. redeploy the bot with the same name
5. Create a facebook channel.
6. appID, App Secret, pageID, page token are restored automatically. <-- NOT AS EXPECTED

Note that this only happened to the facebook channel, I also had Twillio configured but I had to reenter the information for twillio channel. Did not test other channels.

**Comment by anusharavindrar** [comment]
@turbopazenka, thanks for reporting this. Did you create a new bot within the same subscription and tenant with the same name or in a different subscription and tenant? I will attempt a repro on my end and update the thread with my findings.

**Comment by turbozapekanka** [comment]
same everything

**Comment by anusharavindrar** [comment]
@turbozapekanka, I am able to reproduce the issue. 
Adding @craigjensen to further investigate what might be causing this behavior.

**Comment by anusharavindrar** [comment]
@turbozapekanka, a fix for this has already been checked in this week's build. You should be able to test it out by early next week.
