### ISSUE TITLE
ConversationUpdate never fires on SMS

### ISSUE THREAD

**Issue by brandonh-msft** [microsoft/BotFramework-Services#225]
Not unlike [this issue](https://github.com/Microsoft/BotFramework-WebChat/issues/1371), I created a bot with Twilio and never got the greeting from my bot (which should happen at Conversation Update).

While I understand why this isn't possible in the traditional sense, I thinks it's reasonable to expect the bot fire `conversationUpdate` _on the first message it sees from a user_ (like Webchat today).

**Comment by cleemullins** [comment]
We in the SDK believe this could be closed, but wanted to confirm.

**Comment by MichaelHaydenAtMicrosoft** [comment]
Closing issue
