### ISSUE TITLE
[Teams] Message size limits and adaptive cards (413 RequestEntityTooLarge / MessageSizeTooBig)

### ISSUE THREAD

**Issue by mrakn** [microsoft/BotFramework-Services#228]
I have chatbot powered by .NET Bot Framework V4 and the primary communication channel that is used to communicate with the bot is Microsoft Teams.

I have a use case where based on user's input I call an APIs and based on the responses I dynamically build the adaptive card that is then sent to the user. There are however few instances, where trying to send the AC to the user results in error 413 - RequestEntityTooLarge:
`{
	"error": {
		"code": "MessageSizeTooBig",
		"message": "Message size too large."
	}
}`

I am aware, that this happens, because the maximum allowed length of MS Teams' message is only **28 KB** based on [following doc](https://docs.microsoft.com/en-us/microsoftteams/limits-specifications-teams#teams-and-channels). This limitation is very inconvenient for scenarios where I try to send over adaptive card that is _slightly more complex_. I could understand the limit for plain text, but I think it is too small for cards, since majority of actual message content is JSON / metadata.

Is there any way how this limit can be increased or overcome in any way, something like instructing the channel to not apply the limits because the message is attachment / adaptive card? I have seen some suggestions about splitting the card into multiple parts, but this is not an option for me.

**Comment by dandriscoll** [comment]
@Wajeed-msft can you assist?

**Comment by Trinetra-MSFT** [comment]
@mrakn ,  Currently message size limit is 28 kb. Please raise a user voice for this so we can take up for feature request.

**Comment by clearab** [comment]
Unfortunately no, this is the limit currently. The team is exploring the possibility of increasing it in the future.

**Comment by jefecodered** [comment]
@clearab Is there another issue that is tracking this?

**Comment by clearab** [comment]
No, there isn't an Issue tracking this. The limitation is applied by the Teams backend services, and is universal in that infrastructure. We've made their product group aware that this is a common ask - if you'd like to add your voice to that you can reach out to them directly using one of the methods outlined here: https://aka.ms/teamsdevfeedback.

**Comment by mrakn** [comment]
Just for the reference, here are all existing User Voice suggestions related to size limits in MS Teams if anyone would like to vote and add own insights:
* [Maximum message length is too short.](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/31511941-maximum-message-length-is-too-short)
* [Your message is too long. Please shorten it before sending](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/31129300--your-message-is-too-long-please-shorten-it-befor)
* [Sending long chat message in Microsoft Teams](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/37875385-sending-long-chat-message-in-microsoft-teams)
* [Message Length Bug](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/35917897-message-length-bug)
* [Remove character limit in Teams](https://microsoftteams.uservoice.com/forums/555103-public/suggestions/36123373-remove-character-limit-in-teams)

**Comment by Nivedipa-MSFT** [comment]
@mrakn ,@Sujit-Gaikwad - The feature for increasing the size limit is currently in dev state and there is no ETA to share.We will inform you once we get any update

**Comment by jcbartle** [comment]
@mrakn - thanks for posting the UserVoice links. Since those sites have all been taken down, here is the link to the most relevant Feedback Portal item I could find:

[Microsoft Teams - Remove the limit on the length of messages](https://feedbackportal.microsoft.com/feedback/idea/731d5aa0-272e-ec11-b6e6-00224827b493)

**Comment by devtfq** [comment]
Hi @Nivedipa-MSFT  @v-chetsh , we have been seeing this issue regarding message size for a while too.. is there some way teams can lift this limitation?

**Comment by v-chetsh** [comment]
@devtfq - We are checking it with engineering team and let you know the updates.

**Comment by devtfq** [comment]
Thank you @v-chetsh

**Comment by devtfq** [comment]
Hi @v-chetsh  @Nivedipa-MSFT  , can we please change the status to 'Open' as the problem still persists?
I can see the same issue raised in multiple forums as well, but sadly no fix has been provided by MSFT so far.

**Comment by v-chetsh** [comment]
@devtfq - We are checking it internally with engineering team and inform you accordingly.
I am not seeing a option to re-open it.
@mrakn - Could you please me to reopen it.

**Comment by v-chetsh** [comment]
@devtfq -  The feature for increasing the size limit is currently in dev state and there is no ETA to share

**Comment by devtfq** [comment]
Hi @v-chetsh @Wajeed-msft  ,is the size limit lifted ? 

Could you kindly check with the development team? Just doubtful as I am able to see a significant improvement in the card size.. I am able to send data which I was not able to send about months before.Its coming out fine. Can we please check once?

**Comment by devtfq** [comment]
@v-chetsh  could you kindly check with the development team once?

**Comment by Nivedipa-MSFT** [comment]
@devtfq - We are checking with the engineering team. We will get back to you soon.

**Comment by devtfq** [comment]
@Nivedipa-MSFT  thank you so much. Eagerly waiting for the response

**Comment by jcbartle** [comment]
Morning, @devtfq / @Nivedipa-MSFT. I can confirm that, as of this morning, I am still getting the following error if the card size passes some limit. Not sure what that limit is, but, if I attach too large of an object to the Value property of an action button and add that to a Hero Card, I get the following error:

Operation returned an invalid status code 'RequestEntityTooLarge'

**Comment by devtfq** [comment]
I understand @jcbartle , but i feel some improvement came across the size limit. For my use case., along with the remaining card payload,  I was not able to send a particular choice set  whose elements totally consist  of 1700 characters, but now I am able to send the same payload.. also I'm able to send the choice set with total element size of about 5200 characters too..along with the remaining data, thus indicating an improvement

Still there has to be a limit of course, but just that for my use case I am seeing a considerable improvement.. and thus wanted to confirm it with the engineering team .

@Nivedipa-MSFT could you please tell us if there are any updates from the team so far regarding the size limit?

**Comment by devtfq** [comment]
@Nivedipa-MSFT do we have an update from the engineering team?

**Comment by Nivedipa-MSFT** [comment]
@devtfq - This feature is currently in internal review Process.

You can check the updates [here ](https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new)or subscribe to[ RSS feed](https://docs.microsoft.com/en-us/microsoftteams/platform/whats-new#get-latest-updates).

**Comment by mrakn** [comment]
@v-chetsh and @Nivedipa-MSFT, thank you so much for the updates. Unfortunately I cannot reopen this issue since it has been closed by repository collaborator - @clearab.

**Comment by jacksonngoo** [comment]
Any update on this? Seems like it has not been updated for a couple of months.

**Comment by Nivedipa-MSFT** [comment]
@jacksonngoo - We will check the status from engineering team and update you soon.

**Comment by ahmedmahmoudR** [comment]
Any update on this?

**Comment by Nivedipa-MSFT** [comment]
@ahmedmahmoudR - We are checking the status with the engineering team. We will let you know once we have any updates on it.

**Comment by ChetanSharma-msft** [comment]
Hello @ahmedmahmoudR - Sorry for delay in response.
Just wanted to inform you that we are checking the status of this ask with engineering team and let you know once we get any input from them.

**Comment by SURYASARAVANAN** [comment]
@ChetanSharma-msft  any update on this adaptive card message size increase?

**Comment by Nivedipa-MSFT** [comment]
@SURYASARAVANAN - We are checking this with engineering team, we will let you know once we get any update from them.

**Comment by SUNNUWORKS** [comment]
@Nivedipa-MSFT  @ChetanSharma-msft it's been 2 years since users reported this concern and feature request and please let us know the exact update as it is affecting a lot of customers and it's an important feature which lags here.

**Comment by Gorkes** [comment]
@Nivedipa-MSFT any updates? this update is important to us.
Once this is resolved, we will be able to improve communication within organizations.

**Comment by Nivedipa-MSFT** [comment]
@Gorkes, @SUNNUWORKS, @mrakn - We got an update from engineering team saying that message size limit has increased up to 40 KB. 
Below document has updated with message size limit 40 KB.
![image](https://user-images.githubusercontent.com/92150070/216693983-912f8adf-bf32-4b86-a3ee-25edc3a4aa6b.png)

Ref Document: [Format your bot messages](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/format-your-bot-messages)

**Comment by raguravindran** [comment]
@Nivedipa-MSFT Want to understand, is this hard limit for any particular reason?

We have a requirement and we believe it will go double the limit size (80kb). Want to understand if this hard limit is for any particular reason or if this can further be increased upon request?

**Comment by Nivedipa-MSFT** [comment]
@raguravindran - We will check this with engineering team and update you soon.

**Comment by Gorkes** [comment]
@Nivedipa-MSFT 
Today I tried again but got the same error:
"error": "The payload is too large. Make sure the size is less than 28KB."
Is it possible to check with the development team about the 80kb limit? it's too low.

**Comment by a-matthew** [comment]
I have tested the limits using byte counted payload and any messages over ~14kB are not allowed for me (not using a dedicated bot).
This is obviously a small limit and the major part of the JSON payload is a somewhat redundant "encapsulation" in the form of table or other components in the JSON.

Removing even simple styling parts such as "weight": "Bolder" sometimes yielded observable savings (e.g. 40-50 bytes on 100 records). Without a separate limitting algorithm inside the payload producer it doesn't even make sense to send dynamic content messages, because most of the time they just won't arrive.

I absolutely agree with the OP, especially on the flawed data structure.
Additionally, why does the backend send back "X-Proxy-BackendServerStatus": "200", in the headers when the content says "... delivery failed with error: ... 413"? Python for example won't pick it up using response.status_code

It makes it needlessly difficult to handle these payload limit exceptions.

**Comment by YaakovR** [comment]
Is there a way for me to test a card's size before sending to determine if it's too large?

**Comment by fxbtr** [comment]
> Is there a way for me to test a card's size before sending to determine if it's too large?

Yes. My use case: for alerting purposes, I would be OK with a way to post a card telling me there has been an issue with an alert and I should check my dashboards through other means. That would be a last resort obviously, but at least it is not silent.

**Comment by jjjllla** [comment]
Still getting this error.
28KB limit in 2025 is unbelievable. Come on MS, I think you should be able to handle more than 28Kb messages ;)
Did someone find a way to check the size with an expression so at least we can post that message is too long and need to be retrieved in another way ?

**Comment by jker-org** [comment]
@jjjllla : The actual limit is now 40 kb. We are checking the limit with this script:

    const cardPollString = JSON.stringify(cardPoll);
    const cardPollBytes = Buffer.byteLength(cardPollString, "utf-8");
    return (cardPollBytes > BotMaxCardSize);

It is not 100% accurate. If you want to max out the card limit, use something like this:
export const BotMaxCardSize = Math.floor(0.92 * 40000); // (92%-95%)

However, we found out that ~ 40 kb of text is still a lot of text. Such cards need to be scrolled a few times.

We are now working with this factor:
export const BotMaxCardSize = Math.floor(0.75 * 40000); // (75%)

If we have a card that size, we will show a standard size saying something like "Too large to be shown in the chat". It contains a button where the user can proceed with the actions in a popup dialog. Happens very rarely to be honest.

I hope that helps!
