### ISSUE TITLE
Move localization pipeline secrets to keyvault

### ISSUE THREAD

**Issue by Andrea-Orimoto** [microsoft/BotFramework-Services#229]

**Comment by Andrea-Orimoto** [comment]
Tracking work item for Bruce. Localization pipeline in VSO needs secrets stored in keyvault like other pipelines.

**Comment by BruceHaley** [comment]
Done. Key vault location: https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/a063f4ff-3220-4977-8aaf-c9682e9869a3/resourceGroups/BotFrameworkSDKPipelinesKeyVaultsRG/providers/Microsoft.KeyVault/vaults/IntercomKeyVault/secrets
