### ISSUE TITLE
MS teams - adaptive card - toggle visibility buttons are highlighted by default 

### ISSUE THREAD

**Issue by shaikShehanaaz** [microsoft/BotFramework-Services#231]
Following is the JSON, in which we are trying to display weather info:
`{
        "type": "AdaptiveCard",
        "version": "1.2",
        "body": [
          {
            "type": "ColumnSet",
            "columns": [
              {
                "type": "Column",
                "width": "stretch",
                "items": [
                  {
                    "type": "TextBlock",
                    "size": "medium",
                    "weight": "bolder",
                    "text": "London, London, United Kingdom",
                    "spacing": "none"
                  },
                  {
                    "type": "TextBlock",
                    "weight": "bolder",
                    "text": "Today"
                  }
                ],
                "height": "stretch"
              },
              {
                "type": "Column",
                "width": "auto",
                "items": [
                  {
                    "type": "ActionSet",
                    "actions": [
                      {
                        "type": "Action.ToggleVisibility",
                        "targetElements": [
                          {
                            "elementId": "MainF",
                            "isVisible": false
                          },
                          {
                            "elementId": "SubHighF",
                            "isVisible": false
                          },
                          {
                            "elementId": "SubLowF",
                            "isVisible": false
                          },
                          {
                            "elementId": "MainC",
                            "isVisible": true
                          },
                          {
                            "elementId": "SubHighC",
                            "isVisible": true
                          },
                          {
                            "elementId": "SubLowC",
                            "isVisible": true
                          },
                          {
                            "elementId": "MorHighF",
                            "isVisible": false
                          },
                          {
                            "elementId": "MorLowF",
                            "isVisible": false
                          },
                          {
                            "elementId": "AftHighF",
                            "isVisible": false
                          },
                          {
                            "elementId": "AftLowF",
                            "isVisible": false
                          },
                          {
                            "elementId": "EveHighF",
                            "isVisible": false
                          },
                          {
                            "elementId": "EveLowF",
                            "isVisible": false
                          },
                          {
                            "elementId": "NigHighF",
                            "isVisible": false
                          },
                          {
                            "elementId": "NigLowF",
                            "isVisible": false
                          },
                          {
                            "elementId": "MorHighC",
                            "isVisible": true
                          },
                          {
                            "elementId": "MorLowC",
                            "isVisible": true
                          },
                          {
                            "elementId": "AftHighC",
                            "isVisible": true
                          },
                          {
                            "elementId": "AftLowC",
                            "isVisible": true
                          },
                          {
                            "elementId": "EveHighC",
                            "isVisible": true
                          },
                          {
                            "elementId": "EveLowC",
                            "isVisible": true
                          },
                          {
                            "elementId": "NigHighC",
                            "isVisible": true
                          },
                          {
                            "elementId": "NigLowC",
                            "isVisible": true
                          }
                        ],
                        "title": "C"
                      }
                    ]
                  }
                ]
              },
              {
                "type": "Column",
                "width": "auto",
                "items": [
                  {
                    "type": "ActionSet",
                    "actions": [
                      {
                        "type": "Action.ToggleVisibility",
                        "targetElements": [
                          {
                            "elementId": "MainF",
                            "isVisible": true
                          },
                          {
                            "elementId": "SubHighF",
                            "isVisible": true
                          },
                          {
                            "elementId": "SubLowF",
                            "isVisible": true
                          },
                          {
                            "elementId": "MainC",
                            "isVisible": false
                          },
                          {
                            "elementId": "SubHighC",
                            "isVisible": false
                          },
                          {
                            "elementId": "SubLowC",
                            "isVisible": false
                          },
                          {
                            "elementId": "MorHighF",
                            "isVisible": true
                          },
                          {
                            "elementId": "MorLowF",
                            "isVisible": true
                          },
                          {
                            "elementId": "AftHighF",
                            "isVisible": true
                          },
                          {
                            "elementId": "AftLowF",
                            "isVisible": true
                          },
                          {
                            "elementId": "EveHighF",
                            "isVisible": true
                          },
                          {
                            "elementId": "EveLowF",
                            "isVisible": true
                          },
                          {
                            "elementId": "NigHighF",
                            "isVisible": true
                          },
                          {
                            "elementId": "NigLowF",
                            "isVisible": true
                          },
                          {
                            "elementId": "MorHighC",
                            "isVisible": false
                          },
                          {
                            "elementId": "MorLowC",
                            "isVisible": false
                          },
                          {
                            "elementId": "AftHighC",
                            "isVisible": false
                          },
                          {
                            "elementId": "AftLowC",
                            "isVisible": false
                          },
                          {
                            "elementId": "EveHighC",
                            "isVisible": false
                          },
                          {
                            "elementId": "EveLowC",
                            "isVisible": false
                          },
                          {
                            "elementId": "NigHighC",
                            "isVisible": false
                          },
                          {
                            "elementId": "NigLowC",
                            "isVisible": false
                          }
                        ],
                        "title": "F"
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "type": "ColumnSet",
            "columns": [
              {
                "type": "Column",
                "width": "stretch",
                "items": [
                  {
                    "type": "TextBlock",
                    "size": "medium",
                    "weight": "bolder",
                    "text": "Thursday 25 Jun",
                    "height": "stretch"
                  }
                ],
                "height": "stretch"
              }
            ],
            "separator": true
          },
          {
            "type": "ColumnSet",
            "columns": [
              {
                "id": "MainC",
                "type": "Column",
                "width": "50",
                "items": [
                  {
                    "type": "TextBlock",
                    "size": "extraLarge",
                    "weight": "bolder",
                    "text": "29℃",
                    "wrap": true,
                    "height": "stretch"
                  }
                ],
                "horizontalAlignment": "Right"
              },
              {
                "id": "MainF",
                "type": "Column",
                "width": "50",
                "items": [
                  {
                    "type": "TextBlock",
                    "size": "extraLarge",
                    "weight": "bolder",
                    "text": "85℉",
                    "wrap": true,
                    "height": "stretch"
                  }
                ],
                "isVisible": false,
                "horizontalAlignment": "Right"
              },
              {
                "type": "Column",
                "width": "50",
                "items": [
                  {
                    "type": "TextBlock",
                    "id": "SubHighC",
                    "isSubtle": true,
                    "text": "High: 29℃",
                    "wrap": true,
                    "spacing": "none"
                  },
                  {
                    "type": "TextBlock",
                    "id": "SubLowC",
                    "isSubtle": true,
                    "text": "Low: 18℃",
                    "wrap": true,
                    "spacing": "none"
                  },
                  {
                    "type": "TextBlock",
                    "id": "SubHighF",
                    "isSubtle": true,
                    "text": "High: 85℉",
                    "wrap": true,
                    "spacing": "none",
                    "isVisible": false
                  },
                  {
                    "type": "TextBlock",
                    "id": "SubLowF",
                    "isSubtle": true,
                    "text": "Low: 64℉",
                    "wrap": true,
                    "spacing": "none",
                    "isVisible": false
                  },
                  {
                    "type": "TextBlock",
                    "isSubtle": true,
                    "text": "Preciptaion: 1",
                    "wrap": true,
                    "spacing": "none"
                  }
                ]
              },
              {
                "type": "Column",
                "width": "50",
                "items": [
                  {
                    "type": "Image",
                    "size": "medium",
                    "style": "person",
                    "url": "https://developer.accuweather.com/sites/default/files/01-s.png",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "TextBlock",
                    "weight": "bolder",
                    "text": "Sunny",
                    "horizontalAlignment": "center"
                  }
                ]
              }
            ]
          },
          {
            "type": "ColumnSet",
            "columns": [
              {
                "type": "Column",
                "width": "33",
                "items": [
                  {
                    "type": "ActionSet",
                    "actions": [
                      {
                        "type": "Action.Submit",
                        "id": "todayButton",
                        "data": {
                          "msteams": {
                            "value": "Today"
                          }
                        },
                        "title": "Today"
                      }
                    ],
                    "horizontalAlignment": "Center"
                  }
                ],
                "spacing": "none"
              },
              {
                "type": "Column",
                "width": "33",
                "items": [
                  {
                    "type": "ActionSet",
                    "actions": [
                      {
                        "type": "Action.Submit",
                        "id": "hourlyButton",
                        "data": {
                          "msteams": {
                            "value": "Hourly"
                          }
                        },
                        "title": "Hourly"
                      }
                    ],
                    "horizontalAlignment": "Center"
                  }
                ],
                "spacing": "none"
              },
              {
                "type": "Column",
                "width": "33",
                "items": [
                  {
                    "type": "ActionSet",
                    "actions": [
                      {
                        "type": "Action.Submit",
                        "id": "dailyButton",
                        "data": {
                          "msteams": {
                            "value": "Daily"
                          }
                        },
                        "title": "Daily"
                      }
                    ],
                    "horizontalAlignment": "Center"
                  }
                ],
                "spacing": "none"
              }
            ],
            "spacing": "none",
            "horizontalAlignment": "Center"
          },
          {
            "type": "ColumnSet",
            "columns": [
              {
                "type": "Column",
                "width": "20",
                "items": [
                  {
                    "type": "TextBlock",
                    "weight": "bolder",
                    "text": "Morning",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "Image",
                    "url": "https://developer.accuweather.com/sites/default/files/01-s.png"
                  },
                  {
                    "type": "TextBlock",
                    "id": "MorHighC",
                    "text": "25℃",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "TextBlock",
                    "id": "MorLowC",
                    "text": "18℃",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "TextBlock",
                    "id": "MorHighF",
                    "text": "77℉",
                    "horizontalAlignment": "center",
                    "isVisible": false
                  },
                  {
                    "type": "TextBlock",
                    "id": "MorLowF",
                    "text": "65℉",
                    "horizontalAlignment": "center",
                    "isVisible": false
                  }
                ]
              },
              {
                "type": "Column",
                "width": "20",
                "items": [
                  {
                    "type": "TextBlock",
                    "weight": "bolder",
                    "text": "AfterNoon",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "Image",
                    "url": "https://developer.accuweather.com/sites/default/files/01-s.png"
                  },
                  {
                    "type": "TextBlock",
                    "id": "AftHighC",
                    "text": "29℃",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "TextBlock",
                    "id": "AftLowC",
                    "text": "27℃",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "TextBlock",
                    "id": "AftHighF",
                    "text": "85℉",
                    "horizontalAlignment": "center",
                    "isVisible": false
                  },
                  {
                    "type": "TextBlock",
                    "id": "AftLowF",
                    "text": "80℉",
                    "horizontalAlignment": "center",
                    "isVisible": false
                  }
                ]
              },
              {
                "type": "Column",
                "width": "20",
                "items": [
                  {
                    "type": "TextBlock",
                    "weight": "bolder",
                    "text": "Evening",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "Image",
                    "url": "https://developer.accuweather.com/sites/default/files/01-s.png"
                  },
                  {
                    "type": "TextBlock",
                    "id": "EveHighC",
                    "text": "28℃",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "TextBlock",
                    "id": "EveLowC",
                    "text": "22℃",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "TextBlock",
                    "id": "EveHighF",
                    "text": "83℉",
                    "horizontalAlignment": "center",
                    "isVisible": false
                  },
                  {
                    "type": "TextBlock",
                    "id": "EveLowF",
                    "text": "22℃",
                    "horizontalAlignment": "center",
                    "isVisible": false
                  }
                ]
              },
              {
                "type": "Column",
                "width": "20",
                "items": [
                  {
                    "type": "TextBlock",
                    "weight": "bolder",
                    "text": "OverNight",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "Image",
                    "url": "https://developer.accuweather.com/sites/default/files/34-s.png"
                  },
                  {
                    "type": "TextBlock",
                    "id": "NigHighC",
                    "text": "22℃",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "TextBlock",
                    "id": "NigLowC",
                    "text": "20℃",
                    "horizontalAlignment": "center"
                  },
                  {
                    "type": "TextBlock",
                    "id": "NigHighF",
                    "text": "71℉",
                    "horizontalAlignment": "center",
                    "isVisible": false
                  },
                  {
                    "type": "TextBlock",
                    "id": "NigLowF",
                    "text": "67℉",
                    "horizontalAlignment": "center",
                    "isVisible": false
                  }
                ]
              }
            ],
            "spacing": "medium"
          },
          {
            "type": "ColumnSet",
            "columns": [
              {
                "type": "Column",
                "width": "stretch",
                "items": [
                  {
                    "type": "TextBlock",
                    "size": "medium",
                    "weight": "bolder",
                    "color": "accent",
                    "text": "[View more](https://www.accuweather.com/)",
                    "horizontalAlignment": "center",
                    "height": "stretch"
                  }
                ],
                "height": "stretch"
              }
            ],
            "separator": true
          }
        ]
      }
     `

The issue is the toggle buttons 'C' and 'F' comes highlighted by default. How to remove the background color(blue) which comes on load. Later on the behavior is as expected.

**Comment by shaikShehanaaz** [comment]
This is how it is rendered:

![image](https://user-images.githubusercontent.com/37263235/86317757-df1dd780-bc4d-11ea-88fe-9b3a49fc0508.PNG)

**Comment by jwiley84** [comment]
Hi @shaikShehanaaz 

Does this behaviour persist if you use the dark mode on teams? Or is it light mode only? There are some behaviours (the colors of the buttons in teams for instance) that are limited by channel. Are you trying to change the color entirely, or is the button not behaving as expected?

**Comment by Nikitha-MSFT** [comment]
When you add an action inside the column the button will render with blue background,If you add button directly to card without using column the button will render with white background.
Could you please try this sample JSON:
`{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2",
    "actions": [
        {
            "type": "Action.ToggleVisibility",
            "title": "Action.ToggleVisibility with out action set",
            "targetElements": [
                {
                    "elementId": "MyCol4",
                    "isVisible": true
                },
                {
                    "elementId": "MyCol5",
                    "isVisible": false
                }
            ]
        }
    ],
    "body": [
        {
            "type": "TextBlock",
            "text": "Welcome",
            "id": "MyCol4"
        },
        {
            "type": "TextBlock",
            "text": "To Teams",
            "id": "MyCol5"
        },
        {
            "type": "ColumnSet",
            "columns": [
                {
                    "type": "Column",
                    "width": "stretch",
                    "items": [
                        {
                            "type": "ActionSet",
                            "actions": [
                                {
                                    "type": "Action.ToggleVisibility",
                                    "title": "Action.ToggleVisibility Inside a column",
                                    "targetElements": [
                                        {
                                            "elementId": "MyCol4",
                                            "isVisible": true
                                        },
                                        {
                                            "elementId": "MyCol5",
                                            "isVisible": false
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}`
Card will be rendered as shown below:
![image](https://user-images.githubusercontent.com/61688740/87908549-36141100-ca84-11ea-9b20-20a97af3677d.png)

**Comment by arturl** [comment]
@shaikShehanaaz, I hope the solution from @Nikitha-MSFT works for you. If not, feel free to reactivate.
