### ISSUE TITLE
Direct Line channel - SendActivityAsync receiving 503 Service Unavailable

### ISSUE THREAD

**Issue by MikeCardiff** [microsoft/BotFramework-Services#237]
Using the C# SDK we are calling:
```c#
await turnContext.SendActivityAsync(result).ConfigureAwait(false);
```
Since this morning (roughly 7am UTC) we have started receiving a 503 Service Unavailable message when sending messages. It happens often, but not all the time. This screenshot from App Insights shows the failure:
![image](https://user-images.githubusercontent.com/63668650/88382299-10e31380-cda0-11ea-9374-bc633314b804.png)

 Sending a message again after the failure succeeded. 

Is there an issue with Direct Line at the moment? I've also logged a ticket with Azure support to investigate.

Thanks.

**Comment by chatbotalex** [comment]
Same here

Request URL:https://directline.botframework.com/v3/directline/conversations/C46gOO3jIbO4QZl4E0cp51-h/upload?userId=1ac40575-3df6-4bc3-9474-46a83d67ee1a
Request method:POST
Remote address:62.217.251.222:8080
Status code: 503 Service Unavailable
Version:HTTP/2.0
Referrer Policy:no-referrer-when-downgrade

**Comment by MikeCardiff** [comment]
Just an update for anyone having the same issue.

I've had a reply from Azure support. They have said that the Direct Line channel is having a region outage at the moment and they are working on a fix.

**Comment by MikeCardiff** [comment]
Azure support have confirmed that the isse has been resolced. Closing it here too.

Thanks!
