### ISSUE TITLE
DirectLine works intermittently (502 / 503 error codes)

### ISSUE THREAD

**Issue by chatbotalex** [microsoft/BotFramework-Services#238]
Hi there,

Can you please tell me if DirectLine is experiencing some problems right now? We have lots of 502/503 errors in requests 

![image](https://user-images.githubusercontent.com/45290552/88382274-ca49e500-cdb0-11ea-9f07-cd533c17b5c3.png)

Request URL:https://directline.botframework.com/v3/directline/conversations/8eM0OdqP3Z3IZ7smB7w1Ym-h/upload?userId=c83d1d8d-9463-4c8a-af23-a00db7606598
Request method:POST
Remote address:62.217.251.222:8080
Status code: 502
Version:HTTP/2.0
Referrer Policy:no-referrer-when-downgrade

APP ID: a6c8bf7d-1cba-47af-a470-d6b8247dadd8

**Comment by reizY10** [comment]
We are experiencing the same issues!

**Comment by chatbotalex** [comment]
Another example

Request URL:https://directline.botframework.com/v3/directline/conversations/C46gOO3jIbO4QZl4E0cp51-h/upload?userId=1ac40575-3df6-4bc3-9474-46a83d67ee1a
Request method:POST
Remote address:62.217.251.222:8080
Status code: 503 Service Unavailable 
Version:HTTP/2.0
Referrer Policy:no-referrer-when-downgrade

**Comment by Jeffders** [comment]
Thank you for reporting. I can confirm that there was a period where Direct Line in West Europe was returning 503s and 502 gateway timeouts intermittently. Our live site team engaged on the issue and it is resolved now. Please let us know if you continue to see issues with these API calls.
