### ISSUE TITLE
when use a invalid security token to post a message, I get the exception on null conversation, expect forbidden exception

### ISSUE THREAD

**Issue by v-maji** [microsoft/BotFramework-Services#245]
I am try to create a negative test for DL in that when I use dummy security token, I would expect forbidden exception (httpStatusCode 403 throw.  Instead I got this:

"Assert.IsNotNull failed. Failed to start a conversation."

This is not helpful to point out the root cause of problem which is invalidate security token.

**Comment by arturl** [comment]
Talked to v-majj, agreed to close the issue.
