### ISSUE TITLE
Teams bot without Azure subscription

### ISSUE THREAD

**Issue by stefan-reich** [microsoft/BotFramework-Services#247]
Hi,

I'm trying to create a Teams bot (custom code in Java), but I don't have an Azure subscription. I have an app ID, but I need to get the all important "app password", right? Can I even do that without an Azure subscription? I don't have a credit card.

When I try to register the bot in Azure portal, I get "You are currently signed into the 'BotCompany.de' directory which does not have any subscriptions. You have other directories you can switch to or you can sign up for a new subscription."

Thanks

**Comment by clearab** [comment]
Hi! Please see the documentation here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/create-a-bot-for-teams#without-an-azure-subscription

**Comment by alanszp** [comment]
It seems that the section was removed. Do you have an updated page?

**Comment by KygekDev** [comment]
> It seems that the section was removed. Do you have an updated page?

@alanszp I think they want everyone to use Azure. I can't even zip Teams metadata package without an Azure account with the appropriate subscription.

**Comment by KygekDev** [comment]
> Hi - You can use the App Studio app in Teams to create the necessary resources w/o an Azure subscription

@clearab Thank you for your response. I am using the Teams Developer Portal because the App Studio app has been deprecated. However, the Teams Developer Portal only allows me to create app packages. So, how I can connect the app package to my development source code in my local machine?
