### ISSUE TITLE
Simple Rest bot "send a message" not working. First step GET /v3/conversations already fails

### ISSUE THREAD

**Issue by matzegebbe** [microsoft/BotFramework-Services#249]
Hi!
I created a bot in a teams app via the app studio. 
```
https://dev.botframework.com/bots?id=66df54f1-b71c-4ff2-afe6-2d19d7389cbe
```
so far so good. Getting the credentials works fine via

```bash
TOKEN_JSON=$(curl -s -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "grant_type=client_credentials&client_id=${MICROSOFT_APP_ID}&client_secret=${MICROSOFT_APP_PASSWORD}&scope=https%3A%2F%2Fapi.botframework.com%2F.default" https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token)
```
after that my plan is to chat with users who have installed the app:
![image](https://user-images.githubusercontent.com/3482021/92867810-523b8b00-f401-11ea-84d7-c7e4780053c9.png)

How can I send a message to someone who is already interacting with the bot?! I checked the documentation and tried to get all converstation (checking https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0) the GET /v3/conversations?continuationToken={continuationToken} gives me a 405 Error. 

```bash
BASE_URL="https://smba.trafficmanager.net/apis"
curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" "$BASE_URL/v3/conversations"
gives a
{"message":"The requested resource does not support http method 'GET'."}
```

How else would I be able to interact with the users of the teams app? Do I need to start a new conversation fist?

Thanks a lot

**Comment by v-kydela** [comment]
@matzegebbe - Get Conversations only works for Direct Line. You could try Create Conversation or you could try Send to Conversation if you have the conversation ID, etc.

Can you explain more about what you're trying to do? Do you want to message all users who have interacted with the bot, or do you want to message specific users based on their emails or something?

**Comment by matzegebbe** [comment]
It worked with the python bot sdk. Thanks
