### ISSUE TITLE
[Question] How to display Suggested Action Cards on Skype for Business?

### ISSUE THREAD

**Issue by maqnirajj** [Microsoft/BotFramework-Services#25]
I know current version does not support cards. Is there a workaround?

**Comment by v-kydela** [comment]
Thanks for the question, @maqnirajj 

Skype for Business bots are still in developer preview. There are a lot of features that we shouldn't necessarily expect to work entirely or at all.

The best workaround I can think of is to use a different channel. Direct Line and Web Chat are highly customizable and can fit a wide variety of needs.

**Comment by maqnirajj** [comment]
Thanks for response @v-kydela 

I am working on a project where users interact using Skype for Business. I know DirectLine is a good option but does not fit my requirements. I am assuming several teams might have requested this feature. Do we have any workaround for this? 

Also, by SfB bot, do you mean a separate bot or it will be part of Bot framework? Can someone please share Dev preview build so that I can try my hands at it?

**Comment by maqnirajj** [comment]
Thanks for response

I am working on a project where users interact using Skype for Business. I know DirectLine is a good option but does not fit my requirements. I am assuming several teams might have requested this feature. Do we have any workaround for this?

Also, by SfB bot, do you mean a separate bot or it will be part of Bot framework? Can someone please share Dev preview build so that I can try my hands at it?

Thanks
Niraj Kumar Jha
[Sign2]<http://www.maqsoftware.com/>
Direct 425 499 9202 <tel:425%20499%209202>  |  Office 425 526 5399 x 137<tel:+14255265399> |  Lync  fareast\v-niraj  | <mailto:v-niraj@microsoft.com>  Skype maqnirajj<skype:%20maqnirajj>

Redmond    Hyderabad    Mumbai
Microsoft Gold Certified Partner    Microsoft Preferred Vendor

**Comment by v-kydela** [comment]
I have answered your question. The workaround is to use another channel. This is the documentation for Skype for Business bots: https://docs.microsoft.com/en-us/skype-sdk/skype-for-business-bot-framework/docs/overview

I don't recommend trying to make a Skype for Business bot because I don't know how successful you'll be and the roadmap is unknown as to whether we should expect Skype for Business bots to become fully functional

**Comment by maqnirajj** [comment]
Problem is customer already has a working infrastructure setup. It does not make sense to request using another tool (web channel) just for using bot. It will be adding to inconvenience.
I am really surprised that no one else faced this issue. Can we please add this as a feature request?

**Comment by v-kydela** [comment]
I'm sorry for the inconvenience, @maqnirajj. Other people may be facing this issue but that doesn't mean there's a perfect solution. Yes, you certainly can add this as a feature request

**Comment by jwiley84** [comment]
Hi @maqnirajj!

While AFAIK, SfB does not currently support adaptive cards, it does support some of the simpler ones, such as Hero cards, Reciept cards, etc. What kind of cards are you trying to create? 

On of the side effects of the bot framework is that different channels tend to render things like cards differently, or possibly don't support them yet. I can certainly reach out to the SfB team and see what they say about the status of this, or if its on their roadmap. I do know that someone posted on the adaptive cards repo about it recently and was told 'we're still working on it.' While I wait for a reply, perhaps we can try to find a good solution in the mean time for your customer. What is the end goal of the card?

**Comment by jwiley84** [comment]
Hi @maqnirajj! I'm going to re-close this for lack of response. If you still need assistance, please reopen this issue.
