### ISSUE TITLE
GetUploadedAttachment is still not working in Teams.

### ISSUE THREAD

**Issue by abhi421** [microsoft/BotFramework-Services#251]
GetUploadedAttachment is still not working in Teams.
I tried to upload 400 bytes png image but it doesn't work
working in bot emulator
Sample type: BotBuilder-Samples/samples
Sample language: NodeJS
Sample name: 15. handling attachment

_Originally posted by @abhi421 in https://github.com/microsoft/BotFramework-Services/issues/168#issuecomment-691658783_

**Comment by jwiley84** [comment]
As I mentioned in the issue you linked, sample 15 does not work for teams. Please use [sample #56 Teams File Upload](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/56.teams-file-upload) and let us know if the problem is still occuring.

**Comment by Manish-MSFT** [comment]
@abhi421 : [Sample ](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/56.teams-file-upload) and let us know if you still face issues.

**Comment by abhi421** [comment]
![image](https://user-images.githubusercontent.com/30606440/93575484-55adb400-f9b7-11ea-9c13-6cc96ca00730.png)
yes sample 56 working fine in my chatbot but I don't want to show file consent card I directly wanted to show file info card

**Comment by arturl** [comment]
Thanks @abhi421. @jwiley84, can you help with this:
> but I don't want to show file consent card I directly wanted to show file info card

**Comment by jwiley84** [comment]
If you're trying to bypass the "BOTNAME needs permissions to upload this file to your OneDrive", I don't believe you can. Per the Teams apps documentation:

![image](https://user-images.githubusercontent.com/17333688/93647396-344fc680-f9bd-11ea-9fc8-4beccca820ab.png)

This is per: https://docs.microsoft.com/en-us/microsoftteams/app-permissions

**Comment by abhi421** [comment]
@jwiley84 yes I can't bypass file consent card. Is there any other way to upload file on oneDrive/sharePoint which work in teams.

**Comment by Wajeed-msft** [comment]
Hi @abhi421 - You can post messages with card attachments referencing existing SharePoint files using the Microsoft Graph APIs for [OneDrive and SharePoint](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/). Please take a look at [send and receive files with a bot](https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-and-receive-files?tabs=dotnet#using-the-microsoft-graph-apis).

**Comment by MichaelHaydenAtMicrosoft** [comment]
Hi @abhi421 , did Wajeed's solution work for you?

**Comment by jwiley84** [comment]
Closed due to inactivity
