### ISSUE TITLE
OnInstallationUpdateRemoveAsync not called when removing bot from Slack workspace

### ISSUE THREAD

**Issue by haacked** [microsoft/BotFramework-Services#258]
I have a bot connected to Slack via the Azure Bot Service (Bot channels registration). When a customer installs my bot into their Slack workspace, I can see that the `OnInstallationUpdateAddAsync` handle is invoked in my bot class (`ActivityHandler`).

However, when they remove the bot from their Slack workspace, the corresponding `OnInstallationUpdateRemoveAsync` method is never called.

Slack does have an [`app_uninstalled` event](https://api.slack.com/events/app_uninstalled) and it doesn't require any Oath scopes.

**Comment by jwiley84** [comment]
Hi Services Team! Can we look into modifying the slack adapter to enable support for https://api.slack.com/events/app_uninstalled and convert it to an InstallationUpdate with 'remove' action?

**Comment by DingmaomaoBJTU** [comment]
Hi, thanks for reporting this! The fix to support app_uninstalled event is on the way and need some time to go to production. Will update when it is available to use~

**Comment by haacked** [comment]
Thanks for the update! Looking forward to it!

**Comment by DingmaomaoBJTU** [comment]
This changed had been merged to production in 12/14 and you may have a try now~ Let me know if you meet any issue~

**Comment by haacked** [comment]
I confirmed this works now. Thanks!
