### ISSUE TITLE
[Question] Is there any plan to support Google Hangouts as a channel in Bot Framework?

### ISSUE THREAD

**Issue by maqnirajj** [Microsoft/BotFramework-Services#26]
If no, is there please suggest recommended workaround. I read through related issues which were closed since V4 came out. However, I don't see any recommended solution which can work at scale.

**Comment by dawnwin1102** [comment]
Our client also want the feature of Google Hangouts channel, Is there any plan I can expect in V4?

**Comment by jameslew** [comment]
Hi, I'm Jim from the Bot Service team.  Hangouts is not on our short term roadmap for Bot Service; we're continually evaluating our backlog and I'll note your interest to be considered in the next round of planning.
