### ISSUE TITLE
Add support for Slack Events API

### ISSUE THREAD

**Issue by haacked** [microsoft/BotFramework-Services#262]
Somewhat related to #258. I have a [microsoft/botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet/) bot connected to Slack via the Azure Bot Service (Bot channels registration). The [Slack Events API](https://api.slack.com/events-api) has a rich set of events that are important to keep my bot updated. Some that I'm particularly interested in are:

* [`user_change`](https://api.slack.com/events/user_change)
* [`team_join`](https://api.slack.com/events/team_join)
* [`team_rename`](https://api.slack.com/events/team_rename)

None of these events seem to be passed to my bot. I can understand that the service might not have direct support for every event of every chat platform. But I would expect that these "unsupported" events would at least be passed through and would call `OnEventAsync` or `OnUnrecognizedActivityTypeAsync` on my bot (`ActivityHandler`).

Is there a way to do that today that I'm missing? If not, may I request this as a feature? Thanks!

**Comment by DingmaomaoBJTU** [comment]
Hi, thanks for reporting this! This is a good point but considering not involving too many fixed behavior, we will not support all events by default. The fix to support user_change, team_join and team_rename events is on the way and needs some time to go to production. Will update when it is available to use~

**Comment by haacked** [comment]
> The fix to support user_change, team_join and team_rename events is on the way and needs some time to go to production.

Great! Thanks!

**Comment by DingmaomaoBJTU** [comment]
This changed had been merged to production in 12/14 and you may have a try now~ Let me know if you meet any issue~

**Comment by haacked** [comment]
I confirmed these are working. Thanks!

**Comment by haacked** [comment]
Hi, it's me again. I'm running into with these events not being sent to one of my bots. Here's the situation:

I have two Bot Channel Registrations:

Bot | Channel | Endpoint
---- | ------- | ------------
`abbot-bot` | Slack | My Bot hosted as an Azure Web App
`abbot-bot-haackdev` | Slack | My Bot running locally using ngrok

They both are connected to Slack with the same permissions.

In my testing, I notice that `abbot-bot` will receive messages addressed to it, but is not receiving `user_change` and `team_rename`. I confirmed by watching the log console for my bot's Azure Web App.

However, `abbot-bot-haackdev` has the opposite problem. It's not receiving any messages addressed to it, but it _does_ receive `user_change` and `team_rename`. I'm stuck and don't know how to debug this as it seems to be a Bot Service issue but I have no way to confirm or deny that.

**Comment by haacked** [comment]
I should also mention that Azure Bot Service does not show any errors with the Slack channel. The health status says "Running" with both bot registrations.

**Comment by DingmaomaoBJTU** [comment]
OK, let me try if I can repro it~

**Comment by haacked** [comment]
@DingmaomaoBJTU it might be on the Slack side. I’m also talking to their support to look into it.

**Comment by DingmaomaoBJTU** [comment]
@haacked I see... I could not get a repro on my side, (I followed the guide here https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs and add user_change additionally).
If there is anything on our side I can do to help, please let me know.

**Comment by haacked** [comment]
Ok, this was a PEBKAC issue.

![image](https://user-images.githubusercontent.com/19977/107251828-9e5b1d80-69e9-11eb-9ade-30b8831053e7.png)

Everything is working fine. Thanks for looking into it though.
