### ISSUE TITLE
Feature Request: Bot service connect with Line OpenChat 

### ISSUE THREAD

**Issue by CharingJC** [microsoft/BotFramework-Services#266]
# Background

August 19, 2019 – LINE Corporation ("LINE") announced the launch of OpenChat, the new enhanced **group** functionality for the LINE messaging app. It will be awesome if we can have related feature update to enable ABS for OpenChat.

*To use OpenChat, please update LINE to at least 9.12.0 on an iOS device or 9.13.0 on an Android device.

## More information

website: https://openchat-blog.line.me/
To register a phone number please try: https://www.twilio.com/messaging

## The five features of OpenChat
OpenChat enables users to communicate easily and conveniently in a wide range of scenarios in the following five ways.

 

1. Set a different profile for every chat room

OpenChat enables users to set a different nickname and profile image for every chat group they join. This is perfect for users who want to join a group chat using a different profile from their LINE account, or chat with other users about common interests and lifestyles without friending them. Editing and updating OpenChat profiles will not affect a user's LINE profile.

 

2. Designate group administrators

Based on demand for a capability to properly operate and manage large group chats, OpenChat gives users administrative privileges for OpenChat groups they create. This allows users to be responsible for maintaining order and peace within their own groups, such as by using an anti-spam bot to register and filter out prohibited words. Administrators can also designate up to 100 co-administrators.

 

3. Join or be invited to a group in one of three ways

Administrators can choose how users join their group depending on the group’s nature and purpose—by open invitation, based on the administrator's approval, or by entering an invitation code.  Administrators can change this setting at any time.

 

 4. Retrace a group's chat history 

OpenChat lets users see a limited chat history of new groups they join so that they can trace conversations that took place before they joined the group. (Chat history is available for approximately 180 days for messages and 30 days for images.) The purpose of this feature is to help new members gather information from the chat history and gain a feel of the group so that they can integrate themselves more smoothly.

 

5. Groups can contain up to 5,000 users

For greater flexibility, OpenChat allows up to 5,000 users to join a group. This is 10 times more than the maximum number of users who can join a normal LINE group chat.

![image](https://user-images.githubusercontent.com/74894646/99935750-648c5a80-2d9c-11eb-913e-855b2590f166.png)

**Comment by youyu16** [comment]
@CharingJC Currently, the bot can not join a OpenChat like group/room chat. 
[How invite bot to Line Square or OpenChat | LINE developers community (line-community.me)](https://www.line-community.me/en/question/5d47a63f851f743fd7cda978)

**Comment by arturl** [comment]
Hello, thank you for the feedback.  I conferred with our team on this and unfortunately we do not have a short term ETA for this feature, it is a large work item and needs to be evaluated against other priorities.  We've captured this in our planning backlog however and will evaluate it during upcoming planning milestones.
