### ISSUE TITLE
Updating bot end point takes too much time to reflect

### ISSUE THREAD

**Issue by shashank16341** [microsoft/BotFramework-Services#267]
1. Go to Azure Portal
2. Go to bot service
3. Go to Settings blade
4. Modify the messaging endpoint to a new URL(ngrok/ conveyor URL).

It's taking more than 30min to reflect and because of this issue development activities are getting impacted alot. Previously endpoint used to reflect as soon as we update it. This behavior is being shown from yesterday. Please help out asap.

**Comment by vidyakdil** [comment]
I'm facing this issue since today morning. If we go to "Test from webchat" blade in Azure, it's hitting the bot engine. But if tested from Facebook, it's not hitting the end point. It's taking around 30-40 minutes to point to the URL updated in the bot service settings

**Comment by PoojaGidd** [comment]
I am facing same issue from today morning. its taking more then 30mints to point to the URL updated in the azure bot service setting.

**Comment by craigjensen** [comment]
I confirmed that this is a bug in the service code.  We'll get a fix out in the next release.  ETA 12/3

**Comment by vidyakdil** [comment]
Thank you for the update

**Comment by vidyakdil** [comment]
Hi @craigjensen , can you please share an update on this

**Comment by craigjensen** [comment]
fix should be live now - please reopen if you're still seeing this
