### ISSUE TITLE
PUT /v3/conversations/${conversationId}/activities/${activityId} return 403 ServiceError Unknown

### ISSUE THREAD

**Issue by michaelwittig** [microsoft/BotFramework-Services#269]
We receive odd responses from time to time when updating messages in MS Teams:

Request:

* Path: /v3/conversations/${conversationId}/activities/${activityId}
* Method: Put
* Headers:
    * Authorization: Bearer xxx
    * Content-Type: application/json; charset=utf-8
* Body:
```json
{
    "type": "message",
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "content": {
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.0",
                "msteams": {
                    "entities": []
                },
                "body": [
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "Container",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": "...",
                                        "wrap": true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "Container",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": "...",
                                        "wrap": true,
                                        "weight": "Bolder",
                                        "size": "Medium"
                                    },
                                    {
                                        "type": "TextBlock",
                                        "text": "...",
                                        "wrap": true
                                    }
                                ],
                                "style": "warning",
                                "bleed": true
                            },
                            {
                                "type": "ActionSet",
                                "actions": [
                                    {
                                        "type": "Action.OpenUrl",
                                        "url": "...",
                                        "title": "Schedule onboarding call"
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "Container",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": "...",
                                        "wrap": true,
                                        "weight": "Bolder",
                                        "size": "Medium"
                                    },
                                    {
                                        "type": "TextBlock",
                                        "text": "...",
                                        "wrap": true
                                    }
                                ],
                                "style": "good",
                                "bleed": true
                            }
                        ]
                    },
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "Container",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": "...",
                                        "wrap": true,
                                        "weight": "Bolder",
                                        "size": "Medium"
                                    },
                                    {
                                        "type": "TextBlock",
                                        "text": "...",
                                        "wrap": true
                                    }
                                ],
                                "style": "warning",
                                "bleed": true
                            }
                        ]
                    },
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "Container",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": "...",
                                        "wrap": true,
                                        "weight": "Bolder",
                                        "size": "Medium"
                                    }
                                ],
                                "style": "accent",
                                "bleed": true
                            }
                        ]
                    },
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "Container",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": "...",
                                        "wrap": true,
                                        "weight": "Bolder",
                                        "size": "Medium"
                                    }
                                ],
                                "style": "accent",
                                "bleed": true
                            }
                        ]
                    },
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "Container",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": "...",
                                        "wrap": true,
                                        "weight": "Bolder",
                                        "size": "Medium"
                                    }
                                ],
                                "style": "accent",
                                "bleed": true
                            }
                        ]
                    },
                    {
                        "type": "Container",
                        "items": [
                            {
                                "type": "Container",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": "6. Next steps",
                                        "wrap": true,
                                        "weight": "Bolder",
                                        "size": "Medium"
                                    }
                                ],
                                "style": "accent",
                                "bleed": true
                            }
                        ]
                    }
                ]
            }
        }
    ]
}
```

Response:
```json
{
    "error": {
        "code": "ServiceError",
        "message": "Unknown"
    }
}
```

**Comment by jimsam** [comment]
I have the same error message as you but with a response code 400 with the following request:

Request:

- Path: /v3/conversations/<conversation_id>/activities
- Content-Type: application/json
- Authorization: Bearer <token>
- Body:
```
{
    "type": "message",
    "from": {
        "id": <App ID>,
        "name": "<Bot Name>"
    },
    "conversation": {
        "id": <Conversation ID>,
        "name": ""
    },
    "recipient": {
        "id": "29:<Recipient ID>",
        "name": "<Recipient Name>"
    },
    "text": <Text Message>
}
```

**Comment by v-kydela** [comment]
Thank you for the report, @michaelwittig. It looks like you're trying to use an Adaptive Card in Slack. Is that correct? Slack doesn't support Adaptive Cards, so your card would be converted to an image that looks like this:

![image](https://user-images.githubusercontent.com/41968495/101523224-29ae2900-393d-11eb-9bbd-2cfd2c0de0d0.png)

If that's what you're intending, then I have a few questions:

1. Does the problem occur with messages that don't include any Adaptive Cards?
1. Does the problem occur when sending a message rather than updating one?
1. Have you considered using the Slack adapter?
1. Have you considered using Block Kit?

@jimsam - I'm sorry but I don't think I have enough information to diagnose your issue. Perhaps I could investigate further if you provide repro steps.

**Comment by jimsam** [comment]
@v-kydela A few minutes ago I managed to solve my issue by another closed issue that I found, the problem was that the URL that documentation has to make a new activity is a POST at https://smba.trafficmanager.net/apis/v3/conversations/<converations id> but actually is  https://smba.trafficmanager.net/amer/v3/conversations/<converations id>

I really didn't found anywhere what other variation might exists (apis, amer ...) but I am good for now thanks.

**Comment by michaelwittig** [comment]
Hi @v-kydela

Sorry. We use the request to update a message in Teams, not Slack.

**Comment by v-kydela** [comment]
@jimsam - You had been using a service URL for Skype. Teams uses region-specific service URL's. Can you tell us what documentation you're talking about?

@michaelwittig - In case your issue is the same as Jim's can you let me know what your host URL is?

**Comment by jimsam** [comment]
@v-kydela No, I use this for a bot that I build for Teams in order to get a new activity to a conversation with a specific user in Teams from another application, the reference for that has [here](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-send-and-receive-messages?view=azure-bot-service-4.0)

**Comment by v-kydela** [comment]
@jimsam - That doc says `https://smba.trafficmanager.net/apis` is only an example and does not say it is a service URL you should use for Teams. The doc says:

> Use the `serviceUrl` property in the incoming activity to [identify the base URI](https://docs.microsoft.com/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference#base-uri) that your bot should use to issue its response. 

If the doc is still confusing and is leading customers to use `https://smba.trafficmanager.net/apis` as their service URL then is there some way it could be more clear?

**Comment by jimsam** [comment]
@v-kydela I think that I was confused at that point because I didn't read the whole documentation most likely because the /apis/ was making a lot of sense and never got to a point to question the actual URI when I got the error. 
But as you point out there is a part of the documentation that describes where to find the correct URI, you just need to read all of it and not partially as I did.

**Comment by michaelwittig** [comment]
@jimsam not sure why you hijack that issue  for an error report that is not the same. as you mentioned, your response code is different. So please go and open your own issue.

@v-kydela no, I don't run into the sam issue as @jimsam and I don't appreciate that he discusses a very different problem here. We use endpoints such as `https://smba.trafficmanager.net/amer/`, `https://smba.trafficmanager.net/emea/`, ... depending on the tenant. I would appreciate if we could talk about my original error report. Receiving those generic `ServiceError Unknown` is not helpful and should be fixed. This is also not my first request I send to your APIs. We make a bunch of calls and most of them work. But for the one I shared with you we sometimes receive the generic Unknown error. We had the same issue before with other endpoints and it ended with a fix on your side.

**Comment by v-kydela** [comment]
@michaelwittig - I'm sorry but I can't seem to reproduce the error so far, though it sounds like you're saying it's intermittent. Are you sending the request in Postman? Is the message in a personal, group, or channel chat?

In any case, it looks like Teams should implement more verbose error messages.

**Comment by michaelwittig** [comment]
@v-kydela It's a channel message. A retry of the request does not fix the problem. For certain conversations/activities is always fails with the above error. Is it possible that error like: channel removed e.g. are not properly handled?

**Comment by v-kydela** [comment]
@michaelwittig - Thank you for the info. Whether the channel is deleted or the conversation ID is just made up, I get a descriptive error message when trying to update an activity:

```json
{
    "error": {
        "code": "ConversationNotFound",
        "message": "Conversation not found."
    }
}
```

I tried updating an activity in a channel thread using a fake ID, and I got a descriptive error message again:

```json
{
    "error": {
        "code": "ActivityNotFoundInConversation",
        "message": "Message does not exist in the thread."
    }
}
```

However, I do get the unknown error when I try updating an activity in a channel thread using an activity ID that existed at one point but has since been deleted. Is it possible that this is the cause of the errors you're seeing? Also, is the purpose of your report to say that your attempts to update activities are failing when they shouldn't, or are you saying you expect to see an error message but you'd just like the error message to be more descriptive? I will escalate this in either case because the unknown errors are clearly a problem either way, but I need to know if there's also a problem with Update Activity not working when it should.

**Comment by michaelwittig** [comment]
@v-kydela It's possible but I don't know. We see this Unknown Error in the wild not on my tenant, but tenants I have no control over. Therefore, I have no idea what those tenants are doing. All I see is an error message that is of ne help to figure out what's going on. And you are asking me to reverse engineer that :) Sorry, I guess it's easier to just look at the code and ensure that no one ever throws an "Unknown" error. .

**Comment by v-kydela** [comment]
@michaelwittig - All right, well for now I guess we should treat this as an issue with the error message. I will unassign myself so the appropriate people can have a look at it.

**Comment by arturl** [comment]
@michaelwittig, can you share your bot id, conversation id (partial would be OK) and timestamps of the events where you got the error. I'll look it up on the Azure Bot Service end. Is this a recent problem, and if yes when did it start happening?

Going though this thread, I assume this is happening in Slack channel only and any reference to Teams/Skype is irrelevant.

Also, can you confirm the error code is 403? That would be unusual if the error only happens with a specific payload.

**Comment by michaelwittig** [comment]
@arturl My issue is about updating messages in MS Teams, not Slack. Sorry for the confusion. 

> can you share your bot id, conversation id (partial would be OK) and timestamps of the events where you got the error.
bot id: 1dd5785b-d8b3-400d-8e1f-af7c939cd70f
conversation id: (not available anymore, we drop logs after 14 days)
activity id: 1607010293547
time: ~Dec 3, 2020 05:17:22.948 PM

> Is this a recent problem, and if yes when did it start happening?
No, it happens from time to time.

> Also, can you confirm the error code is 403?
Yes, 403.

**Comment by Trinetra-MSFT** [comment]
@michaelwittig , is this a prod bot? If you can provide us the tenant id as well i can check the logs for the bots?

**Comment by michaelwittig** [comment]
@Trinetra-MSFT, yet, it is. Tenant id: f1123783-951a-416c-be65-baaf60761486

**Comment by michaelwittig** [comment]
@Trinetra-MSFT any news on this issue?

**Comment by michaelwittig** [comment]
@NickEricson can you help me out here?

**Comment by MichaelHaydenAtMicrosoft** [comment]
We’re going to update error code returned to the bot. Fix would be deployed to Production by 2nd of February.

**Comment by michaelwittig** [comment]
Thanks for the update @MichaelHaydenAtMicrosoft

**Comment by MichaelHaydenAtMicrosoft** [comment]
@michaelwittig - wanted to check to see if this is working correctly for you now.

**Comment by michaelwittig** [comment]
@MichaelHaydenAtMicrosoft I can confirm that I'm not seeing the error anymore in our logs.

**Comment by BK3223** [comment]
Hi ALL,  
I am also facing similar issue.
