### ISSUE TITLE
DirectLine Enhanced Authentication->getsessionid results in 400 BadRequest  and Without DirectLine Enhanced Authentication->Giving magic code, instead of automatic login

### ISSUE THREAD

**Issue by selvaduraiece** [microsoft/BotFramework-Services#271]
I am facing few strange issues.

1. I have enabled DirectLine Enhanced Authentication -->I added trusted origin as well. But if I try to hit using webchat I am getting 400 error and bot not able to connect even.
2. I have disabled DirectLine Enhanced Authentication --> My bot is working at least but still getting magic code, instead of auto login.

I need your assistance on How to get rid of magic code? This really creates huge impact and users completely dislike MSBot and wanna move out to different vendors.

It would be great help, if we could address this at the earliest

**Comment by stevkan** [comment]
@selvaduraiece, please take a look at this blog posting, [Enhanced Direct Line Authentication Features](https://blog.botframework.com/2018/09/25/enhanced-direct-line-authentication-features/) for additional help. Check if there are any additional steps you maybe missed. With Enhanced Authentication, pay particular attention to the `userID` property as this value needs to be sent in the request payload when requesting a token. The value should also be prepended with "dl_".

**Comment by selvaduraiece** [comment]
Ya I got it work. Thanks a lot. I am facing strange issue as mentioned here - #3639, it would be great if I get fix for this issue.
