### ISSUE TITLE
Activating Cortana Channel in Bot Framework 

### ISSUE THREAD

**Issue by 007-fr** [microsoft/BotFramework-Services#273]
When I attempt to add Cortana as a channel in a Bot via Azure, I receive a number of different errors errors.
![image](https://user-images.githubusercontent.com/66075770/102659004-ae235780-4146-11eb-8fde-79731a88cf55.png)

When I 1st click deploy, I get the incorrect image error.
![image](https://user-images.githubusercontent.com/66075770/102659031-baa7b000-4146-11eb-81ca-95867669e2d3.png)

Once I upload another image for the Bot, I receive an internal server error. Below is a screenshot of it along with what's shown with the api call.
![image](https://user-images.githubusercontent.com/66075770/102659064-c8f5cc00-4146-11eb-93ab-820b9d8ce897.png)

![image](https://user-images.githubusercontent.com/66075770/102659101-d612bb00-4146-11eb-86b9-244eba9e16fe.png)

**Comment by EricDahlvang** [comment]
Hi @007-fr 

Cortana Skills have been retired, except for members of the TAP program: 
https://docs.microsoft.com/en-us/cortana/skills/third-party-deprecation#how-do-i-build-cortana-skills-in-the-future

https://docs.microsoft.com/en-us/cortana/enterprise/overview

https://github.com/MicrosoftDocs/bot-docs/issues/1959

I'm not sure how to contact someone from the TAP program.  Does anyone on the ABS team know if this is documented anywhere?

**Comment by stevkan** [comment]
I have seen it suggested in forums that Enterprise-level customers need to reach out to a Microsoft Account rep in order to start the process of joining a TAP program. But, I don't know if that is still the case and no link / reference was provided in those cases.

**Comment by p-nagpal** [comment]
Hi @007-fr, we have fixed the errors in the screenshot above and you should be able to make progress now.  However, please keep in mind, that Cortana Skills have been retired except for TAP program: https://docs.microsoft.com/en-us/cortana/skills/third-party-deprecation#how-do-i-build-cortana-skills-in-the-future.

**Comment by 007-fr** [comment]
@p-nagpal The company I work for is member of the tap program, but I don’t think it’s a good idea to start Cortana if it’s already retired. 

What the recommendation for using voice interaction in the Bot Framework?

**Comment by p-nagpal** [comment]
Hi @007-fr, the roadmap for Cortana Skills will be updated on https://docs.microsoft.com/en-us/cortana/skills/third-party-deprecation#how-do-i-build-cortana-skills-in-the-future as we make changes. Additionally, you might also be interested in looking at Direct Line Speech Channel. Here is some documentation on building voice assistants with Direct Line Speech Channel: https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/direct-line-speech
