### ISSUE TITLE
In Team SSO not getting the id_token field as token response

### ISSUE THREAD

**Issue by bommareddysandhya** [microsoft/BotFramework-Services#274]
## Sample information
1. Sample type: samples
2. Sample language: dotnetcore 
3. Sample name: Teams oauth SSO

## Describe the bug
In Team bot implemented SSO using Active directory v2. in the sample once user click on Sign in, as response getting access token as response. But we have one requirement to get the id_token also. how to get this. 

## To Reproduce
1. Teams SSO, after click on Sigin in , the result which comes to next waterfall as only token , doesn't id_token.
2.

## Expected behavior
How to access the id_token from oauth response.

**Comment by EricDahlvang** [comment]
@ABS is access to the id_token something the bot framework auth service can provide?

**Comment by Jeffders** [comment]
We do not support providers that return the "id_token", only the "auth_token" property, so what @joshgummersall said is correct.

If you still wanted to use the OAuthCard, the easiest way would be to make your own oauth endpoint and call it in your OAuth connection setting, and in your endpoint you call your identity provider and copy the id_token property over to the auth_token field.
