### ISSUE TITLE
ReconnectToConversationAsync with client withsecret key returns conversation token without "user" claim

### ISSUE THREAD

**Issue by dradoaica** [microsoft/BotFramework-Services#277]
## Version
Microsoft.Bot.Connector.DirectLine 3.0.2

## Describe the bug
ReconnectToConversationAsync with client withsecret key returns conversation token without "user" claim, even when the conversation is started by GenerateTokenForNewConversationAsync with ChannelAccount data

## To Reproduce
using (DirectLineClient client = new DirectLineClient(secretKey))
{
	var conversation = await client.Tokens.GenerateTokenForNewConversationAsync(new TokenParameters { User = new ChannelAccount { Id = authorizationDto.UserId } });
	using (DirectLineClient clientViaConvToken = new DirectLineClient(conversation.Token))
	{
		conversation = await clientViaConvToken.Conversations.StartConversationAsync();
	}
	
	conversation = await client.Conversations.ReconnectToConversationAsync(channel.ConversationId);
}

## Expected behavior
GenerateTokenForNewConversationAsync token payload:
{
  "bot": "dev-demo2-bot1onabp5nx893-bot",
  "site": "tBVqTE8j4Xs",
  "conv": "79OGvUz4Cr93eqhDFqM5FV-h",
  "user": "anonymous",
  "nbf": 1612281773,
  "exp": 1612285373,
  "iss": "https://directline.botframework.com/",
  "aud": "https://directline.botframework.com/"
}

ReconnectToConversationAsync  token payload:
{
  "bot": "dev-demo2-bot1onabp5nx893-bot",
  "site": "tBVqTE8j4Xs",
  "conv": "79OGvUz4Cr93eqhDFqM5FV-h",
  "nbf": 1612281773,
  "exp": 1612285373,
  "iss": "https://directline.botframework.com/",
  "aud": "https://directline.botframework.com/"
}

## Additional context

[bug]

**Comment by p-nagpal** [comment]
Hi @dradoaica, could you reconnect to the conversation with clientViaConvToken? This should have the right token state with user claim. 

Here is test I tried and it contains the user claim in the reconnected conversation: 

            Conversation conversation;
            using (DirectLineClient tokenClient = new DirectLineClient(secretKey))
            {
                var tp = new TokenParameters
                {
                    User = new ChannelAccount { Id = "user12345" }
                };

                conversation = await tokenClient.Tokens.GenerateTokenForNewConversationAsync(tp);
            }

            using (DirectLineClient clientViaConvToken = new DirectLineClient(conversation.Token))
            {
                conversation = await clientViaConvToken.Conversations.StartConversationAsync();
                .....
                conversation = await clientViaConvToken.Conversations.ReconnectToConversationAsync(conversation.ConversationId);
            }

**Comment by dradoaica** [comment]
Hi @p-lekkala, we do not store the client token resulted from GenerateTokenForNewConversationAsync. We have another authetication in our app, so by using the secret key we reconnect the user authenticated in our app to his conversation (even though his client token from BotFramework had expired). Maybe an option to generate a client token for an existing conversation and with that token cu call the ReconnectToConversationAsync or the option to pass the ChannelAccount  to ReconnectToConversationAsync (and the token returned to contain the "user" claim)

**Comment by p-nagpal** [comment]
Hi @dradoaica, extending ReconnectToConversationAsync to support token parameters is a good suggestion. This would be a new feature in Directline and we will start evaluating the feature request. 

Meanwhile, the recommended method for getting user claims in the token is to implement a token cache and save the latest unexpired token for use in the call to ReconnectToConversationAsync.

**Comment by p-nagpal** [comment]
Adding @Jeffders to track feature request.
