### ISSUE TITLE
Bot installation issue

### ISSUE THREAD

**Issue by vitaliishandra** [microsoft/BotFramework-Services#278]
We have teams application that supports proactive user messaging and static app. App is certified and published in Teams App store.

Customer installed and pinned our app to 'Global (Org-wide default)'. As a result only ~10% users received the latest version of our bot application. It tooks few days after app install and more than 50% users were already opening and logged in MS Teams but not received the latest version of application.

The current published version of app is 1.0.5. It includes static app and bot.
The previous app version was 1.0.4. It included only static app. Customer removed it prior to installing the new version.

- Some users received the old version of app 1.0.4 with prompt to update.
- Some users didn't receive any app version and should relogin. 

Is this expected behaviour or no?
Are there any way to force the installation of the latest version of app to all users?

**Comment by Nikitha-MSFT** [comment]
Could you please share tenant id? Also could you please share how you are removing the version for store app?

**Comment by vitaliishandra** [comment]
Tenant Id: 3013a262-bac5-4391-ab35-d43cf52ad904
Apps where removed from installed and pinned apps in Teams app Global setup policy:
![image](https://user-images.githubusercontent.com/56965286/107664099-bd310c80-6c94-11eb-801a-815bf8b95788.png)

Additionall info:
We install app via Microsoft Graph and the latest version was successfully installed for all users. However via setup policy it doesn't work for all users. Microsoft Graph is not an option for us as our we provide our app for many customers.

**Comment by Nikitha-MSFT** [comment]
@vitallishandra - Could you please share the Application id? Also Is this a Teams global app?

**Comment by Jagadeesh-MSFT** [comment]
@vitallishandra - Could you please share the Application id? Also Is this a Teams global app?

**Comment by vitaliishandra** [comment]
The application Id is 5d7b15f5-b634-49fe-9d62-88a9eb0fea3d (retrieved from Graph Api). 
Brainstorm App is globally publsihed: https://appsource.microsoft.com/en-us/product/office/WA200001549?tab=Overview

**Comment by Nikitha-MSFT** [comment]
We are checking with internal team, Will get back to you

**Comment by MichaelHaydenAtMicrosoft** [comment]
Hi @Nikitha-MSFT , any updates here?

**Comment by Nikitha-MSFT** [comment]
I just checked this appId, it's a Teams Global app. I saw the store version already updated to 1.0.5 with bot. But the new change from 1.0.4 to 1.0.5 is adding a bot. That will need user's consented upgrade. We don't force auto upgrade for apps added a new bot. But the users should be able to find the new version of this app from apps store and upgrade it

**Comment by vitaliishandra** [comment]
It is just one of the issue. 
What about another case:
1. Customer didn't have our app installed
2. Customer installed our app globally
3. Some users didn't receive the latest version of app after login in MS Teams

Relogin/clearing cache/PC restart sometimes helps to solve the issue for some users but not for all. Sometimes it is shown in web version but not desktop. It is reproduced for different tenants.

However if we run app installation  via Graph API everything works great, even relogin is not required. Why it is not working in same way using the  'Global (Org-wide default)' policy?

**Comment by Nikitha-MSFT** [comment]
For global policy it need to update from the user. user should reinstall the bot.

**Comment by vitaliishandra** [comment]
@Nikitha-MSFT Yes, we laready understood it that user needs to reinstall it manually if he had the old version. But what about the case I described in the latest comment (where no any version was installed previously)?

**Comment by Nikitha-MSFT** [comment]
Are you facing issue when new user install the app? if yes could you please share you manifest to test?

**Comment by Nikitha-MSFT** [comment]
@vitaliishandra - please share the required inputs if the issue still persists?

**Comment by MichaelHaydenAtMicrosoft** [comment]
@vitaliishandra - Please let us know if you need anything else from us and if we can close this issue.
