### ISSUE TITLE
Extra slash character in the attachment URL with Slack

### ISSUE THREAD

**Issue by haacked** [microsoft/BotFramework-Services#279]
## Version
What package version of the SDK are you using. __4.10.3__

## Describe the bug
When sending a message in Slack with an attachment, the `turnContext.Activity.Attachments[0].AttachmentUrl` property contains an extra slash character. It's not a big deal, but I noticed it when filing microsoft/botbuilder-dotnet#4888 

## To Reproduce
1. Create a bot and connect it to Slack using Azure Bot Service.
2. In Slack, type a message that also includes an attachment.
3. Check out the properties of `turnContext` in `OnMessageActivityAsync`

## Expected behavior
__Expected__ that `turnContext.Activity.Attachments[0].AttachmentUrl` has a URL without any double slashes.
__Actual:__ `turnContext.Activity.Attachments[0].AttachmentUrl` is populated with a URL with a double slash after the domain name. For example, `https://slack.botframework.com//v3/attachments/XXXXXXXXXX/views/original`

**Comment by arturl** [comment]
I have a fix, ETA for deployment 3/16/2021

**Comment by v-kydela** [comment]
@arturl - Will the fix apply to Telegram and LINE as well?

**Comment by arturl** [comment]
Yes @v-kydela
