### ISSUE TITLE
Activity.Text is set to filename and not the message text when sending a Slack message with attachment

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/BotFramework-Services#280]
Issue initially reported in the [Dotnet SDK repo](https://github.com/microsoft/botbuilder-dotnet/issues/4888). We are keeping the original issue to track the fix in the SDK Slack Adapter. This item tracks the fix in ABS.

**Comment by arturl** [comment]
We cannot fix this without breaking backward compatibility. We are working on a feature (schema transformation versioning) that would allow bots to opt into the new behavior but until then it must remain unchanged. I'm closing it for now, we will re-evaluate once we have schema transform versioning available.

**Comment by haacked** [comment]
Thanks for following up! I logged the original issue this is based on.

@arturl Is there an issue tracking the schema transform versioning?

I understand that changing the behavior breaks backwards compatibility, but is this not a relatively safe breaking change considering the current behavior is a bug?

I imagine that very few people are relying on their Slack message text to get overridden and discarded when sending an attachment. One way to look at it is you opt-in to the new behavior is to set the message text. The way you opt in to the old behavior is to not set the message text.

Or are there some other factors under the hood I'm not aware of?

**Comment by KayMKM** [comment]
Hi @haacked I am working on fixing this bug now. We will keep the old behavior in old schema transformation version. And fix this in new version. I think though there might be a few bots are relying Slack message to get attachment name, we need to prevent breaking these bots' behavior.

**Comment by haacked** [comment]
@KayMKM thanks for following up!

> I think though there might be a few bots are relying Slack message to get attachment name, we need to prevent breaking these bots' behavior.

I suppose these bots would be broken today if there's more than one attachment attached to the message though.

> we need to prevent breaking these bots' behavior.

I understand.

**Comment by KayMKM** [comment]
@haacked We had fixed this issue in schema transformation version 1.2. You can refer to this doc to upgrade the version: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-channels?view=azure-bot-service-4.0#bot-schema-transformation-version
