### ISSUE TITLE
DirectLine loses activities sometimes

### ISSUE THREAD

**Issue by SergeyPr** [microsoft/BotFramework-Services#283]
### Version
Microsoft.Bot.Builder DotNet 4.10.3
botframework-webchat Js 4.9.2

### Description
We are using Bot Framework SDK with communication via the WebChat channel.
When the user enters the chat page, we are sending an "event" activity to notify the bot. When the bot receives this "event" activity it prepares initial "message" activities as a response.
Last month our customers reported the issue the they sometimes didn't receive any initial messages when they enters the chat.

After investigation, we have found that our backend receives the "event" activity and sends "message" activities, but for some reason, these activities do not come to the user and disappear from the DirectLine.
The problem occurs sometimes and we did not find a way to reproduce.

### Example
Conversation ID: 40rlEJkHgSX7iO8ZGJ2ofB-a
User entered the chat on 22/02/2021 and 23/02/2021
The following activities were found in the logs:
22/02/2021:
`{"type":"event","id":"40rlEJkHgSX7iO8ZGJ2ofB-a|0000000","timestamp":"2021-02-22T08:56:18.4565986+00:00", "name":"attachDialog", ...}`
`{"type":"event","id":"40rlEJkHgSX7iO8ZGJ2ofB-a|0000001","timestamp":"2021-02-22T08:56:18.4515981+00:00", "name":"preventWatermark", ...}`
`{"type":"message","id":"40rlEJkHgSX7iO8ZGJ2ofB-a|0000002", ...}`
`{"type":"message","id":"40rlEJkHgSX7iO8ZGJ2ofB-a|0000003", ...}`
23/02/2021:
`{"type":"event","id":"40rlEJkHgSX7iO8ZGJ2ofB-a|0001010","timestamp":"2021-02-23T12:24:02.2332091+00:00", "name":"preventWatermark", ...}`
`{"type":"event","id":"40rlEJkHgSX7iO8ZGJ2ofB-a|0001011","timestamp":"2021-02-23T12:24:02.2363421+00:00", "name":"attachDialog", ...}`
But when I am making a call to directline and first 4 activities does not exist in the API response.
https://directline.botframework.com/v3/directline/conversations/40rlEJkHgSX7iO8ZGJ2ofB-a/activities
Only activities for 23/02/2021 are present:
`{"type":"event","id":"40rlEJkHgSX7iO8ZGJ2ofB-a|0001010","timestamp":"2021-02-23T12:24:02.2332091Z", "name":"preventWatermark", ...}`
`{"type":"event","id":"40rlEJkHgSX7iO8ZGJ2ofB-a|0001011","timestamp":"2021-02-23T12:24:02.2363421Z", "name":"attachDialog", ...}`

We would appreciate any information that may help to find the reason of the problem or solve it.

**Comment by stevkan** [comment]
Possibly related to Web Chat issue #[3623](https://github.com/microsoft/BotFramework-WebChat/issues/3623)

**Comment by stevkan** [comment]
@SergeyPr, the above referenced issue (and associated [PR](https://github.com/microsoft/BotFramework-WebChat/pull/3705)) fixes a race condition that was occurring between some bot and user activities, in particular, between the initial activities. This would result in a time out warning in the browser's console and, sometimes, the 'losing' activity being lost.

The fix is in and will be available in v4.12.0 of Web Chat. In the mean time, could you try testing with the published daily package to see if this fix mitigates the issue?
`<script src="https://github.com/microsoft/BotFramework-WebChat/releases/download/daily/webchat.js"></script>`

**Comment by Mallipriya-MSFT** [comment]
Hi @SergeyPr,  Thanks for reaching out to us. We are the developer support team for Microsoft teams focused on helping developers resolve their code issues specifically to Teams channel.

**Comment by MichaelHaydenAtMicrosoft** [comment]
Hi @SergeyPr - just wondering if you were able to try Stevkan's suggestion by testing with the published daily package?

**Comment by SergeyPr** [comment]
Hi @stevkan
Thank you for you help. We could not test daily package on our servers for now, but we have tries a fix, described in the issue [3623](https://github.com/microsoft/BotFramework-WebChat/issues/3623) with adding timeout before sending the first event. It looks like it solved the problem

Hi @MichaelHaydenAtMicrosoft For now we just applied the fix with timeout described here: [3623](https://github.com/microsoft/BotFramework-WebChat/issues/3623)

**Comment by MichaelHaydenAtMicrosoft** [comment]
Thank you SergeyPr. This is great news! I will close the issue for now. Please let us know if the issue returns.
