### ISSUE TITLE
[JavaScript/NodeJS] Improve CardFactory/AdaptiveCards the rendered image quality for unsupported platforms

### ISSUE THREAD

**Issue by Kadae** [microsoft/BotFramework-Services#284]
This is the similar issue to my https://github.com/microsoft/AdaptiveCards/issues/5421 - Just don't know where is a problem...

Example: Telegram doesn't support Adaptive Cards, so BotFramework renders image. Image quality is very very low.
Is there a way to improve the image quality on NodeJS? They're so pixelated... Thank you.

**Comment by Jeffders** [comment]
Azure Bot Services uses the AdaptiveCards.Rendering libraries from Nuget to assist in the "image rendering" of cards. These renderers do have limitations. If you look in these libraries, the only parameter that controls the resulting image is "width", which says nothing of card resolution.

I've opened an issue with that library on Adaptive Cards and you can follow it here:
https://github.com/microsoft/AdaptiveCards/issues/5430

In the mean time, I would suggest that you use the 'channelId' property on incoming Activities and avoid sending Adaptive Cards to the channels where the rendering is poor and instead send a HeroCard or some other alternate.
