### ISSUE TITLE
"Azure Bot Services" should be "Azure Bot Service" singular

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Services#287]
- On the [Azure Bot Services](https://azure.microsoft.com/en-us/services/bot-services/) marketing site, the product name appears with an "s" (plural).
- In the docs and according to Andrea the singular version is the official service name.

See also https://github.com/MicrosoftDocs/bot-docs/pull/2041

**Comment by MichaelHaydenAtMicrosoft** [comment]
@Andrea-Orimoto to address as part of resource naming. Closing issue for now.
