### ISSUE TITLE
POST to bot timed out after 15s

### ISSUE THREAD

**Issue by Swati02041991** [microsoft/BotFramework-Services#290]
I am using Bot framework .Net SDK v4 and directline channel. I keep getting this timeout exception in the very last step of the entire conversation. Once I get this error, the bot continues to timeout till I refresh the Sharepoint website on which it is hosted.

In App insights I can see the following:
problemID - Microsoft.Bot.Schema.BotTimeoutException at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__35.MoveNext
type - Microsoft.Bot.Schema.BotTimeoutException
outerMessage  - POST to bot-ent-chatbot-d timed out after 15s

Is this timeout configurable?

**Comment by craigjensen** [comment]
The 15s timeout is not configurable.  If your bot needs to do extensive processing you may need to update it to quickly ack the message and move the processing to a background thread where it can be completed asynchronously.

**Comment by MichaelHaydenAtMicrosoft** [comment]
@Swati02041991 - Just following up to see if Craig's workaround was helpful in resolving your issue.

**Comment by Swati02041991** [comment]
Yes, we optimised the code and seems to work fine.

**Comment by MichaelHaydenAtMicrosoft** [comment]
Great! I shall close this case. Thank you!
