### ISSUE TITLE
Can't delete bot registration resource

### ISSUE THREAD

**Issue by orsharab** [microsoft/BotFramework-Services#291]
I can't delete bot registration - msbot-i9tekgf, subscription ID - 0a05d163-70d7-4b44-a4ca-1e1df8acad43
Tried both Azure portal and AZ cli and got the same error - 

`{"error":{"code":"UnknownError","message":"message: Illegal characters in path. original trace:    at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)\r\n   at System.IO.Path.GetFileName(String path)\r\n   at Intercom.Models.BotStore.<FreeBotIconUrl>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at DevPortalLib.Helpers.BotHelper.<DeleteBotAsync>d__21.MoveNext() in C:\\__w\\1\\s\\DevPortalLib\\Helpers\\BotHelper.cs:line 415\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()\r\n   at Intercom.ResourceProvider.DataProviders.ResourceDataProvider.<DeleteResourceAsync>d__10.MoveNext() in C:\\__w\\1\\s\\Intercom.ResourceProvider\\DataProviders\\ResourceDataProvider.cs:line 396"}}
`

**Comment by xieofxie** [comment]
Hi @orsharab do you use a custom url for the bot icon? (i.e. an external url) If so, it could be a bug in our service

**Comment by orsharab** [comment]
Seems like it
![image](https://user-images.githubusercontent.com/78015512/112099427-28330480-8bac-11eb-8082-49ed37ad9653.png)

**Comment by xieofxie** [comment]
@orsharab There are two cases: 
1 is uploading a file from Portal and 
2 is set an url from ARM api. 
Could you verify which one is it?
You could use F12 to see the url of the displayed icon. If it is case one, it should be like `background-image: url("//bot-framework.azureedge.net/bot-icons-v1/BOTID_SOMEVALUE.png");`.

**Comment by orsharab** [comment]
It was set with ARM API

**Comment by xieofxie** [comment]
@orsharab I see.. It is a bug in our service. A workaround: you could upload some arbitrary icon to replace the one you set and delete again. It should work in this way.

**Comment by orsharab** [comment]
The workaround solved the issue, thanks @xieofxie!

**Comment by xieofxie** [comment]
Create an internal work item to fix this. Close the issue now
