### ISSUE TITLE
Slack Channel Does Not Include Team Id

### ISSUE THREAD

**Issue by kluhman** [microsoft/BotFramework-Services#292]
I am using the Azure Bot Service to connect to Slack, but it does not appear to be sending the Slack Team Id in the activity to our Bot. We can obtain the Team Id from the channel data directly, but that is not a fool-proof solution, since the contents of that Channel Data are not consistent between messages. For example, for a simple text activity, it contains a `SlackMessage` property, but for button press events, it has a `Payload` property, and the structure of those two properties are different as well. We also have the option of parsing it out of the account id's, but this feels like a dangerous assumption as well.

It would be really great if the Azure Bot Service could place the Team Id in the `Conversation.TenantId` property which seems like a pretty good analog for what the Team Id is, the uniquely identifying Slack Tenant Id. Based on the ability to generate account id's using the Team Id, it seems the Bot Service has the Team Id available to it, it just doesn't expose it as a stand-alone property. For reference, this is what Microsoft Teams seems to do with it's messages to the Bot. 

However it would be passed, it would be great to have some conventional way to retrieve that value for Slack without having to parse out message data. We're trying to minimize as much channel specific code in our bot as possible, and needing to parse out the Slack Team Id is a big pain point. 

Below is an abbreviated JSON snippet of the activity data from the Azure Bot Service Slack channel for reference.

```json
{
  "type": "message",
  "serviceUrl": "https://slack.botframework.com/",
  "channelId": "slack",
  "from": {
    "id": "U0123456789:T0123456789"
  },
  "conversation": {
    "id": "B0123456789:T0123456789:D01RM387LUU",
    "tenantId": null
  },
  "recipient": {
    "id": "B0123456789:T0123456789"
  },
  "text": "hi",
  "channelData": {
    "SlackMessage": {
      "team_id": "T0123456789"
    }
  }
}
```

**Comment by arturl** [comment]
Hi @kluhman, it's pretty hard for us to do this reliably, for the reasons you stated yourself. If we get it wrong, it will be hard to change without breaking bots dependent on it.

Can you try a middleware approach similar to this and see if it works for you: https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L1689

**Comment by kluhman** [comment]
@arturl Yep, we can do an approach like that. I was just hopeful it would be possible to do this on the ABS side to minimize channel specific code in our implementation. It seemed to me that the ABS connector already has some mechanism of parsing the Team Id from the various types of Slack requests because it is used in the `<user-id>:<team-id>` recipient and from account object ids. I'm pretty sure Slack user id's are not returned in that format, so to me it implied the ABS connector was doing the concatenation before sending it to our bot.

**Comment by MichaelHaydenAtMicrosoft** [comment]
Hi @kluhman  - just wondering if Artur's solution will suffice for now. If so, we would like to close this issue.

**Comment by kluhman** [comment]
Yes, we have a workaround in place for this. But it would be great in the future to have support from the ABS for this

**Comment by MichaelHaydenAtMicrosoft** [comment]
Closing with suggestion to provide future support from us for this feature.
