### ISSUE TITLE
Azure Bot does not support Adaptive Card Version 3.0

### ISSUE THREAD

**Issue by damlaalkan** [microsoft/BotFramework-Services#293]
## Describe the bug

The bot which uses adaptive cards version 3.0 and works perfectly in Bot Framework Composer Web Chat and Bot Emulator does not works when it has published and deployed on Azure Bot. In each browser Chrome, Edge, Firefox, it gave the adaptive cad error and when the adaptive cards updated to version 1.0 it worked. The version 1.0 does not support new features. What should be done to fix this version error?

**Comment by NickEricson** [comment]
Hi @damlaalkan - Does AdaptiveCards 2.5.1 support the feature you need? If so try using that version in your bot.

If that doesn't work - what is the feature you need and what is the error you are seeing. Do you have the json for the Adaptive Card you send and the Adaptive Card you receive in WebChat (when it doesn't work)?

**Comment by MichaelHaydenAtMicrosoft** [comment]
Hi @damlaalkan - Just following up to see if Nick's suggestion on upgrading versions worked for you? Please let us know.

**Comment by damlaalkan** [comment]
> Hi @damlaalkan - Does AdaptiveCards 2.5.1 support the feature you need? If so try using that version in your bot.
> 
> If that doesn't work - what is the feature you need and what is the error you are seeing. Do you have the json for the Adaptive Card you send and the Adaptive Card you receive in WebChat (when it doesn't work)?

Hello NickEricson,

There is no 2.5.1 Adaptive Card version, I could not find it in https://www.adaptivecards.io/designer/

The situation is 1.3 version adaptive card works fine in Bot Composer WebChat and Emulator but when I publish the same bot it does not work in the web channel and gives error as "The maximum supported version is 1.0"

I also add the screenshots.
![errorhtml](https://user-images.githubusercontent.com/28626390/117172380-70149080-add4-11eb-8ce6-42989be871bc.png)
![trueversionwebchat](https://user-images.githubusercontent.com/28626390/117172384-7145bd80-add4-11eb-9298-fcb6b33f059e.png)
![cannotrenderinwebchannel](https://user-images.githubusercontent.com/28626390/117172386-71de5400-add4-11eb-8f1b-05b8a96caaf5.png)




Here is the json format of the 1.3 version adaptive card which cannot be rendered with masking url data.

{
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
"type": "AdaptiveCard",
"version": "1.3",
"body": [
{
"type": "TextBlock",
"text": "Yurtiçi Üniversite Yerleşimi",
"weight": "Bolder",
"size": "ExtraLarge",
"spacing": "None",
"wrap": true,
"horizontalAlignment": "Center"
},
{
"type": "Image",
"url": "",
"horizontalAlignment": "Center",
"width": "0px"
},
{
"speak": "Yurtiçi detay",
"type": "ColumnSet",
"columns": [
{
"type": "Column",
"width": 2,
"items": [
{
"type": "TextBlock",
"text": "2020 yılı",
"wrap": true,
"fontType": "Monospace",
"size": "Small"
},
{
"type": "TextBlock",
"text": "Mezun öğrencilerimizin **115**'i toplamda **₺1.8M** değerinde burs kazandılar. Çeşitli üniversitelerden kabul alan öğrencilerimiz başta **Ekonomi** olmak üzere Mühendislik, Dil, Hukuk gibi bölümlerde eğitim hayatlarına devam edecekler.",
"size": "Small",
"wrap": true,
"maxLines": 4
}
]
}
]
}
],
"actions": [
{
"type": "Action.OpenUrl",
"title": "Yerleşilen üniversitelerle ilgili detaylı bilgi",
"url": "",
"style": "positive"
},
{
"type": "Action.OpenUrl",
"title": "Yurtiçi yerleşim oranları",
"url": "",
"style": "destructive"
}
]
}

**Comment by NickEricson** [comment]
@damlaalkan - We will make a change that may help you soon. What I believe is happening is that the DirectLine service is using an older version of Adaptive Cards. DirectLine processes the Adaptive Cards attached to messages and this processing can drop properties that exist in newer versions of Adaptive Cards.

We now support a feature, Schema Transformation Version, within bots.
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-channels?view=azure-bot-service-4.0#bot-schema-transformation-version
We will release a version 1.3 that remove much of the Adaptive Card processing which may leave the fields intact.

Additionally, webchat within the Azure portal is being updated. The version we host in the portal can be mismatched from the version used in, say, Composer.

Both of these changes _should_ go out next week.

**Comment by MichaelHaydenAtMicrosoft** [comment]
@NickEricson  @arturl  - checking to see if changes have been rolled out yet?

**Comment by NickEricson** [comment]
@damlaalkan We have releases version 1.3. You will need to update your bot (see the docs above) - please let us know if this resolves your issue.

**Comment by MichaelHaydenAtMicrosoft** [comment]
Closing issue. Please let us know if new information surfaces that would facilitate us investigating this issue further.
