### ISSUE TITLE
Autogenerated Azure SDKs use old Swagger Files

### ISSUE THREAD

**Issue by cleemullins** [microsoft/BotFramework-Services#295]
The .Net SDK for Azure uses a very old swagger file (from 2017) and needs to be updated:
* https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/botservice/Microsoft.Azure.Management.BotService/src/Generated/SdkInfo_AzureBotService.cs#L14
![image](https://user-images.githubusercontent.com/1165321/116746087-e5392d80-a9b0-11eb-9678-9a38465158b1.png)

The Python SDK for Azure uses an old swagger file (2020-06-02) and needs to be updated:
* https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/botservice/azure-mgmt-botservice/azure/mgmt/botservice/operations/_bot_connection_operations.py#L65

The Javascript SDK is the same as Python (2020-06-02):
* https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/botservice/arm-botservice/src/azureBotServiceContext.ts#L47

The GO SDK uses a version from 2018, issue is tracked here:
https://github.com/Azure/azure-sdk-for-go/issues/14627

The Java SDK doesn't appear to have this at all, and should. 

All of these can be updated via: 
* http://aka.ms/openapiportal

**Comment by MichaelHaydenAtMicrosoft** [comment]
@hailiu2586  - any updates here?

**Comment by hailiu2586** [comment]
The following PR and SDK release requests have been created/submitted

1. sdk-for-net: https://github.com/Azure/azure-sdk-for-net/pull/20955
2. sdk-for-js: https://github.com/Azure/azure-sdk-for-js/pull/15208
3. sdk-for-python: https://github.com/Azure/azure-sdk-for-python/pull/18615
4. sdk-for-java/ sdk-for-go: https://github.com/Azure/sdk-release-request/issues/1535

**Comment by MichaelHaydenAtMicrosoft** [comment]
Closing this ticket for now. Please reopen if the concern has not been addressed or resurfaces.
