### ISSUE TITLE
Sometimes the response is BadGateway but the messages have been sent to chat group

### ISSUE THREAD

**Issue by danghoanghai** [microsoft/BotFramework-Services#298]
I am using Bot Framework to send messages to chat groups. Sometimes, I got the issue that the results when I action send message to Azure response the **BadGateway** error, but the skype group received the messages.

I am using .NET Core 2.2 now.

**Comment by v-kydela** [comment]
Thank you for the report, @danghoanghai 

It sounds like you're saying you have a Skype bot and sometimes when the bot sends messages to Skype you see an error even though the messages are delivered successfully. Is that correct? Where are you seeing the error? Can you post screenshots?

I should warn you that Skype bots are deprecated and it's unlikely that you'll be able to find a solution to this problem

**Comment by danghoanghai** [comment]
> Thank you for the report, @danghoanghai
> 
> It sounds like you're saying you have a Skype bot and sometimes when the bot sends messages to Skype you see an error even though the messages are delivered successfully. Is that correct? Where are you seeing the error? Can you post screenshots?
> 
> I should warn you that Skype bots are deprecated and it's unlikely that you'll be able to find a solution to this problem

Thank you for the early response. I am using Try catch in my code and it's throwing an exception BadGateway. I usually get this exception before, but this case just appears about 2 weeks ago. Here is the exception I had captured.
![image](https://user-images.githubusercontent.com/18319715/117757455-58149500-b24a-11eb-99a5-380d3ffd2d8b.png)

**Comment by v-kydela** [comment]
@danghoanghai - Well I don't see any obvious reasons why you might be encountering this problem. Like I said, Skype bots have been deprecated for a while and you can't expect to get any official support for these kinds of problems. You could try debugging more on your own, but my recommendation is to switch to a supported platform like Microsoft Teams. I'll go ahead and close this now.
