### ISSUE TITLE
Slack Hero Buttons Clicks Do Not Include Original Message Text

### ISSUE THREAD

**Issue by haacked** [microsoft/BotFramework-Services#299]
Hi! I'm using the C# BotFramework 4.12.2. In the code sample below, I also use `Microsoft.Bot.Builder.Dialogs` 4.12.2 to generate the choice buttons.

Rendering the buttons (actually, Hero cards) works great! But when a user clicks on them...

```csharp
public class MetaBot : ActivityHandler
{
    protected override async Task OnMessageActivityAsync(
        ITurnContext<IMessageActivity> turnContext,
        CancellationToken cancellationToken)
    {
        if (turnContext.Activity.Text.EndsWith("test", StringComparison.Ordinal))
        {
            var reply = ChoiceFactory.ForChannel(
                turnContext.Activity.ChannelId,
                new List<Choice>
                {
                    new("Red"),
                    new("Blue"),
                    new("Green")
                },
                "choose a color!");
            reply.Text = "You have choices";
            await turnContext.SendActivityAsync(reply, cancellationToken);
            return;
        }

        if (turnContext.Activity.Text is "Red" or "Blue" or "Green")
        {
            var channelData = JsonConvert.SerializeObject(turnContext.Activity.ChannelData, Formatting.Indented);
            var reply = new Activity("message")
            {
                Text = $"You chose {turnContext.Activity.Text}\n\n{channelData}"
            };
            await turnContext.SendActivityAsync(reply, cancellationToken);
            return;
        }
    }
}
```

This is the response:

```json
You chose Blue
{
 "Payload": {
   "type": "interactive_message",
   "actions": [
     {
       "name": "imBack",
       "type": "button",
       "value": "Blue"
     }
   ],
   "callback_id": "REDACTED",
   "team": {
     "id": "T013108BYLS",
     "domain": "aseriousbiz"
   },
   "channel": {
     "id": "C01A3DGTSP9",
     "name": "abbot-dev-playground"
   },
   "user": {
     "id": "U012LKJFG0P",
     "name": "haacked"
   },
   "action_ts": "1620771671.767135",
   "message_ts": "1620771661.004500",
   "attachment_id": "2",
   "token": "REDACTED",
   "is_app_unfurl": false,
   "enterprise": null,
   "is_enterprise_install": false,
   "original_message": {
     "bot_id": "B014DK3ARS5",
     "type": "message",
     "text": "",
     "user": "U013U8MQV8W",
     "ts": "1620771661.004500",
     "team": "T013108BYLS",
     "bot_profile": {
       "id": "B014DK3ARS5",
       "deleted": false,
       "name": "Costello",
       "updated": 1620667675,
       "app_id": "A014QR5UQMN",
       "icons": {
         "image_36": "https://a.slack-edge.com/80588/img/plugins/app/bot_36.png",
         "image_48": "https://a.slack-edge.com/80588/img/plugins/app/bot_48.png",
         "image_72": "https://a.slack-edge.com/80588/img/plugins/app/service_72.png"
       },
       "team_id": "T013108BYLS"
     },
     "attachments": [
       {
         "callback_id": "REDACTED",
         "text": "choose a color!",
         "id": 1,
         "fallback": "choose a color!"
       },
       {
         "callback_id": "B014DK3ARS5:T013108BYLS",
         "id": 2,
         "actions": [
           {
             "id": "1",
             "name": "imBack",
             "text": "Red",
             "type": "button",
             "value": "Red",
             "style": "default"
           },
           {
             "id": "2",
             "name": "imBack",
             "text": "Blue",
             "type": "button",
             "value": "Blue",
             "style": "default"
           },
           {
             "id": "3",
             "name": "imBack",
             "text": "Green",
             "type": "button",
             "value": "Green",
             "style": "default"
           }
         ],
         "fallback": "[no preview available]"
       }
     ]
   },
   "response_url": "https://hooks.slack.com/actions/REDACTED",
   "trigger_id": "REDACTED"
 },
 "ApiToken": "REDACTED"
}
```

If you look at the `original_message`, you can see that the text is blank. According to the [Slack docs](https://api.slack.com/reference/interaction-payloads/block-actions) there should be a `message` property of the Block Actions Payload that contains the full state of the message.

Wasn't sure if this was a bug in the Bot Framework Service or the Bot Framework. We are using the Azure Bot Service for our bot. Thanks!

**Comment by haacked** [comment]
Also, the `replyToId` is null. It'd be nice if that were set to the message. I'm trying to match up the click with the message that the click corresponds to.

**Comment by haacked** [comment]
Ok, I think I figured out why. I have a middleware that sets the outgoing `ChannelData.Text` property to `turnContext.Activity.Text` and then sets `turnContext.Activity.Text` to `null`. The reason for this is we wanted the `<@SlackUserId>` formatting to work, which didn't work when setting `turnContext.Activity.Text`.

Any ideas how I can work around that?

**Comment by v-kydela** [comment]
Thank you for the report, @haacked 

It sounds like you're saying you no longer think there's a bug, but you're encountering a problem based on your own middleware. What is the problem, and what are you trying to do? Can you post screenshots, links, etc.?

**Comment by haacked** [comment]
@v-kydela Yeah. The above code is the repro. The only thing its missing is I also have middleware that does the following (pseudocode).

```csharp
public class SlackMiddleware : IMiddleware
{
    public async Task OnTurnAsync(
        ITurnContext turnContext,
        NextDelegate next,
        CancellationToken cancellationToken = new CancellationToken())
    {
        turnContext.OnSendActivities(async (_, activities, nextSend) =>
        {
            foreach (var activity in activities)
            {
                var channelId = activity.ChannelId ?? string.Empty;
                if (channelId is "slack")
                {
                    activity.ChannelData = new SlackOutgoingChannelData
                    {
                        Text = activity.Text
                    };
                    activity.Text = null;
                }
            }

            // run full pipeline
            return await nextSend().ConfigureAwait(false);
        });
        
        // process bot logic
        await next(cancellationToken).ConfigureAwait(false);
    }
}
```

Even though I set the `Activity.Text` to null, I expected that when the user clicked the button, all the info Bot Framework needs to populate the original message would be there. Does that make sense?

**Comment by v-kydela** [comment]
@haacked - There's still a lot of missing information about your problem and it sounds like you don't know how to get us on the same page as you. Maybe I can ask some guiding questions that will help.

Your middleware is taking the activity text and putting it in the activity channel data instead. The channel data has the same effect on Slack as the text would because the Slack connector uses the activity's channel data to populate the Slack message in the same way that it would use the activity's text if it was there. Therefore, the text you're putting in channel data ends up getting rendered in Slack. Is that correct?

I'm not understanding why you're doing this. You say:

> The reason for this is we wanted the `<@SlackUserId>` formatting to work, which didn't work when setting `turnContext.Activity.Text`.

What does that mean? Can you elaborate and post screenshots?

What happens if you populate both the channel data and the text? Does that serve the purpose you're trying to serve?

Have you tried using the [`TextFormat`](https://docs.microsoft.com/dotnet/api/microsoft.bot.schema.activity.textformat#Microsoft_Bot_Schema_Activity_TextFormat) property?

What specific text are you expecting to populate the original message? Can you post a screenshot of a message with that text and the buttons that aren't returning the text?

Slack makes it easy to see where one message ends and the next begins because the messages become highlighted when you mouse over them. Have you confirmed that the text you're expecting to be included in the original message is actually part of the same message as the buttons? Can you show that in a screenshot of the message where you're highlighting it with your mouse?

Also, it sounds like you're saying you expect your hero cards to be rendered using blocks, but blocks are a newer Slack schema that replaces an [old one](https://api.slack.com/legacy/message-buttons). Are you sure your buttons are rendered in blocks?

**Comment by haacked** [comment]
> I'm not understanding why you're doing this. You say:

I misspoke. The reason we're using the channel data for the Text is because we want to support Slack stye markdown in our responses. We only do this for the Slack channel. For example, two differences are:

```
Slack code: `code`
Bot Framework code: \`code\`
Slack newline: \n
Bot Framework newline: \n\n
```

> What happens if you populate both the channel data and the text? Does that serve the purpose you're trying to serve?

No, if the `Text` property is set on `Activity` AND it's set on `ChannelData`, they both are sent to the response. This is not the behavior I expected. Is that by design?

**Comment by v-kydela** [comment]
@haacked - The behavior of the connector services is somewhat complicated, but I presume that's by design. Thank you for the information so far. Do you think you might be able to answer the rest of my questions? I need to have a good idea of what's happening in order to help

**Comment by haacked** [comment]
> The behavior of the connector services is somewhat complicated, but I presume that's by design.

Ah, that might explain it then. If that's by design, can you help me understand why? I feel like my mental model of ChannelData must be incorrect. It is surprising to me that if both the `IMessageActivity.Text` AND `ChannelData.Text` are set, that I get two messages.

> I need to have a good idea of what's happening in order to help

Sure! I set up a simpler example.

Here's my bot code.

```csharp
public class MyBot : ActivityHandler
{ 
    protected override async Task OnMessageActivityAsync(
        ITurnContext<IMessageActivity> turnContext,
        CancellationToken cancellationToken)
    {
        var activity = turnContext.Activity;
        if (activity.Text.EndsWith("test", StringComparison.InvariantCultureIgnoreCase))
        {
            var heroCard = new HeroCard
            {
                Buttons = new List<CardAction>
                {
                    new(ActionTypes.ImBack)
                    {
                        Title = "Cup 1",
                        DisplayText = "You chose Cup1",
                        Value = "cup1"
                    },
                    new(ActionTypes.ImBack)
                    {
                        Title = "Cup 2",
                        DisplayText = "You chose Cup2",
                        Value = "cup2"
                    }
                }
            };
            var response = MessageFactory.Text("Choose wisely");
            response.Attachments.Add(heroCard.ToAttachment());
            await turnContext.SendActivityAsync(response, cancellationToken);
            return;
        }
        
        // Handle user click
        var original = turnContext.Activity.ChannelData.Payload.original_message.text;
        await turnContext.SendActivityAsync(MessageFactory.Text($"Original Message was: {original}"), cancellationToken);
    }
}
```

## Test Case 1

I don't have any middleware set up in this example.
And here's a screenshot of interacting with it in Slack.

<img width="422" alt="Screen Shot 2021-05-14 at 9 58 30 AM" src="https://user-images.githubusercontent.com/19977/118304518-9c4aa400-b49b-11eb-8f05-6aa92dfe54d9.png">

As you can see, everything works fine. I click the button and I'm able to get the original message from the `ChannelData Payload`.

## Test Case 2

Ok, now I'll set up the same middleware I posted above where I set `IMessageActivity.Text` to null because I'm using the `ChannelData.Text` to send a message to slack instead.

<img width="479" alt="Screen Shot 2021-05-14 at 9 59 45 AM" src="https://user-images.githubusercontent.com/19977/118304775-f51a3c80-b49b-11eb-8e13-a483cb2ea9a0.png">

As you can see, when I click the button, I expected to be able to retrieve the original message, but I got nothing.

It seems to me that something got lost into the translation when posting the message to Slack. The reason I expected the original message to be there is even though I set `IMessageActivity.Text` to null, I _did_ set the text of the message in the ChannelData. And I know that Slack is getting that message. So I expected that when slack responded to the event, the original message would be populated just fine. But since it's not, I'm guessing that Azure Bot Service is doing something in between.

Does this all make sense now?

**Comment by v-kydela** [comment]
@haacked 

> Ah, that might explain it then. If that's by design, can you help me understand why? I feel like my mental model of ChannelData must be incorrect. It is surprising to me that if both the `IMessageActivity.Text` AND `ChannelData.Text` are set, that I get two messages.

Think of it like this. Suppose `IMessageActivity.Text` and `ChannelData.Text` contain two different values. If the Slack connector was only supposed to display one of them as a message, how would it know which one to display?

> Does this all make sense now?

It generally makes sense, but there's still some important information I need in order to diagnose the problem. It was good of you to provide screenshots, but they don't show you highlighting the messages with the mouse like I asked so I can't tell where the break between messages is. However, I think I can detect a very slight difference in the vertical space between "Choose wisely" and the buttons, so I suspect that means my hunch about them being separate messages is correct.

When I said "I need to have a good idea of what's happening in order to help," that was directly referring to my need for you to answer my questions. Are you able to see the questions in this comment? https://github.com/microsoft/BotFramework-Services/issues/299#issuecomment-840098796

Would you be more comfortable if I asked one question at a time?

**Comment by haacked** [comment]
> Think of it like this. Suppose `IMessageActivity.Text` and `ChannelData.Text` contain two different values. If the Slack connector was only supposed to display one of them as a message, how would it know which one to display?

Well my original mental model was that the `ChannelData` represented the final form of the JSON that would get posted to the Slack API in order to send a message. So if both were set, `ChannelData` would win.  But now I can see my mental model is incorrect. It looks like they are effectively two different messages sent to Slack. And that matches up with your hunch:

> so I suspect that means my hunch about them being separate messages is correct.

I think this also explains the behavior I'm getting. Since the buttons are part of an attachment set on `IMessageActivity`, but the text is set on `ChannelData`, they are sent as two different messages. So there's no way a click on the button could have the original message.

Thanks for your help in this! I'll close it unless you think my conclusion is incorrect. 😄
