### ISSUE TITLE
Bot does not respond in Teams Free but works in Teams (paid service) 

### ISSUE THREAD

**Issue by desflan** [Microsoft/BotFramework-Services#3]
**Bot Info**
- SDK Platform: .NET
- SDK Version: 3.16.0.38344
- Active Channels: MS Teams (paid & free), Skype
- Deployment Environment: Azure Bot Service
- Bot name: blueybot
- App ID: 86a089d9-add4-4b71-9466-afb23474ccec

**Issue Description**

This issue was originally opened & assigned in previous V3 repo [here](https://github.com/Microsoft/BotBuilder/issues/5022)

My simple bot receives messages & replies with text. I have published it to Microsoft Teams (paid service) & Microsoft Teams FREE using the "upload a custom app" link. The scope in manifest.json is both "team" and "personal". The manifest.json was created in Teams App Studio. 

In Teams FREE - When I send a message to the bot in a team using @mention, it does not reply.
In Teams FREE -When I send a message to the bot in a personal 1:1 chat, it does not reply. This had worked a few hours ago, with no app changes made since.

In Microsoft Teams (paid service) the bot works perfectly in both a team channel & 1:1 personal chat.
In Skype, the bot works perfectly also.

The same Manifest.json was upload to Teams FREE and Teams (paid service).

In Azure Portal Bot Channel Registration, no issues are reported for Microsoft Teams channel.

**Code Example**
No code to share. Regular code that compiles and runs fine in Skype and paid version of MS Teams

**Expected Behavior**
In Microsoft Teams FREE I expected to receive replies from the bot in both a team channel & 1:1 chat

**Actual Results**
In Microsoft Teams FREE there are no message received from the bot in a team channel or a 1:1 chat.
Tried remote debugging using VS and no message received by the bot.

**Comment by jwiley84** [comment]
Hi @desflan! Just wanted to let you know I haven't forgotten about you! I have been able to replicate this (bots loaded in Free Teams does not respond, at all). I'm working on tracking down a reason and solution.

**Comment by desflan** [comment]
thank you @jwiley84

**Comment by billbliss** [comment]
@desflan - Bill from the Microsoft Teams team here. We think we know what's happening but want to verify. Can you get the conversationId from a conversation between your bot and the paid version of Teams, i.e. where it works? You have to stop it in the debugger or log it, but judging from the above I think you're familiar with that.

**Comment by desflan** [comment]
@billbliss conversationId from a conversation between my bot and the paid version of Teams where it works is as follows:
"19:79f4d148bf364737800f534db916f313@thread.skype;messageid=1540924083460"

**Comment by CoHealer** [comment]
@billbliss, any word on the verification?

**Comment by mhodovaniuk** [comment]
@Wajeed-msft , I am facing a similar issue: my bot receives messages from the Web Chat, but I am not able to receive messages from the MS Teams. I have started a conversation with a new user, but still, it does not work. For some reason, I was able to get a message yesterday, but today it doesn't work again. My app id is e2d829d8-7698-4c9f-86e0-4481798d2f28. This is self-hosted bot.

**Comment by desflan** [comment]
@Wajeed-msft I can no longer repro this issue, it seems to have been fixed....was there a setting on the bot side that I missed? Thanks for resolving.

**Comment by CoHealer** [comment]
Removed bot support team from assignment as the issue appears to have been resolved server side in Teams

**Comment by EricDahlvang** [comment]
Closing, since this issue has been resolved.
