### ISSUE TITLE
Hero card is not displaying within Skype for Business

### ISSUE THREAD

**Issue by Falansh** [Microsoft/BotFramework-Services#30]
We have added Skype for Business as new channel for our bot and somehow it is not displaying the hero card. Same hero card works in MS teams channel. We tried to change hero card to thumbnail card as well, but still no luck.

**Comment by stevkan** [comment]
@Falansh, unfortunately the hero card is not supported in Skype for Business. Many features are channel specific. While they may work in one environment, they may not in another. Hence, the hero card working in Teams.

**Comment by Falansh** [comment]
@stevkan thanks for the reply.
Can you please suggest what else can be used in place of hero card in skype for business channel. I need something to give users choices and to select one of them and based on that perform an action.

https://docs.botframework.com/en-us/channel-inspector/channels/SkypeForBusiness?f=HeroCard&e=example1
Also can you check this channel inspector link, it suggests hero card works in Skype for Business channel.
![image](https://user-images.githubusercontent.com/36635284/49674243-2d1a2b80-fa69-11e8-9a8b-e6871f038072.png)

**Comment by EricDahlvang** [comment]
@Falansh The Skype for Business client and version are also pertinent to the level of card support (not all clients and versions provide the same features).

**Comment by Falansh** [comment]
@EricDahlvang Thanks for the reply. Can you please tell which skype for business client version supports card.

**Comment by EricDahlvang** [comment]
I'm sorry, but I'm not aware of any Skype for Business clients that actually support cards, as stated here: https://docs.microsoft.com/en-us/skype-sdk/skype-for-business-bot-framework/docs/overview#feature-support

> Cards and buttons: Skype for Business does not support rendering cards and buttons. The cards and buttons sent by a bot will fall back to text in the Skype for Business clients.
