### ISSUE TITLE
Adaptive Card 1.4 Support for Directline channel

### ISSUE THREAD

**Issue by harshithkashyap** [microsoft/BotFramework-Services#300]
## Version
BotbuilderJS - 4.13.2

## Describe the bug
The latest release of the [Adaptive Cards](https://github.com/microsoft/AdaptiveCards/releases/tag/21.03) package has enabled support for Action.Execute type with Adaptive Card Version 1.4. This is currently working with Teams bot when sending an 1.4 AC using the directline channel results in _We're sorry, this card couldn't be displayed_ card to be displayed. The frontend client has the latest adaptive cards package and I've verified the directline websocket stream which seems to convert the 1.4 AC into a card with the above message.

## To Reproduce
1. Create a Directline Bot.
2. Use WebChat or any other client which uses Directline on the frontend.
3. Send any AC with version 1.4 from the backend.

## Expected behavior
Any AC with version 1.4 is expected to reach the client through the directline channel.

## Screenshots
![image](https://user-images.githubusercontent.com/4183260/118162354-44318480-b43e-11eb-8c2f-70c1d36e71e4.png)

![image](https://user-images.githubusercontent.com/4183260/118161754-9625da80-b43d-11eb-8cac-e71390e0cbe2.png)

**Comment by tdurnford** [comment]
@dandriscoll Can you chime in on this?

**Comment by harshithkashyap** [comment]
@tdurnford @dandriscoll I went through #87 and it seems like there still is no permanent fix for this and it wasn't clear from the directline team why they need to serialize the AC sent by the customer. #87 seems to have taken almost 5 months to get a new version of AC out. I'm trying to use `Action.Execute` from AC as we have bots deployed to Directline as well as Teams and would prefer to avoid the suggested workaround. This is going to be a common ask. The Directline would always endup being out of sync with the latest AC releases if the DIrectline and AC release cycles are out of sync and it's really best to let the AC JSON pass through.

**Comment by harshithkashyap** [comment]
@tdurnford Adding a little more context into this, we're a multi-tenant bot and we let our customers configure messages or responses they send back proactively. When we receive a response from the customer to the bot, we deliver the response as it is to the end bot user. It's going to end up requiring us to add the middleware both on frontend as well as backend to specify the AC contentType, check the AC version to see if it needs a custom type and perform a channel check for the DL. While it can be done, it's not a clean solution.

**Comment by DDEfromOR** [comment]
We have roadmap items for upgrading the AC packages in DirectLine to 1.4, and for enabling support for the inline responses required by the Action.Execute schema, but no firm ETA. Having this customer request will help bump the priority of those changes, so thank you for opening the issue. 

I think WebChat will also need updates to support the Action.Execute model, but @compulim  would be the expert there.

**Comment by MichaelHaydenAtMicrosoft** [comment]
@harshithkashyap @compulim - do we have anything else to add here? Please let me know if the provided information on our roadmap will suffice for now.

**Comment by compulim** [comment]
In the next release of Web Chat (4.14.0), we will bump to AC renderer 2.9, which will support AC schema 1.4. It should unblock this issue. Link to the merged pull request, https://github.com/microsoft/BotFramework-WebChat/pull/3846.

The change is currently live in our dev branch, https://github.com/microsoft/BotFramework-WebChat/releases/tag/daily.

However, our PM is working on a plan to enable a new feature we benefit from AC schema 1.4, namely "Action.Execute". The work can be tracked in this issue, https://github.com/microsoft/BotFramework-WebChat/issues/3844.

**Comment by MichaelHaydenAtMicrosoft** [comment]
Thanks @compulim ! I am going to close this issue for now.
