### ISSUE TITLE
REST API links broken

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Services#305]
Originally reported by @jmnsf in bot-docs [issue 2044](https://github.com/MicrosoftDocs/bot-docs/issues/2044)

> Previously-working links are now broken and redirect to https://docs.microsoft.com/en-us/azure/bot-service/?view=azure-bot-service-4.0
>
> For example:
> * https://docs.botframework.com/en-us/restapi/connector/#!/Conversations/Conversations_GetActivityMembers
>
> What's worse the new page has absolutely no pointers to the REST API, so I had to go around digging for them again. For anyone reading this with the same issue, they're here: https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-overview?view=azure-bot-service-4.0
>
> One would expect there to be a redirect in place. Even if the anchors stop working, at least you're not stuck looking at a mostly unrelated page.

**Comment by MichaelHaydenAtMicrosoft** [comment]
Upon further investigation, this appears to be a case of broken “bookmark”, where somebody saved a link somewhere (internal docs in this case) and we moved the doc. 
 
Docs team is in the process of investigating the redirect file for this.

Other than that, I’m not sure we can do anything about this.
