### ISSUE TITLE
{"code":"ResourceNotFound","message":"/ does not exist"}

### ISSUE THREAD

**Issue by najwachehaibi** [microsoft/BotFramework-Services#306]
please how can i fix this issue?

**Comment by dmvtech** [comment]
Hi @najwachehaibi Can you please give more information? Where are you getting this error? What were you doing when it happened?

**Comment by dmvtech** [comment]
Hi @najwachehaibi Are you still having this issue? Any more information you can give us?

**Comment by MichaelHaydenAtMicrosoft** [comment]
Closing due to lack of response. Please reopen if you need us to investigate further.
