### ISSUE TITLE
Icon for Azure Bot is using the wrong blue 

### ISSUE THREAD

**Issue by mareekuh** [microsoft/BotFramework-Services#307]
Background of Azure bot Icon is wrong blue
Please fix to be the following Azure blue :  HEX 0078D4

<img width="766" alt="Screen Shot 2021-06-21 at 11 07 50 AM" src="https://user-images.githubusercontent.com/48503434/122807970-16cbc800-d281-11eb-8a89-c8d0b2a655c3.png">

(Already filed months ago in ADO but not yet fixed)

**Comment by Andrea-Orimoto** [comment]
Tracking this in ADO, we don't need this additional issue here. 
https://fuselabs.visualstudio.com/BotFramework/_workitems/edit/60336
