### ISSUE TITLE
Slack DeliveryMode = Ephemeral does not work (again)

### ISSUE THREAD

**Issue by dulfe** [microsoft/BotFramework-Services#308]
I am reporting this issue again because the first time I did it was merged with another one but never fixed.

Issue microsoft/botbuilder-dotnet#5604 was merged with microsoft/botbuilder-dotnet#5602 and closed, but the solution for microsoft/botbuilder-dotnet#5602 (Commit microsoft/botbuilder-dotnet#5665) only fixed one issue.

`DeliveryMode = Ephemeral` still does not send an "ephemeral" message.

I might be misunderstanding how DeliveryMode works, but if I am, What is it for?

_**I apologize for "opening" a new ticket, but I was unsure if "closed" reports were monitored.**_

### Steps to reproduce the behavior:
```c#
      var reply=MessageFactory.Text("text");
      reply.DeliveryMode = DeliveryModes.Ephemeral;

      await turnContext.SendActivityAsync(reply, cancellationToken);
```

### Current behavior

Slack receives the message, but as "normal" instead of "ephemeral".

### Expected behavior

The message should be ephemeral. (visible only to the user)

**Comment by arturl** [comment]
This issue is still on our backlog.

**Comment by ssss141414** [comment]
In progress.

**Comment by ssss141414** [comment]
PR merged. Will come to prod in a week.

**Comment by ssss141414** [comment]
Hi @stevkan ,
The feature is onboard. Please have a try with: 
```
activity.DeliveryMode = DeliveryModes.Ephemeral;
```

Screen shot:
![image](https://user-images.githubusercontent.com/18118994/153838137-74df7572-3a66-4a8f-91d6-69929d9df6fb.png)

**Comment by bobokids** [comment]
Fix released in 2/14.
