### ISSUE TITLE
Bot created in Composer doesn't show 'Open In Composer' in Azure

### ISSUE THREAD

**Issue by xieofxie** [microsoft/BotFramework-Services#313]
## Describe the bug

![image](https://user-images.githubusercontent.com/2876650/127284082-88d96cb5-4bf4-4536-b9c0-6d7787a44d59.png)

should be:

![image](https://user-images.githubusercontent.com/2876650/127284064-e842f370-fff0-4b6e-bef2-9f71787edabe.png)

## Browser

- [ ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ ] Windows
- [ ] Ubuntu

**Comment by hailiu2586** [comment]
@cwhitten @luhan2017 do we know whether composer created bot has  "openWithHint" set for "azurebot"? Could you provide a point to the composer code where the property is being set before the request is sent? thanks

**Comment by hailiu2586** [comment]
@swagatmishra2007 do you know why JS SDK uses https://github.com/Azure/azure-sdk-for-js/blob/33602ffe73abe54cf4c4e232ee60057d0ab3395e/sdk/botservice/arm-botservice/src/models/mappers.ts#L106 to only allow known property names?

**Comment by hailiu2586** [comment]
I have created  PR https://github.com/Azure/azure-rest-api-specs/pull/15456/files  add the properties to the swagger spec. Once that is published, and when the new JS SDK gets AutoRest generated. The composer can take on the new JS SDK to get the property set. If the composer wants to make the scenario work without waiting, it can issue direct ARM REST PUT on the bot to patch the properties.

**Comment by luhan2017** [comment]
https://github.com/microsoft/BotFramework-Composer/search?q=openWithHint&type=code here is the composer code for openWithHint.

**Comment by dudeed** [comment]
Hai's PR needs to get reviewed and checked in for this to be fixed.

**Comment by luhan2017** [comment]
Hai's PR just got merged, and I submitted api release request. I will update the package version in composer when the release is done. @MichaelHaydenAtMicrosoft

**Comment by luhan2017** [comment]
The package is already released, @zhixzhan, could you help create a PR in composer to update to the new version? https://www.npmjs.com/package/@azure/arm-botservice/v/3.1.0
