### ISSUE TITLE
ConversationParameters object needed to create conversation in Bot Service email channel

### ISSUE THREAD

**Issue by Bolleman** [microsoft/BotFramework-Services#317]
I can't find any documentation on what the [ConversationParameters](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#conversationparameters-object) object needs to look like in order to use the Bot Service [Create Conversation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#create-conversation) with an email channel.  Documentation says that the ChannelData object needs to be a "Channel-specific payload for creating the conversation.", but I'm guessing this is something other than the typical email channelData which is part of the activity object (which I've tried).  As an example, I figured out through trial and error that in the case of a Teams channel, the ConversationParameters object needs to be: 
` {
                "activity": {
                  "text": "some message",
                  "type": "message"
                },
                "channelData": {
                  "channel": {
                    "id": "<teamsChannelId>"
                  }
                },
                "isGroup": true
              }
`
If someone has a similar example of one that works for creating an email conversation that would be awesome, thanks!

**Comment by Jeffders** [comment]
To proactively create conversations in the bot to send email to a user, you'll want to use these fields on the ConversationParameter object:

For the email channel, the fields that are used by this API call are:
```
{
    "activity": { "text": "some message", "type": "message" },
    "members": [
        { "id": "...email address...", "name": "... friendly name..." }
    ]
} 
```

**Comment by Bolleman** [comment]
Thanks for the quick response @Jeffders!  

Your exact payload (except with a real email address) generated the following error:  
`
    "code": "MissingProperty",
    "message": "'bot' is required"
`  

However, the error message was nice and specific, so I just added the bot property according to the [docs](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#conversationparameters-object) and it worked great.  The entire working payload ended up being as follows, for anyone else trying to do the same thing: 
```
{
    "bot": {
      "aadObjectId": "e283adf........",
      "id": "bot@wni.app",
      "name": "WNI Bot",
      "role": "bot"
    },
    "activity": {
      "text": "some message",
      "type": "message"
    },
    "members": [
      {
        "id": "brent@wni.app",
        "name": "Brent Email"
      }
    ]
  }
```
That just saved me a huge amount of time, I really appreciate the help.

**Comment by MichaelHaydenAtMicrosoft** [comment]
Great work, @Jeffders!! 
@Bolleman - is there anything further you may need here or can we close this issue?

**Comment by Bolleman** [comment]
@MichaelHaydenAtMicrosoft Oh yes, my bad, I should have closed.  Thanks again.
