### ISSUE TITLE
Please add support for the Slack `bot_changed` event

### ISSUE THREAD

**Issue by haacked** [microsoft/BotFramework-Services#323]
Related to #262

It appears that the [`bot_changed`](https://api.slack.com/events/bot_changed) event is not forwarded by Azure Bot Service to my bot.

In Slack, a user can change the Bot Username in the App configuration page as shown in the screenshot.

<img width="794" alt="Slack App configuration page where the bot username was changed" src="https://user-images.githubusercontent.com/19977/142741433-d23902fc-8ff6-4345-9646-0724db72ad05.png">

It's important for us to know what this name is when the user changes it.

**Comment by haacked** [comment]
It may be that the `user_change` event is raised when this changes, but I'm not getting that from Bot Service either.

**Comment by ToddN** [comment]
Thanks for your request. We are evaluating it.

**Comment by ssss141414** [comment]
Hi @haacked ,
It seems Bot User is a legacy feature: https://api.slack.com/legacy/custom-integrations/bot-users. Also I cannot find it anywhere in my App Configuration.
![image](https://user-images.githubusercontent.com/18118994/150499649-68d881b8-5bd2-4223-ab7c-8483ee9e5cec.png)

If I misunderstand the feature, please provide the detailed repro steps. Thank you very much.

**Comment by bobokids** [comment]
We have no plan to support the feature as it's  deprecated in Slack.
