### ISSUE TITLE
List of bots not appearing on dev.botframework.com

### ISSUE THREAD

**Issue by MasonStricklin** [microsoft/BotFramework-Services#324]
# Version

Not using sdk

# Describe the bug

Hello,

I believe I ran into a similar issue as https://github.com/microsoft/BotFramework-Services/issues/248. 

When I login to dev.botframework.com and navigate to my list of bots, none of my bots appear.

# Expected behavior

I expect 3 bots to appear in this list: 1) the production bot (in below screenshot), 2) a staging version of the bot, and 3) a local development version of the bot

# Screenshots

<img width="894" alt="Screen Shot 2021-12-08 at 12 04 24 PM" src="https://user-images.githubusercontent.com/8322505/145276703-c33730ad-7c2a-402c-977e-cb61b19b1e00.png">

^ One of the bots that doesn't appear dev.botframework.com

<img width="1277" alt="Screen Shot 2021-12-08 at 12 08 30 PM" src="https://user-images.githubusercontent.com/8322505/145277079-9168280c-29f4-4ff6-a2f6-dafba57b39e9.png">

^ What I see when I navigate to "My bots" on dev.botframework.com

# Additional context

Just like in the above github issue I linked to, our bot is still functional and sending messages.

**Comment by mgbennet** [comment]
What are the bot Ids of the bots you're expecting to see? Also, is the account you're logging in to the dev portal tied to the email address of your github account or a different email address?

**Comment by MasonStricklin** [comment]
Here are the 3 bot ID's. I took these from their manifest files.

1) Local development bot ID: `f90d1293-c2c9-493a-9b6b-a9a4146a58f6`
2) Staging bot ID: `4a5b685b-8fb3-4952-bb68-b299a422a85e`
3) Production bot ID: `2c951ed5-c5c6-493f-9b02-4b42e3ba536c`

As for the email, yes it's different than my github email. The email address I use to log into the bot framework is "operations@qualified.com".

Thanks for taking a look at this issue, I appreciate it.

**Comment by mgbennet** [comment]
I've confirmed that those bots are owned by that email address. Are you certain that you're logged in with the account tied to that email address? You can check by clicking on the box to the right of the notification bell at the top of the page.

**Comment by MasonStricklin** [comment]
> I've confirmed that those bots are owned by that email address.

Thanks for confirming.

> Are you certain that you're logged in with the account tied to that email address? You can check by clicking on the box to the right of the notification bell at the top of the page.

Yeah, I am sure that I am logged into the operations@qualified.com email address. Here's a screenshot:

![Screen Shot 2021-12-14 at 12 44 27 PM](https://user-images.githubusercontent.com/8322505/146076672-19fd8422-2dc8-49e9-bd83-696c527d0dd3.png)

---

Furthermore, if I navigate to https://dev.botframework.com/bots/new (while logged in as operations@qualified.com) and create a new bot, even that newly created bot does not appear for me. Here are some screenshots of this process:

1) I navigate to https://dev.botframework.com/bots/new and fill out the form. The App ID used in the below screenshot is: "7fc1c850-5fb7-4677-a0d1-8140ed8ca4db"

![Screen Shot 2021-12-14 at 12 43 30 PM](https://user-images.githubusercontent.com/8322505/146077015-e506aecd-7708-42af-8752-e6068d18e5a2.png)

2) I click the blue "Register" button at the bottom and see a popover message that says "Bot created":

![Screen Shot 2021-12-14 at 12 43 41 PM](https://user-images.githubusercontent.com/8322505/146077238-f5a01b04-d563-457e-9a25-6406357b7409.png)

3) I click "ok" in the above prompt, and then I see this error message: "Unable to find the bot with the specific id."

![Screen Shot 2021-12-14 at 12 43 59 PM](https://user-images.githubusercontent.com/8322505/146077318-b4401a7f-dbeb-4d8a-ae81-980ef27f5a0a.png)

4) I click on the blue "ok" button on this error message popover. Then I'm brought back to the "My Bots" page and I don't see any bots (including the old bots and the bot I just created:

![Screen Shot 2021-12-14 at 12 44 19 PM](https://user-images.githubusercontent.com/8322505/146077464-554437d9-e904-4731-851c-411445d6e9d5.png)

**Comment by dudeed** [comment]
Thank you for the information requested Mason, we will get back after analyzing it.

**Comment by MasonStricklin** [comment]
Hello, checking in to see if there are any updates?

**Comment by mgbennet** [comment]
@MasonStricklin We're still a bit stuck on this what's going on here. Couple things to check with you:
1) Were you able to see the bots with this account at an earlier time?
2) Do you happen to know if that account's user type is "guest" on the AD tenant? This can happen if the account is invited to the tenant.
3) If you can, can you collect a .har file of logging in from at https://dev.botframework.com/bots in an incognito window? Rather than posting it here, you should send to me at mibenne at microsoft.com.

**Comment by bobokids** [comment]
Hi @MasonStricklin, any update on this issue?

**Comment by MasonStricklin** [comment]
Hello, thanks for the bump and sorry for the delay. I have been traveling and wasn't able to respond. Here are my responses to the questions @mgbennet asked.

>Were you able to see the bots with this account at an earlier time?

Yes. The last time I logged in and accessed these configurations was mid-2021.

>Do you happen to know if that account's user type is "guest" on the AD tenant? This can happen if the account is invited to the tenant.

I don't think that is the case. This is the only account I see in our directory. The user type is listed as `Member`.

>If you can, can you collect a .har file of logging in from at https://dev.botframework.com/bots in an incognito window? Rather than posting it here, you should send to me at mibenne at microsoft.com.

I saved a .har file and sent it to the email address you provided. The email subject is "Mason Stricklin - Login .har file".

**Comment by MasonStricklin** [comment]
Hello, checking in again. @mgbennet, have you had a chance to review the email I sent you?

I am still at a point where I don't _need_ to access these bots. However, I'd love to regain access before anything arises that would require access.

**Comment by MasonStricklin** [comment]
Also, I filed an issue here, because I saw #248 was similar to my problem and you were able to help this user out. If there is another Github project or another way to file this issue with Microsoft, I can followup there too.

**Comment by MasonStricklin** [comment]
Hi again, bumping to ask if there are any updates. Thanks!

**Comment by dudeed** [comment]
Mike, can you reply to Mason, or have someone in STCA attach to this issue on Github to make progress?

**Comment by MasonStricklin** [comment]
Hello, checking in again. It's been almost a month since my last bump. Any update?

Is there another org I can reach out to who might be able to help? Or am I correct in that this is the right place to report this sort of issue?

**Comment by dudeed** [comment]
I am on another team now, and Mike will have to suggest others to include on this thread.

@Mike ***@***.***>, how is this issue going and is there anyone else who should be added to it now?

**Comment by MasonStricklin** [comment]
Hello all,

I ended up signing up for an Azure support subscription and filing a bug within Azure. 

A hotfix was released, and it looks like I am able to once again access these bots in the Bot Framework portal. I will close this issue.

Screenshot:
![Screen Shot 2022-05-17 at 12 59 23 PM](https://user-images.githubusercontent.com/8322505/168912297-dfcf914e-c45c-41fa-b61a-a31a5166243f.png)

**Comment by dweeb1937** [comment]
Did they give any indication of what the cause was? I'm having a similar issue. 
Similar? It does show bots, but long deleted ones, and none of the current ones. If I paste a current bot ID after the ?id= I get "Unable to find the bot with the specified ID".

**Comment by MasonStricklin** [comment]
Here was their exact description of the problem:

>I was able to get more clarification on this and it is your account in the Microsoft tenant that is the issue. Your account is also in your own tenant which is the one that you use to access your Azure subscription and that is showing up as a member. The account is in both tenants but since it’s a guest in the Microsoft tenant, that is causing the problem per our engineering team. We have 2 options for you. There is a hotfix that is scheduled to roll out in a couple weeks (around May 14) that should address this issue if you can wait for that or you can proceed with removing your account from the Microsoft tenant following the instructions below.

I wasn't quite sure what to make of this. Since they had a hotfix, I simply waited until it was released and no further action was required on my end.

Your situation sounds somewhat different. Might be worth re-opening this issue, opening a new issue, or reaching out to Azure support.

**Comment by BashitaliShaikh** [comment]
I too having the same issue please guide me how to solve this error. ASAP 
![IMG_20240327_101628](https://github.com/microsoft/BotFramework-Services/assets/60057901/b11cccfa-fd36-40ef-b133-b047e886f922)

@MasonStricklin @mgbennet
