### ISSUE TITLE
"Sign In code was not found or expired"

### ISSUE THREAD

**Issue by rodriguesnich** [microsoft/BotFramework-Services#329]
# Describe the bug
After the bot asks to sign in if the action isn't completed for a while when trying to sign in again:
"The Sign In code was not found or expired. Please try asking the bot to sign in again".

# To Reproduce
- Ask for sign-in on Teams
- Didn't complete the action
- wait for a while ( a day in my case)
- Try to sign in, on the last sign-in card

# Expected behavior
To sign in without errors

# Screenshots
![image](https://user-images.githubusercontent.com/62729174/150343279-cb93888d-9e1a-49f9-bf15-6d2b76308eae.png)

An issue is logged on the channel as well but haven't more details
![image](https://user-images.githubusercontent.com/62729174/150344824-3a8ac0ce-690e-40ea-a368-9ce6f1754212.png)

I would like to understand why this behavior is occurring and if there's something I can do to solve it. I'm using the bot composer v2.1.1 action to send the sign-in card to Teams

**Comment by bobokids** [comment]
Ported the bug to Composer repo: https://github.com/microsoft/BotFramework-Composer/issues/8926
