### ISSUE TITLE
[Question] ChosenInlineResult message update not received from telegram

### ISSUE THREAD

**Issue by alokkms** [microsoft/BotFramework-Services#330]
I have implemented a simple bot with channel specific handling for telegram's inline mode (using the example shared in #110).

I have also enabled "inline feedback" on the telegram bot (https://core.telegram.org/bots/inline#collecting-feedback). 

But when the user selects one of the inline results, I do not receive any callback for the ChosenInlineResult (https://core.telegram.org/bots/api#choseninlineresult)

The question I have is if this feature is supported by the bot service? If so, how do I receive these callbacks using the bot sdk?

**Comment by bobokids** [comment]
@alokkms, this feature is not supported in telegram channel. Currently we do not have plan to add the new feature support. but please let us know if you have biz justification and we can put this request to our backlog.
