### ISSUE TITLE
Unable to upload Microsoft Excel sheet in Slack Channel

### ISSUE THREAD

**Issue by RamkumarManavalan** [microsoft/BotFramework-Services#334]
Details of the Composer version I use:
- Version:  2.1.1
- Electron: 8.2.4
- Chrome: 80.0.3987.165
- NodeJS: 12.13.0
- V8: 8.0.426.27-electron.0

I use the "File or Attachment" option to accept files from users in Slack. Every other common file types work, except for Microsoft Excel/Word files. The "File or Attachment" does not return any result back, but shows a preview of the file properly. Please see the picture below.
<img width="521" alt="slack-file-attachment-error" src="https://user-images.githubusercontent.com/7835046/160161596-87a7dff3-2288-4dbf-8baa-bd6fd8c8820f.png">

Any help in resolving this?  Thanks.

**Comment by RamkumarManavalan** [comment]
Thank you so much @stevkan.

Please keep this thread posted on which release this bug is planned to be fixed as part of.

**Comment by RamkumarManavalan** [comment]
Any update on this, team? We are totally blocked on this.

**Comment by ssss141414** [comment]
Hi @RamkumarManavalan ,
I'm working on fixing this issue. Sorry for keeping you waiting.

**Comment by ssss141414** [comment]
The fix will be onboard next week.

**Comment by RamkumarManavalan** [comment]
Glad to hear. Thank you so much.

**Comment by RamkumarManavalan** [comment]
@ssss141414 , has this fix been rolled out to production? If yes, which version of bot framework should I upgrade to?

**Comment by ssss141414** [comment]
@RamkumarManavalan Yes the fix has come to Prod. Since the fix is on server side, you don't need to update version. Please have a try to see if the issue persists. Thank you.

**Comment by bobokids** [comment]
Resolved the issue for now. Please reactivate it if you still get it repro-ed.
