### ISSUE TITLE
Slack channel: Update registerBeforeOAuthFlow property to enable saving customer data

### ISSUE THREAD

**Issue by bobokids** [microsoft/BotFramework-Services#335]
Current Slack channel only support registerBeforeOAuthFlow as readonly property. Per the API design, it should be true/false value and updatable. Please check detail requirement from customer here: https://github.com/Azure/azure-sdk-for-go/issues/17358

**Comment by ssss141414** [comment]
We’ve update the swagger file, so that we can set ‘registerBeforeOAuthFlow’ property to true.

**Comment by bobokids** [comment]
Resolved in code.
