### ISSUE TITLE
Generic Oauth 2.0 in  Oauth Connection Setting in Azure for Bot User Authentication 

### ISSUE THREAD

**Issue by inb18** [microsoft/BotFramework-Services#336]
Hi,
I am working on bot that and implementing user authentication , I did oauth connection setting with generic oauth 2.0 but i get this error while I test connection
on url:-https://token.botframework.com/.auth/web/redirect?code=zNEUkT&state=82e83c4f6bd7425c929f9c6b0fe140fe
{
"error": {
"code": "ServiceError",
"message": "Missing session cookie (consent82e83c4f6bd7425c929f9c6b0fe140fe) in consent redirect request."
}
}

**Comment by xieofxie** [comment]
@inb18 This url `https://token.botframework.com/.auth/web/redirect?XXX` is not copyable. You should use one like this `https://token.scratch.botframework.com/api/oauth/signin?signin=` before the redirect

**Comment by inb18** [comment]
Hello,
Actually I am configuring Oauth Connection Setting using Generic Oauth 2.0 for my domain , I provided login url in Authorization Url after succesfull authentication my domain url return code and state to the redirected url. And redirect url is https://token.botframework.com/.auth/web/redirect as per this documentation https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=userassigned%2Caadv2%2Ccsharp

**Comment by Danieladu** [comment]
hi @inb18 , could you provide the botid so that we can check the log to see what happens. Thanks.
![image](https://user-images.githubusercontent.com/7289268/167776438-e9ee7c2e-9cdb-4c28-a610-c73987b70025.png)

**Comment by xieofxie** [comment]
What oauth provider do you use?

**Comment by bobokids** [comment]
@inb18, do you have the info xieofxie mentioned above?

**Comment by luhan2017** [comment]
@inb18 , we didn't see your response for a long time, do you still see the error?

**Comment by luhan2017** [comment]
@inb18 , I am closing this since it is inactive for a long time, please reactive it if it is still needed
