### ISSUE TITLE
OAuth Sign in: Unable to let the user switch the credentials

### ISSUE THREAD

**Issue by RamkumarManavalan** [microsoft/BotFramework-Services#340]
Details of the Bot Framework Composer version I use:
    Version: 2.1.1
    Electron: 8.2.4
    Chrome: 80.0.3987.165
    NodeJS: 12.13.0
    V8: 8.0.426.27-electron.0

I use the 'OAuth Login' of the composer to let the user sign in via service providers (I support Google & Microsoft for now). This works. 

When the user logs out, I tried using "Sign out user" option of composer, but I kept getting the error: "signOutUser() not supported by the current adapter". So, I wrote a custom action (see below):
```
const adapter = new BotFrameworkAdapter({
        msAppId,
        msAppPwd
      });
adapter.signOutUser(dc.context, connectionName, userId)
```
The above executes without any error.

However, the challenge I face is I am not able to let the user switch the account next time when they want to log in. As I read from numerous blogs, issues and documents, I understand that the existing access token is sent back if it already exists. This is a nice feature because it does not let user to go through the consent prompt over and over. However, in my case, I need to give my users an option to re-login with the same account or re-login with a different account. So, I am stuck.

In case of Google, during logout, I tried revoking the access token through this API: "POST https://oauth2.googleapis.com/revoke?token=". Though this revokes the token successfully, the "OAuth Login" component of Bot composer returns the same revoked token to me back, instead of taking the user to the account selection and consent pages.

Possible solutions I would expect are:
- Botframeworkadapter's signOutUser method should revoke/delete access token and any associated refresh token. In the next re-login, user should be allowed to select an account.
- The "Sign out user" option in composer should revoke/delete access token and any associated refresh token, without throwing any error. In the next re-login, user should be allowed to select an account.
- The 'OAuth Login' option in the composer should accept "prompt" parameter, accepting the respective values ('consent' for Google and 'login' for Microsoft). Setting prompt=login or prompt=consent works from my other web applications, as intended.

Or is there any solution for me to let my user change the account/credentials during re-login? Please help me.

**Comment by EricDahlvang** [comment]
Hi @RamkumarManavalan 

Sorry, I'm not sure why that is happening. I've transferred this issue to the BotFramework-Services repository as the token service is part of Azure Bot Service. Maybe someone here will have some ideas.

**Comment by xieofxie** [comment]
Hi @[RamkumarManavala](https://github.com/RamkumarManavalan) it is advised to use Service Provider `Azure Active Directory v2` for Microsoft and `Google` for Google.

I have verified that they worked in signin and signout scenario (after signout, user could not get token any more).

Hi @[EricDahlvang](https://github.com/EricDahlvang), could you help to verify Composer works as what SDK does? Thanks~

**Comment by EricDahlvang** [comment]
Yes, Composer and SDK work similarly. What this issue is about however, is the account selection or consent popup.  For AAD apps, you can go here: https://portal.office.com/account/?ref=MeControl#apps and remove consent under 'You can revoke permission for these apps' The login experience is different when consent has not been provided. As far as I know, the bot framework user auth api does not provide a parameter to always force consent. I was hoping the oauth 2 generic provider would expose these parameters and enable forcing consent every time.

**Comment by xieofxie** [comment]
@[RamkumarManavalan](https://github.com/RamkumarManavalan) For the signout, please reach out to Composer / SDK for fix. For your request, I have verified with the following configs, please test:

Microsoft:
|Name|Value|
|-|-|
|Authorization URL Template|https://login.microsoftonline.com/common/oauth2/v2.0/authorize|
|Authorization URL Query String Template|?client_id={ClientId}&response_type=code&scope={Scopes}&redirect_uri={RedirectUrl}&state={State}&prompt=login|
|Token URL Template|https://login.microsoftonline.com/common/oauth2/v2.0/token|
|Token URL Query String Template|?|
|Token Body Template|code={Code}&redirect_uri={RedirectUrl}&scope={Scopes}&grant_type=authorization_code&client_id={ClientId}&client_secret={ClientSecret}|
|Refresh URL Template|https://login.microsoftonline.com/common/oauth2/v2.0/token|
|Refresh URL Query String Template|?|
|Refresh Body Template|refresh_token={RefreshToken}&redirect_uri={RedirectUrl}&grant_type=refresh_token&client_id={ClientId}&client_secret={ClientSecret}|

Google:
|Name|Value|
|-|-|
|Authorization URL Template|https://accounts.google.com/o/oauth2/auth|
|Authorization URL Query String Template|?client_id={ClientId}&response_type=code&scope={Scopes}&redirect_uri={RedirectUrl}&state={State}&access_type=offline&prompt=consent|
|Token URL Template|https://accounts.google.com/o/oauth2/token|
|Token URL Query String Template|?|
|Token Body Template|code={Code}&redirect_uri={RedirectUrl}&scope={Scopes}&grant_type=authorization_code&client_id={ClientId}&client_secret={ClientSecret}|
|Refresh URL Template|https://accounts.google.com/o/oauth2/token|
|Refresh URL Query String Template|?|
|Refresh Body Template|refresh_token={RefreshToken}&grant_type=refresh_token&client_id={ClientId}&client_secret={ClientSecret}|

**Comment by luhan2017** [comment]
closed since inactive for long time, please reopen if needed.
