### ISSUE TITLE
Size Limit on Adaptive Cards

### ISSUE THREAD

**Issue by milapshah15** [microsoft/BotFramework-Services#341]
Hello Team,

We are implementing a usecase where I need to send a large JSON in the payload. Sometimes I get below error. I am sure there would be a size limit but is there a way to overcome this may be by sending compressed JSON or something? Open for suggestions

`{
    "error": {
        "code": "MessageSizeTooBig",
        "message": "Message size too large."
    }
}`

**Comment by luhan2017** [comment]
@milapshah15 We have a size limitation for ABS payload as 256k, please make sure your payload size don't exceed that value.

**Comment by luhan2017** [comment]
@milapshah15 I am closing this issue since it is inactive for 3 weeks, please reactive it if needed.
