### ISSUE TITLE
Is the serviceURL of "https://smba.trafficmanager.net" fixed?

### ISSUE THREAD

**Issue by kafka-yu** [microsoft/BotFramework-Services#342]
Hi team,

We're building msteams bot app, question about the 'serviceURL', now we received is "https://smba.trafficmanager.net/xxx (region?). Will this domain fixed (means won't change, we can always trust https://smba.trafficmanager.net)? Since for security reason, we want to add a whitelist in backend server to ensure URLs only under this domain is allowed.

Thanks.

**Comment by kafka-yu** [comment]
hi @ericwill-msft @EricDahlvang, would you pls help check? Thank you!

**Comment by boydc2014** [comment]
Hi, @kafka-yu this smba endpoint, from what we know, is a well known Teams api endpoint, you should be safe to trust this endpoint.

**Comment by kafka-yu** [comment]
Good to know that, Thanks! @boydc2014
