### ISSUE TITLE
Receiving The bot is not part of the conversation roster for few users

### ISSUE THREAD

**Issue by sandhi23** [microsoft/BotFramework-Services#344]
Hi,

Our bot is not able to communicate with few users using our Teams personal app published on the Teams Catalog.

We have stored the the conversation reference when the app got installed. Sending any activity over that conversation gives
an error "The bot is not part of the conversation roster.','Stack':'Error: The bot is not part of the conversation roster." 

This is happening on couple of Tenants and with very few subset of users. Strangely the conversation reference looks odd like

19:03bcf1de-c298-4955-8959-a3249849694b_56ecd439-300b-473d-9c3f-b158a0def669@unq.gbl.spaces
19:meeting_ODU0NjhkYzktZGMwNi00MjBmLTg1NDUtNjE0ODNjYWEwMWZj@thread.v2

Cleaning the conversation from our internal backend and creating new conversation (on new user interaction) reference works fine. But we want to understand why the initial conversation reference received as part of app installation is incorrect. We are using the NodeJS BotFramework.

Thanks

**Comment by luhan2017** [comment]
@sandhi23, This is seems a Teams related issue, could you please contact Teams for this?

**Comment by luhan2017** [comment]
Close it for now, please feel free to reopen if needed.
