### ISSUE TITLE
bot framework - web chat - uploading attachment with Arabic name

### ISSUE THREAD

**Issue by Olakhrisat** [microsoft/BotFramework-Services#345]
Hi All,

I am using the default web chat from Microsoft and I have noticed while uploading an attachment with Arabic name that the upload API failed

![image](https://user-images.githubusercontent.com/59798587/184106655-9a8620d2-6b67-4175-ad06-e27ea9135085.png)
![image](https://user-images.githubusercontent.com/59798587/184106668-54a84e01-4fa2-4277-a502-90119f07c592.png)

any idea? how to fix this issue?

**Comment by ZiyuanGuo** [comment]
This issue had been already fixed, please try again.
