### ISSUE TITLE
Unable to publish Node Azure Bot from Bot Framework Composer

### ISSUE THREAD

**Issue by pckyn** [microsoft/BotFramework-Services#351]
Hi Team,

We have created a Node Azure bot and unable to publish in azure.. Please help on this.

"{\"name\":\"DEPLOY_ZIP_ERROR\",\"message\":\"There was a problem publishing bot assets (zip deploy). {\\\"stack\\\":\\\"Error: write EPIPE\\\\n    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)[\\\",\\\"message\\\":\\\"write](https://github.com/%22,/%22message/%22:/%22write) EPIPE\\\",\\\"code\\\":\\\"EPIPE\\\",\\\"config\\\":{}}\",\"stack\":\"Error[\\n](https://github.com/n)    at new CustomizeError (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:276418:25)[\\n](https://github.com/n)    at createCustomizeError (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:276423:10)\\n    at BotProjectDeploy.deployZip (/Applications/Bot Framework Composer.app/Contents/Resources/app.asar.unpacked/extensions/azurePublish/dist/extension.js:276954:13)\"}"
---
 
---
"DEPLOY_ZIP_ERROR - There was a problem publishing bot assets (zip deploy). {\"stack\":\"Error: write EPIPE\\n    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)\",\"message\":\"write EPIPE\",\"code\":\"EPIPE\",\"config\":{}}"

![image](https://github.com/microsoft/BotFramework-Services/assets/126873481/91f9f4c3-9113-433d-bc0d-cca9ab031feb)

![image](https://github.com/microsoft/BotFramework-Services/assets/126873481/5e7afd9e-be42-4164-a972-8842437d03a9)

Thanks,
Prashant

**Comment by luhan2017** [comment]
@pckyn,  could you please create an issue in Composer repo directly? https://github.com/microsoft/BotFramework-Composer/issues
