### ISSUE TITLE
BOT Rest API End Point https://smba.trafficmanager.net/emea/v3/conversations/19:21a4ba5358a5487ea69a616148aac1aa@thread.tacv2/activities/{messageID} sending message as new message instead of reply message.

### ISSUE THREAD

**Issue by ChiranjeeviJammula16** [microsoft/BotFramework-Services#356]
BOT Rest API End Point https://smba.trafficmanager.net/emea/v3/conversations/19:21a4ba5358a5487ea69a616148aac1aa@thread.tacv2/activities/{messageID} sending message as new message instead of reply message.

I have used https://smba.trafficmanager.net/emea/v3/conversations/19:21a4ba5358a5487ea69a616148aac1aa@thread.tacv2/activities end point url to send message to teams channel. 

When I tried to send reply to message using https://smba.trafficmanager.net/emea/v3/conversations/19:21a4ba5358a5487ea69a616148aac1aa@thread.tacv2/activities/{messageID} , message is delivering as new message instead of sending as reply to existing message.

here is the payload I am sending for the request.
const headers = {
            Authorization: `Bearer ${token}`,
            "Content-Type": "application/json"
          };
  
          var reply_data = {
            "type": "message",
            "from": {
                "id": "1ccad7b5-29cd-4ea0-87cd-5d16dd5679d5" //BOT ID
            },
            "text": "Hello, this is a reply from a bot."
        }

Can you please help me on this issue.

**Comment by luhan2017** [comment]
@ChiranjeeviJammula16 , Azure Bot service doesn't own the data plane for teams channel. I have created an ICM for teams team for this. https://portal.microsofticm.com/imp/v3/incidents/incident/432653664/summary

Here is how they replied:
We need more details to investigate the issue, can you provide the bot id and timestamp (with timezone) so that I can check in the log to find what's happening over there?
Can you also add a screenshot so we can easily understand what's the issue looks like?

**Comment by luhan2017** [comment]
@ChiranjeeviJammula16 , any update on this?

**Comment by luhan2017** [comment]
@ChiranjeeviJammula16 . are you still seeing this issue? could you please share more details?

**Comment by ChiranjeeviJammula16** [comment]
Hi Luhan,

Sorry for delay in response, I was able to solve issue by using end point like this.

https://smba.trafficmanager.net/amer/v3/conversations/{channelId;messageid={activityId}/activities

**Comment by luhan2017** [comment]
Thanks for your quick reply, then I will close this issue, please reopen if needed.
