### ISSUE TITLE
Facebook "Submit Review" button reporting 500 Error

### ISSUE THREAD

**Issue by Dmenter91** [microsoft/BotFramework-Services#357]
Failed to load resource: the server responded with a status of 500 ()
/ads/async/advertiser_dashboard/fetch_appeal_information/?page_id=106683521169211&_flowletID=9955:1 

Broken Link: https://www.facebook.com/ads/async/advertiser_dashboard/fetch_appeal_information/?page_id=106683521169211&_flowletID=9955

**Comment by luhan2017** [comment]
@Dmenter91 do you have more details for this issue. Why do you think it is a bot service issue?

**Comment by luhan2017** [comment]
Close this due to inactivity for weeks, please reopen if needed.
