### ISSUE TITLE
Microsoft Bot Framework - Email channel Issue - Unable to save Credentials

### ISSUE THREAD

**Issue by tomlm** [Microsoft/BotFramework-Services#4]
_From @fj4870 on October 2, 2018 3:42_

Unable to register Microsoft bot framework Email channel as getting following error "Unable to save. Unable to validate the given credentials" while saving email id and password.

 I have tried using different emails including Office 365, @outlook.com etc but none of them working. Has anyone run into the same problem?

_Copied from original issue: Microsoft/BotBuilder#5085_

**Comment by EricDahlvang** [comment]
@fj4870 Does the email address you are using pass the Microsoft Exchange Web Services Connectivity Tests here: https://testconnectivity.microsoft.com/  Usually, when an email address configuration issue occurs, it is related to Auto Discovery.

Are you able to save this same email address into a different bot's configuration?

Also, there have historically been times where the email channel saves correctly even though there has been an exception in the UI: https://github.com/Microsoft/BotBuilder/issues/3201

**Comment by dandriscoll** [comment]
Hi @fj4870, can you provide either the bot ID or the MSA App ID for the bot where you're seeing this failure?

**Comment by EricDahlvang** [comment]
Closing due to no response.
