### ISSUE TITLE
Cortana Skill Timeout

### ISSUE THREAD

**Issue by RaviKishore94** [Microsoft/BotFramework-Services#40]
In Cortana Bot Skills, the current timeout of a cortana skill waiting for the bot's response is 10 seconds.

We are integrating automation tools like ServiceNow for ticket creation based on user's query in the bot where the ticket creation takes a minute and return back for the bot to respond the user about the ticket details.

Is there any way to increase this timeout value? Is this configurable? Need help on this.

Thanks in Advance.

**Comment by EricDahlvang** [comment]
The 10 second timeout is within the Cortana Connector Service itself, and cannot be modified by consumers of the API.  However, there are some workarounds that enable the bot to respond within 90 seconds.  If you are using Bot Builder V3, this example demonstrates one method: https://docs.microsoft.com/en-us/cortana/skills/show-progress

1) the bot needs to respond with a status code 200 within 10 seconds, then 

2) on another thread perform the long running operation, periodically (every < 10 seconds) sending a status message to Cortana with reply.InputHint = InputHints.IgnoringInput; and 

3) send the final message with operation results and reply.InputHint = InputHints.ExpectingInput;

---
In the future, please use StackOverflow for usage type questions.  The team prefers to use the GitHub repositories for DCRs, Feature Requests and Bug Reports.

**Comment by RaviKishore94** [comment]
Thanks @EricDahlvang . Will try your suggestion.
