### ISSUE TITLE
[Feature Request] Extend Teams Channel Registration page

### ISSUE THREAD

**Issue by iMicknl** [microsoft/BotFramework-Services#42]
At the moment it is very unclear what the possibilities of Teams bots are and how you can [sideload a bot](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/apps/apps-upload). Without uploading the app package (manifest), not all Teams specific functionality is supported. However functionality like OAuthCards and File Uploads is also unsupported, which is unclear for developers at the moment.

>When a bot has been added through one of these methods, it will not be addressable in channel conversations. Nor can you take advantage of other Microsoft Teams app capabilities like tabs or messaging extensions. ([source](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-test#adding-a-bot-for-personal-chat-only))

**Is your feature request related to a problem? Please describe.**:
- Channel Registration page is not detailed enough 
- Messaging - Learn more points to `https://dev.skype.com/bots` instead of Teams documentation

**Describe the solution you'd like**:
- Add more information about packaging a bot for testing purposes (not only publishing)
- Add links to Teams specific documentation
- Change Skype link to Teams specific documentation

<img width="938" alt="screenshot 2019-01-30 at 21 59 09" src="https://user-images.githubusercontent.com/1424596/52012227-5475fd80-24da-11e9-93d2-0d5f6af3394c.png">

**Related**:
https://github.com/Microsoft/AI/pull/410
https://github.com/Microsoft/BotFramework-WebChat/issues/1667

**Comment by CoHealer** [comment]
Hi @iMicknl, a request has just been made for these docs from Teams so that they will be integrated into our own. I will follow up on this thread upon completion.

**Comment by iMicknl** [comment]
Thanks for your response, @CoHealer. Does this mean that the Bot Framework documentation will be merged with the Teams Bot documentation on docs.microsoft.com? Or does this also apply to the blade in Azure (ibiza).

**Comment by CoHealer** [comment]
TBD @iMicknl. I'll follow up this afternoon and see if they have settled on a plan.

**Comment by CoHealer** [comment]
Apologies for the delay @iMicknl. It will be a couple of weeks before the content is received from Teams, at which time the link will be updated. Regarding the blade, are you asking if all of that content will be in the blade itself? If so, then no there are no plans to make that change at this time.

**Comment by iMicknl** [comment]
No worries, @CoHealer. My main point of this issue was that the 'Channel Registration page is not detailed enough'. Customers and partners are struggling with developing for Teams; just an intro text which links to the docs would be great. Only 'Messaging is available by default for your bot' isn't helpful.

**Comment by CoHealer** [comment]
Ack @iMicknl & thx for your feedback. I'll update this issue in 1-2 weeks when we've received the content and update the link. I've passed on your comments to the team regarding the channel registration page details (or lack thereof) and will provide an update detailing the response.

**Comment by iMicknl** [comment]
@CoHealer, any update? I would like to add https://github.com/MicrosoftDocs/bot-docs/issues/1294 to this issue. Most customer/partner questions (and even internal) around the Teams channel are regarding the OAuth card not working.

**Comment by xieofxie** [comment]
Yeah, if one could set Valid domain in 'Configure MSTeams', it would be very helpful.

**Comment by CoHealer** [comment]
Sincerest apologies that I dropped this. The content did eventually update, now pointing to https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?tabs=dotnet

**Comment by iMicknl** [comment]
@CoHealer thanks for the update, looks good!
