### ISSUE TITLE
Confusion when working with Bot Registration vs Web App Bot 

### ISSUE THREAD

**Issue by ayako** [microsoft/BotFramework-Services#44]
The blade options in Azure are different when working with a Bot Channel Registration vs a Web App Bot. For example you can quickly & easily get to the application settings in the latter while it doesn't exist in the former. It's not apparent to end users that a Web App Bot spins up two separate entities in Azure and then provides a "lens" over them both (hence the App Settings being available here). 

![webappbot_vs_botregi](https://user-images.githubusercontent.com/1762438/51946426-cdd30900-2464-11e9-9b21-ddd252c17c38.PNG)

**Comment by ayako** [comment]
No, I mean differences the menus between Web App Bot and Bot Channel Registration

**Comment by AviralGarg1993** [comment]
Same question: `differences the menus between Web App Bot and Bot Channel Registration`

**Comment by jameslew** [comment]
The differences there are indeed confusing; however the way the portal is implemented, when you "bring your own web app", the bot service doesn't know about it's existence.  Your app could be on Azure right next to the registration or on a raspberry pi in your home - the only thing we have is the endpoint URL you provide.

I will create a documentation work item to update this topic with a call out that indicates where you might look for your application settings:

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration

**Comment by sbasu60** [comment]
Function and Web App bots are essentially the same thing. The core difference is that most of the business logic for a functions bot is contained in one or more Azure functions which are c# scripts, while the business logic for a WebApp bot is contained in an WebAPI running as an App Service. Now, a Bot Channels Registration is an entirely different beast. This resource is what you use when you want to use the Bot Service functionality in Azure. It is the middle piece to connect your bot to the various channels that it supports. A channel is an external 'client application' such as Facebook Messenger, Twitter, twillio, web chat, etc. This is the basics but there is plenty of information in the Bot Framework documentation.
