### ISSUE TITLE
Bot Channels Registration never shows auto-generated app password

### ISSUE THREAD

**Issue by navzam** [microsoft/BotFramework-Services#46]
If you create a Bot Channels Registration resource through the Azure portal and leave the default of "Auto create App ID and password", it never shows you the generated ID and password. You can find the ID under `Settings -> Microsoft App ID`, but to get a password, you have to go into the app registration and regenerate a new password. This is a confusing experience.

**Comment by EricDahlvang** [comment]
The documentation does have some instructions for how to generate a new password: 
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-3.0#bot-channels-registration-password

The blog also has instructions for how to retrieve the MicrosoftAppPassword after creating a bot: https://blog.botframework.com/2018/07/03/find-your-azure-bots-appid-and-appsecret/

**Comment by navzam** [comment]
I didn't find the first doc since it's in the v3 section and I haven't seen an equivalent doc in the v4 section. Even if there are docs/blogs out there, the experience is still confusing, and I've seen many developers get lost trying to find where their newly generated password went.

**Comment by jameslew** [comment]
The documentation has been updated in V4.  The reason we do this BTW is to protect the secret from prying eyes.  It is unfortunately a little convoluted, but from a security perspective we don't store this information anywhere in the bot services servers proper.

The new app registration UI is now a part of the Azure portal proper which should improve navigation/discovery.
