### ISSUE TITLE
SMS Channel ignores TextFormat = TextFormatTypes.Plain

### ISSUE THREAD

**Issue by mekinney** [microsoft/BotFramework-Services#48]
The twilio / sms channel currently ignores the TextFormat property.  Setting it to Plain has no effect.  Every response appears to be run through the markdown process.

The webchat channel does honor this setting.

```csharp
var response = turnContext.Activity.CreateReply();
var text = new StringBuilder();

text.AppendLine("**Bold Text As The First Line**");
text.AppendLine("Normal text here.");
text.AppendLine("# H1 Header Line");
response.Text = text.ToString();
response.TextFormat = TextFormatTypes.Plain;
```
SMS Screen Shot - TextFormat = Plain
Notice it still displayed a markdown processed SMS.
![img_7603](https://user-images.githubusercontent.com/7552362/52429815-a8c04500-2ab9-11e9-873b-2c42343c51a9.jpg)

TextFormat = Plain in emulator
![bug plaintext](https://user-images.githubusercontent.com/7552362/52429628-45ceae00-2ab9-11e9-8cc4-abae2067f234.JPG)

TextFormat = Markdown in emulator
![bug chat formatted](https://user-images.githubusercontent.com/7552362/52429634-49facb80-2ab9-11e9-87d5-cae795c60bbf.JPG)

**Comment by mdrichardson** [comment]
I can confirm this. I also wasn't able to find anything in the [Twilio Docs](https://www.twilio.com/docs/sms) that would cause this, so I'm assuming it is indeed a bug on our end with the Twilio Channel.

**Comment by mekinney** [comment]
Thanks for the update.  Is the Twilio Channel code on GitHub?  After looking for a bit, I don't see it.  Was going to give a look over.

**Comment by mdrichardson** [comment]
It's not. Channel code is private to MSFT for security.

**Comment by mekinney** [comment]
Okay, thanks.
