### ISSUE TITLE
SMS Channel NewLine processing inconsistent with other channels

### ISSUE THREAD

**Issue by mekinney** [microsoft/BotFramework-Services#49]
The SMS channel requires a blank line to cause an end of line.  This is inconsistent with other channels and prevents a general purpose messages from working across multiple channels.

```csharp
public static IMessageActivity BuildNewLineBug(ITurnContext turnContext, bool addLine)
{
    var text = new StringBuilder();

    text.AppendLine("Line 1");
    text.AppendLine("Line 2");
    text.AppendLine("Line 3");
    text.AppendLine("");
    text.AppendLine("Line 5 (4 was blank)");

    var response = turnContext.Activity.CreateReply(text.ToString());
    return response;
}
```
SMS screenshot - notice no line breaks after line 1 and line 2.  Line break after Line 3 is caused by an additional blank line.

![image-1](https://user-images.githubusercontent.com/7552362/52434084-656ad400-2ac3-11e9-82ee-006164eaba89.png)

Emulator Output
![bug - line spacing - emulator](https://user-images.githubusercontent.com/7552362/52434161-964b0900-2ac3-11e9-956e-c7e723a4d157.JPG)

WebChat output
![bug-linespacing-webchat](https://user-images.githubusercontent.com/7552362/52434830-2473bf00-2ac5-11e9-8271-535378335458.JPG)

**Comment by mdrichardson** [comment]
I can confirm that this is a bug and will forward this for resolution.

You can probably see that it *did* create a new line. Line 3 was separated by line 4, but unlike web chat and emulator, it does not put each `AppendLine` line on its own line, almost like the first `\n` (or whatever is used at the end of each line) is ignored by the Twilio channel.

If you need an immediate fix, you can get the user's channel and append an extra line to each line if they are using an SMS channel. Until then, this should be considered a bug.

For reference:

[Twilio Line Break docs](https://support.twilio.com/hc/en-us/articles/223181468-How-do-I-Add-a-Line-Break-in-my-SMS-or-MMS-Message-)

### Tests

#### Twilio
![image](https://user-images.githubusercontent.com/40401643/52447427-893f1180-2ae5-11e9-9d22-d1b44d132176.png)

#### Web Chat
![image](https://user-images.githubusercontent.com/40401643/52447722-6f51fe80-2ae6-11e9-8f93-f9f0c6d43990.png)
![image](https://user-images.githubusercontent.com/40401643/52447730-76790c80-2ae6-11e9-9fd6-24c868ed53bc.png)

#### How each message was created

*Note:* I changed the window size on my Twilio client to confirm whether or not a line break worked at all.

*slash n*: `text.AppendLine("\n");` -- Works in Twilio, not Web
*nbsp*: `text.AppendLine("&nbsp;");` -- Works in Web, not Twilio
*percent 0 a*: `text.AppendLine("%0a");` -- Doesn't work
*empty parens*: `text.AppendLine();` -- Works in Twilio, not in Web
*blank string*: `text.AppendLine("");` -- Works in Twilio and web
*blank string with space*: `text.AppendLine(" ");` -- Works in Twilio and web

**Comment by mekinney** [comment]
Is there any update on this?

**Comment by CoHealer** [comment]
@mdrichardson "...If you need an immediate fix, you can get the user's channel and append an extra line to each line if they are using an SMS channel. Until then, this should be considered a bug."

@jameslew , can you confirm this has been triaged and added to the service backlog?

**Comment by jameslew** [comment]
Thanks for the report. I've added it to our internal backlog for prioritzation and will close this one.  If the issue changes or otherwise, let us know!

**Comment by craigjensen** [comment]
The SMS channel defaults to TextFormat='markdown' which is likely what's causing the differences in display.  Please try setting TextFormat='plain' and see if that helps.
