### ISSUE TITLE
DirectLine - Random timeouts when starting conversation via REST API

### ISSUE THREAD

**Issue by Stardox** [Microsoft/BotFramework-Services#50]
### Brief description of our setup:
We are using [WebChat](https://github.com/Microsoft/BotFramework-WebChat) as a bot client which is connected to our bot service using DirectLine channel. Our bot is hosted in Azure as an App Service and is implemented using [version 3 of the BotBuilder .NET SDK](https://github.com/Microsoft/BotBuilder-V3).

Instead of letting WebChat to start the conversation, we are generating both the time bound DirectLine token and conversation id using the documentation on [this page](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-start-conversation). This happens on our bot backend when specific API is called when user navigates to the page where WebChat is embedded. Both the DirectLine token and conversation id are then returned to the frontend and are passed into the WebChat.

### Problem description:
The calls to DirectLine's start conversation endpoint either randomly timeout or return an error. We observed following three possible behaviors:

1. The API call times out after approx. 1.7m without any response and `HttpClient` throws `TaskCanceledException`.
2. The API call results in status code 500 after just couple of milliseconds and following response body is returned: `{ "error": { "code": "ServiceError" } }`
3. The API call times out after approx. 1.6m and results in 502. The response body is HTML which apart from HTML tags contain following text: `502 - Web server received an invalid response while acting as a gateway or proxy server.`

There does not seem to be any pattern in this behavior as it happens really randomly during various parts of the day. Also good portion of the API calls are successful.

### How we call the endpoint:
We are using .NET's `HttpClient` for the job which is instantiated as a **singleton per host**. This means that we are **not** re-creating and disposing it after every single HTTP request.

Sending the HTTP request itself is really straightforward according to the [docs](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-start-conversation):
```
POST https://directline.botframework.com/v3/directline/conversations
Accept: application/json
Authorization: Bearer directLineStaticSecretGoesHere
```

Anyone has any ideas what could be the issue here? Apart from DirectLine, our bot is calling various other external APIs - these are however not timing out.

**Comment by EricDahlvang** [comment]
Hi @Stardox 

Are you using: `System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12`

Reference: https://blog.botframework.com/2018/11/06/announcement-azure-bot-service-enforcing-transport-layer-security-tls-1-2/

**Comment by Stardox** [comment]
Hi @EricDahlvang, thanks for the reply.

No, I am not using that setting to set the `ServicePointManager.SecurityProtocol` explicitly. It is worth to try it, but I have few questions related to that:

1. If it was really issue with the `TLS`, then wouldn't just **all** API calls to DirectLine fail immediately without any timeouts with the specific TLS / certificate error message? Its just that in my case only minor portion of calls fail.

2. Won't that setting enforce `TLS 1.2` for all API calls, not just the ones related to DirectLine? Should I use `|=` operator instead (or set the TLS only for the specific `ServicePoint` related to DirectLine) so that calls to other APIs which I consume continue to work even if they do not yet support `TLS 1.2`?

3. In some scenarios in my bot, I am using `ConnectorClient` to send activity back to the user which is also going through DirectLine. Something like:
```
var reply = activity.CreateReply();
reply.Type = ActivityTypes.Message;
reply.Text = "This is a test.";

ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
await connector.Conversations.ReplyToActivityAsync(reply).ConfigureAwait(false);
```
I however did not notice any timeouts when using `Conversations.ReplyToActivityAsync`. Does `ConnectorClient` sets TLS to 1.2 internally?

**Comment by EricDahlvang** [comment]
Oh, based on your further description, it sounds like the issue you are running into could be related to MicrosoftAppCredentials.TrustServiceUrl

Please add the following:
`MicrosoftAppCredentials.TrustServiceUrl(activity.ServiceUrl)` 
before sending the message with the ConnectorClient

```cs
MicrosoftAppCredentials.TrustServiceUrl(activity.ServiceUrl)
ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
await connector.Conversations.ReplyToActivityAsync(reply).ConfigureAwait(false);
```

(You're right, if it were .TLS it should be affecting all messages.)

**Comment by EricDahlvang** [comment]
@Stardox One of the Direct Line service engineers suggests that the issue you are seeing is possibly related to the following:

> 1.	Errors from internal dependencies
> 	a.	We are in the process of moving our internal databases to CosmosDB which will give better performance and resiliency. That should be done in the next couple weeks.
> 2.	Errors from the platform
> 	a.	We've battling a networking problem and have engaged other Azure teams to root cause this. This is our highest priority issue.
> 3.	Errors from deployment
> 	a.	We are deploying some fixes that will make deployments less impactful. This should also be in place in the next couple weeks
> 
> The good news is that we're aware of each of these and making progress on their fixes. The bad news is that it's taking far too long and for that I apologize. These issues are frustrating for us, too.

I apologize for the confusion my earlier suggestions may have caused.  This is most likely the underlying cause of the random timeouts you are experiencing.

**Comment by Stardox** [comment]
@EricDahlvang, regarding following point:

> 2. Errors from the platform
>     a.	We've battling a networking problem and have engaged other Azure teams to root cause this. This is our highest priority issue.

Does this networking problem relate only to DirectLine Azure services or it can potentially affects all Azure hosted App Services / Web Apps (for example ones which are not related to MS bots at all)?

But anyways, thanks for the info which you provided. Lets see whether there will be any updates regarding the above issues from service engineers.

**Comment by EricDahlvang** [comment]
@Stardox My understanding is that this has only been affecting the DirectLine services.

I'm going to close this issue, since there is a previous issue here: https://github.com/Microsoft/BotFramework-Services/issues/39 

Please follow along there for updates.
