### ISSUE TITLE
Skype For Business BOT registration error: Microsoft.Skype.EnterpriseVoice.CbdServ ice.DataAccess.EntityNotFoundException

### ISSUE THREAD

**Issue by PrasenjitSaha** [Microsoft/BotFramework-Services#51]
Trying to register Azure Bot in Skype for Business Channel using below command -

Import-PSSession (New-CsOnlineSession -Credential (Get-Credential))

New-CsOnlineApplicationEndpoint -ApplicationId <Application Id> -Name NameOfTheBot -Uri sip:username@yourdomain.com

But got below errors multiple time-

`Cmdlet invocation error
    + CategoryInfo          : NotSpecified: (:) [New-CsOnlineApplicationEndpoint], CmdletInvocationException
    + FullyQualifiedErrorId : Error processing cmdlet request,Microsoft.Rtc.Management.Hosted.PlatformService.NewPla 
   tformServiceAppEndpointConfigCmdlet
    + PSComputerName        : admin0f.online.lync.com
 
{
  "error":{
    "code":"","message":"An error has occurred.","innererror":{
      "message":"Application: '9c37b446-08d6-4dfc-a415-f9dd9243552d'","type":"**Microsoft.Skype.EnterpriseVoice.CbdServ
ice.DataAccess.EntityNotFoundException**","stacktrace":"   at 
Microsoft.Skype.EnterpriseVoice.Common.Contracts.CheckNonNull[T,TException](T val, String msg)\r\n   at Microsoft.Sky
pe.EnterpriseVoice.CbdService.DataAccess.AppEndpointOperations.<ValidateInsertStateAsync>d__45.MoveNext() in 
D:\\a\\_work\\88\\s\\BVD\\CBD\\DataAccess\\Operations\\AppEndpointOperations.cs:line 1692\r\n--- End of stack trace 
from previous location where exception was thrown ---\r\n   at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
Microsoft.Skype.EnterpriseVoice.CbdService.DataAccess.AppEndpointOperations.<InsertAsync>d__8.MoveNext() in 
D:\\a\\_work\\88\\s\\BVD\\CBD\\DataAccess\\Operations\\AppEndpointOperations.cs:line 111\r\n--- End of stack trace 
from previous location where exception was thrown ---\r\n   at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
Microsoft.Skype.EnterpriseVoice.CbdService.Controller.BvdEntitiesAccessor`3.<AddEntity>d__5.MoveNext() in 
D:\\a\\_work\\88\\s\\BVD\\CBD\\CBDService.FrontEnd\\Controller\\BvdEntitiesAccessor.cs:line 0\r\n--- End of stack 
trace from previous location where exception was thrown ---\r\n   at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
Microsoft.Skype.EnterpriseVoice.Common.OData.Controller.NavEntitiesController`2.<AddEntity>d__2.MoveNext()\r\n--- 
End of stack trace from previous location where exception was thrown ---\r\n   at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous 
location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack 
trace from previous location where exception was thrown ---\r\n   at 
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at 
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous 
location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n  
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at 
System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()"
    }
  }
}
    + CategoryInfo          : InvalidOperation: (Microsoft.Rtc.M...
    }
  }
}:PlatformServiceCmdletException) [New-CsOnlineApplicationEndpoint], DataServiceClientException
    + FullyQualifiedErrorId : {
  "error":{
    "code":"","message":"An error has occurred.","innererror":{
          "message":"Application: '9c37b446-08d6-4dfc-a415-f9dd9243552d'","type":"Microsoft.Skype.EnterpriseVoice.Cb 
   dService.DataAccess.EntityNotFoundException","stacktrace":"   at Microsoft.Skype.EnterpriseVoice.Common.Contract  
  s.CheckNonNull[T,TException](T val, String msg)\r\n   at Microsoft.Skype.EnterpriseVoice.CbdService.DataAccess.A   
 ppEndpointOperations.<ValidateInsertStateAsync>d__45.MoveNext() in D:\\a\\_work\\88\\s\\BVD\\CBD\\DataAccess\\Op    
erations\\AppEndpointOperations.cs:line 1692\r\n--- End of stack trace from previous location where exception wa    
s thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.Com    
pilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Skype.Enterprise    
Voice.CbdService.DataAccess.AppEndpointOperations.<InsertAsync>d__8.MoveNext() in D:\\a\\_work\\88\\s\\BVD\\CBD\    
\DataAccess\\Operations\\AppEndpointOperations.cs:line 111\r\n--- End of stack trace from previous location wher    
e exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Syst    
em.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Sk    
ype.EnterpriseVoice.CbdService.Controller.BvdEntitiesAccessor`3.<AddEntity>d__5.MoveNext() in D:\\a\\_work\\88\\    
s\\BVD\\CBD\\CBDService.FrontEnd\\Controller\\BvdEntitiesAccessor.cs:line 0\r\n--- End of stack trace from previ    
ous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Thro    
w()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n      
 at Microsoft.Skype.EnterpriseVoice.Common.OData.Controller.NavEntitiesController`2.<AddEntity>d__2.MoveNext()\    
r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.Exceptio    
nServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAnd    
DebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveN    
ext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.Ex    
ceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSucc    
essAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeAct    
ionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n     
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.Ta    
skAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterRe    
sult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown -    
--\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServi    
ces.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.Exceptio    
nFilterResult.<ExecuteAsync>d__0.MoveNext()"
    }
  }
},Microsoft.Rtc.Management.Hosted.PlatformService.NewPlatformServiceAppEndpointConfigCmdlet
    + PSComputerName        : admin0f.online.lync.com`
 
Error Type mentioned as: 

**"type":"Microsoft.Skype.EnterpriseVoice.CbdServ
ice.DataAccess.EntityNotFoundException"**

Please let me know how to solve this error.

**Comment by odd-mithril** [comment]
Hi @PrasenjitSaha

I have tried several times, still got the same error...

**Comment by EricDahlvang** [comment]
Hi @PrasenjitSaha and @odd-mithril 

Skype for Business Bots are still in Preview.  As such, they are not fully supported and odd issues such as this do sometimes occur.   

Other things to try, or consider:

* Open a ticket with Skype for Business support: https://support.office.com/en-us/skype-for-business (they will most likely have suggestions for how to turn on tracing, and assist with debugging this issue)

* Start over from the beginning, following these instructions carefully: https://docs.microsoft.com/en-us/skype-sdk/skype-for-business-bot-framework/docs/bot-hybrid-support

This issue seems specific to your configuration or environment and the Bot Framework support team does not have the tools to assist with your root cause investigation as this is not a supported scenario (someone on the Skype for Business team may be able to assist more than us). 

I'm sorry I couldn't help.
