### ISSUE TITLE
Directline API returning 500 internal server error in Azure

### ISSUE THREAD

**Issue by vishmonne** [Microsoft/BotFramework-Services#53]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.14.1
* Active Channels: Skype, Direct Line (Webchat)
* Deployment Environment: Azure Bot Service

## Issue Description
Getting different errors from directline API endpoint today. The bot is not performing and frequently stops responding to user's request.

Please find below one of the error log entry. We are running the bot in production for a few months now and are observing such errors for the first time. Please help.

POST to 'https://directline.botframework.com/v3/conversations/4****************/activities/4******************************8' failed: [500] Internal Server Error
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:647:46)

**Comment by EricDahlvang** [comment]
@vishmonne if you still require assistance, please share the requested information so we can investigate further.

Closing due to no response.
