### ISSUE TITLE
Directline POST activity API returning 500 & 503 errors

### ISSUE THREAD

**Issue by bhushanvadgave** [Microsoft/BotFramework-Services#54]
Since last 2 weeks, our bot service, when tries to post a message (as a response to user's message) over DirectLine, have been facing DirectLine API failures. DirectLine POST Activity API returns 500(Internal Server Error ) or 503(Site Unavailable) errors intermittently. 

One of API calls which gave 500 errors is mentioned below
https://directline.botframework.com/v3/conversations/3NIzLtGFmXdEQGqoIqUbsn/activities/3NIzLtGFmXdEQGqoIqUbsn%7C0000000

**Comment by EricDahlvang** [comment]
We apologize for the issues you've been experiencing.  I just wanted to provide an update that the above mentioned changes are still in progress.

**Comment by EricDahlvang** [comment]
Closing this issue.  The fixes for this have been completed.
