### ISSUE TITLE
LINE Channel doesn't work

### ISSUE THREAD

**Issue by runceel** [Microsoft/BotFramework-Services#55]
I tried steps written by following document to add LINE channel.

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-line?view=azure-bot-service-4.0

However, my bot that is just echo bot didn't work on LINE.
The bot works fine on the other channels(ex: webchat, teams).

The following message is shown on the Azure portal.
> There was an error sending this message to your bot: HTTP status code InternalServerError

I did trouble shooting written on the document, however the error wasn't fixed.

**Comment by runceel** [comment]
Following logs is in App Insights:

> Message
> POST to <bot name> failed: POST to the bot's endpoint failed with HTTP status 500 POST to the bot's endpoint failed with HTTP status 500 
> 
> Exception type
System.Exception
> 
> Failed method
Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext
> 
> Microsoft.Bot.Schema.BotException:
>    at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext (Microsoft.Bot.ChannelConnector, Version=3.2.2.5, Culture=neutral, PublicKeyToken=null)
> Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext で処理された内部例外 System.Exception:
>    at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__31.MoveNext (Microsoft.Bot.ChannelConnector, Version=3.2.2.5, Culture=neutral, PublicKeyToken=null)

**Comment by VanyLaw** [comment]
Hi @runceel , Do you scan the QR code of your channel using the account which you register the channel? According to LINE Doc, It need to activate the channel by adding the channel to be you friend.

**Comment by runceel** [comment]
Hi @VanyLaw ,

I've fixed the issue.
The cause of the issue is plan of Messaging API.
I selected Free plan when I created a Messaging API. In this case, the issue is occurred.
Now, I have been selecting Developer trial plan. It works correctly.

Selecting free plan on the screen capture of the document, then I thought I can use free plan.
I think it is better that write about plan of Messaging API on the document.

**Comment by youyu16** [comment]
hi @VanyLaw , I just create a free plan bot with an echo bot, it work just fine for me.
seems the message is failed sending to the bot. can you provide the available feature for your free account?
![image](https://user-images.githubusercontent.com/17819112/53315220-157e7080-38fd-11e9-8870-fe853d0b2567.png)
and please refresh the LINE console page to ensure the webhook is enabled and auto-reply is disabled.
line console have an issue when saving webhook url.

**Comment by runceel** [comment]
Thank you @youyu16 

In my case, there is no PUSH_MESSAGE feature in free plan of Messaging API.

![image](https://user-images.githubusercontent.com/79868/53316777-73668480-390c-11e9-9ab5-5b4cb6e2be36.png)

My account is a personal account.
This issue related to country? or account type?

**Comment by youyu16** [comment]
@runceel PUSH_MESSAGE is needed for now, because of limitation of REPLY_MESSAGE. 
I believe this is why you got the exception.

**Comment by runceel** [comment]
@youyu16 I also think so.
I think that the thing is "PUSH_MESSAGE is needed " should write on the document is better, right?

**Comment by youyu16** [comment]
@runceel Sure, will notify our colleague to update it.

**Comment by runceel** [comment]
@youyu16
Thank you for all your help. 😊
