### ISSUE TITLE
[LINE channel] Adaptive card cannot display many cards 

### ISSUE THREAD

**Issue by angie4u** [Microsoft/BotFramework-Services#56]
### Description
If the bot returns so many Adaptive cards, it cause error (return 15 adaptive cards using carousel format)

### Screenshot
![image](https://user-images.githubusercontent.com/16282358/53499804-68952680-3aa9-11e9-9180-753c06fdb637.png)

### Reproduce
1. Find & Add friends at LINE Channel  Name: Alpine Ski
2. type 3 -> 4 -> 1 like the screenshot above
3. it will cause error

**Comment by angie4u** [comment]
FYI, if the number of cards is not many, it displays card well. 
![image](https://user-images.githubusercontent.com/16282358/53501445-76987680-3aac-11e9-867c-429f92955e1f.png)

**Comment by jwiley84** [comment]
Hi @angie4u!

I believe all the channels have caps on how many cards can be sent in a carousel. If your bot is returning cards, you can always implement a check to see how many it's returning, and then if it's returning more then the max, have a button that says 'would you like to see more?' (더 많이 표시하려면 누르십시오.)

**Comment by youyu16** [comment]
hi @angie4u,
LINE only accept cards count less then **10** in carousel.  and the maximum size of JSON data that defines a carousel container is **50 KB**.

**Comment by angie4u** [comment]
Hello @youyu16 
Thank you for investigating this! I checked this with other channel how they support this kind of issue over maximum size.
I deployed same bot with Facebook channel and it handles like this.
![image](https://user-images.githubusercontent.com/16282358/53569433-7eb3ed00-3b64-11e9-9ac2-fd3694148b92.png)
Is it possible to support like this for LINE channel?

**Comment by angie4u** [comment]
Hello team! Is there any update on this issue? :)

**Comment by EricDahlvang** [comment]
@youyu16 How did you determine the maximum number of cards in a carousel is 10?  I just tested this, and if the carousel has more than 10 cards, LINE channel on Bot Framework creates a new carousel with the next 10 cards for the next line.  

Here is an example with a carousel of 20 cards:

![image](https://user-images.githubusercontent.com/11055362/54570212-f4a8b880-499a-11e9-9724-ab75a51a95e8.png)

**Comment by youyu16** [comment]
@EricDahlvang  this is because the latest change has been deployed and message with too many cards with be split now. and the max number 10 is depend on LINE message api document.
![image](https://user-images.githubusercontent.com/17819112/54597870-4ec87d00-4a72-11e9-93e4-f45f25cce9f3.png)

**Comment by youyu16** [comment]
@angie4u I will close this bug because the latest change has been deployed and verified by EricDahlvang.
feel free to reopen this if your the problem still there.
