### ISSUE TITLE
[LINE Channel] Bot reply message always returns one blank line at the end of the message

### ISSUE THREAD

**Issue by angie4u** [Microsoft/BotFramework-Services#57]
It always returns one blank line at the end of the message when it replies to user
![image](https://user-images.githubusercontent.com/16282358/53504423-376d2400-3ab2-11e9-8f94-9d6616fcc825.png)

**Comment by jwiley84** [comment]
investigating.

**Comment by youyu16** [comment]
@angie4u  
you need to add textformat when bot reply. otherwise channel will treat text as markdown and add a blank line.
`reply.TextFormat = TextFormatTypes.Plain;`

**Comment by EricDahlvang** [comment]
This appears to be fixed.
