### ISSUE TITLE
Teams channel seems to duplicate message for long-running API calls

### ISSUE THREAD

**Issue by dividor** [microsoft/BotFramework-Services#59]
Our SDK 4.2.1 bot is used for support, part of which can result in the bot making a REST call to a support system to create a support issue. Issues are created when the user clicks a submit button on an adaptive card, which is detected in middleware and the REST call made. These REST calls can sometimes take 5+ seconds to complete due to the target system being under-resourced.

The process works perfectly when running the bot on a website using WebChat, issues are created with no issue.

However, in Teams, for long-running REST calls we are getting duplicate issues created because the bot is re-sending the same REST call multiple times. Looking at the logs it seems this is what's happening:

1. User clicks submit button, Action.Submit sends postback message
2. Bot middleware detects message, makes REST call, long-running query. Call is made with 'await'
3. Bot middle detects *another* identical message with different timestamp, makes REST call
4. etc, sometimes up to 4

It almost seems as if in teams, if the REST call takes a long time, somehow the button even gets sent again.

Obviously, this is a big problem for us because we get multiple support tickets created.

Any ideas please?

**Comment by jameslew** [comment]
Hello @dividor, apologies for the long delay; this repo had become a bit idle.

I know this has been open for some time however is your issue still a problem that you're facing?

**Comment by jameslew** [comment]
Closing as inactive.

**Comment by ruggedjungleboy** [comment]
We are experiencing the same issue with long running REST API calls in Teams as mentioned by dividor above. The bot in Teams is logging multiple support tickets for the same submit action and this is a problem. 

This doesn't happen in other channels or in the emulator.

Was this bug addressed or is there a workaround that can be used?

**Comment by saikumaru** [comment]
@sgellock and @jameslew do you have an update on this please? Its not just teams, but also any channel which receives two user responses when bot is processing a long running API.

**Comment by sgellock** [comment]
@saikumaru, I apologize that you haven't gotten any data from the service team on this issue.  I've reached out to jameslew just now and asked for some traction.

**Comment by jameslew** [comment]
Hey there.  I'll add the MS Teams team to this.  In the context of MS Teams, the messages from your bot go directly to the Teams endpoint without passing through Bot Service servers, so we'll need their input.

**Comment by jameslew** [comment]
@Wajeed-msft - can you take a look here and provide guidance?

**Comment by Wajeed-msft** [comment]
@Jameslew, @ruggedjungleboy , @saikumaru - I have copied this over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/4592

**Comment by ToddN** [comment]
Since this moved to the Teams github repo, closing it here to avoid a dupe.
