### ISSUE TITLE
Only Facebook channel not working

### ISSUE THREAD

**Issue by blueelvis** [Microsoft/BotFramework-Services#6]
## Bot Info

* SDK Platform: NodeJs
* SDK Version: v3 Latest
* Active Channels: Facebook, DirectLine, WebChat
* Plan: S1 (Paid)
* Deployment Environment: Azure Bot Service
* Bot name: est1-hum-azf-bot-dev-02

## Issue Description
The issue which is happening is that whenever a message is sent to the bot from Facebook messenger, it seems to be received by the Azure Function on the backend but then nothing happens. Whereas, if this is tried via Webchat or Emulator, it works fine.

It stopped responding suddenly and it was working earlier fine. Any idea what could be wrong? We haven't touched any configuration as well when it stopped responding.

**Comment by EricDahlvang** [comment]
Have you tried debugging locally?  
https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/

Do you have Application Insights setup?  
bot: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-app-insights-keys?view=azure-bot-service-4.0
web app: https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs

Have you checked the web app's diagnostic logs?  
https://docs.microsoft.com/en-us/azure/app-service/web-sites-enable-diagnostic-log

**Comment by blueelvis** [comment]
@EricDahlvang -- As I said above, it works fine locally using the emulator in Debug mode.

I have checked App Insights and there isn't any error coming up on passing a message from Facebook. I see that the trace is generated when a message comes from FB but no error.

Yes, I have checked them as well. The function exits successfully.

**Comment by blueelvis** [comment]
@EricDahlvang -- The issue has been resolved. For some reason, my account (administrator) in Facebook app is having issues while trying to connect the app and the bot. The other administrator performed the same steps and it was successful. Do note that both me and the other person had same privileges everywhere.

Closing this.
