### ISSUE TITLE
Skype channel embed on website not displaying chat bubble

### ISSUE THREAD

**Issue by xenflux** [Microsoft/BotFramework-Services#60]
Skype chat bubble isn't displayed anymore. It was working fine and now i don't see the chat bubble on my website anymore. Tried on Firefox, Chrome and Safari.

Here is my embed code:

```
<span class="skype-button bubble" data-bot-id="..."></span>
<script src="https://swc.cdn.skype.com/sdk/v1/sdk.min.js"></script>
```

I noticed GET error on `https://swc.cdn.skype.com` in browser's console. Screenshot below,
<img width="772" alt="screen shot 2019-03-04 at 2 55 38 pm" src="https://user-images.githubusercontent.com/47638187/53762592-1d568b80-3e8e-11e9-9e1b-242f5e77bb2e.png">

Any idea?

**Comment by jwiley84** [comment]
This CDN (the one that controls the skype bubble) is controlled by Skype, not the Bot Framework unfortunately. 

https://swc.cdn.skype.com/sdk/v1/sdk.min.js
