### ISSUE TITLE
Portal Default bot is C# even when Nodejs SDK language is selected

### ISSUE THREAD

**Issue by Joll59** [Microsoft/BotFramework-Services#61]
When creating a new bot using the azure portal, after user has select nodejs as their SDK language but has not made a bot choice. See attached image. A default C# Basic bot is created.

![image](https://user-images.githubusercontent.com/16693765/53755904-980eaf00-3e6c-11e9-8cbb-0d63201230a7.png)

Expected behavior: 
When Nodejs is selected, portal should set the new default to match the selection, it is unclear and undocumented that not selecting a bot picks a default for you, but also that default is always C#.

**Comment by Andrea-Orimoto** [comment]
You are absolutely right, we'll look into it and fix it.
Thanks for your feedback.
Andrea

**Comment by Andrea-Orimoto** [comment]
A fix for this issue was deployed a couple of weeks ago, please try it and re-open this issue if you see any problems.
Thanks for your feedback!
