### ISSUE TITLE
Cortana Skill filtering everything after a colon when passing message to Bot Framework v4

### ISSUE THREAD

**Issue by sebastianzolg** [microsoft/BotFramework-Services#65]
When I invoke my **Cortana skill** and say *"Ask MyBot find me a meeting room from 10:00 AM to 11:00 AM"*, it is understood correctly and shown on the Cortana canvas. 

**However**, the message I receive on bot side is *"find me a meeting room from 10"*.

The same happens when I say *"Ask MyBot book me a room tomorrow 10:00 o'clock"*. Bot receives *"book me a room tomorrow 10"*.

Even the simplest *"Ask MyBot 9:30 AM"* results in *"9"* on bot site. 

So all pieces of the utterance after a colon seem to be truncated.

When I type the above directly into the Cortana canvas instead of speaking it, then the full text is received by the bot.

**Comment by bw-kforce-ms** [comment]
I've confirmed the defects. On turn zero, anything after the : is truncated. On turn one, the intents are incorrect. Filing two bugs on runtime.

**Comment by sebastianzolg** [comment]
thanks @bw-kforce-ms . Good to hear it's confirmed as you could image how much I doubted about myself. You've opened the bugs with Cortana PG, right? Seems to be a major one in my opinion, so I'm asking for the next steps here.

**Comment by bw-kforce-ms** [comment]
mentioned on stack you can try "open bot" and then "book meeting between 10:30 am and 11:30 am" until its fixed.

**Comment by sebastianzolg** [comment]
@bw-kforce-ms Hi - any update on this critical issue? In reality this breaks many solution. This must be priority 1, right? Would be great getting an update. Thanks.

**Comment by bw-kforce-ms** [comment]
@sebastianzolg Hi!  This was fixed! Please try again.
