### ISSUE TITLE
[Feature Request] Better feedback on Add to Slack action

### ISSUE THREAD

**Issue by gmmarc** [microsoft/BotFramework-Services#66]
I'm directly copying this feature request, as it hasn't been resolved and seems like this should be the place to post it: https://github.com/Microsoft/BotBuilder/issues/2655

--

Imagine following workflow:

* User starts conversation with the bot on webchat/directline channel
* The bot mentions it supports Slack and suggests moving there. User aggrees
* Bot provides Add to Slack button, user goes through OAuth process and adds the bot to their team

Then the flow falls apart. Because the most logical thing now is to proactively start onboarding process with the user on the Slack channel. But you can't do that because BotFramework gives you zero information on who added the bot to the team.

The only callback you get when the bot is added to the team is _installationUpdate_ event which is not documented anywhere, and is not even declared in node SDK (C# got it declared only a month ago). This _installationUpdate_ event is the BotFramework's wrapper of Slack's _bot_added_ RTM event. It holds the only helpful thing inside - the bot token, which gives you ability to provision the new team on your side but holds no information on who actually added (authorized) the bot on the team.

What's wrong with the whole situation is that BotFramework makes OAuth process comepletely black box and swallows its results:

1. _state_ is totally occupied with the bot name. No ability to pass your own information and get it back in the callback. E.g. you could pass your internal user/transition id to link two users on different channels.
2. no callback with the results of oauth code exchange, which have very important information - user token with _identify_ scope, which gives you ability to know which particular user in the team is the one who authorised the bot and the one with whom you had a conversation on different channel.
3. no custom scopes, yet not all scopes can be requested alongside the _bot_ scope, so this problem is actually not serious.

These problems still can be solved with the current state of the BotFramework but the code and more important the UX the user gets makes me sad everytime:

* the only way I found to get to know the user who authorized the bot on Slack is to pass the user through OAuth two times - first with my own callback to get the token, second with the BotFramework callback. Horrible from UX point of view.
* then to initiate the conversation you have to assemble the address of the user. To do that you have to manually combine user id with user team id (U123456:T214234) which becomes ugly and dangerous in code.

What I would really like to see is total control and feedback of Add to Slack process. Adding a bot to a Slack team is not something you can pretend not important at all. You expect to get actionable feedback on that.

**Comment by arturl** [comment]
Hi @gmmarc, we're adding this to our issues backlog but don't have an ETA at this time. Thanks for the suggestion.
