### ISSUE TITLE
[Feature Request] Support Slack's `app_mention` Event

### ISSUE THREAD

**Issue by mherrema** [microsoft/BotFramework-Services#69]
### Bot Info

- SDK Platform: Node.js
- SDK Version: 4.3.2
- Active Channels: Slack
- Deployment Environment: Azure Bot Service

### Issue Description

Continuation of [an issue on SDK 3](https://github.com/Microsoft/BotBuilder/issues/4662). Add support for the `app_mention` event in Slack. Right now subscribing to `app_mention` doesn't do anything. This means that the bot has to be specifically coded for Slack. It would be nice if there was an option to just have the bot respond whenever it was mentioned in a channel instead of all the time. Passing all messages through middleware to filter the mentions through isn't a "solution" to supporting slack's mention event.

### Expected Behavior

Adding in the `app_mention` event in Slack would trigger a response from Bot Service whenever a bot is mentioned.

### Actual Results

Bot Service doesn't receive the `app_mention` event so there is no response from the bot when mentioning if `channel.messages` is turned off. If it is turned on, the bot answers to all messages, not just ones where it is mentioned.

**Comment by jameslew** [comment]
Thank you for the suggestion @mherrema  ; we're behind in this forum but will be catching up shortly.

Is your intent to have a new activity type from connector that's actionable at the SDK side for mentions, or just to have the scoping changed such that you get a regular message activity only when the bot is mentioned?  

I think the request is for the latter?

**Comment by mherrema** [comment]
The intent would be the latter, correct. Just making a way to be able to talk to the bot with its typical response flow via mentioning it.

**Comment by jameslew** [comment]
Transferring to our internal backlog for triage.  Thank you for reporting!

**Comment by haacked** [comment]
Are there any updates on this? We're concerned that Slack customers will not want to install a bot built with Bot Framework if the bot has access to every message sent in every channel the bot is in.

**Comment by haacked** [comment]
In my local testing, I am receiving the `app_mention` event, it's just the Bot Service (or .NET Bot Framework) converts it to a Message Activity.
