### ISSUE TITLE
Facebook - Activity Exceptions: Value cannot be null. Parameter name: invalid activity-missing Conversation.Id

### ISSUE THREAD

**Issue by jamsoft** [Microsoft/BotFramework-Services#71]
## Version
4.2.2

## Describe the bug
It seems a conversation arrived via the Facebook channel that was potentially missing key data.  I can't tell if the BotFramework got things wrong or something went wrong on the Facebook side

The first exception was dealing with a missing From details (which is understandable as I believe it started in the Web Chat Plugin that doesn't start new conversation with a user opt-in thus allowing access to the users profile data).

`Value cannot be null. Parameter name: invalid activity-missing From.Id`

Occured on this line:
`var userState = await _accessors.AAUserStateAccessor.GetAsync(turnContext, () => new AAUserState(), cancellationToken);`

The code I have written to handle exceptions contains this:

```
await _accessors.ConversationState.LoadAsync(turnContext, false, cancellationToken);
await _accessors.ConversationState.ClearStateAsync(turnContext, cancellationToken);
await _accessors.ConversationState.SaveChangesAsync(turnContext, true, cancellationToken);
```

So then the next exception in the stack was

Value cannot be null. Parameter name: invalid activity-missing Conversation.Id
This occured on this line:
`await _accessors.ConversationState.LoadAsync(turnContext, false, cancellationToken);`

Then once all of this had happened the final exception happened in my OnTurnError global handler:
`Object reference not set to an instance of an object.`
On this line:

`await context.SendActivityAsync(Constants.ErrorMessage);`

```
options.OnTurnError = async (context, exception) =>
{
    var ai = new TelemetryClient();
    ai.TrackException(exception);

    logger.LogError($"Exception caught : {exception}");
    await context.SendActivityAsync(Constants.ErrorMessage);

    await _conversationState.LoadAsync(context);
    await _conversationState.ClearStateAsync(context);
    await _conversationState.SaveChangesAsync(context);

    // https://github.com/Microsoft/BotBuilder/issues/5175
    //wait _conversationState.DeleteAsync(context);
};
```
Which is suggesting that `context` was in fact null!!

## To Reproduce
1. Start a new conversaion via Web Chat Plugin

I can understand the `From` property being null due to the optin issues on Facebook when using the Web Chat Plugin but I'm not sure that it makes sense that the ConversationId is null.

I have now also updated this particular bot to v4.3.1 of the SDK.

[bug]

**Comment by EricDahlvang** [comment]
The fixes for the facebook messenger handover protocol are in production (including standby events).  This sample has been modified to demonstrate: https://github.com/EricDahlvang/FacebookEventsBotExpanded

**Comment by EricDahlvang** [comment]
The fixes for the facebook messenger handover protocol are in production (including standby events).  This sample has been modified to demonstrate: https://github.com/EricDahlvang/FacebookEventsBotExpanded

**Comment by marcasmar94** [comment]
Using the Virtual Assistant template, i keep getting:
 **ArgumentNullException: invalid activity-missing Conversation.Id**
at  **Microsoft.Bot.Builder.ConversationState.GetStorageKey**

Please check the issue opened here [issue](https://github.com/microsoft/botbuilder-dotnet/issues/2630)
This only happens on Facebook Channel.

**Comment by EricDahlvang** [comment]
@marcasmar94  Which Facebook Messenger events have you subscribed to?

**Comment by marcasmar94** [comment]
Webhoook  is subscribed to:

- messages
- messaging_postbacks
- messaging_optins
- message_deliveries
- standby
- message_echoes
- messaging_handovers

**Comment by marcasmar94** [comment]
It seems **message_echoes** was causing these issues, As soon as i Unsubscribed from this event in Facebook settings, the exceptions were gone.

Thank you @EricDahlvang  for pointing me to the right direction!
