### ISSUE TITLE
encrypt aad password in OAuth Connection Settings 

### ISSUE THREAD

**Issue by dorcohe** [microsoft/BotFramework-Services#72]
## Issue Description

In bot channel registration under OAuth Connection Settings the client secret is shown in **plain text**.
Everyone who owns the bot channel registration can see the client secret. The client secret is generate by Azure Active Directory and is shown to the user once, and then the user should keep it in a safe place. I believe that showing the password in plain text is a security vulnerability and I think it should be fixed. 

## Proposed change
Don't display client password, allow only to change it.

## Component Impact 
Bot Channel Registration

## Customer Impact
Our subscription was compromised and the client secret was stolen.

**Comment by jameslew** [comment]
This has been entered as a ticket in our system.  Proposed fix is to password obscure the field and not allow it to be retrieved from that field. I don't yet have an ETA for this, but will update when the issue is resolved.

**Comment by jameslew** [comment]
I can confirm that this work is under way now with the intent to deploy to production within the next few weeks.  Thank you for the report.

**Comment by mickeydjw** [comment]
Fix Deployed

**Comment by docohe** [comment]
Thanks !
