### ISSUE TITLE
[Azure Web App Bot] Failed to download bot code from Azure Portal

### ISSUE THREAD

**Issue by lucvanzanten** [Microsoft/BotFramework-Services#76]
### Bot info
SDK: v3, Node.js
Deployment environment: Microsoft Azure

### Issue Description
Unable to download the source code .zip file.
The error is:
File download error
Failed to dynamically fetch target download uri.

In the Build tab, select " Download Bot Source Code".
This should download the source code .zip file, but gives the error instead.

Thank you in advance.

**Comment by EricDahlvang** [comment]
I'm sorry you've encountered this issue.  I've seen this before, but I'm unsure why it happens exactly.  One workaround is to go to the Kudu console, and download from there: https://YourWebAppName.scm.azurewebsites.net/DebugConsole  then navigate to d:\home\site  and download the wwwroot folder.  Please try this, and let us know how it goes.

**Comment by ferin08** [comment]
I came across the same issue and when I tried using the link you provided @EricDahlvang, it says I am not authorized.

**Comment by EricDahlvang** [comment]
@ferin08 You can see the web app in the Azure portal, but you cannot see the Kudu console?  Does the App Service Editor work?

**Comment by ferin08** [comment]
Yes, I have created the bot app on azure portal but I am not able to download the source code. And when I tried using the link you gave for Kudu console it says I have no authorization.

**Comment by lucvanzanten** [comment]
@EricDahlvang 
I haven't tried this solution, because I didn't have to. I tried downloading via the button again yesterday, on a whim, this time with success. 
To my knowledge, I haven't done anything to cause or influence this, and I still don't know what solved the issue, or caused it to begin with.
Thank you for your assistance.
