### ISSUE TITLE
Fail to decrypt conversation id 

### ISSUE THREAD

**Issue by ricardopieper** [Microsoft/BotFramework-Services#8]
We have a working integration with Skype and directline.

However, I created a new bot today and now I'm getting this:

{"error":{"code":"BadArgument","message":"Failed to decrypt conversation id"}}

Other bots are working as normal. What does this error mean?

**Comment by nyxsys** [comment]
Just double checking, this is a plain old bot right off the template correct, echo bot or basic bot? Which sdk are you using? (v3/v4 nodejs/c#)?

**Comment by nyxsys** [comment]
Also, it would probably be a good idea to open up this issue on the actual repo for your SDK:

[node](https://github.com/Microsoft/botbuilder-js/issues/new?template=javascript-sdk-bug-report.md)
[C#](https://github.com/Microsoft/botbuilder-dotnet/issues/new?template=-net-sdk-bug.md)

**Comment by JasonSowers** [comment]
@ricardopieper you are calling the directline methods via the rest API?

**Comment by ricardopieper** [comment]
@JasonSowers yes, we are. This problem stopped happening after I recreated everything from scratch, so that might have been a mistake on my end. 

However, I found the "fail to decrypt conversation id" a bit weird, seems like that's an error message only useful for the Bot Framework backend, and not for the end user of the API.

To give credit where it's due, @ksikorsk found out that I was using the wrong conversation ID in the URL in an unrelated issue (#1). This mistake was fixed today, and I feel like it could cause this issue somehow.

I'll let you guys decide if this issue should be closed, for me it's no problem if I can reopen it if I see it again.

**Comment by dandriscoll** [comment]
@ricardopieper thanks for providing detail on this issue. We started independent verification a few days ago that confirms this issue is specific to the skypeforbusiness channel. We have your other issue tracking the 400 and ErrorResponse object so given that we've identified the source, I'm closing this issue now.
