### ISSUE TITLE
[Problems] Some major rendering issues in Slack in 4.4.3

### ISSUE THREAD

**Issue by Unders0n** [microsoft/BotFramework-Services#82]
### Details
**Version:** 4.4.3
**SDK**: C#
**Channel:** Slack channel
**Bot:** Slightly changed virtual assistant solution (ex Enterprise)

Problems somehow related so i decided not to create separate issues for that, feel free to decompose if needed.
All mentioned works just fine in emulator and in web chat that's why i suppose its a bug and not question.

### 1:
Adaptive card seems not working, as example rendering slightly changed NewUserGreeting.json card with template renderer: 

```c#
// . . .
view = new MainResponses();
await view.ReplyWith(dc.Context, MainResponses.ResponseIds.NewUserGreeting);
```

nothing showed in slack and no errors anywhere (not in slack, in app insights or in portal). If there's some place to debug such stuff in Slack dashboard please tell.

### 2: 
Virtual assistant example is using aproach with OnEventAsync() in Maindialog and adaptiveCard have submit actions that are callbacked in this method, also that working when we're using suggestedActions or herocards with messageBack method, but none of that working in slack, click hits DialogBot but not hitting this method.

### 3:
New template rendering system with suggested actions not seems to render buttons in Slack, it just rendering options:

```c#
return await sc.PromptAsync(DialogIds.TimezonePrompt, new PromptOptions
            {
                Prompt = await _responder.RenderTemplate(sc.Context, sc.Context.Activity.Locale,
                    OnboardingResponses.ResponseIds.TimezonePrompt)
            });
ResponseIds.TimezonePrompt,
                    (context, data) =>
                    {
                       // var tmzns = TimeZoneInfo.GetSystemTimeZones().Select(info => info.DisplayName);
                        var tmzns = new List<string>() { "UTC+00 - UTC+04", "*UTC+05* - *UTC+13*", "*UTC-00* - *UTC-07*"}; 

                        return MessageFactory.SuggestedActions(
                            tmzns,
                            OnboardingStrings.TIMEZONE_PROMPT);
                    }
```

![изображение](https://user-images.githubusercontent.com/18035628/58270306-1dca3880-7d92-11e9-996e-48ed9ae36f46.png)

I've tryied many aproaches, wrap it in dialog and set Style=List , and many others and nothing worked, just getting back to old aproach worked:

```c#
return await sc.PromptAsync(DialogIds.TimezonePrompt, new PromptOptions
            {
                Choices = new List<Choice>()
                {
                    new Choice("UTC+00 - UTC+04"),
                    new Choice("*UTC+05* - *UTC+13*"),
                    new Choice("*UTC-00* - *UTC-07*"),
                }
            });

```

**Comment by Unders0n** [comment]
@jwiley84 hi, any updates on that. I badly need some of this functionality, for example buttons with .openUri() and whole stuff with SuggestedActions not seems to render in slack.

**Comment by v-kydela** [comment]
@Unders0n - Sorry for the delay. Are you still working on this?

Your second code block seems to be malformed. Can you please fix it so that it only includes complete statements and not fragments?

**Comment by Unders0n** [comment]
@v-kydela 
Hi, i used a workaround, basically i'm not using new template aproach and not using SuggestedActions for now, just using ChoiceFactory.ToChoices in prompt instead. Though it would be cool if you handle that.
As for malformed code - i can't find it in my code now, butmy guess is that just brackets not closed at the end. Actually to repro you can just use smth like this

                ```
   var tmzns = new List<string>() { "UTC+00 - UTC+04", "*UTC+05* - *UTC+13*", "*UTC-00* - *UTC-07*"}; 

                        return MessageFactory.SuggestedActions(
                            tmzns,
                            "test prompt");
```

**Comment by v-kydela** [comment]
@Unders0n - It sounds like you've resolved your issue. Is it all right if I close this? You can open a new issue if you have more questions.

**Comment by Unders0n** [comment]
@v-kydela , as i mentioned last time i checked recommended way of rendering options - MessageFactory.SuggestedActions was not drawing them correctly in slack, while in is drawng buttons well in emulator, skype, telegram.
Can you please check it in latest version and confirm \ decline?

**Comment by v-kydela** [comment]
@Unders0n - Are you asking if Slack supports suggested actions? What Slack client are you using?

**Comment by Unders0n** [comment]
i'm telling that it not render buttons with new MessageFactory and template aproaches - it just renders text as i showed in 1st pic. Only way it renders buttons is old aproach with 

PromptOptions
            {
                Choices = new List<Choice>()
...

**Comment by v-kydela** [comment]
@Unders0n - I've reported this bug [here](https://github.com/microsoft/botbuilder-dotnet/issues/2291)

It looks like Slack does not support suggested actions. You'll need to render choices as card actions. This can be done by setting your list style to hero card when you construct the prompt:

```c#
AddDialog(new ChoicePrompt(CHOICEPROMPT5) { Style = ListStyle.HeroCard });
```

You can also set the list style in your prompt options.

Does this resolve your issue?

**Comment by v-kydela** [comment]
@Unders0n - Are you still working on this?

**Comment by Unders0n** [comment]
@v-kydela this stuff is on hold now, and i bealieve your aproach fshould work just fine. i guess we can close this issue, thanks
