### ISSUE TITLE
Web chat solution for internal bots (private tenant)

### ISSUE THREAD

**Issue by shaikatzir** [microsoft/BotFramework-Services#83]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We are running the bot framework solution on Azure private tenant. We are able to successfully run Web Chat solution for external bot use cases for public access through the bot connector channel manager. We would like to add a web client for internal use cases (internal network) without connecting through the bot connector public access. 

**Describe the suggestion or request in detail**
We would like to use the WebChat solution to run internal use cases. Is there a way to integrate interface directly to the bot framework without Direct Line through bot connector?

**Comment by compulim** [comment]
(Transferring channel issues to `botframework-services` repository)

**Comment by jameslew** [comment]
Hello @shaikatzir ; apologies for the delayed response.

@compulim is correct, currently webchat utilizes DirectLine which in the released form passes all messages through our shared Azure service.

We are currently developing an implementation however that implements DirectLine as an app service extension, such that messages pass directly between your client and your app service in Azure, skipping our shared service.  It is in public preview, you can read more at the repo here: https://github.com/Jeffders/DirectLineAppServiceExtensionPreview/tree/master/docs.

**Comment by jameslew** [comment]
Closing for now, please feel free to re-open if the most recent comment isn't a good solution for the request.

**Comment by shaikatzir** [comment]
Hi @jameslew ,
For my understanding that would be only for Microsoft App Services, right?
We are running the bot service on AKS, on a separate vnet that connects to the private network.
Will that be available for AKS too?
