### ISSUE TITLE
Some Facebook events are still not supported

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Services#86]
While testing Facebook handovers I discovered that [`app_roles`](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_handovers#app_roles) events are not supported.

While `app_roles` events aren't hugely important, every event we don't support is a potential problem that customers could encounter, and a potential reason to not use the Bot Framework. There are currently [15 webhook event groups](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events) that a Facebook app can subscribe to, with each group potentially corresponding to multiple events. For example, subscribing to `messaging_handovers` will allow a Facebook app to receive `pass_thread_control`, `take_thread_control`, `request_thread_control`, and `app_roles` events. It might be a good idea to allow our Facebook connector to pass along any event from those 15 groups to the bot so that nothing gets absorbed.

**Comment by v-kydela** [comment]
@craigjensen - I plan to work on a Messenger Platform NuGet package soon: https://github.com/microsoft/botbuilder-dotnet/issues/1931

It would be very helpful if we could solidify the Bot Framework's compatibility with the Messenger Platform before the package gets released. Ideally our connector would not "swallow" any events. I'm hoping there's a way to handle events generically so that they all get forwarded, rather than needing to hard-code in each event we want to support specifically.

**Comment by jameslew** [comment]
@Kyle; this may be something to take up directly with EgorN as a feature request.  I don't think this is as simple as unblocking a set of events.

**Comment by v-kydela** [comment]
Thank you @jameslew 

I have been in contact with Egor and Artur about this over email. I'm hoping to set up a meeting with them.

**Comment by v-kydela** [comment]
@mickeydjw - What was the resolution?
