### ISSUE TITLE
"Get Conversations" only ever returns a continuation token and never returns the conversations

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Services#88]
While "Get Conversations" is missing from the [REST API documentation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-3.0#conversation-operations), that will soon be rectified and its syntax can be seen in the Bot Builder SDK:

```http
GET /v3/conversations?continuationToken={continuationToken}
```

While most channels like Teams will return MethodNotAllowed because they don't support that API, we can see that Direct Line does support it. However, it will only ever return a continuation token, indicating that there are additional results that haven't been returned. If you've started a conversation with your bot then there should be at least one conversation for the API to return, but it always returns this instead:

```json
{
  "continuationToken": "<token>",
  "conversations": []
}
```

I have tested this using cURL and also using the Bot Builder C# SDK. This code can be used to reproduce the behavior:

```c#
private async Task TestGetConversationsAsync(ITurnContext turnContext, CancellationToken cancellationToken)
{
    var connectorClient = turnContext.TurnState.Get<IConnectorClient>() as ConnectorClient;
    var result = await connectorClient.Conversations.GetConversationsAsync(null, cancellationToken);
    var count = 0;

    while ((result.Conversations == null || result.Conversations.Count <= 0) && !string.IsNullOrWhiteSpace(result.ContinuationToken) && count < 20)
    {
        await turnContext.SendActivityAsync($"{count++} : {result.ContinuationToken}");

        result = await connectorClient.Conversations.GetConversationsAsync(result.ContinuationToken, cancellationToken);
    }

    if (result.Conversations != null)
    {
        await turnContext.SendActivityAsync(JsonConvert.SerializeObject(result));
    }
}
```

Even though I'm passing each new continuation token into the API call each time, it just keeps producing more continuation tokens and never returns the actual conversations.

## Expected

The Get Conversations API documentation suggests that it should return a list of all conversations the bot has participated in.

## Actual

There may be some bug in the service that's not allowing the operation to complete.

**Comment by jameslew** [comment]
I'll have to check with some people to see if this is intentional (i.e. that it should support it), or that it should be blocking and is not. Is there a particular scenario you had in mind to use this for?

**Comment by v-kydela** [comment]
Thank you @jameslew 

There is no particular scenario I want to use this for. I was just testing it to see if it worked because I was assigned to fix an issue with the REST API documentation.

My understanding is that the Get Conversations API was added for the purpose satisfying a legal requirement about privacy and transparency. Is that correct?

**Comment by ToddN** [comment]
@v-kydela,  You need to be passing the bot ID in to the call. Otherwise, we have no idea which bot's conversations you're trying to get.  I'll have to look at the SDK to see if it's really not asking for the bot ID.  Also, there should be error checking that flagged the missing ID.

**Comment by v-kydela** [comment]
@ToddN - I guess I figured the bot ID could be inferred from the HTTP call's authorization token. Is that not the case?

I was reverse-engineering this API call from the [.NET SDK](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Connector/Conversations.cs#L53), and it doesn't seem to provide any hints about how to pass in a bot ID.

**Comment by ToddN** [comment]
CIL

**Comment by ToddN** [comment]
After investigating with Kyle,  we have concluded that this is working as design. It's just a lot slower than we'd like it to be. But fixing the perf would require creating new indices in Azure Bot Service and we're not ready to sign on for that work at this time.

**Comment by martinoss** [comment]
@ToddN I just noticed the same behavior and expected the credentials to be enough to figure out which conversations to get. But I'm always getting an empty list.
Can you explain a little bit about what you have investigated with @v-kydela ?
