### ISSUE TITLE
 ChatConnector: startConversation - address is invalid.

### ISSUE THREAD

**Issue by sagarmodhavaniya** [microsoft/BotFramework-Services#90]
i am got the error inside the 
`  bot.loadSession(event.address, (err, session) => {}`
Here the session are undefined null session are revived 
`Error: Invalid address.`
i am try to use the `session.messages.address`  are undefined  so display error

**Comment by v-kydela** [comment]
Hello @sagarmodhavaniya 

Can you explain what you're ultimately trying to accomplish?

Are you using the v3 Node SDK? Would you consider [migrating to the v4 SDK](https://docs.microsoft.com/en-us/azure/bot-service/migration/migration-overview)?

**Comment by sagarmodhavaniya** [comment]
yes i am using sdk 3
i am try to make bot for whatsapp using twillo

**Comment by v-kydela** [comment]
@sagarmodhavaniya - Can you provide screenshots and a minimum verifiable example and steps to reproduce the problem?

**Comment by sagarmodhavaniya** [comment]
problem are identified now Microsoft bot framework are not support the twilio whatsapp messages only support the twilio SMS so this error are accursed

**Comment by sagarmodhavaniya** [comment]
if you have idea to make a whatsapp bot using bot framework so mail me on sagar.modhvaniya@kevit.io

**Comment by v-kydela** [comment]
@sagarmodhavaniya 

Yes it's true that the Bot Framework does not currently support WhatsApp, but you can track the progess here: https://github.com/Microsoft/BotFramework-Services/issues/7

There may be workarounds you can implement, as described here: https://stackoverflow.com/a/55367260/2122672

You can see the Twilio API for WhatsApp here: https://www.twilio.com/whatsapp

This article describes some of the longstanding barriers for anyone creating WhatsApp bots even without using the Bot Framework, and it may offer another potential alternative: https://medium.com/@AlfredBaudisch/how-a-whatsapp-bot-got-famous-and-evolved-as-the-brazilian-wechat-and-conversational-commerce-e2213262183d

**Comment by sagarmodhavaniya** [comment]
there is anthher way i found to make whatsapp  bot using the Microsoft-bot framework + twilio 
if you have webchat,facebook have in Microsoft-bot framework  and you need to develop the whatsapp bot yo can do it it's pretty simple
