### ISSUE TITLE
OAuthPrompt not sending signin/verifyState for IE11

### ISSUE THREAD

**Issue by VKAlwaysWin** [microsoft/BotFramework-Services#91]
## Version
4.4.5

## Describe the bug
When you create OAuth ConnectionSetting you can use name to pass in OAuthPromptSettings. It will use token.botframework.com under the hood. It is working fine in all browsers (including Edge) instead of IE11. 

IE11 has issues with arrow function and https://token.botframework.com/api/oauth/PostSignInCallback code looks like this:
setTimeout(() => {
	document.getElementById('instructionText').style.display = 'initial';
}, 5000);

## To Reproduce
Setup bot using Bot Channels Registration for MS Teams, add OAuth ConnectionSetting for Google and use OAuthPrompt to login.

## Expected behavior
State code (magic number) is sent back with invoke signin/verifyState as it is working for all other browsers.

## Screenshots
![image](https://user-images.githubusercontent.com/14337164/60257165-9e251180-98db-11e9-8e57-2843f138dd3d.png)

## Additional context
It can be fixed using function instead of () =>.
Please let me know if you can help. Thank you in advance.

[bug]

**Comment by EricDahlvang** [comment]
Hi @VKAlwaysWin,

The fix for this is released.

**Comment by VKAlwaysWin** [comment]
It is working great. Thank you @EricDahlvang
