### ISSUE TITLE
Facebook channel creating internal server HTTP 500 error

### ISSUE THREAD

**Issue by seanbetts** [microsoft/BotFramework-Services#93]
**BotFramework Version**: 4.4 in JavaScript

## Bug Description ##
When connecting to my chatbot using Facebook Messenger, it's generating an internal server HTTP 500 error. This happens whenever a message is sent from Facebook Messenger (i.e. received by the chatbot).

## Steps to Reproduce ##
1. Connect to chatbot from Facebook Messenger
2. Inspect log files

## Actual Experience ##
The chatbot works as expected but the error message is appearing in the log files and shows up as an issue in the Facebook channel in the Azure portal. 

## Additional Context ##
Here are the error details:

[onTurnError]: TypeError: Cannot read property 'role' of undefined
BotFrameworkAdapter.processActivity(): 500 ERROR - Error: BotFrameworkAdapter.sendActivity(): missing conversation id.<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>IIS Detailed Error - 500.0 - Internal Server Error</title><style type="text/css"></style>
</head><body><div id="content"><div class="content-container"><h3>HTTP Error 500.0 - Internal Server Error</h3><h4>The page cannot be displayed because an internal server error has occurred.</h4></div><div class="content-container"><fieldset><h4>Most likely causes:</h4><ul> 	<li>IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred.</li> 	<li>IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.</li> 	<li>IIS was not able to process configuration for the Web site or application.</li> 	<li>The authenticated user does not have permission to use this DLL.</li> 	<li>The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.</li> </ul></fieldset></div><div class="content-container"><fieldset><h4>Things you can try:</h4><ul> 	<li>Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account.</li> 	<li>Check the event logs to see if any additional information was logged.</li> 	<li>Verify the permissions for the DLL.</li> 	<li>Install the .NET Extensibility feature if the request is mapped to a managed handler.</li> 	<li>Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwlink/?LinkID=66439">here</a>. </li> </ul></fieldset></div>
<div class="content-container"><fieldset><h4>Detailed Error Information:</h4><div id="details-left"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;iisnode</td></tr><tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;ExecuteRequestHandler</td></tr><tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;iisnode</td></tr><tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x00000000</td></tr>
</table></div><div id="details-right"><table border="0" cellpadding="0" cellspacing="0"><tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://mihndbotdev:80/index.js</td></tr><tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\home\site\wwwroot\index.js</td></tr><tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr><tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr>
</table><div class="clear"></div></div></fieldset></div>
<div class="content-container"><fieldset><h4>More Information:</h4>This error means that there was a problem while processing the request. The request was received by the Web server, but during processing a fatal error occurred, causing the 500 error.<p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=500,0,0x00000000,14393">View more information &raquo;</a></p><p>Microsoft Knowledge Base Articles:</p>

</fieldset></div></div></body></html>

**Comment by stevkan** [comment]
Hi @seanbetts, are you able to post what the activity looks like that is being received by the bot? Also, has your bot been working fine under Facebook and only recently produced this error? Or, did you recently build it out for FB?

**Comment by seanbetts** [comment]
Hi @stevkan. My bot has been working fine under Facebook until recently. Here's an example of the activity that is bing received by the bot:

    var welcomeCardFB = {
        channelData: {
            attachment: {
                type: 'template',
                payload: {
                    template_type: 'generic',
                    sharable: true,
                    image_aspect_ratio: 'square',
                    elements: [
                        {
                            title: '👋 Hello ' + userName + '!',
                            image_url: 'https://mihndbotblob.blob.core.windows.net/resources/MiHNDbot-logo.jpg',
                            subtitle: "I'm designed to help people learn about Mental Health and NeuroDiversity",
                            default_action: {
                                type: 'web_url',
                                url: 'https://www.mihnd.co.uk',
                                webview_height_ratio: 'tall'
                            },
                            buttons: [
                                {
                                    type: 'postback',
                                    title: 'Mental Health',
                                    payload: 'WHAT_IS_MENTAL_HEALTH'
                                }, {
                                    type: 'postback',
                                    title: 'NeuroDiversity',
                                    payload: 'WHAT_IS_NEURODIVERSITY'
                                }, {
                                    type: 'postback',
                                    title: 'Get Help',
                                    payload: 'GET_HELP'
                                }] }] } } } };

    return welcomeCardFB;
    };`

**Comment by stevkan** [comment]
Apologies for the delay. I'm assuming you are sending that card from the bot? Can you capture and post an actual activity object? Also, do you have a date and time when this error occurred?

**Comment by stevkan** [comment]
So, I recreated the card and received it back as an activity which I have included below. The conversation id is normally recorded under `conversation` and the role under `recipient`. For one reason or another, I suspect your bot lost the context and, subsequently, didn't have an id which meant it couldn't apply a value to role. This resulted in the the error detailing your missing conversation id and undefined role.

If you can provide the date/time of the error, I can try and see if there was a service hiccup at that time that might have resulted in your bot failing. But, again, 500 errors are _usually_ internal related.

```json
{
  "direction": "incoming",
  "activity": {
    "channelData": {
      "attachment": {
        "type": "template",
        "payload": {
          "template_type": "generic",
          "sharable": true,
          "image_aspect_ratio": "square",
          "elements": [
            {
              "title": "👋 Hello Steve!",
              "image_url": "https://mihndbotblob.blob.core.windows.net/resources/MiHNDbot-logo.jpg",
              "subtitle": "I'm designed to help people learn about Mental Health and NeuroDiversity",
              "default_action": {
                "type": "web_url",
                "url": "https://www.mihnd.co.uk",
                "webview_height_ratio": "tall"
              },
              "buttons": [
                {
                  "type": "postback",
                  "title": "Mental Health",
                  "payload": "WHAT_IS_MENTAL_HEALTH"
                },
                {
                  "type": "postback",
                  "title": "NeuroDiversity",
                  "payload": "WHAT_IS_NEURODIVERSITY"
                },
                {
                  "type": "postback",
                  "title": "Get Help",
                  "payload": "GET_HELP"
                }
              ]
            }
          ]
        }
      }
    },
    "channelId": "facebook",
    "serviceUrl": "https://facebook.botframework.com/",
    "conversation": {
      "isGroup": false,
      "id": "15196xxxxxxxxx37873"
    },
    "from": {
      "id": "2050867055237873",
      "name": "v-xxxxxxxxx-bot"
    },
    "recipient": {
      "id": "1519649474831492",
      "name": "Steve",
      "role": "user"
    },
    "replyToId": xxxxxxxxx",
    "type": "message",
    "timestamp": "2019-08-09T00:08:03.517Z"
  }
}
```

**Comment by seanbetts** [comment]
Hi @stevkan, thanks for getting back to me. The error was being caused by an issue with my Facebook credentials and it’s all fixed now!
