### ISSUE TITLE
Links from Bot Framework Activity schema to the Bot Framework protocol are broken

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/BotFramework-Services#95]
The [Bot Framework -- Activity](https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md) spec has broken links again.

Of note the links to the **Bot Framework protocol** are broken.

- Current, broken target: https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-protocol/botframework-protocol.md
- Probably target: https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-protocol/botframework-channel.json

**Comment by jameslew** [comment]
Made pull request with fix.
