### ISSUE TITLE
A Teams activity with both text and a card yields no resource response ID

### ISSUE THREAD

**Issue by v-kydela** [microsoft/BotFramework-Services#98]
I believe the problem here is that Teams is a channel that isolates cards in their own messages so that one Teams message cannot contain both a card and text outside of that card. This forces the Teams connector to send two separate messages to Teams, even though there's only one activity and the Send Activity API was only called once.

## To reproduce

1. Send a Bot Framework activity to Microsoft Teams with text in the `text` property and a card in the `attachments` property
2. Observe the empty string in the resource response

## Expected behavior

Sending just text will yield a resource response ID, and sending just a card will yield a resource response ID. A resource response can only have one ID so I'm not sure what the best solution here is. The best developer experience would be to get a response that not only contains an ID for each Teams message but also a way to tell which is which.

**Comment by mdrichardson** [comment]
Chiming in to say that:

1. I can repro
2. WebChat also *appears* to separate this into two activities, but *does* return an response ID, whereas Teams does not

**Comment by v-kydela** [comment]
I don't know if this is plausible, but I've been thinking that an even better developer experience would be to just get a resource response like normal. Then when the bot tries to update an activity using that ID, the Teams connector would know to update both activities using both the text and attachments in the update-activity content.

**Comment by SidU** [comment]
Our real goal here is to get rid of this splitting behavior eventually for Teams. It kicks in for text+attachment case, and for multi-attachment case when attachmentLayout="list". 

Do you see a reason why keeping the existing splitting behavior is preferable over posting a single activity?

**Comment by v-kydela** [comment]
@SidU - No, I do not. I think posting a single activity is preferable.

**Comment by v-kydela** [comment]
@Andrea-Orimoto - Why was this closed? Was there a fix?

**Comment by b0rnua** [comment]
I have faced with the very same problem, is there any solution if not @Andrea-Orimoto why this issue is closed?
