### ISSUE TITLE
Web Chat embedding example / ease of doing correctly

### ISSUE THREAD

**Issue by ChrisRisner** [microsoft/BotFramework-Services#99]
Currently, if you go to the WebChat channel in the Azure portal for a bot the embed code demonstrates how to iframe in a bot using your secret key.  Given the risk in this approach, the page should more explicitly tell developers that this approach should only be used for local testing and never be deployed anywhere.

There are assorted other samples for how to embed webchat including how to embed using a token you retrieve using your secret, as well as how to reach out to an endpoint to get a token with each load of webchat.  As the last is a common scenario and the best direction to point users it, it might be a good idea to provide boilerplate code to the Bot Builder SDKs so an endpoint to fulfill this purpose could be added and exposed in a single line of code.

**Comment by Andrea-Orimoto** [comment]
The Webchat embed UI in the Azure Portal does heave a link to an advanced customization options doc page, which explains how to get the DL token from the secret and use that instead.
https://github.com/microsoft/BotFramework-WebChat/blob/master/README.md

![image](https://user-images.githubusercontent.com/17152540/62640225-f9441e00-b8f5-11e9-9f9f-2d1f85090028.png)

I'm going to close this issue. If you feel like there is a better way, please reopen and provide your suggestion.

Thanks!
Andrea
